
-- =============================================
-- Author:		Yelena Shmidt
-- Create date: 08/19/2013
-- Description:	MRP PO Actions by supplier report. Replacing VFP MRPPOSUP report form
-- Modified:	10/01/2013 DRP:  Removed @lcWhere and modificed the MrpFullActionView call per Yelena changes.
--12/03/2013  YS:  Default 'All' where multiple selection is allowed 
--					added @userid and get list of approved suppliers for this user
--02/28/2014 DRP:  needed to change the @dLastActionDate parameter to @lcLastAction so that it will match the other procedures and also work properly with the webmanex. 
--12/12/14 DS Added supplier status filter
--03/02/15 DRP: changed part range paramaters from lcpart to lcuniq_key, remove single lcuniq_key
--03/12/15 ys replaced invtmfhd table with 2 new tables
--06/24/2015 DRP:  Found that due to the fact that the MRPACT.DTTAKEACT would have a null value if there was no date to take action that the results would filter out those Null values.  
--				 Removing the No Actions and Firm Planned records from the results.  Users reported that they need those records to display. 
--				 Changed all locations from <<and DATEDIFF(Day,MRPACT.DTTAKEACT,@lcLastAction)>=0>> to <<and (DATEDIFF(Day,MRPACT.DTTAKEACT,@lcLastAction)>=0 or MRPACT.DTTAKEACT is null)>>
--				 added the @MrpDate in order to get the MRPDate in the final Results. 
--07/02/15 DRP:  needed to add the closing brakets around the GetSupplier.SuplPartNo is not null and GetSupplier.SuplPartNo<>''   Without the closing brakets the "Select Actions with Default Supplier Assigned" selection would have zero resulting records
--07/07/15 DRP:  found that two of the fiels where switched around in the union join within the "GetSupplier" section 
--- 03/28/17 YS changed length of the part_no column from 25 to 35
--06/15/17 DRP:  Per request added @lcAction.  This will allow the users to filter the results even further.  for example if they want to only see Release PO actions.  
--10/10/17 YS: Move supplier filter to the last sql. in distron data took more than 7 min to return information.
--03/14/18 VL found record already exist in previous SQL statement, also appear in the 2nd SQL statement, so added SelectMrpAct.Action = 'Release PO' to filter out the duplicate
-- 09/11/18 VL:   Added 'MRC' report parameter, request by Circuitronics, Zendesk#2465 
--10/08/18 VL found if partmfgr='GENR' and mfgr_pt_no= '', then next criteria would not work, so separate it into two criteria, zendesk#2688
--10/12/18 VL changed from CTE cursor to tabel variable, hope to speed up, zendesk#2702
--10/10/19 VL added all missing code 09/11/18-10/12/18 from manex_fc
-- 12/11/20 VL: now the buyer is not saved in Buyer_type, it's saved in AspnetBuyer, CAPA 3284
-- =============================================

CREATE PROCEDURE [dbo].[rptMrpPoActionBySupplier]
	-- Add the parameters for the stored procedure here

--10/01/2013 DRP:	@lcWhere varchar(max)= '1=1'	-- this will actually be populated from the MRP Filter screen, using Vicky's code	@lcWhere varchar(max)= '1=1'	-- will setup 1=1, if we have need to create CR and call it form VFP fron end will send the parameter generated by the MRP form
	@lcUniqBomParent char(10)=''	-- this is the Bom Parent Part.  This too will be populated by the MRP Filter Screen if CR is created.
	,@lcUniq_keyStart char(10)=''
	--,@lcPartStart as varchar(25)=''	--This is the component start range that will be populated by the users within the report parameter selection screen	--03/02/15 DRP:  replaced by @lcUniq_keyStart
	--,@lcPartEnd as varchar(25)=''	--This is the component end range that will be populated by the users within the report parameter selection screen		--03/02/15 DRP:  replaced by @lcUniq_keyEnd
	,@lcUniq_keyEnd char(10)=''
	,@lcLastAction as date = null	--This is the Last Action Date filter which should defaulted from the MRP Setup
	,@lcClass as varchar (max) = 'All'	--user would select a class, or multiple classes or if value is empty, no filter by part class wil be applied to the result.
	,@lcBuyer varchar(max) = 'All'		-- user would select a buyer or multiple buyers or if value is empty, no filter by buyer wil be applied to the result.
	,@SupplSelection char(50) = 'All'	-- "All" = All Parts ; with and without default supplier will be selected
										-- 'Select Actions with Default Supplier Assigned' - only parts that have default supplier assigned   
										-- 'Select Parts with no Default Supplier' - only parts that have no default supplier assigned									
	,@lcUniqSupNo varchar(max) = 'All'	    -- if user selects "Parts with Supplier Contracts" then this second parameter will be display to select from a Supplier Selection box. 
	,@OrderPref1 bit = 0 -- if 1 show only with OrderPref=1, 0 - show any 
	, @userId uniqueidentifier=null 
	,@supplierStatus varchar(20) = 'All'
	,@lcAction char(15) = 'All PO Actions'	--  All PO Actions, Pull Ins,Push Outs, Release PO,Cancel PO 	--06/15/17 DRP:  added
	-- 09/11/18 VL added MRC
	,@lcMRC char(15) = 'All'
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

/*PART RANGE*/
	SET NOCOUNT ON;
	--03/02/15 DRP changed part range paramaters from lcpart to lcuniq_key, remove single lcuniq_key
	--- 03/28/17 YS changed length of the part_no column from 25 to 35
	declare @lcPartStart char(35)='',@lcRevisionStart char(8)='',
	@lcPartEnd char(35)='',@lcRevisionEnd char(8)=''
		
		--03/02/15 DRP changed part range paramaters from lcpart to lcuniq_key, remove single lcuniq_key	
		--09/13/2013 DRP: If null or '*' then pass ''
		IF  @lcUniq_keyStart IS NULL or  @lcUniq_keyStart ='' 
			SELECT @lcPartStart=' ', @lcRevisionStart=' '
		ELSE
		SELECT @lcPartStart = ISNULL(I.Part_no,' '), 
			@lcRevisionStart = ISNULL(I.Revision,' ') 
		FROM Inventor I where Uniq_key=@lcUniq_keyStart
		
		-- find ending part number
		IF  @lcUniq_keyEnd IS NULL or  @lcUniq_keyEnd ='' 
		--- 03/28/17 YS changed length of the part_no column from 25 to 35
			SELECT @lcPartEnd = REPLICATE('Z',35), @lcRevisionEnd=REPLICATE('Z',8)
		ELSE
			SELECT @lcPartEnd =ISNULL(I.Part_no,' '), 
				@lcRevisionEnd = ISNULL(I.Revision,' ') 
			FROM Inventor I where Uniq_key=@lcUniq_keyEnd	

declare @MrpDate smalldatetime = null				
    -- Insert statements for procedure here
	SELECT @lcLastAction=CASE WHEN @lcLastAction is NOT null then @lcLastAction else CAST(DATEADD(Day,Mpssys.viewdays,getdate()) as DATE) end ,@MrpDate = MRPDATE FROM MPSSYS --06/24/2015 DRP:  added the @MrpDate

	-- 10/12/18 VL changed from CTE cursor to tabel variable, hope to speed up
	DECLARE @GetSupplier TABLE (Uniq_Key char(10), PartMfgr char(8), Mfgr_Pt_No char(30), Uniqsupno char(10), UNIQMRPACT char(10),SupName char(50), SuplPartNo char(30))

-- 12/03/13 YS move below @mrpactionview insert
	--DECLARE @Supplier TABLE (Uniqsupno char(10))
	--SELECT @lcUniqSupno =  CASE WHEN @lcUniqSupno is null OR @SupplSelection ='Select Parts with no Default Supplier' THEN '' 
	--						ELSE @lcUniqSupno END

	--IF @lcUniqSupno is not null and @lcUniqSupno <>''
	--	INSERT INTO @Supplier SELECT * FROM dbo.[fn_simpleVarcharlistToTable](@lcUniqSupno,',')


	--declaring the table so that it can be populated using Yelena Stored Procedured called MrpFullActionView
	--- 03/28/17 YS changed length of the part_no column from 25 to 35
	Declare @MrpActionView as table (Uniq_key char(10),Part_class char(8),Part_Type char(8),Part_no char(35),Revision char(8)
									,CustPartNo char(35),CustRev char(8),Descript char(45),Part_sourc char(10),UniqMrpAct char(10))
	
	--08/08/13 YS changed to receive @lcUniqBomParent for the parameters have to send part and revision
	--- 03/28/17 YS changed length of the part_no column from 25 to 35
	DECLARE @lcBomParentPart char(35)='',@lcBomPArentRev char(8) =''
	if @lcUniqBomParent is null OR @lcUniqBomParent=''
		SELECT @lcBomParentPart ='',@lcBomPArentRev =''
	else
		SELECT @lcBomParentPart = I.Part_no,@lcBomPArentRev =I.Revision FROM INVENTOR I where UNIQ_KEY=@lcUniqBomParent 
	--08/08/13 YS}		
--10/01/2013 DRP:  modified the call to the MrpFullActionView below											
	--Insert into @MrpActionView exec MrpFullActionView @lcWhere,@lcBomParentPart,@lcBomPArentRev
	Insert into @MrpActionView exec MrpFullActionView @lcBomParentPart=@lcBomParentPart,@lcBomPArentRev=@lcBomPArentRev									
						
	-- 08/08/13 YS added code to handle suplier list
	--12/03/13 YS get list of approved suppliers for this user
	DECLARE @tSupplier tSupplier
	DECLARE @Supplier TABLE (Uniqsupno char(10))
	INSERT INTO @tSupplier EXEC [aspmnxSP_GetSuppliers4User] @userid, NULL, @supplierStatus;
	
	SELECT @lcUniqSupno =  CASE WHEN @lcUniqSupno is null OR @SupplSelection ='Select Parts with no Default Supplier' THEN '' 
							ELSE @lcUniqSupno END

	--IF @lcUniqSupno is not null and @lcUniqSupno <>''
	--	INSERT INTO @Supplier SELECT * FROM dbo.[fn_simpleVarcharlistToTable](@lcUniqSupno,',')
	 --12/03/13	YS	use 'All' in place of ''. Empty or null means no supplier is entered  	
	IF @lcUniqSupNo<>'All' and @lcUniqSupNo<>'' and @lcUniqSupNo is not null
		insert into @Supplier  select * from  dbo.[fn_simpleVarcharlistToTable](@lcUniqSupNo,',') 
			WHERE cast(ID as char(10)) IN (SELECT UniqSupno from @tSupplier)
	ELSE
	BEGIN
	IF @lcUniqSupNo='All'
	BEGIN
		-- select only one with access
		insert into @Supplier select UniqSupno from @tSupplier
	END
	END		

	-- 08/08/13 YS added code to handle buyer list
	-- 12/11/20 now the buyer is not saved in Buyer_type, it's saved in AspnetBuyer
	--DECLARE @BuyerList TABLE (BUYER_TYPE char(3))
	DECLARE @BuyerList TABLE (BuyerId uniqueidentifier)    
	
	IF @lcBuyer is not null and @lcBuyer <>'' and @lcBuyer <>'All'
	INSERT INTO @BuyerList SELECT * FROM dbo.[fn_simpleVarcharlistToTable](@lcBuyer,',')

	-- 08/08/13 YS added code to handle class list
	DECLARE @PartClass TABLE (part_class char(8))
	
	IF @lcClass is not null and @lcClass <>'' and  @lcClass <>'All'
	INSERT INTO @PartClass SELECT * FROM dbo.[fn_simpleVarcharlistToTable](@lcClass,',')
	 
	declare  @Report Table (
		[UNIQ_KEY] [char](10) NOT NULL,
		[DUE_DATE] [smalldatetime] NULL,
		[STARTDATE] [smalldatetime] NULL,
		[BALANCE] [numeric](9, 0) NOT NULL,
		[REQQTY] [numeric](9, 0) NOT NULL,
		[REF] [char](25) NOT NULL,
		[ACTION] [char](15) NOT NULL,
		[PARENTPT] [char](20) NOT NULL,
		[DTTAKEACT] [smalldatetime] NULL,
		[REQDATE] [smalldatetime] NULL,
		[MFGRS] [text] NOT NULL,
		[DAYS] [numeric](4, 0) NOT NULL,
		[WONO] [char](10) NOT NULL,
		[UNIQMRPACT] [char](10) NOT NULL,
		[UNIQMRPSCH] [char](10) NOT NULL,
		[PRJUNIQUE] [char](10) NOT NULL,
		[PREFAVL] [char](40) NOT NULL,
		[POUNIQLNNO] [char](10) NOT NULL,
		[MATLTYPE] [char](10) NOT NULL,
		--- 03/28/17 YS changed length of the part_no column from 25 to 35
		[part_no] char(35) NOT NULL,
		[Revision]char(8) NOT NULL, 
		Part_Class char(8) NOT NULL, 
		Part_Type char(8) NOT NULL, 
		Descript char(45) NOT NULL,
		U_of_meas char(4) not null, 
		Pur_uofm char(4) not null,
		MrpDate smalldatetime
	 PRIMARY KEY CLUSTERED
	(
		[UNIQMRPACT] ASC
	))
	-- geta all actions according to the criteria enters 
	INSERT INTO @Report
		([UNIQ_KEY] ,
		[DUE_DATE],
		[STARTDATE],
		[BALANCE],
		[REQQTY] ,
		[REF] ,
		[ACTION] ,
		[PARENTPT] ,
		[DTTAKEACT],
		[REQDATE] ,
		[MFGRS],
		[DAYS] ,
		[WONO] ,
		[UNIQMRPACT],
		[UNIQMRPSCH],
		[PRJUNIQUE] ,
		[PREFAVL] ,
		[POUNIQLNNO],
		[MATLTYPE] ,
		[part_no] ,
		[Revision], 
		Part_Class, 
		Part_Type , 
		Descript ,
		U_of_meas, 
		Pur_uofm, 
		MrpDate)
		SELECT mrpact.[UNIQ_KEY] ,
			MrpAct.[DUE_DATE] ,
			MrpAct.[STARTDATE] ,
			MrpAct.[BALANCE] ,
			MrpAct.[REQQTY] ,
			MrpAct.[REF] ,
			MrpAct.[ACTION] ,
			MrpAct.[PARENTPT],
			MrpAct.[DTTAKEACT],
			MrpAct.[REQDATE] ,
			MrpAct.[MFGRS] ,
			MrpAct.[DAYS] ,
			MrpAct.[WONO] ,
			MrpAct.[UNIQMRPACT],
			MrpAct.[UNIQMRPSCH],
			MrpAct.[PRJUNIQUE] ,
			MrpAct.[PREFAVL] ,
			MrpAct.[POUNIQLNNO],
			MrpAct.[MATLTYPE]   , 
			Inventor.Part_No,Inventor.Revision, Inventor.Part_Class, Inventor.Part_Type, Inventor.Descript,
			Inventor.U_of_meas, Inventor.Pur_uofm ,@MrpDate
		FROM MrpAct 
		INNER JOIN @MrpActionView Base ON Mrpact.UniqMrpAct=Base.UniqMrpAct
		INNER JOIN Inventor ON Inventor.Uniq_Key = MrpAct.Uniq_Key
		WHERE  (DATEDIFF(Day,MRPACT.DTTAKEACT,@lcLastAction)>=0 or MRPACT.DTTAKEACT is null)		--06/24/2015 DRP  Replaced:  and DATEDIFF(Day,MRPACT.DTTAKEACT,@lcLastAction)>=0 
		-- 08/08/13 YS change default for part number from '*' to '', indicating all parts are to be selected
		and Inventor.Part_no>= case when @lcPartStart='' then Inventor.Part_no else @lcPartStart END
		and Inventor.PART_NO<= CASE WHEN @lcPartEnd='' THEN Inventor.PART_NO ELSE @lcPartEnd END
		--08/08/13 YS change to be able to use multiple part clasees CSV
		--12/03/13 YS use 'All' for all 
		AND 1= CASE WHEN @lcClass ='All' THEN 1    -- any class
		WHEN Inventor.Part_class IN (SELECT Part_class FROM @PartClass) THEN 1 ELSE 0  END
		--08/08/13 YS change to be able to use multiple buyers CSV
		--12/03/13 YS use 'All' for all 
		AND 1= CASE WHEN @lcBuyer ='All' THEN 1    -- any class
		-- 12/11/20 now the buyer is not saved in Buyer_type, it's saved in AspnetBuyer
		--WHEN INVENTOR.BUYER_TYPE IN (SELECT BUYER_TYPE FROM @BuyerList) THEN 1 ELSE 0  END
		WHEN INVENTOR.AspnetBuyer IN (SELECT BuyerId FROM @BuyerList) THEN 1 ELSE 0  END
		and Base.Uniq_key in (select uniq_key from mrpact where 
							(@lcAction = 'All PO Actions' and MRPACT.ACTION like '%PO%')
							OR (@lcAction = 'Pull Ins' and (MRPACT.ACTION  like '%RESCH PO%' and DATEDIFF(day,REQDATE,DUE_DATE)>0))
							OR (@lcAction = 'Push Outs' and (MRPACT.ACTION  like '%RESCH PO%' and DATEDIFF(day,REQDATE,DUE_DATE)<0))
							or (@lcAction = 'Release PO' and MRPACT.ACTION = 'Release PO')
							OR (@lcAction = 'Cancel PO' and MRPACT.ACTION = 'Cancel PO' )
							)	--06/15/17 DRP  Added
		-- 09/11/18 VL added filter for MRC
		AND 1 = CASE WHEN (@lcMRC = 'All' OR @lcMRC IS NULL OR @lcMRC = '') THEN 1
			WHEN MRC = @lcMRC THEN 1 ELSE 0 END
	-- 10/12/18 VL changed from CTE cursor to tabel variable, hope to speed up
	--;WITH
	--GetSupplier
	--AS
	--(
	INSERT INTO @GetSupplier 
		-- first find suppliers for existing POs
		SELECT DISTINCT MrpPo.Uniq_Key, MrpPo.PartMfgr, MrpPo.Mfgr_Pt_No, MrpPo.Uniqsupno, MRPPO.UNIQMRPACT ,  
					SupInfo.SupName  ,ISNULL(subSupplno.SUPLPARTNO ,SPACE(30) ) as  SuplPartNo
			 FROM MrpPo INNER JOIN @Report SelectMrpAct ON MrpPo.UniqMrpAct = SelectMrpAct.UniqMrpAct 
			 INNER JOIN SupInfo ON MrpPo.uniqsupno = SupInfo.Uniqsupno 
			 OUTER APPLY 
			 --03/12/15 YS replaced invtmfhd table with 2 new tables
				--(Select h.Uniq_key,H.UNIQMFGRHD, Sp.UNIQSUPNO,SP.SUPLPARTNO 
				--	FROM INVTMFHD H INNER JOIN Invtmfsp Sp on H.UNIQMFGRHD =Sp.UNIQMFGRHD  
				--	WHERE h.uniq_key=mrppo.uniq_key and h.PARTMFGR=MrpPo.PartMfgr and h.MFGR_PT_NO = mrppo.MFGR_PT_NO 
				--	and Sp.UNIQSUPNO=Mrppo.UNIQSUPNO ) subSupplno
				(Select l.Uniq_key,l.UNIQMFGRHD, Sp.UNIQSUPNO,SP.SUPLPARTNO 
					FROM Invtmpnlink L INNER JOIN Mfgrmaster M on L.mfgrmasterid=M.mfgrmasterid
					INNER JOIN	Invtmfsp Sp on L.UNIQMFGRHD =Sp.UNIQMFGRHD  
					WHERE l.uniq_key=mrppo.uniq_key and m.PARTMFGR=MrpPo.PartMfgr and m.MFGR_PT_NO = mrppo.MFGR_PT_NO 
					and Sp.UNIQSUPNO=Mrppo.UNIQSUPNO ) subSupplno
			 WHERE SelectMrpAct.Action <> 'Release PO' 
			 --12/03/13 YS use supplier list for which the user has an access 
			 --10/10/17 YS: Move supplier filter to the last sql. in distron data took more than 7 min to return information.
			 --AND Supinfo.UNIQSUPNO IN (SELECT UniqSupno FROM @Supplier) 
		UNION
		-- now find all others which will exclude all that found already I think
		 --03/12/15 YS replaced invtmfhd table with 2 new tables
		SELECT DISTINCT M.Uniq_key, MH.PartMfgr, MH.Mfgr_Pt_No, 
					 S.UNIQSUPNO,M.UniqMrpAct, S.SupName, MfSp.SuplPartNo		--07/07/15 DRP:  flipped the S.UNIQSUPNO AND UNIQMRPACT AROUND.  They were flip flopped before and it was causing the results to not properly be linked. 
		FROM @Report M INNER JOIN 
			--	InvtMfhd MH ON M.Uniq_key=MH.Uniq_key  
			Invtmpnlink L ON M.Uniq_key=L.Uniq_key
			INNER JOIN MfgrMaster MH on l.mfgrmasterid=mh.mfgrmasterid
				INNER JOIN Invtmfgr MFG ON L.UniqMfgrhd=MFG.UniqMfgrhd 
				INNER JOIN InvtMfSp MFSP On  MfSp.UniqMfgrHd = L.UniqMfgrHd 
				INNER JOIN SupInfo S ON MFSP.uniqsupno = S.UNIQSUPNO  
		-- 10/08/18 VL found if partmfgr='GENR' and mfgr_pt_no= '', then next criteria would not work, so separate it into two criteria
		--WHERE CHARINDEX(MH.PartMfgr + ' ' + RTRIM(mh.Mfgr_Pt_No),M.Mfgrs)<>0
		WHERE ((MH.Partmfgr = 'GENR' AND Mfgr_pt_no = '' AND CHARINDEX('GENR',M.Mfgrs)<>0)
		OR NOT(MH.Partmfgr = 'GENR' AND Mfgr_pt_no = '') AND CHARINDEX(MH.PartMfgr + ' ' + RTRIM(mh.Mfgr_Pt_No),M.Mfgrs)<>0)

		AND MFG.Is_Deleted =0
		AND MFSP.IS_DELETED=0
		AND MfSp.PfdSupl = 1
		AND ((@OrderPref1=1 and l.ORDERPREF = 1 ) OR (@OrderPref1<>1))
		-- 03/14/18 VL found record already exist in previous SQL statement, also appear in the 2nd SQL statement, so added SelectMrpAct.Action = 'Release PO' to filter out the duplicate
		AND M.Action = 'Release PO' 
		--and l.ORDERPREF = CASE WHEN @OrderPref1=1 THEN 1 ELSE MH.ORDERPREF END
		 --12/03/13 YS use supplier list for which the user has an access 
		--AND 1= CASE WHEN @lcUniqSupno IS Null OR @lcUniqSupno='' THEN 1    -- any supplier
		--			WHEN S.UNIQSUPNO IN (SELECT UniqSupno FROM @Supplier) THEN 1 ELSE 0  END
		--10/10/17 YS: Move supplier filter to the last sql. in distron data took more than 7 min to return information.
		--AND S.UNIQSUPNO IN (SELECT UniqSupno FROM @Supplier) 
	-- 10/12/18 VL changed from CTE cursor to tabel variable, hope to speed up
	--)
--select * from GetSupplier 

	-- 10/12/18 VL changed from CTE cursor to tabel variable, hope to speed up
	SELECT SelectMrpAct.*,GetSupplier.UniqSupno,GetSupplier.SupName ,
		GetSupplier.Partmfgr,GetSupplier.Mfgr_pt_no  ,GetSupplier.SuplPartNo
		   from @Report SelectMrpAct
					LEFT OUTER JOIN @GetSupplier GetSupplier ON SelectMrpAct.UNIQMRPACT =GetSupplier.UNIQMRPACT  
					-- all aprts with and w/o default suppliers
		WHERE (@SupplSelection ='All' OR (@SupplSelection ='Select Parts with no Default Supplier' AND  (GetSupplier.SuplPartNo is null OR GetSupplier.SuplPartNo='') )
		OR (@SupplSelection ='Select Actions with Default Supplier Assigned' AND  (GetSupplier.SuplPartNo is not null and GetSupplier.SuplPartNo<>'')))
		--10/10/17 YS move to the end to select supplier
		and  GetSupplier.uniqsupno is null OR exists (select 1 from @Supplier where [@Supplier].Uniqsupno=GetSupplier.UNIQSUPNO)
		--10/10/17 YS change the were 
		--1=CASE WHEN @SupplSelection ='All' THEN  1
		--		---- only parts without default supplier
		--		WHEN @SupplSelection ='Select Parts with no Default Supplier' AND  (GetSupplier.SuplPartNo is null OR GetSupplier.SuplPartNo='')  then 1
		--		--- parts with default supplier assigned
		--		WHEN @SupplSelection ='Select Actions with Default Supplier Assigned' AND  (GetSupplier.SuplPartNo is not null and GetSupplier.SuplPartNo<>'') THEN 1 ELSE 0 END	--07/02/15 DRP:  needed to add the closing brakets around the GetSupplier.SuplPartNo is not null and GetSupplier.SuplPartNo<>'' 
order by SUPNAME,Part_Class,Part_Type,part_no,Revision,UNIQ_KEY
				
END