--=============================================================
-- Name : Nitesh B
-- Created Date : 5/15/2016
-- Description: To improve the performance for inventory grid
--=============================================================
CREATE PROCEDURE spMANUFACTURERPTNO_NEW  
(  
@InventorType CHAR(30) = null,
@UNIQUEKEYS AS dbo.UniqueKeys READONLY 
)  
AS  
BEGIN  
IF(@InventorType = 'Internal Inventory')  
  BEGIN  
  SELECT L.ORDERPREF, M.MFGR_PT_NO, M.PARTMFGR, L.UNIQ_KEY, L.UNIQMFGRHD, M.MATLTYPE, M.LDISALLOWBUY, M.LDISALLOWKIT,M.AUTOLOCATION,  
    SUM(ISNULL(W.QTY_OH,0.00)) AS TOTAL_QTY_OH  
  FROM INVTMPNLINK L  
    INNER JOIN MFGRMASTER M ON L.MFGRMASTERID=M.MFGRMASTERID  
    LEFT OUTER JOIN INVTMFGR W ON L.UNIQMFGRHD=W.UNIQMFGRHD AND W.IS_DELETED=0  
  WHERE L.UNIQ_KEY IN (SELECT UNIQKEY FROM @UNIQUEKEYS)
    AND L.IS_DELETED = 0  
    AND M.IS_DELETED = 0  
  GROUP BY L.ORDERPREF, M.MFGR_PT_NO, M.PARTMFGR, L.UNIQ_KEY, L.UNIQMFGRHD, M.MATLTYPE, M.LDISALLOWBUY, M.LDISALLOWKIT,M.AUTOLOCATION  
  ORDER BY L.ORDERPREF, M.PARTMFGR, M.MFGR_PT_NO  
  END  
ELSE IF(@InventorType = 'In-Plant Supplier (IPS)')  
  BEGIN   
  SELECT L.ORDERPREF, M.MFGR_PT_NO, M.PARTMFGR, L.UNIQ_KEY, L.UNIQMFGRHD, M.MATLTYPE, M.LDISALLOWBUY, M.LDISALLOWKIT,M.AUTOLOCATION,  
  SUM(ISNULL(W.QTY_OH,0.00)) AS TOTAL_QTY_OH  
  FROM INVTMPNLINK L  
  INNER JOIN MFGRMASTER M ON L.MFGRMASTERID=M.MFGRMASTERID  
  LEFT OUTER JOIN INVTMFGR W ON L.UNIQMFGRHD=W.UNIQMFGRHD AND W.IS_DELETED=0  
  INNER JOIN SUPINFO S ON W.UNIQSUPNO=S.UNIQSUPNO  
  WHERE L.UNIQ_KEY IN (SELECT UNIQKEY FROM @UNIQUEKEYS)  
  AND L.IS_DELETED = 0  
  AND M.IS_DELETED = 0  
  GROUP BY L.ORDERPREF, M.MFGR_PT_NO, M.PARTMFGR, L.UNIQ_KEY, L.UNIQMFGRHD, M.MATLTYPE, M.LDISALLOWBUY, M.LDISALLOWKIT,M.AUTOLOCATION  
  ORDER BY L.ORDERPREF, M.PARTMFGR, M.MFGR_PT_NO  
  END  
ELSE IF(@InventorType = 'In-Plant Customer (IPC)')  
  BEGIN   
  SELECT L.ORDERPREF, M.MFGR_PT_NO, M.PARTMFGR, L.UNIQ_KEY,L.UNIQMFGRHD, M.MATLTYPE, M.LDISALLOWBUY, M.LDISALLOWKIT,M.AUTOLOCATION,  
  SUM(ISNULL(W.QTY_OH,0.00)) AS TOTAL_QTY_OH  
  FROM INVTMPNLINK L  
  INNER JOIN MFGRMASTER M ON L.MFGRMASTERID=M.MFGRMASTERID  
  LEFT OUTER JOIN INVTMFGR W ON L.UNIQMFGRHD=W.UNIQMFGRHD AND W.IS_DELETED=0  
  WHERE L.UNIQ_KEY IN (SELECT UNIQKEY FROM @UNIQUEKEYS)  
  AND L.IS_DELETED = 0  
  AND M.IS_DELETED = 0  
  GROUP BY L.ORDERPREF, M.MFGR_PT_NO, M.PARTMFGR, L.UNIQ_KEY, L.UNIQMFGRHD, M.MATLTYPE, M.LDISALLOWBUY, M.LDISALLOWKIT,M.AUTOLOCATION
  ORDER BY L.ORDERPREF, M.PARTMFGR, M.MFGR_PT_NO  
  END  
END