-- ======================================================================================
-- Author:		<Avinash>
-- Create date: 06/24/2015
-- Description:	Created for the ICM for Supplier Consigned Filter
-- 06/07/2016 Nitesh B : Added a SUPLPARTNO columns when selecting supplier consg details
-- ======================================================================================
CREATE PROCEDURE spSUPPLIERCONSIGNEDINVENTORY
(
@UNIQMFGRHD NVARCHAR(20)
)
AS
BEGIN
SELECT	S.SUPNAME,S.SUPID,W.WAREHOUSE,MF.LOCATION,ISNULL(P.NUMBEROFPKGS,0) AS NUMBEROFPKGS , MF.QTY_OH,MF.RESERVED,MF.QTY_OH-MF.RESERVED AS AVAILABLE,
		MF.COUNT_DT AS LAST_COUNT,MF.NETABLE,MF.IS_VALIDATED,MF.W_KEY,MF.UNIQMFGRHD,MF.UNIQWH,W.WHNO, Q.SUPLPARTNO
FROM	INVTMFGR MF 
		INNER JOIN WAREHOUS W ON MF.UNIQWH=W.UNIQWH
		INNER JOIN SUPINFO S ON MF.UNIQSUPNO=S.UNIQSUPNO 
		-- 06/07/2016 Nitesh B : Added a SUPLPARTNO columns when selecting supplier consg details
		OUTER APPLY (SELECT SUPLPARTNO from INVTMFSP where UNIQMFGRHD =@UNIQMFGRHD) Q 
		OUTER APPLY (SELECT W_KEY,COUNT(*) AS NUMBEROFPKGS FROM IPKEY WHERE IPKEY.W_KEY=MF.W_KEY AND PKGBALANCE<>0.00 GROUP BY IPKEY.W_KEY) P
WHERE	MF.IS_DELETED=0 AND MF.INSTORE=1 AND UNIQMFGRHD=@UNIQMFGRHD 
END