CREATE TYPE [dbo].[tApAgingFC] AS TABLE (
    [SupName]       CHAR (50)       NULL,
    [InvNo]         CHAR (50)       NULL,
    [InvDate]       SMALLDATETIME   NULL,
    [Due_Date]      SMALLDATETIME   NULL,
    [Trans_Dt]      SMALLDATETIME   NULL,
    [PoNum]         CHAR (15)       NULL,
    [InvAmount]     NUMERIC (12, 2) NULL,
    [BalAmt]        NUMERIC (12, 2) NULL,
    [ApStatus]      CHAR (15)       NULL,
    [Current]       NUMERIC (12, 2) NULL,
    [Range1]        NUMERIC (12, 2) NULL,
    [Range2]        NUMERIC (12, 2) NULL,
    [Range3]        NUMERIC (12, 2) NULL,
    [Range4]        NUMERIC (12, 2) NULL,
    [Over]          NUMERIC (12, 2) NULL,
    [R1Start]       NUMERIC (3)     NULL,
    [R1end]         NUMERIC (3)     NULL,
    [R2Start]       NUMERIC (3)     NULL,
    [R2End]         NUMERIC (3)     NULL,
    [R3Start]       NUMERIC (3)     NULL,
    [R3End]         NUMERIC (3)     NULL,
    [R4Start]       NUMERIC (3)     NULL,
    [R4End]         NUMERIC (3)     NULL,
    [UniqSupno]     CHAR (10)       NULL,
    [Phone]         CHAR (19)       NULL,
    [Terms]         CHAR (15)       NULL,
    [AsofDate]      SMALLDATETIME   NULL,
    [InvAmountFC]   NUMERIC (12, 2) NULL,
    [BalAmtFC]      NUMERIC (12, 2) NULL,
    [CurrentFC]     NUMERIC (12, 2) NULL,
    [Range1FC]      NUMERIC (12, 2) NULL,
    [Range2FC]      NUMERIC (12, 2) NULL,
    [Range3FC]      NUMERIC (12, 2) NULL,
    [Range4FC]      NUMERIC (12, 2) NULL,
    [OverFC]        NUMERIC (12, 2) NULL,
    [Fcused_uniq]   CHAR (10)       NULL,
    [Fchist_key]    CHAR (10)       NULL,
    [Old2NewRate]   NUMERIC (11, 8) NULL,
    [AskPrice]      NUMERIC (13, 5) NULL,
    [InvAmountPR]   NUMERIC (12, 2) NULL,
    [BalAmtPR]      NUMERIC (12, 2) NULL,
    [CurrentPR]     NUMERIC (12, 2) NULL,
    [Range1PR]      NUMERIC (12, 2) NULL,
    [Range2PR]      NUMERIC (12, 2) NULL,
    [Range3PR]      NUMERIC (12, 2) NULL,
    [Range4PR]      NUMERIC (12, 2) NULL,
    [OverPR]        NUMERIC (12, 2) NULL,
    [Old2NewRatePR] NUMERIC (11, 8) NULL,
    [AskPricePR]    NUMERIC (13, 5) NULL,
    [TSymbol]       CHAR (3)        NULL,
    [PSymbol]       CHAR (3)        NULL,
    [FSymbol]       CHAR (3)        NULL);

