CREATE TYPE [dbo].[tArAging] AS TABLE (
    [CUSTNO]    CHAR (10)       NULL,
    [custname]  CHAR (35)       NULL,
    [INVNO]     CHAR (20)       NULL,
    [PONO]      CHAR (20)       NULL,
    [INVDATE]   SMALLDATETIME   NULL,
    [DUE_DATE]  SMALLDATETIME   NULL,
    [InvTotal]  NUMERIC (20, 2) NULL,
    [BalAmt]    NUMERIC (12, 2) NULL,
    [Current]   NUMERIC (12, 2) NULL,
    [Range1]    NUMERIC (12, 2) NULL,
    [Range2]    NUMERIC (12, 2) NULL,
    [Range3]    NUMERIC (12, 2) NULL,
    [Range4]    NUMERIC (12, 2) NULL,
    [Over]      NUMERIC (12, 2) NULL,
    [R1Start]   NUMERIC (3)     NULL,
    [R1End]     NUMERIC (3)     NULL,
    [R2Start]   NUMERIC (3)     NULL,
    [R2End]     NUMERIC (3)     NULL,
    [R3Start]   NUMERIC (3)     NULL,
    [R3End]     NUMERIC (3)     NULL,
    [R4Start]   NUMERIC (3)     NULL,
    [R4End]     NUMERIC (3)     NULL,
    [AsOfDate]  SMALLDATETIME   NULL,
    [phone]     CHAR (19)       NULL,
    [terms]     CHAR (15)       NULL,
    [credlimit] NUMERIC (9)     NULL);

