CREATE TYPE [dbo].[tArAgingFC] AS TABLE (
    [CUSTNO]        CHAR (10)       NULL,
    [custname]      CHAR (35)       NULL,
    [INVNO]         CHAR (20)       NULL,
    [PONO]          CHAR (20)       NULL,
    [INVDATE]       SMALLDATETIME   NULL,
    [DUE_DATE]      SMALLDATETIME   NULL,
    [InvTotal]      NUMERIC (20, 2) NULL,
    [BalAmt]        NUMERIC (12, 2) NULL,
    [Current]       NUMERIC (12, 2) NULL,
    [Range1]        NUMERIC (12, 2) NULL,
    [Range2]        NUMERIC (12, 2) NULL,
    [Range3]        NUMERIC (12, 2) NULL,
    [Range4]        NUMERIC (12, 2) NULL,
    [Over]          NUMERIC (12, 2) NULL,
    [R1Start]       NUMERIC (3)     NULL,
    [R1End]         NUMERIC (3)     NULL,
    [R2Start]       NUMERIC (3)     NULL,
    [R2End]         NUMERIC (3)     NULL,
    [R3Start]       NUMERIC (3)     NULL,
    [R3End]         NUMERIC (3)     NULL,
    [R4Start]       NUMERIC (3)     NULL,
    [R4End]         NUMERIC (3)     NULL,
    [AsOfDate]      SMALLDATETIME   NULL,
    [phone]         CHAR (19)       NULL,
    [terms]         CHAR (15)       NULL,
    [credlimit]     NUMERIC (9)     NULL,
    [InvTotalFC]    NUMERIC (20, 2) NULL,
    [BalAmtFC]      NUMERIC (12, 2) NULL,
    [CurrentFC]     NUMERIC (12, 2) NULL,
    [Range1FC]      NUMERIC (12, 2) NULL,
    [Range2FC]      NUMERIC (12, 2) NULL,
    [Range3FC]      NUMERIC (12, 2) NULL,
    [Range4FC]      NUMERIC (12, 2) NULL,
    [OverFC]        NUMERIC (12, 2) NULL,
    [Fchist_key]    CHAR (10)       NULL,
    [Old2NewRate]   NUMERIC (10, 8) NULL,
    [InvTotalPR]    NUMERIC (20, 2) NULL,
    [BalAmtPR]      NUMERIC (12, 2) NULL,
    [CurrentPR]     NUMERIC (12, 2) NULL,
    [Range1PR]      NUMERIC (12, 2) NULL,
    [Range2PR]      NUMERIC (12, 2) NULL,
    [Range3PR]      NUMERIC (12, 2) NULL,
    [Range4PR]      NUMERIC (12, 2) NULL,
    [OverPR]        NUMERIC (12, 2) NULL,
    [Old2NewRatePR] NUMERIC (10, 8) NULL,
    [TSymbol]       CHAR (3)        NULL,
    [FSymbol]       CHAR (3)        NULL,
    [PSymbol]       CHAR (3)        NULL,
    [Fcused_uniq]   CHAR (10)       NULL);

