CREATE TYPE [dbo].[tBomDet] AS TABLE (
    [Item_no]    NUMERIC (4)     NULL,
    [Part_sourc] CHAR (10)       NULL,
    [ViewPartNo] CHAR (25)       NULL,
    [ViewRev]    CHAR (8)        NULL,
    [Part_class] CHAR (8)        NULL,
    [Part_type]  CHAR (8)        NULL,
    [Descript]   CHAR (45)       NULL,
    [Qty]        NUMERIC (9, 2)  NULL,
    [Part_no]    CHAR (25)       NULL,
    [Revision]   CHAR (8)        NULL,
    [CustPartno] CHAR (25)       NULL,
    [Custrev]    CHAR (8)        NULL,
    [BomParent]  CHAR (10)       NULL,
    [Uniq_key]   CHAR (10)       NULL,
    [Dept_id]    CHAR (4)        NULL,
    [Item_note]  VARCHAR (MAX)   NULL,
    [Offset]     NUMERIC (4)     NULL,
    [Term_dt]    SMALLDATETIME   NULL,
    [Eff_dt]     SMALLDATETIME   NULL,
    [Used_inKit] CHAR (1)        NULL,
    [Custno]     CHAR (10)       NULL,
    [Inv_note]   VARCHAR (MAX)   NULL,
    [U_of_meas]  CHAR (4)        NULL,
    [Scrap]      NUMERIC (6, 2)  NULL,
    [Setupscrap] NUMERIC (4)     NULL,
    [UniqBomno]  CHAR (10)       NOT NULL,
    [Phant_Make] BIT             NULL,
    [StdCost]    NUMERIC (13, 5) NULL,
    [Make_buy]   BIT             NULL,
    [Status]     CHAR (8)        NULL,
    [LeadTime]   INT             NULL,
    PRIMARY KEY CLUSTERED ([UniqBomno] ASC));

