CREATE TYPE [dbo].[timportBOMInventor] AS TABLE (
    [importId]   UNIQUEIDENTIFIER NULL,
    [rowId]      UNIQUEIDENTIFIER NULL,
    [uniq_key]   CHAR (10)        NULL,
    [UseCustPFX] BIT              DEFAULT ((0)) NOT NULL,
    [class]      VARCHAR (10)     NULL,
    [validation] VARCHAR (10)     NULL,
    [Custno]     VARCHAR (MAX)    NULL,
    [CustPartNo] VARCHAR (MAX)    NULL,
    [CustRev]    VARCHAR (MAX)    NULL,
    [Descript]   VARCHAR (MAX)    NULL,
    [Int_uniq]   VARCHAR (MAX)    NULL,
    [Inv_note]   VARCHAR (MAX)    NULL,
    [make_buy]   VARCHAR (MAX)    NULL,
    [Useipkey]   VARCHAR (MAX)    NULL,
    [Part_class] VARCHAR (MAX)    NULL,
    [Part_no]    VARCHAR (MAX)    NULL,
    [Part_sourc] VARCHAR (MAX)    NULL,
    [Part_type]  VARCHAR (MAX)    NULL,
    [Revision]   VARCHAR (MAX)    NULL,
    [Serialyes]  VARCHAR (MAX)    NULL,
    [StdCost]    VARCHAR (MAX)    NULL,
    [U_of_meas]  VARCHAR (MAX)    NULL);

