CREATE TYPE [dbo].[tImportIPS] AS TABLE (
    [Supid]              CHAR (10)       NOT NULL,
    [UniqSupno]          CHAR (10)       NOT NULL,
    [SupName]            CHAR (50)       NOT NULL,
    [Uniq_key]           CHAR (10)       NOT NULL,
    [Qty_oh]             NUMERIC (12, 2) NOT NULL,
    [Part_no]            CHAR (25)       NOT NULL,
    [Revision]           CHAR (8)        NOT NULL,
    [Partmfgr]           CHAR (8)        NOT NULL,
    [Mfgr_pt_no]         CHAR (30)       NOT NULL,
    [Part_class]         CHAR (8)        NOT NULL,
    [Part_type]          CHAR (8)        NOT NULL,
    [U_of_meas]          CHAR (4)        NOT NULL,
    [Pur_Uofm]           CHAR (4)        NOT NULL,
    [Uniqmfgrhd]         CHAR (10)       NOT NULL,
    [Matl_cost]          NUMERIC (13, 5) NOT NULL,
    [StdCost]            NUMERIC (13, 5) NOT NULL,
    [Price]              NUMERIC (13, 5) NOT NULL,
    [Contr_no]           CHAR (20)       NOT NULL,
    [UniqWh]             CHAR (10)       NOT NULL,
    [Whno]               CHAR (3)        NOT NULL,
    [Location]           CHAR (17)       NOT NULL,
    [Warehouse]          CHAR (6)        NOT NULL,
    [Invt_gl_nbr]        CHAR (13)       NOT NULL,
    [AutoLocation]       BIT             NOT NULL,
    [W_key]              CHAR (10)       NOT NULL,
    [Instore]            BIT             NOT NULL,
    [Contr_Uniq]         CHAR (10)       NOT NULL,
    [Mfgr_Uniq]          CHAR (10)       NOT NULL,
    [Pric_uniq]          CHAR (10)       NOT NULL,
    [LotCode]            CHAR (15)       NOT NULL,
    [ExpDate]            SMALLDATETIME   NULL,
    [Reference]          CHAR (12)       NOT NULL,
    [Uniq_lot]           CHAR (10)       NOT NULL,
    [SerialNoM]          VARCHAR (MAX)   NOT NULL,
    [SerialNo]           CHAR (30)       NOT NULL,
    [SerialUniq]         CHAR (10)       NOT NULL,
    [Qty4Price]          NUMERIC (12, 2) NOT NULL,
    [nQpp]               NUMERIC (12, 2) NOT NULL,
    [lInStore]           BIT             NOT NULL,
    [UserId]             CHAR (8)        NOT NULL,
    [lSaveSameContrNo]   BIT             NOT NULL,
    [lOverwriteOldPrice] BIT             NOT NULL,
    [PriceFC]            NUMERIC (13, 5) NOT NULL,
    [Matl_costPR]        NUMERIC (13, 5) NOT NULL,
    [StdCostPR]          NUMERIC (13, 5) NOT NULL,
    [PricePR]            NUMERIC (13, 5) NOT NULL,
    [Fcused_uniq]        CHAR (10)       NULL,
    [Fchis_key]          CHAR (10)       NULL);

