CREATE TYPE [dbo].[tPoCreate] AS TABLE (
    [supname]         CHAR (50)       NULL,
    [PONUM]           CHAR (15)       NULL,
    [PODATE]          SMALLDATETIME   DEFAULT (getdate()) NULL,
    [POSTATUS]        CHAR (8)        DEFAULT ('NEW') NULL,
    [CONUM]           NUMERIC (3)     DEFAULT ((0)) NULL,
    [VERDATE]         SMALLDATETIME   DEFAULT (getdate()) NULL,
    [BUYER]           CHAR (3)        NULL,
    [APPVNAME]        CHAR (8)        NULL,
    [FINALNAME]       CHAR (8)        NULL,
    [POTAX]           NUMERIC (10, 2) NULL,
    [POTOTAL]         NUMERIC (12, 2) NULL,
    [TERMS]           CHAR (15)       NULL,
    [PONOTE]          VARCHAR (MAX)   NULL,
    [POFOOTER]        VARCHAR (MAX)   NULL,
    [CLOSDDATE]       SMALLDATETIME   NULL,
    [IS_PRINTED]      BIT             NULL,
    [C_LINK]          CHAR (10)       NULL,
    [R_LINK]          CHAR (10)       NULL,
    [I_LINK]          CHAR (10)       NULL,
    [B_LINK]          CHAR (10)       NULL,
    [SHIPCHG]         NUMERIC (8, 2)  NULL,
    [IS_SCTAX]        BIT             NULL,
    [SCTAXPCT]        NUMERIC (7, 4)  NULL,
    [CONFNAME]        CHAR (20)       NULL,
    [CONFIRMBY]       CHAR (6)        NULL,
    [SHIPCHARGE]      CHAR (15)       NULL,
    [FOB]             CHAR (15)       NULL,
    [SHIPVIA]         CHAR (15)       NULL,
    [DELTIME]         CHAR (8)        NULL,
    [ISINBATCH]       BIT             NULL,
    [RECONTODT]       NUMERIC (12, 2) NULL,
    [ARCSTAT]         CHAR (8)        NULL,
    [POPRIORITY]      CHAR (10)       DEFAULT ('Standard') NULL,
    [POACKNDOC]       VARCHAR (200)   NULL,
    [VERINIT]         CHAR (8)        NULL,
    [UNIQSUPNO]       CHAR (10)       NULL,
    [POCHANGES]       VARCHAR (MAX)   NULL,
    [LFREIGHTINCLUDE] BIT             NULL,
    [UNIQLNNO]        CHAR (10)       NULL,
    [UNIQ_KEY]        CHAR (10)       NULL,
    [ITEMNO]          CHAR (3)        NULL,
    [COSTEACH]        NUMERIC (13, 5) NULL,
    [ORD_QTY]         NUMERIC (10, 2) NULL,
    [RECV_QTY]        NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [REJ_QTY]         NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [ACPT_QTY]        NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [NOTE1]           VARCHAR (MAX)   NULL,
    [IS_TAX]          BIT             NULL,
    [TAX_ID]          CHAR (10)       NULL,
    [IS_CONTR]        BIT             NULL,
    [OVERAGE]         NUMERIC (5, 2)  NULL,
    [POITTYPE]        CHAR (9)        NULL,
    [L_PRINT]         BIT             NULL,
    [NO_PKG]          NUMERIC (9, 2)  NULL,
    [PART_NO]         CHAR (25)       NULL,
    [REVISION]        CHAR (8)        NULL,
    [DESCRIPT]        CHAR (45)       NULL,
    [PARTMFGR]        CHAR (8)        NULL,
    [MFGR_PT_NO]      CHAR (30)       NULL,
    [PACKAGE]         CHAR (15)       NULL,
    [PART_CLASS]      CHAR (8)        NULL,
    [PART_TYPE]       CHAR (8)        NULL,
    [U_OF_MEAS]       CHAR (4)        NULL,
    [PUR_UOFM]        CHAR (4)        NULL,
    [S_ORD_QTY]       NUMERIC (10, 2) NULL,
    [ISFIRM]          BIT             NULL,
    [UNIQMFGRHD]      CHAR (10)       NULL,
    [FIRSTARTICLE]    BIT             NULL,
    [INSPEXCEPT]      BIT             NULL,
    [INSPEXCEPTION]   CHAR (20)       NULL,
    [INSPEXCINIT]     CHAR (3)        NULL,
    [INSPEXCDT]       SMALLDATETIME   NULL,
    [INSPEXCNOTE]     VARCHAR (MAX)   NULL,
    [INSPEXCDOC]      VARCHAR (200)   NULL,
    [uniqmfsp]        CHAR (10)       NULL,
    [LCANCEL]         BIT             DEFAULT ((0)) NULL,
    [UNIQDETNO]       CHAR (10)       NULL,
    [SCHD_DATE]       SMALLDATETIME   NULL,
    [REQ_DATE]        SMALLDATETIME   NULL,
    [SCHD_QTY]        NUMERIC (10, 2) NULL,
    [RECDQTY]         NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [BALANCE]         NUMERIC (10, 2) NULL,
    [GL_NBR]          CHAR (13)       NULL,
    [REQUESTTP]       CHAR (10)       NULL,
    [REQUESTOR]       CHAR (40)       NULL,
    [UNIQWH]          CHAR (10)       NULL,
    [LOCATION]        CHAR (17)       NULL,
    [WONUMBER]        CHAR (10)       NULL,
    [PRJNUMBER]       CHAR (10)       NULL,
    [COMPLETEDT]      SMALLDATETIME   NULL,
    [ORIGCOMMITDT]    SMALLDATETIME   NULL,
    [SCHDNOTES]       VARCHAR (MAX)   NULL,
    [warehouse]       CHAR (6)        NULL,
    [UniqMrpAct]      CHAR (10)       NULL,
    [PoUnique]        CHAR (10)       DEFAULT ('') NOT NULL,
    [fcused_uniq]     CHAR (10)       DEFAULT ('') NOT NULL,
    [fchist_key]      CHAR (10)       DEFAULT ('') NOT NULL,
    [POTAXfc]         NUMERIC (10, 2) DEFAULT ((0)) NOT NULL,
    [POTOTALfc]       NUMERIC (12, 2) DEFAULT ((0)) NOT NULL,
    [SHIPCHGfc]       NUMERIC (8, 2)  DEFAULT ((0)) NOT NULL,
    [RECONTODTFC]     NUMERIC (12, 2) DEFAULT ((0)) NOT NULL,
    [COSTEACHfc]      NUMERIC (15, 7) DEFAULT ((0)) NOT NULL,
    [UseDefaultTax]   BIT             DEFAULT ((0)) NOT NULL,
    [defaultTaxId]    CHAR (8)        DEFAULT ('') NOT NULL,
    [defaultTaxRate]  NUMERIC (8, 4)  DEFAULT ((0.00)) NOT NULL,
    [POTAXPR]         NUMERIC (10, 2) DEFAULT ((0)) NOT NULL,
    [POTOTALPR]       NUMERIC (12, 2) DEFAULT ((0)) NOT NULL,
    [SHIPCHGPR]       NUMERIC (8, 2)  DEFAULT ((0)) NOT NULL,
    [RECONTODTPR]     NUMERIC (12, 2) DEFAULT ((0)) NOT NULL,
    [COSTEACHPR]      NUMERIC (15, 7) DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       DEFAULT ('') NOT NULL);

