CREATE TYPE [dbo].[tPODetails] AS TABLE (
    [ImportId]        UNIQUEIDENTIFIER NULL,
    [RowId]           UNIQUEIDENTIFIER NULL,
    [CssClass]        CHAR (10)        NULL,
    [Validation]      CHAR (10)        NULL,
    [UniqLnNo]        CHAR (10)        NULL,
    [CONFTO]          CHAR (20)        NULL,
    [COSTEACH]        NUMERIC (13, 5)  NULL,
    [COSTEACHFC]      NUMERIC (13)     NULL,
    [DESCRIPT]        CHAR (60)        NULL,
    [FIRSTARTICLE]    BIT              DEFAULT ((0)) NULL,
    [GLNBR]           CHAR (13)        NULL,
    [INSPEXCEPT]      BIT              DEFAULT ((0)) NULL,
    [INSPEXCEPTION]   CHAR (20)        NULL,
    [INSPEXNOTE]      TEXT             NULL,
    [IS_SCTAX]        BIT              DEFAULT ((0)) NULL,
    [ISFIRM]          BIT              DEFAULT ((0)) NULL,
    [ITEMNO]          CHAR (4)         NULL,
    [ITEMNOTE]        VARCHAR (MAX)    NULL,
    [LFREIGHTINCLUDE] BIT              DEFAULT ((0)) NULL,
    [LOCATION]        CHAR (256)       NULL,
    [MFGR_PT_NO]      CHAR (30)        NULL,
    [MINORD]          NUMERIC (7)      DEFAULT ((0)) NULL,
    [ORD_QTY]         NUMERIC (10, 2)  NULL,
    [ORDMULT]         NUMERIC (7)      DEFAULT ((0)) NULL,
    [ORIGCOMMITDT]    SMALLDATETIME    NULL,
    [PARTMFGR]        CHAR (8)         NULL,
    [PARTNO]          CHAR (35)        NULL,
    [POITTYPE]        CHAR (10)        NULL,
    [PONOTE]          CHAR (10)        NULL,
    [PUR_LTIME]       NUMERIC (3)      DEFAULT ((0)) NULL,
    [PUR_LUNIT]       CHAR (2)         NULL,
    [PUR_UOFM]        CHAR (4)         NULL,
    [REQUESTOR]       CHAR (40)        NULL,
    [REQUESTTP]       CHAR (10)        NULL,
    [REVISION]        CHAR (15)        NULL,
    [S_ORD_QTY]       NUMERIC (10, 2)  NULL,
    [SCHDDATE]        SMALLDATETIME    NULL,
    [SCHDQTY]         NUMERIC (9)      NULL,
    [SCTAXPCT]        CHAR (10)        NULL,
    [SHIPCHGAMOUNT]   NUMERIC (15)     NULL,
    [TAXABLE]         CHAR (20)        NULL,
    [TAXID]           CHAR (10)        NULL,
    [TERMS]           CHAR (10)        NULL,
    [WAREHOUSE]       CHAR (30)        NULL,
    [WOPRJNUMBER]     CHAR (10)        NULL,
    [ORD_QTYF]        NUMERIC (9, 2)   NULL,
    [COSTEACHF]       NUMERIC (13, 5)  NULL);

