CREATE TYPE [dbo].[tWipDueDt] AS TABLE (
    [WONO]       CHAR (10)       NULL,
    [due_date]   SMALLDATETIME   NULL,
    [OpenClos]   CHAR (10)       NULL,
    [CUSTNAME]   CHAR (35)       NULL,
    [Uniq_key]   CHAR (10)       NULL,
    [PART_NO]    CHAR (25)       NULL,
    [REVISION]   CHAR (8)        NULL,
    [PROD_ID]    CHAR (10)       NULL,
    [PART_CLASS] CHAR (8)        NULL,
    [PART_TYPE]  CHAR (8)        NULL,
    [descript]   CHAR (45)       NULL,
    [Kit]        BIT             NULL,
    [SoNo]       CHAR (10)       NULL,
    [BldQty]     NUMERIC (13)    NULL,
    [BalQty]     NUMERIC (13)    NULL,
    [Dept_Id]    CHAR (4)        NULL,
    [NUMBER]     NUMERIC (4)     NULL,
    [Dept_name]  CHAR (25)       NULL,
    [Curr_Qty]   NUMERIC (13)    NULL,
    [uniqueln]   CHAR (10)       NULL,
    [Price]      NUMERIC (12, 5) NULL,
    [PoNo]       CHAR (20)       NULL);

