CREATE TYPE [dbo].[tWip] AS TABLE (
    [WoNo]       CHAR (10)       NULL,
    [Due_Date]   SMALLDATETIME   NULL,
    [OpenClos]   CHAR (10)       NULL,
    [CustName]   CHAR (50)       NULL,
    [Uniq_key]   CHAR (10)       NULL,
    [part_no]    CHAR (25)       NULL,
    [revision]   CHAR (8)        NULL,
    [Prod_id]    CHAR (10)       NULL,
    [Part_Class] CHAR (8)        NULL,
    [Part_type]  CHAR (8)        NULL,
    [Kit]        BIT             NULL,
    [SoNo]       CHAR (10)       NULL,
    [BldQty]     NUMERIC (13)    NULL,
    [BalQty]     NUMERIC (13)    NULL,
    [Buildable]  NUMERIC (13)    NULL,
    [Dept_Id]    CHAR (4)        NULL,
    [Number]     NUMERIC (4)     NULL,
    [Curr_Qty]   NUMERIC (13)    NULL,
    [RunTime]    NUMERIC (11, 5) NULL,
    [SetupTime]  NUMERIC (11, 5) NULL,
    [Priority]   NUMERIC (7, 3)  NULL,
    [JobType]    CHAR (10)       NULL);

