-- =============================================
-- Author:		Yelena Shmidt
-- Create date: 05/08/2012
-- Description:	get information for MRP replaces zMpsInvt cursor
-- =============================================
CREATE PROCEDURE [dbo].[zMpsInvt] 
	-- Add the parameters for the stored procedure here
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	--05/24/12 YS populate MrpInvt. I am not sure why we need this table, but for now
	-- will populate here and no need to update in the mupdatetables when running mrp
	TRUNCATE TABLE [MrpInvt]
	INSERT INTO [MrpInvt]
           ([UNIQ_KEY]
           ,[PART_CLASS]
           ,[PART_TYPE]
           ,[CUSTNO]
           ,[PART_NO]
           ,[REVISION]
           ,[PROD_ID]
           ,[CUSTPARTNO]
           ,[CUSTREV]
           ,[DESCRIPT]
           ,[U_OF_MEAS]
           ,[PUR_UOFM]
           ,[ORD_POLICY]
           ,[PACKAGE]
           ,[NO_PKG]
           ,[INV_NOTE]
           ,[BUYER_TYPE]
           ,[STDCOST]
           ,[MINORD]
           ,[ORDMULT]
           ,[USERCOST]
           ,[PULL_IN]
           ,[PUSH_OUT]
           ,[PTLENGTH]
           ,[PTWIDTH]
           ,[PTDEPTH]
           ,[FGINOTE]
           ,[STATUS]
           ,[PERPANEL]
           ,[ABC]
           ,[LAYER]
           ,[PTWT]
           ,[GROSSWT]
           ,[REORDERQTY]
           ,[REORDPOINT]
           ,[PART_SPEC]
           ,[PUR_LTIME]
           ,[PUR_LUNIT]
           ,[KIT_LTIME]
           ,[KIT_LUNIT]
           ,[PROD_LTIME]
           ,[PROD_LUNIT]
           ,[UDFFIELD1]
           ,[WT_AVG]
           ,[PART_SOURC]
           ,[INSP_REQ]
           ,[CERT_REQ]
           ,[CERT_TYPE]
           ,[SCRAP]
           ,[SETUPSCRAP]
           ,[OUTSNOTE]
           ,[BOM_STATUS]
           ,[BOM_NOTE]
           ,[BOM_LASTDT]
           ,[SERIALYES]
           ,[LOC_TYPE]
           ,[DAY]
           ,[DAYOFMO]
           ,[DAYOFMO2]
           ,[SALETYPEID]
           ,[FEEDBACK]
           ,[ENG_NOTE]
           ,[BOMCUSTNO]
           ,[LABORCOST]
           ,[INT_UNIQ]
           ,[EAU]
           ,[REQUIRE_SN]
           ,[OHCOST]
           ,[PHANT_MAKE]
           ,[CNFGCUSTNO]
           ,[CONFGDATE]
           ,[CONFGNOTE]
           ,[XFERDATE]
           ,[XFERBY]
           ,[PRODTPUNIQ]
           ,[MRP_CODE]
           ,[MAKE_BUY]
           ,[LABOR_OH]
           ,[MATL_OH]
           ,[MATL_COST]
           ,[OVERHEAD]
           ,[OTHER_COST]
           ,[STDBLDQTY]
           ,[USESETSCRP]
           ,[CONFIGCOST]
           ,[OTHERCOST2]
           ,[MATDT]
           ,[LABDT]
           ,[OHDT]
           ,[OTHDT]
           ,[OTH2DT]
           ,[STDDT]
           ,[ARCSTAT]
           ,[IS_NCNR]
           ,[TOOLREL]
           ,[TOOLRELDT]
           ,[TOOLRELINT]
           ,[PDMREL]
           ,[PDMRELDT]
           ,[PDMRELINT]
           ,[ITEMLOCK]
           ,[LOCKDT]
           ,[LOCKINIT]
           ,[LASTCHANGEDT]
           ,[LASTCHANGEINIT]
           ,[BOMLOCK]
           ,[BOMLOCKINIT]
           ,[BOMLOCKDT]
           ,[BOMLASTINIT]
           ,[ROUTREL]
           ,[ROUTRELDT]
           ,[ROUTRELINT]
           ,[TARGETPRICE]
           ,[FIRSTARTICLE]
           ,[MRC]
           ,[TARGETPRICEDT]
           ,[PPM]
           ,[MATLTYPE]
           ,[NEWITEMDT]
           ,[BOMINACTDT]
           ,[BOMINACTINIT]
           ,[MTCHGDT]
           ,[MTCHGINIT]
           ,[BOMITEMARC]
           ,[CNFGITEMARC]
           ,[C_LOG])
           SELECT [UNIQ_KEY]
      ,[PART_CLASS]
      ,[PART_TYPE]
      ,[CUSTNO]
      ,[PART_NO]
      ,[REVISION]
      ,[PROD_ID]
      ,[CUSTPARTNO]
      ,[CUSTREV]
      ,[DESCRIPT]
      ,[U_OF_MEAS]
      ,[PUR_UOFM]
      ,[ORD_POLICY]
      ,[PACKAGE]
      ,[NO_PKG]
      ,[INV_NOTE]
      ,[BUYER_TYPE]
      ,[STDCOST]
      ,[MINORD]
      ,[ORDMULT]
      ,[USERCOST]
      ,[PULL_IN]
      ,[PUSH_OUT]
      ,[PTLENGTH]
      ,[PTWIDTH]
      ,[PTDEPTH]
      ,[FGINOTE]
      ,[STATUS]
      ,[PERPANEL]
      ,[ABC]
      ,[LAYER]
      ,[PTWT]
      ,[GROSSWT]
      ,[REORDERQTY]
      ,[REORDPOINT]
      ,[PART_SPEC]
      ,[PUR_LTIME]
      ,[PUR_LUNIT]
      ,[KIT_LTIME]
      ,[KIT_LUNIT]
      ,[PROD_LTIME]
      ,[PROD_LUNIT]
      ,[UDFFIELD1]
      ,[WT_AVG]
      ,[PART_SOURC]
      ,[INSP_REQ]
      ,[CERT_REQ]
      ,[CERT_TYPE]
      ,[SCRAP]
      ,[SETUPSCRAP]
      ,[OUTSNOTE]
      ,[BOM_STATUS]
      ,[BOM_NOTE]
      ,[BOM_LASTDT]
      ,[SERIALYES]
      ,[LOC_TYPE]
      ,[DAY]
      ,[DAYOFMO]
      ,[DAYOFMO2]
      ,[SALETYPEID]
      ,[FEEDBACK]
      ,[ENG_NOTE]
      ,[BOMCUSTNO]
      ,[LABORCOST]
      ,[INT_UNIQ]
      ,[EAU]
      ,[REQUIRE_SN]
      ,[OHCOST]
      ,[PHANT_MAKE]
      ,[CNFGCUSTNO]
      ,[CONFGDATE]
      ,[CONFGNOTE]
      ,[XFERDATE]
      ,[XFERBY]
      ,[PRODTPUNIQ]
      ,[MRP_CODE]
      ,[MAKE_BUY]
      ,[LABOR_OH]
      ,[MATL_OH]
      ,[MATL_COST]
      ,[OVERHEAD]
      ,[OTHER_COST]
      ,[STDBLDQTY]
      ,[USESETSCRP]
      ,[CONFIGCOST]
      ,[OTHERCOST2]
      ,[MATDT]
      ,[LABDT]
      ,[OHDT]
      ,[OTHDT]
      ,[OTH2DT]
      ,[STDDT]
      ,[ARCSTAT]
      ,[IS_NCNR]
      ,[TOOLREL]
      ,[TOOLRELDT]
      ,[TOOLRELINT]
      ,[PDMREL]
      ,[PDMRELDT]
      ,[PDMRELINT]
      ,[ITEMLOCK]
      ,[LOCKDT]
      ,[LOCKINIT]
      ,[LASTCHANGEDT]
      ,[LASTCHANGEINIT]
      ,[BOMLOCK]
      ,[BOMLOCKINIT]
      ,[BOMLOCKDT]
      ,[BOMLASTINIT]
      ,[ROUTREL]
      ,[ROUTRELDT]
      ,[ROUTRELINT]
      ,[TARGETPRICE]
      ,[FIRSTARTICLE]
      ,[MRC]
      ,[TARGETPRICEDT]
      ,[PPM]
      ,[MATLTYPE]
      ,[NEWITEMDT]
      ,[BOMINACTDT]
      ,[BOMINACTINIT]
      ,[MTCHGDT]
      ,[MTCHGINIT]
      ,[BOMITEMARC]
      ,[CNFGITEMARC]
      ,[C_LOG]
  FROM Inventor
	select inventor.*,
		CASE WHEN Part_Sourc = 'BUY' OR (Part_sourc='MAKE' and MAKE_BUY=1) THEN 
				CAST(CASE WHEN Pur_LUnit='DY' THEN Pur_LTime
						  WHEN  Pur_LUnit='WK' THEN Pur_LTime*5
				          WHEN Pur_LUnit='MO' THEN Pur_LTime*20
				     ELSE 0 END AS Numeric(6))
			WHEN PART_SOURC='MAKE' THEN
	 			CAST(CASE WHEN PROD_LUNIT='DY' THEN Prod_ltime
						  WHEN  PROD_LUNIT='WK' THEN Prod_ltime*5
						  WHEN PROD_LUNIT='MO' THEN Prod_ltime*20
					ELSE 0 END +
				CASE WHEN Kit_LUNIT='DY' THEN Kit_ltime
						WHEN  Kit_LUNIT='WK' THEN Kit_ltime*5
						WHEN Kit_LUNIT='MO' THEN Kit_ltime*20
						ELSE 0 END as numeric(6))
			ELSE
				cast(0 as numeric(6))	  
			END   AS L_TimeD 
			FROM inventor	
END