CREATE TABLE [dbo].[ACCTSREC] (
    [CUSTNO]                CHAR (10)        CONSTRAINT [DF__ACCTSREC__CUSTNO__0BC6C43E] DEFAULT ('') NOT NULL,
    [INVNO]                 CHAR (10)        CONSTRAINT [DF__ACCTSREC__INVNO__0CBAE877] DEFAULT ('') NOT NULL,
    [INVDATE]               SMALLDATETIME    NULL,
    [INVTOTAL]              NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__INVTOT__0DAF0CB0] DEFAULT ((0)) NOT NULL,
    [DUE_DATE]              SMALLDATETIME    NULL,
    [ARCREDITS]             NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__ARCRED__0EA330E9] DEFAULT ((0)) NOT NULL,
    [ARNOTE]                TEXT             CONSTRAINT [DF__ACCTSREC__ARNOTE__0F975522] DEFAULT ('') NOT NULL,
    [UNIQUEAR]              CHAR (10)        CONSTRAINT [DF__ACCTSREC__UNIQUE__108B795B] DEFAULT ('') NOT NULL,
    [lPrepay]               BIT              CONSTRAINT [DF_ACCTSREC_lPrepay] DEFAULT ((0)) NOT NULL,
    [INVTOTALFC]            NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__INVTOT__23169FEF] DEFAULT ((0)) NOT NULL,
    [ARCREDITSFC]           NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__ARCRED__240AC428] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ]           CHAR (10)        CONSTRAINT [DF__ACCTSREC__FCUSED__24FEE861] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]            CHAR (10)        CONSTRAINT [DF__ACCTSREC__FCHIST__25F30C9A] DEFAULT ('') NOT NULL,
    [isManualCM]            BIT              CONSTRAINT [DF_ACCTSREC_isManualCM] DEFAULT ((0)) NOT NULL,
    [INVTOTALPR]            NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__INVTOT__25AA8A85] DEFAULT ((0)) NOT NULL,
    [ARCREDITSPR]           NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__ARCRED__269EAEBE] DEFAULT ((0)) NOT NULL,
    [PRFcused_Uniq]         CHAR (10)        CONSTRAINT [DF__ACCTSREC__PRFcus__2886F730] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ]       CHAR (10)        CONSTRAINT [DF__ACCTSREC__FUNCFC__2A6F3FA2] DEFAULT ('') NOT NULL,
    [DiscTaken]             NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__DiscTa__58F5EFB8] DEFAULT ((0.00)) NOT NULL,
    [DiscTakenFc]           NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__DiscTa__59EA13F1] DEFAULT ((0.00)) NOT NULL,
    [DiscTakenPr]           NUMERIC (20, 2)  CONSTRAINT [DF__ACCTSREC__DiscTa__5ADE382A] DEFAULT ((0.00)) NOT NULL,
    [LastInvoiceSent]       DATETIME2 (7)    NULL,
    [LastInvoiceSentUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [ACCTSREC_PK] PRIMARY KEY CLUSTERED ([UNIQUEAR] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTDUEDT]
    ON [dbo].[ACCTSREC]([CUSTNO] ASC, [DUE_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [CUSTINVNO]
    ON [dbo].[ACCTSREC]([CUSTNO] ASC, [INVNO] ASC);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[ACCTSREC]([CUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [INVNO]
    ON [dbo].[ACCTSREC]([INVNO] ASC);

