CREATE TABLE [dbo].[ACTCAP] (
    [DEPT_ID]    CHAR (4)    CONSTRAINT [DF__ACTCAP__DEPT_ID__1367E606] DEFAULT ('') NOT NULL,
    [ACTIV_ID]   CHAR (4)    CONSTRAINT [DF__ACTCAP__ACTIV_ID__145C0A3F] DEFAULT ('') NOT NULL,
    [SHIFT_NO]   NUMERIC (3) CONSTRAINT [DF__ACTCAP__SHIFT_NO__164452B1] DEFAULT ((0)) NOT NULL,
    [UNIQ_CAP]   CHAR (10)   CONSTRAINT [DF__ACTCAP__UNIQ_CAP__173876EA] DEFAULT ('') NOT NULL,
    [STARTMONTH] NUMERIC (2) CONSTRAINT [DF__ACTCAP__STARTMON__182C9B23] DEFAULT ((0)) NOT NULL,
    [RESMONTH1]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1920BF5C] DEFAULT ((0)) NOT NULL,
    [RESMONTH2]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1A14E395] DEFAULT ((0)) NOT NULL,
    [RESMONTH3]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1B0907CE] DEFAULT ((0)) NOT NULL,
    [RESMONTH4]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1BFD2C07] DEFAULT ((0)) NOT NULL,
    [RESMONTH5]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1CF15040] DEFAULT ((0)) NOT NULL,
    [RESMONTH6]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1DE57479] DEFAULT ((0)) NOT NULL,
    [RESMONTH7]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1ED998B2] DEFAULT ((0)) NOT NULL,
    [RESMONTH8]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__1FCDBCEB] DEFAULT ((0)) NOT NULL,
    [RESMONTH9]  NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__20C1E124] DEFAULT ((0)) NOT NULL,
    [RESMONTH10] NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__21B6055D] DEFAULT ((0)) NOT NULL,
    [RESMONTH11] NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__22AA2996] DEFAULT ((0)) NOT NULL,
    [RESMONTH12] NUMERIC (3) CONSTRAINT [DF__ACTCAP__RESMONTH__239E4DCF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ACTCAP_PK] PRIMARY KEY CLUSTERED ([UNIQ_CAP] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEPTACTSFT]
    ON [dbo].[ACTCAP]([DEPT_ID] ASC, [ACTIV_ID] ASC, [SHIFT_NO] ASC);

