CREATE TABLE [dbo].[ACTPKG] (
    [ACTIV_ID]    CHAR (4)       CONSTRAINT [DF__ACTPKG__ACTIV_ID__46E78A0C] DEFAULT ('') NOT NULL,
    [UNIQPKG]     CHAR (10)      CONSTRAINT [DF__ACTPKG__UNIQPKG__47DBAE45] DEFAULT ('') NOT NULL,
    [VOL_HR]      NUMERIC (8, 2) CONSTRAINT [DF__ACTPKG__VOL_HR__48CFD27E] DEFAULT ((0)) NOT NULL,
    [YIELD]       NUMERIC (6, 2) CONSTRAINT [DF__ACTPKG__YIELD__49C3F6B7] DEFAULT ((0)) NOT NULL,
    [UNIQUERECID] CHAR (10)      CONSTRAINT [DF__ACTPKG__UNIQUERE__4AB81AF0] DEFAULT ('') NOT NULL,
    CONSTRAINT [ACTPKG_PK] PRIMARY KEY CLUSTERED ([UNIQUERECID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACTIDPKGID]
    ON [dbo].[ACTPKG]([ACTIV_ID] ASC, [UNIQPKG] ASC);


GO
CREATE NONCLUSTERED INDEX [ACTIV_ID]
    ON [dbo].[ACTPKG]([ACTIV_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQPKG]
    ON [dbo].[ACTPKG]([UNIQPKG] ASC);

