CREATE TABLE [dbo].[ACTSETTP] (
    [ACTIV_ID]   CHAR (4)    CONSTRAINT [DF__ACTSETTP__ACTIV___560B68B9] DEFAULT ('') NOT NULL,
    [ACTSETTPID] CHAR (10)   CONSTRAINT [DF__ACTSETTP__ACTSET__56FF8CF2] DEFAULT ('') NOT NULL,
    [TIME_MIN]   NUMERIC (6) CONSTRAINT [DF__ACTSETTP__TIME_M__57F3B12B] DEFAULT ((0)) NOT NULL,
    [SETUPINSTR] TEXT        CONSTRAINT [DF__ACTSETTP__SETUPI__58E7D564] DEFAULT ('') NOT NULL,
    [SETUPPICT]  CHAR (200)  CONSTRAINT [DF__ACTSETTP__SETUPP__59DBF99D] DEFAULT ('') NOT NULL,
    [ACTSETTPUK] CHAR (10)   CONSTRAINT [DF__ACTSETTP__ACTSET__5AD01DD6] DEFAULT ('') NOT NULL,
    CONSTRAINT [ACTSETTP_PK] PRIMARY KEY CLUSTERED ([ACTSETTPUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACTIDSETID]
    ON [dbo].[ACTSETTP]([ACTIV_ID] ASC, [ACTSETTPID] ASC);


GO
CREATE NONCLUSTERED INDEX [ACTIV_ID]
    ON [dbo].[ACTSETTP]([ACTIV_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [ACTSETTPID]
    ON [dbo].[ACTSETTP]([ACTSETTPID] ASC);

