CREATE TABLE [dbo].[ACTSETST] (
    [ACTSETTPNM] CHAR (25)   CONSTRAINT [DF__ACTSETST__ACTSET__4E88ABD4] DEFAULT ('') NOT NULL,
    [NUMBER]     NUMERIC (3) CONSTRAINT [DF__ACTSETST__NUMBER__4F7CD00D] DEFAULT ((0)) NOT NULL,
    [ACTSETTPID] CHAR (10)   CONSTRAINT [DF__ACTSETST__ACTSET__4D94879B] DEFAULT ('') NOT NULL,
    CONSTRAINT [ACTSETST_PK] PRIMARY KEY CLUSTERED ([ACTSETTPID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACTSETTPNM]
    ON [dbo].[ACTSETST]([ACTSETTPNM] ASC);


GO
CREATE NONCLUSTERED INDEX [NUMBER]
    ON [dbo].[ACTSETST]([NUMBER] ASC);

