CREATE TABLE [dbo].[ACTV_QTY] (
    [WONO]        CHAR (10)   CONSTRAINT [DF__ACTV_QTY__WONO__628FA481] DEFAULT ('') NOT NULL,
    [ACTIV_ID]    CHAR (4)    CONSTRAINT [DF__ACTV_QTY__ACTIV___6383C8BA] DEFAULT ('') NOT NULL,
    [CURR_QTY]    NUMERIC (7) CONSTRAINT [DF__ACTV_QTY__CURR_Q__6477ECF3] DEFAULT ((0)) NOT NULL,
    [XFER_QTY]    NUMERIC (7) CONSTRAINT [DF__ACTV_QTY__XFER_Q__656C112C] DEFAULT ((0)) NOT NULL,
    [XFER_MIN]    NUMERIC (6) CONSTRAINT [DF__ACTV_QTY__XFER_M__66603565] DEFAULT ((0)) NOT NULL,
    [XFER_SETUP]  NUMERIC (6) CONSTRAINT [DF__ACTV_QTY__XFER_S__6754599E] DEFAULT ((0)) NOT NULL,
    [NUMBERA]     NUMERIC (4) CONSTRAINT [DF__ACTV_QTY__NUMBER__68487DD7] DEFAULT ((0)) NOT NULL,
    [DEPTKEY]     CHAR (10)   CONSTRAINT [DF__ACTV_QTY__DEPTKE__693CA210] DEFAULT ('') NOT NULL,
    [WO_WC_NOTE]  TEXT        CONSTRAINT [DF__ACTV_QTY__WO_WC___6A30C649] DEFAULT ('') NOT NULL,
    [ACTVKEY]     CHAR (10)   CONSTRAINT [DF__ACTV_QTY__ACTVKE__6B24EA82] DEFAULT ('') NOT NULL,
    [UNIQUERECID] CHAR (10)   CONSTRAINT [DF__ACTV_QTY__UNIQUE__6C190EBB] DEFAULT ('') NOT NULL,
    CONSTRAINT [ACTV_QTY_PK] PRIMARY KEY CLUSTERED ([UNIQUERECID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACTIV_ID]
    ON [dbo].[ACTV_QTY]([ACTIV_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [CURR_QTY]
    ON [dbo].[ACTV_QTY]([CURR_QTY] ASC);


GO
CREATE NONCLUSTERED INDEX [DEPTKEY]
    ON [dbo].[ACTV_QTY]([DEPTKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [DEPTKEYID]
    ON [dbo].[ACTV_QTY]([WONO] ASC, [DEPTKEY] ASC, [ACTVKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [DEPTKEYNUM]
    ON [dbo].[ACTV_QTY]([WONO] ASC, [DEPTKEY] ASC, [NUMBERA] ASC);


GO
CREATE NONCLUSTERED INDEX [NUMBERA]
    ON [dbo].[ACTV_QTY]([NUMBERA] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[ACTV_QTY]([WONO] ASC);


GO
CREATE NONCLUSTERED INDEX [WONOACTV]
    ON [dbo].[ACTV_QTY]([WONO] ASC, [ACTIV_ID] ASC);

