CREATE TABLE [dbo].[APBATDET] (
    [DISC_AMT]        NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__DISC_A__2180FB33] DEFAULT ((0)) NOT NULL,
    [DISC_TKN]        NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__DISC_T__22751F6C] DEFAULT ((0)) NOT NULL,
    [APRPAY]          NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__APRPAY__236943A5] DEFAULT ((0)) NOT NULL,
    [IS_PRINTED]      BIT             CONSTRAINT [DF__APBATDET__IS_PRI__245D67DE] DEFAULT ((0)) NOT NULL,
    [BATCHUNIQ]       CHAR (10)       CONSTRAINT [DF__APBATDET__BATCHU__25518C17] DEFAULT ('') NOT NULL,
    [BATDETUNIQ]      CHAR (10)       CONSTRAINT [DF__APBATDET__BATDET__2645B050] DEFAULT ('') NOT NULL,
    [FK_UNIQAPHEAD]   CHAR (10)       CONSTRAINT [DF__APBATDET__FK_UNI__282DF8C2] DEFAULT ('') NOT NULL,
    [DISC_AMTFC]      NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__DISC_A__383CA55E] DEFAULT ((0)) NOT NULL,
    [DISC_TKNFC]      NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__DISC_T__3930C997] DEFAULT ((0)) NOT NULL,
    [APRPAYFC]        NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__APRPAY__3A24EDD0] DEFAULT ((0)) NOT NULL,
    [ORIG_FCHIST_KEY] CHAR (10)       CONSTRAINT [DF__APBATDET__ORIG_F__599D9929] DEFAULT ('') NOT NULL,
    [DISC_AMTPR]      NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__DISC_A__585605E3] DEFAULT ((0)) NOT NULL,
    [DISC_TKNPR]      NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__DISC_T__594A2A1C] DEFAULT ((0)) NOT NULL,
    [APRPAYPR]        NUMERIC (12, 2) CONSTRAINT [DF__APBATDET__APRPAY__5B32728E] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APBATDET_PK] PRIMARY KEY CLUSTERED ([BATDETUNIQ] ASC),
    CONSTRAINT [FK_APBATDET_APBATCH] FOREIGN KEY ([BATCHUNIQ]) REFERENCES [dbo].[APBATCH] ([BATCHUNIQ]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [batchuniq]
    ON [dbo].[APBATDET]([BATCHUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [uniqaphead]
    ON [dbo].[APBATDET]([FK_UNIQAPHEAD] ASC);

