CREATE TABLE [dbo].[APBATCH] (
    [BATCH_DATE]      SMALLDATETIME   NULL,
    [BATCH_TOT]       NUMERIC (12, 2) CONSTRAINT [DF__APBATCH__BATCH_T__151B244E] DEFAULT ((0)) NOT NULL,
    [IS_EDITED]       CHAR (3)        CONSTRAINT [DF__APBATCH__IS_EDIT__160F4887] DEFAULT ('') NOT NULL,
    [IS_CLOSED]       BIT             CONSTRAINT [DF__APBATCH__IS_CLOS__17036CC0] DEFAULT ((0)) NOT NULL,
    [BATCHUNIQ]       CHAR (10)       CONSTRAINT [DF__APBATCH__BATCHUN__17F790F9] DEFAULT ('') NOT NULL,
    [BK_UNIQ]         CHAR (10)       CONSTRAINT [DF__APBATCH__BK_UNIQ__18EBB532] DEFAULT ('') NOT NULL,
    [BATCHDESCR]      CHAR (40)       CONSTRAINT [DF__APBATCH__BATCHDE__19DFD96B] DEFAULT ('') NOT NULL,
    [DATEPAID]        SMALLDATETIME   NULL,
    [RecVer]          ROWVERSION      NOT NULL,
    [lReprinted]      BIT             CONSTRAINT [DF__APBATCH__lReprin__7D102741] DEFAULT ((0)) NOT NULL,
    [BATCH_TOTFC]     NUMERIC (12, 2) CONSTRAINT [DF__APBATCH__BATCH_T__4C439E0B] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ]     CHAR (10)       CONSTRAINT [DF__APBATCH__FCUSED___4D37C244] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]      CHAR (10)       CONSTRAINT [DF__APBATCH__FCHIST___4E2BE67D] DEFAULT ('') NOT NULL,
    [PMTTYPE]         VARCHAR (50)    CONSTRAINT [DF__APBATCH__PMTTYPE__4F200AB6] DEFAULT ('') NOT NULL,
    [PMTCURRENCY]     CHAR (10)       CONSTRAINT [DF__APBATCH__PMTCURR__50142EEF] DEFAULT ('') NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__APBATCH__PRFCUSE__6F6E7565] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__APBATCH__FUNCFCU__7062999E] DEFAULT ('') NOT NULL,
    [BATCH_TOTPR]     NUMERIC (12, 2) CONSTRAINT [DF__APBATCH__BATCH_T__7156BDD7] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APBATCH_PK] PRIMARY KEY CLUSTERED ([BATCHUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [BATCH_DATE]
    ON [dbo].[APBATCH]([BATCH_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IS_CLOSED]
    ON [dbo].[APBATCH]([IS_CLOSED] ASC);


GO
CREATE NONCLUSTERED INDEX [bk_uniq]
    ON [dbo].[APBATCH]([BK_UNIQ] ASC);

