CREATE TABLE [dbo].[APDETAILTAX] (
    [UNIQAPDETAILTAX] CHAR (10)      CONSTRAINT [DF__APDETAILT__UNIQA__2B76DBC6] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [UNIQAPHEAD]      CHAR (10)      CONSTRAINT [DF__APDETAILT__UNIQA__2C6AFFFF] DEFAULT ('') NOT NULL,
    [UNIQAPDETL]      CHAR (10)      CONSTRAINT [DF__APDETAILT__UNIQA__2D5F2438] DEFAULT ('') NOT NULL,
    [TAX_ID]          CHAR (8)       CONSTRAINT [DF__APDETAILT__TAX_I__2E534871] DEFAULT ('') NOT NULL,
    [TAX_RATE]        NUMERIC (8, 4) CONSTRAINT [DF__APDETAILT__TAX_R__2F476CAA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__APDETAIL__2605593D298E9354] PRIMARY KEY CLUSTERED ([UNIQAPDETAILTAX] ASC)
);

