CREATE TABLE [dbo].[APDETAIL] (
    [UNIQAPHEAD]   CHAR (10)       CONSTRAINT [DF__APDETAIL__UNIQAP__6FB49575] DEFAULT ('') NOT NULL,
    [UNIQAPDETL]   CHAR (10)       CONSTRAINT [DF__APDETAIL__UNIQAP__70A8B9AE] DEFAULT ('') NOT NULL,
    [SHIPNO]       CHAR (10)       CONSTRAINT [DF__APDETAIL__SHIPNO__72910220] DEFAULT ('') NOT NULL,
    [ITEM_NO]      NUMERIC (7)     CONSTRAINT [DF__APDETAIL__ITEM_N__73852659] DEFAULT ((0)) NOT NULL,
    [ITEM_DESC]    CHAR (25)       CONSTRAINT [DF__APDETAIL__ITEM_D__74794A92] DEFAULT ('') NOT NULL,
    [QTY_EACH]     DECIMAL (10, 2) CONSTRAINT [DF__APDETAIL__QTY_EA__756D6ECB] DEFAULT ((0)) NOT NULL,
    [PRICE_EACH]   NUMERIC (13, 5) CONSTRAINT [DF__APDETAIL__PRICE___76619304] DEFAULT ((0)) NOT NULL,
    [IS_TAX]       BIT             CONSTRAINT [DF__APDETAIL__IS_TAX__7755B73D] DEFAULT ((0)) NOT NULL,
    [TAX_PCT]      NUMERIC (8, 4)  CONSTRAINT [DF__APDETAIL__TAX_PC__7849DB76] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTAL]   NUMERIC (12, 2) CONSTRAINT [DF__APDETAIL__ITEM_T__793DFFAF] DEFAULT ((0)) NOT NULL,
    [GL_NBR]       CHAR (13)       CONSTRAINT [DF__APDETAIL__GL_NBR__7A3223E8] DEFAULT ('') NOT NULL,
    [ITEM_NOTE]    TEXT            CONSTRAINT [DF__APDETAIL__ITEM_N__7B264821] DEFAULT ('') NOT NULL,
    [TRANS_NO]     NUMERIC (10)    CONSTRAINT [DF__APDETAIL__TRANS___7C1A6C5A] DEFAULT ((0)) NOT NULL,
    [PRICE_EACHFC] NUMERIC (13, 5) CONSTRAINT [DF__APDETAIL__PRICE___3223D955] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTALFC] NUMERIC (12, 2) CONSTRAINT [DF__APDETAIL__ITEM_T__3317FD8E] DEFAULT ((0)) NOT NULL,
    [PRICE_EACHPR] NUMERIC (13, 5) CONSTRAINT [DF__APDETAIL__PRICE___25407631] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTALPR] NUMERIC (12, 2) CONSTRAINT [DF__APDETAIL__ITEM_T__26349A6A] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APDETAIL_PK] PRIMARY KEY CLUSTERED ([UNIQAPDETL] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQAPHEAD]
    ON [dbo].[APDETAIL]([UNIQAPHEAD] ASC);


GO
-- =============================================
-- Author:		Vicky Lu	
-- Create date: 12/06/16
-- Description:	After Delete trigger for the Apdetail table
-- =============================================
CREATE TRIGGER  [dbo].[Apdetail_Delete]
   ON  [dbo].[Apdetail] 
   AFTER DELETE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRANSACTION 
	DELETE FROM ApdetailTax WHERE Uniqapdetl IN (SELECT Uniqapdetl FROM DELETED)
	COMMIT

END