CREATE TABLE [dbo].[APMASTER] (
    [UNIQAPHEAD]      CHAR (10)       CONSTRAINT [DF__APMASTER__UNIQAP__11158940] DEFAULT ('') NOT NULL,
    [TRANS_DT]        SMALLDATETIME   NULL,
    [UNIQSUPNO]       CHAR (10)       CONSTRAINT [DF__APMASTER__UNIQSU__13F1F5EB] DEFAULT ('') NOT NULL,
    [INVNO]           CHAR (20)       CONSTRAINT [DF__APMASTER__INVNO__15DA3E5D] DEFAULT ('') NOT NULL,
    [INVDATE]         SMALLDATETIME   NULL,
    [DUE_DATE]        SMALLDATETIME   NULL,
    [PONUM]           CHAR (15)       CONSTRAINT [DF__APMASTER__PONUM__16CE6296] DEFAULT ('') NOT NULL,
    [SUBTOTAL]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__SUBTOT__17C286CF] DEFAULT ((0)) NOT NULL,
    [TERMS]           CHAR (15)       CONSTRAINT [DF__APMASTER__TERMS__18B6AB08] DEFAULT ('') NOT NULL,
    [TAX]             NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__TAX__19AACF41] DEFAULT ((0)) NOT NULL,
    [FREIGHT]         NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__FREIGH__1A9EF37A] DEFAULT ((0)) NOT NULL,
    [INVAMOUNT]       NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__INVAMO__1B9317B3] DEFAULT ((0)) NOT NULL,
    [APPMTS]          NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__APPMTS__1C873BEC] DEFAULT ((0)) NOT NULL,
    [PAYPRI]          CHAR (1)        CONSTRAINT [DF__APMASTER__PAYPRI__1D7B6025] DEFAULT ('') NOT NULL,
    [DISC_PERC]       NUMERIC (6, 2)  CONSTRAINT [DF__APMASTER__DISC_P__1E6F845E] DEFAULT ((0)) NOT NULL,
    [DISC_AMT]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__DISC_A__1F63A897] DEFAULT ((0)) NOT NULL,
    [DISC_TKN]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__DISC_T__2057CCD0] DEFAULT ((0)) NOT NULL,
    [APRPAY]          NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__APRPAY__214BF109] DEFAULT ((0)) NOT NULL,
    [APNOTE]          TEXT            CONSTRAINT [DF__APMASTER__APNOTE__22401542] DEFAULT ('') NOT NULL,
    [APTYPE]          CHAR (10)       CONSTRAINT [DF__APMASTER__APTYPE__2334397B] DEFAULT ('') NOT NULL,
    [IS_REL_GL]       BIT             CONSTRAINT [DF__APMASTER__IS_REL__24285DB4] DEFAULT ((0)) NOT NULL,
    [IS_PRINTED]      BIT             CONSTRAINT [DF__APMASTER__IS_PRI__251C81ED] DEFAULT ((0)) NOT NULL,
    [LINKADD]         CHAR (10)       CONSTRAINT [DF__APMASTER__LINKAD__2610A626] DEFAULT ('') NOT NULL,
    [C_LINK]          CHAR (10)       CONSTRAINT [DF__APMASTER__C_LINK__2704CA5F] DEFAULT ('') NOT NULL,
    [R_LINK]          CHAR (10)       CONSTRAINT [DF__APMASTER__R_LINK__27F8EE98] DEFAULT ('') NOT NULL,
    [INIT]            CHAR (8)        CONSTRAINT [DF__APMASTER__INIT__28ED12D1] DEFAULT ('') NOT NULL,
    [PMTTYPE]         CHAR (5)        CONSTRAINT [DF__APMASTER__PMTTYP__29E1370A] DEFAULT ('') NOT NULL,
    [PAID]            CHAR (1)        CONSTRAINT [DF__APMASTER__PAID__2AD55B43] DEFAULT ('') NOT NULL,
    [APGLLINK]        CHAR (10)       CONSTRAINT [DF__APMASTER__APGLLI__2BC97F7C] DEFAULT ('') NOT NULL,
    [APSTATUS]        CHAR (15)       CONSTRAINT [DF__APMASTER__APSTAT__2CBDA3B5] DEFAULT ('') NOT NULL,
    [EDITDATE]        SMALLDATETIME   NULL,
    [REASON]          CHAR (30)       CONSTRAINT [DF__APMASTER__REASON__2DB1C7EE] DEFAULT ('') NOT NULL,
    [CHOLDSTATUS]     CHAR (10)       CONSTRAINT [DF__APMASTER__CHOLDS__2EA5EC27] DEFAULT ('') NOT NULL,
    [LPAYMENTPROCESS] BIT             CONSTRAINT [DF__APMASTER__LPAYME__2F9A1060] DEFAULT ((0)) NOT NULL,
    [BATCHUNIQ]       CHAR (10)       CONSTRAINT [DF__APMASTER__BATCHU__308E3499] DEFAULT ('') NOT NULL,
    [lPrepay]         BIT             CONSTRAINT [DF_APMASTER_lPrepay] DEFAULT ((0)) NOT NULL,
    [lForceUpdate]    BIT             CONSTRAINT [DF_APMASTER_lForceUpdate] DEFAULT ((0)) NOT NULL,
    [RecVer]          ROWVERSION      NOT NULL,
    [SUBTOTALFC]      NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__SUBTOT__340C21C7] DEFAULT ((0)) NOT NULL,
    [TAXFC]           NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__TAXFC__35004600] DEFAULT ((0)) NOT NULL,
    [FREIGHTFC]       NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__FREIGH__35F46A39] DEFAULT ((0)) NOT NULL,
    [INVAMOUNTFC]     NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__INVAMO__36E88E72] DEFAULT ((0)) NOT NULL,
    [APPMTSFC]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__APPMTS__37DCB2AB] DEFAULT ((0)) NOT NULL,
    [DISC_AMTFC]      NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__DISC_A__38D0D6E4] DEFAULT ((0)) NOT NULL,
    [DISC_TKNFC]      NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__DISC_T__39C4FB1D] DEFAULT ((0)) NOT NULL,
    [APRPAYFC]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__APRPAY__3AB91F56] DEFAULT ((0)) NOT NULL,
    [FcUsed_uniq]     CHAR (10)       CONSTRAINT [DF__APMASTER__FcUsed__3BAD438F] DEFAULT ('') NOT NULL,
    [Fchist_key]      CHAR (10)       CONSTRAINT [DF__APMASTER__Fchist__3CA167C8] DEFAULT ('') NOT NULL,
    [Orig_Fchist_key] CHAR (10)       CONSTRAINT [DF__APMASTER__Orig_F__7A3F72E5] DEFAULT ('') NOT NULL,
    [SUBTOTALPR]      NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__SUBTOT__1BB70BF7] DEFAULT ((0)) NOT NULL,
    [TAXPR]           NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__TAXPR__1CAB3030] DEFAULT ((0)) NOT NULL,
    [FREIGHTPR]       NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__FREIGH__1D9F5469] DEFAULT ((0)) NOT NULL,
    [INVAMOUNTPR]     NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__INVAMO__1E9378A2] DEFAULT ((0)) NOT NULL,
    [APPMTSPR]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__APPMTS__1F879CDB] DEFAULT ((0)) NOT NULL,
    [DISC_AMTPR]      NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__DISC_A__207BC114] DEFAULT ((0)) NOT NULL,
    [DISC_TKNPR]      NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__DISC_T__216FE54D] DEFAULT ((0)) NOT NULL,
    [APRPAYPR]        NUMERIC (12, 2) CONSTRAINT [DF__APMASTER__APRPAY__22640986] DEFAULT ((0)) NOT NULL,
    [PRFcused_Uniq]   CHAR (10)       CONSTRAINT [DF__APMASTER__PRFcus__23582DBF] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__APMASTER__FUNCFC__244C51F8] DEFAULT ('') NOT NULL,
    CONSTRAINT [APMASTER_PK] PRIMARY KEY CLUSTERED ([UNIQAPHEAD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTINV]
    ON [dbo].[APMASTER]([UNIQSUPNO] ASC, [INVNO] ASC, [DUE_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INVNO]
    ON [dbo].[APMASTER]([INVNO] ASC);


GO
CREATE NONCLUSTERED INDEX [IS_REL_GL_INCLUDE]
    ON [dbo].[APMASTER]([IS_REL_GL] ASC, [lPrepay] ASC, [TAX] ASC, [APSTATUS] ASC)
    INCLUDE([UNIQAPHEAD], [TRANS_DT], [UNIQSUPNO], [INVNO], [PONUM]);

