CREATE TABLE [dbo].[APOFFSET] (
    [UNIQ_APOFF]      CHAR (10)       CONSTRAINT [DF__APOFFSET__UNIQ_A__336AA144] DEFAULT ('') NOT NULL,
    [UNIQAPHEAD]      CHAR (10)       CONSTRAINT [DF__APOFFSET__UNIQAP__345EC57D] DEFAULT ('') NOT NULL,
    [DATE]            SMALLDATETIME   CONSTRAINT [DF_APOFFSET_DATE] DEFAULT (getdate()) NULL,
    [UNIQSUPNO]       CHAR (10)       CONSTRAINT [DF__APOFFSET__UNIQSU__36470DEF] DEFAULT ('') NOT NULL,
    [REF_NO]          CHAR (12)       CONSTRAINT [DF__APOFFSET__REF_NO__382F5661] DEFAULT ('') NOT NULL,
    [INVNO]           CHAR (22)       CONSTRAINT [DF__APOFFSET__INVNO__39237A9A] DEFAULT ('') NOT NULL,
    [AMOUNT]          NUMERIC (15, 2) CONSTRAINT [DF__APOFFSET__AMOUNT__3A179ED3] DEFAULT ((0)) NOT NULL,
    [INITIALS]        CHAR (8)        CONSTRAINT [DF__APOFFSET__INITIA__3B0BC30C] DEFAULT ('') NOT NULL,
    [OFFNOTE]         TEXT            CONSTRAINT [DF__APOFFSET__OFFNOT__3BFFE745] DEFAULT ('') NOT NULL,
    [CGROUP]          CHAR (10)       CONSTRAINT [DF__APOFFSET__CGROUP__3CF40B7E] DEFAULT ('') NOT NULL,
    [DCURDATE]        SMALLDATETIME   NULL,
    [UNIQ_SAVE]       CHAR (10)       CONSTRAINT [DF__APOFFSET__UNIQ_S__3DE82FB7] DEFAULT ('') NOT NULL,
    [is_rel_gl]       BIT             CONSTRAINT [DF__APOFFSET__LRELEA__3EDC53F0] DEFAULT ((0)) NOT NULL,
    [AMOUNTFC]        NUMERIC (15, 2) CONSTRAINT [DF__APOFFSET__AMOUNT__7D1BDF90] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ]     CHAR (10)       CONSTRAINT [DF__APOFFSET__FCUSED__7E1003C9] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]      CHAR (10)       CONSTRAINT [DF__APOFFSET__FCHIST__7F042802] DEFAULT ('') NOT NULL,
    [ORIG_FCHIST_KEY] CHAR (10)       CONSTRAINT [DF__APOFFSET__ORIG_F__7FF84C3B] DEFAULT ('') NOT NULL,
    [AMOUNTPR]        NUMERIC (15, 2) CONSTRAINT [DF__APOFFSET__AMOUNT__1104735A] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__APOFFSET__PRFCUS__11F89793] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__APOFFSET__FUNCFC__12ECBBCC] DEFAULT ('') NOT NULL,
    CONSTRAINT [APOFFSET_PK] PRIMARY KEY CLUSTERED ([UNIQ_APOFF] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ApOFFSET_DATE]
    ON [dbo].[APOFFSET]([DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INVNO]
    ON [dbo].[APOFFSET]([INVNO] ASC);


GO
CREATE NONCLUSTERED INDEX [is_rel_gl]
    ON [dbo].[APOFFSET]([is_rel_gl] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_SAVE]
    ON [dbo].[APOFFSET]([UNIQ_SAVE] ASC);


GO
CREATE NONCLUSTERED INDEX [uniqaphead]
    ON [dbo].[APOFFSET]([UNIQAPHEAD] ASC);

