CREATE TABLE [dbo].[ARDEP] (
    [CUSTNO]       CHAR (10)       CONSTRAINT [DF__ARDEP__CUSTNO__324172E1] DEFAULT ('') NOT NULL,
    [INVNO]        CHAR (10)       CONSTRAINT [DF__ARDEP__INVNO__3335971A] DEFAULT ('') NOT NULL,
    [REC_DATE]     SMALLDATETIME   NULL,
    [REC_AMOUNT]   NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__REC_AMOUN__3429BB53] DEFAULT ((0)) NOT NULL,
    [DATE_CHG]     SMALLDATETIME   NULL,
    [DEP_CREDIT]   NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__DEP_CREDI__351DDF8C] DEFAULT ((0)) NOT NULL,
    [ARDEPUNIQ]    CHAR (10)       CONSTRAINT [DF__ARDEP__ARDEPUNIQ__361203C5] DEFAULT ('') NOT NULL,
    [dep_no]       CHAR (10)       CONSTRAINT [DF_ARDEP_dep_no] DEFAULT ('') NOT NULL,
    [REC_AMOUNTFC] NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__REC_AMOUN__6B274C87] DEFAULT ((0)) NOT NULL,
    [REC_AMOUNTBK] NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__REC_AMOUN__6C1B70C0] DEFAULT ((0)) NOT NULL,
    [DEP_CREDITFC] NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__DEP_CREDI__6D0F94F9] DEFAULT ((0)) NOT NULL,
    [REC_AMOUNTPR] NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__REC_AMOUN__5DEEE3A8] DEFAULT ((0)) NOT NULL,
    [DEP_CREDITPR] NUMERIC (12, 2) CONSTRAINT [DF__ARDEP__DEP_CREDI__5EE307E1] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ARDEP_PK] PRIMARY KEY CLUSTERED ([ARDEPUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTINV]
    ON [dbo].[ARDEP]([CUSTNO] ASC, [INVNO] ASC);


GO
CREATE NONCLUSTERED INDEX [DEP_NO]
    ON [dbo].[ARDEP]([dep_no] ASC);


GO
CREATE NONCLUSTERED INDEX [INVNO]
    ON [dbo].[ARDEP]([INVNO] ASC);

