CREATE TABLE [dbo].[ARRETCK] (
    [DEP_NO]          CHAR (10)       CONSTRAINT [DF__ARRETCK__DEP_NO__436BFEE3] DEFAULT ('') NOT NULL,
    [UNIQRETNO]       CHAR (10)       CONSTRAINT [DF__ARRETCK__UNIQRET__4460231C] DEFAULT ('') NOT NULL,
    [CUSTNO]          CHAR (10)       CONSTRAINT [DF__ARRETCK__CUSTNO__45544755] DEFAULT ('') NOT NULL,
    [UNIQLNNO]        CHAR (10)       CONSTRAINT [DF__ARRETCK__UNIQLNN__46486B8E] DEFAULT ('') NOT NULL,
    [REC_DATE]        SMALLDATETIME   NULL,
    [REC_ADVICE]      CHAR (10)       CONSTRAINT [DF__ARRETCK__REC_ADV__473C8FC7] DEFAULT ('') NOT NULL,
    [REC_AMOUNT]      NUMERIC (12, 2) CONSTRAINT [DF__ARRETCK__REC_AMO__4830B400] DEFAULT ((0)) NOT NULL,
    [BANKCODE]        CHAR (10)       CONSTRAINT [DF__ARRETCK__BANKCOD__4924D839] DEFAULT ('') NOT NULL,
    [RET_DATE]        SMALLDATETIME   NULL,
    [RET_NOTE]        TEXT            CONSTRAINT [DF__ARRETCK__RET_NOT__4A18FC72] DEFAULT ('') NOT NULL,
    [IS_REL_GL]       BIT             CONSTRAINT [DF__ARRETCK__IS_REL___4B0D20AB] DEFAULT ((0)) NOT NULL,
    [GL_NBR]          CHAR (13)       CONSTRAINT [DF__ARRETCK__GL_NBR__4C0144E4] DEFAULT ('') NOT NULL,
    [CSTATUS]         CHAR (10)       CONSTRAINT [DF__ARRETCK__CSTATUS__4CF5691D] DEFAULT ('') NOT NULL,
    [cInitials]       CHAR (8)        CONSTRAINT [DF_ARRETCK_cInitials] DEFAULT ('') NOT NULL,
    [dRetDate]        SMALLDATETIME   CONSTRAINT [DF_ARRETCK_dRetDate] DEFAULT (getdate()) NOT NULL,
    [REC_AMOUNTFC]    NUMERIC (12, 2) CONSTRAINT [DF__ARRETCK__REC_AMO__72343CC9] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ]     CHAR (10)       CONSTRAINT [DF__ARRETCK__FCUSED___73286102] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]      CHAR (10)       CONSTRAINT [DF__ARRETCK__FCHIST___741C853B] DEFAULT ('') NOT NULL,
    [REC_AMOUNTPR]    NUMERIC (12, 2) CONSTRAINT [DF__ARRETCK__REC_AMO__2F88FA7A] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__ARRETCK__PRFCUSE__307D1EB3] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__ARRETCK__FUNCFCU__317142EC] DEFAULT ('') NOT NULL,
    CONSTRAINT [ARRETCK_PK] PRIMARY KEY CLUSTERED ([UNIQRETNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEP_NO]
    ON [dbo].[ARRETCK]([DEP_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [RECV_ADVIC]
    ON [dbo].[ARRETCK]([REC_ADVICE] ASC);


GO
CREATE TRIGGER [dbo].[ArRetCk_Insert]
   ON  [dbo].[ARRETCK]
   AFTER  INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for trigger here
	BEGIN TRANSACTION
	-- 01/13/17 VL added functional currency fields and FC field (it seems missed when we converted to FC)
	UPDATE Banks SET Bank_bal = Bank_bal-Inserted.Rec_Amount,
					Bank_balFC = Bank_balFC-Inserted.Rec_AmountFC,
					Bank_balPR = Bank_balPR-Inserted.Rec_AmountPR FROM Inserted,Deposits 
		WHERE Inserted.dep_no = Deposits.dep_no and Banks.bk_acct_no =Deposits.bk_acct_no 
	COMMIT
END