CREATE TABLE [dbo].[aspnet_Profile] (
    [UserId]                  UNIQUEIDENTIFIER NOT NULL,
    [PropertyNames]           NTEXT            NULL,
    [PropertyValuesString]    NTEXT            NULL,
    [PropertyValuesBinary]    IMAGE            NULL,
    [LastUpdatedDate]         DATETIME         NULL,
    [FirstName]               VARCHAR (50)     CONSTRAINT [DF_aspnet_Profile_FirstName] DEFAULT ('') NULL,
    [LastName]                VARCHAR (50)     CONSTRAINT [DF_aspnet_Profile_LastName] DEFAULT ('') NULL,
    [Midname]                 VARCHAR (50)     CONSTRAINT [DF_aspnet_Profile_Midname] DEFAULT ('') NULL,
    [Initials]                VARCHAR (8)      CONSTRAINT [DF_aspnet_Profile_Inititals] DEFAULT ('') NULL,
    [dept_id]                 CHAR (4)         CONSTRAINT [DF_aspnet_Profile_dept_id] DEFAULT ('') NULL,
    [Department]              CHAR (35)        CONSTRAINT [DF_aspnet_Profile_workcenter] DEFAULT ('') NULL,
    [SuperUser]               BIT              CONSTRAINT [DF_aspnet_Profile_SuperVisor] DEFAULT ((0)) NULL,
    [shift_no]                INT              NULL,
    [exempt]                  BIT              CONSTRAINT [DF_aspnet_Profile_exempt] DEFAULT ((0)) NULL,
    [maxpasswc]               BIT              CONSTRAINT [DF_aspnet_Profile_maxpasswc] DEFAULT ((0)) NULL,
    [homescreen]              CHAR (8)         CONSTRAINT [DF_aspnet_Profile_homescreen] DEFAULT ('') NULL,
    [homeapp]                 CHAR (10)        CONSTRAINT [DF_aspnet_Profile_homeapp] DEFAULT ('') NULL,
    [CHGWKSTWC]               BIT              CONSTRAINT [DF_aspnet_Profile_CHGWKSTWC] DEFAULT ((0)) NULL,
    [LCHPASSWORDNEXT]         BIT              CONSTRAINT [DF_aspnet_Profile_LCHPASSWORDNEXT] DEFAULT ((0)) NULL,
    [LCANNOTCHPASSWORD]       BIT              CONSTRAINT [DF_aspnet_Profile_LCANNOTCHPASSWORD] DEFAULT ((0)) NULL,
    [LPASSWORDNEVEREXP]       BIT              CONSTRAINT [DF_aspnet_Profile_LPASSWORDNEVEREXP] DEFAULT ((0)) NULL,
    [NPASSWORDEXPIN]          INT              CONSTRAINT [DF_aspnet_Profile_NPASSWORDEXPIN] DEFAULT ((0)) NULL,
    [TPASSWORDENETERED]       SMALLDATETIME    NULL,
    [AcctAdmin]               BIT              CONSTRAINT [DF_aspnet_Profile_AcctAdmin] DEFAULT ((0)) NOT NULL,
    [CompanyAdmin]            BIT              CONSTRAINT [DF_aspnet_Profile_CompanyAdmin] DEFAULT ((0)) NOT NULL,
    [externalEmp]             BIT              CONSTRAINT [DF_aspnet_Profile_externalEmp] DEFAULT ((1)) NOT NULL,
    [ProdAdmin]               BIT              CONSTRAINT [DF_aspnet_Profile_ProdAdmin] DEFAULT ((0)) NOT NULL,
    [minuteLimit]             INT              CONSTRAINT [DF_aspnet_Profile_minuteLimit] DEFAULT ((20)) NOT NULL,
    [LicenseType]             VARCHAR (50)     CONSTRAINT [DF_aspnet_Profile_LicenseType] DEFAULT ('Full') NOT NULL,
    [title]                   VARCHAR (50)     NULL,
    [workPhone]               VARCHAR (25)     NULL,
    [fax]                     VARCHAR (19)     NULL,
    [mobile]                  CHAR (25)        NULL,
    [note]                    VARCHAR (MAX)    NULL,
    [photoPath]               VARCHAR (100)    NULL,
    [nickname]                VARCHAR (20)     NULL,
    [gridLineHeight]          VARCHAR (50)     NULL,
    [badgeCode]               VARCHAR (20)     CONSTRAINT [DF_aspnet_Profile_badgeCode] DEFAULT ('') NULL,
    [ApiKey]                  VARCHAR (10)     NULL,
    [isbuyer]                 BIT              CONSTRAINT [DF_aspnet_Profile_isbuyer] DEFAULT ((0)) NOT NULL,
    [frstAmtInvtApproved]     NUMERIC (18, 2)  CONSTRAINT [DF_aspnet_Profile_frstAmountInvtApproved] DEFAULT ((0)) NOT NULL,
    [finalAmtInvtApproved]    NUMERIC (18, 2)  CONSTRAINT [DF_aspnet_Profile_finalAmtNonInvtApproved] DEFAULT ((0)) NOT NULL,
    [frstAmtNonInvtApproved]  NUMERIC (18, 2)  CONSTRAINT [DF_aspnet_Profile_frstAmtNonInvtApproved] DEFAULT ((0)) NOT NULL,
    [finalAmtNonInvtApproved] NUMERIC (18, 2)  CONSTRAINT [DF_aspnet_Profile_finalAmtNonInvtApproved_1] DEFAULT ((0)) NOT NULL,
    [LanguageId]              INT              CONSTRAINT [DF__aspnet_Pr__Langu__0C54017F] DEFAULT ((1)) NOT NULL,
    [ITARrestricted]          BIT              CONSTRAINT [DF_aspnet_Profile_ITARrestricted] DEFAULT ((0)) NOT NULL,
    [STATUS]                  CHAR (10)        CONSTRAINT [DF__aspnet_Pr__STATU__52282B41] DEFAULT ('Active') NOT NULL,
    [HRType]                  CHAR (50)        CONSTRAINT [DF__aspnet_Pr__HRTyp__531C4F7A] DEFAULT ('Full Time') NOT NULL,
    [ScmAdmin]                BIT              CONSTRAINT [DF__aspnet_Pr__ScmAd__7B6A37F6] DEFAULT ((0)) NULL,
    [CrmAdmin]                BIT              CONSTRAINT [DF__aspnet_Pr__CrmAd__7C5E5C2F] DEFAULT ((0)) NULL,
    [CAPAAdmin]               BIT              NULL,
    [PayRate]                 NUMERIC (20, 2)  NULL,
    [SalaryUpdatedDate]       DATETIME         NULL,
    [SalaryUpdatedBy]         VARCHAR (8)      NULL,
    [StartDate]               DATETIME         NULL,
    [TerminationDate]         DATETIME         NULL,
    [ProjectsTasks]           BIT              CONSTRAINT [DF__aspnet_Pr__Proje__5C3C70B7] DEFAULT ((0)) NOT NULL,
    [EngAdmin]                BIT              NULL,
    CONSTRAINT [PK__aspnet_P__1788CC4C0FADFA69] PRIMARY KEY CLUSTERED ([UserId] ASC),
    CONSTRAINT [FK__aspnet_Pr__UserI__119642DB] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId])
);

