CREATE TABLE [dbo].[ASSYCHK] (
    [UNIQ_KEY]   CHAR (10)     CONSTRAINT [DF__ASSYCHK__UNIQ_KE__1A34DF26] DEFAULT ('') NOT NULL,
    [SHOPFL_CHK] NVARCHAR (50) CONSTRAINT [DF__ASSYCHK__SHOPFL___1B29035F] DEFAULT ('') NOT NULL,
    [CHKUNIQ]    CHAR (10)     CONSTRAINT [DF__ASSYCHK__CHKUNIQ__1C1D2798] DEFAULT ('') NOT NULL,
    [isMnxCheck] BIT           CONSTRAINT [DF_ASSYCHK_isMnxCheck] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ASSYCHK_PK] PRIMARY KEY CLUSTERED ([CHKUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ASSYCHK]
    ON [dbo].[ASSYCHK]([UNIQ_KEY] ASC, [SHOPFL_CHK] ASC);


GO
CREATE NONCLUSTERED INDEX [ASSYID]
    ON [dbo].[ASSYCHK]([UNIQ_KEY] ASC);

