CREATE TABLE [dbo].[BKADDETL] (
    [UNIQBKADDT]    CHAR (10)       CONSTRAINT [DF__BKADDETL__UNIQBK__3D7E1B63] DEFAULT ('') NOT NULL,
    [FK_UNIQBKADMN] CHAR (10)       CONSTRAINT [DF__BKADDETL__FK_UNI__3E723F9C] DEFAULT ('') NOT NULL,
    [ITEM_NO]       NUMERIC (3)     CONSTRAINT [DF__BKADDETL__ITEM_N__3F6663D5] DEFAULT ((0)) NOT NULL,
    [ITEM_DESC]     CHAR (25)       CONSTRAINT [DF__BKADDETL__ITEM_D__405A880E] DEFAULT ('') NOT NULL,
    [ITEM_TOTAL]    NUMERIC (10, 2) CONSTRAINT [DF__BKADDETL__ITEM_T__414EAC47] DEFAULT ((0)) NOT NULL,
    [GL_NBR]        CHAR (13)       CONSTRAINT [DF__BKADDETL__GL_NBR__4242D080] DEFAULT ('') NOT NULL,
    [ITEM_TOTALFC]  NUMERIC (10, 2) CONSTRAINT [DF__BKADDETL__ITEM_T__4B4F79D2] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTALPR]  NUMERIC (10, 2) CONSTRAINT [DF__BKADDETL__ITEM_T__63C7B88F] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [BKADDETL_PK] PRIMARY KEY CLUSTERED ([UNIQBKADDT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQBKADMN]
    ON [dbo].[BKADDETL]([FK_UNIQBKADMN] ASC);

