CREATE TABLE [dbo].[BKADMAIN] (
    [UNIQBKADMN]      CHAR (10)       CONSTRAINT [DF__BKADMAIN__UNIQBK__46136164] DEFAULT ('') NOT NULL,
    [FK_BK_UNIQ]      CHAR (10)       CONSTRAINT [DF__BKADMAIN__FK_BK___4707859D] DEFAULT ('') NOT NULL,
    [DAYOFMO]         NUMERIC (2)     CONSTRAINT [DF__BKADMAIN__DAYOFM__47FBA9D6] DEFAULT ((0)) NOT NULL,
    [SETUPDATE]       SMALLDATETIME   NULL,
    [PMTAMT]          NUMERIC (10, 2) CONSTRAINT [DF__BKADMAIN__PMTAMT__48EFCE0F] DEFAULT ((0)) NOT NULL,
    [DESCRIPT]        CHAR (30)       CONSTRAINT [DF__BKADMAIN__DESCRI__49E3F248] DEFAULT ('') NOT NULL,
    [MAXPMTS]         NUMERIC (3)     CONSTRAINT [DF__BKADMAIN__MAXPMT__4AD81681] DEFAULT ((0)) NOT NULL,
    [PMTSDED]         NUMERIC (3)     CONSTRAINT [DF__BKADMAIN__PMTSDE__4BCC3ABA] DEFAULT ((0)) NOT NULL,
    [FIRSTPMT]        SMALLDATETIME   NULL,
    [LASTPMTGEN]      SMALLDATETIME   NULL,
    [EDITDATE]        SMALLDATETIME   NULL,
    [INIT]            CHAR (8)        CONSTRAINT [DF__BKADMAIN__INIT__4CC05EF3] DEFAULT ('') NOT NULL,
    [REASON]          CHAR (30)       CONSTRAINT [DF__BKADMAIN__REASON__4DB4832C] DEFAULT ('') NOT NULL,
    [IS_CLOSED]       BIT             CONSTRAINT [DF__BKADMAIN__IS_CLO__4EA8A765] DEFAULT ((0)) NOT NULL,
    [ADNOTE]          TEXT            CONSTRAINT [DF__BKADMAIN__ADNOTE__4F9CCB9E] DEFAULT ('') NOT NULL,
    [PMTAMTFC]        NUMERIC (10, 2) CONSTRAINT [DF__BKADMAIN__PMTAMT__4A5B5599] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ]     CHAR (10)       CONSTRAINT [DF__BKADMAIN__FCUSED__51FC7761] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]      CHAR (10)       CONSTRAINT [DF__BKADMAIN__FCHIST__52F09B9A] DEFAULT ('') NOT NULL,
    [PMTAMTPR]        NUMERIC (10, 2) CONSTRAINT [DF__BKADMAIN__PMTAMT__60EB4BE4] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__BKADMAIN__PRFCUS__61DF701D] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__BKADMAIN__FUNCFC__62D39456] DEFAULT ('') NOT NULL,
    CONSTRAINT [BKADMAIN_PK] PRIMARY KEY CLUSTERED ([UNIQBKADMN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FK_BK_UNIQ]
    ON [dbo].[BKADMAIN]([FK_BK_UNIQ] ASC);

