CREATE TABLE [dbo].[BomRefDeleteLog] (
    [BomRefDeleteLogId] CHAR (10)     CONSTRAINT [DF__BomRefDel__BomRe__23C176BC] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [UNIQBOMNO]         CHAR (10)     CONSTRAINT [DF__BomRefDel__UNIQB__24B59AF5] DEFAULT ('') NOT NULL,
    [REF_DES]           VARCHAR (50)  CONSTRAINT [DF__BomRefDel__REF_D__25A9BF2E] DEFAULT ('') NOT NULL,
    [NBR]               NUMERIC (7)   CONSTRAINT [DF__BomRefDelet__NBR__269DE367] DEFAULT ((0)) NOT NULL,
    [UNIQUEREF]         CHAR (10)     CONSTRAINT [DF__BomRefDel__UNIQU__279207A0] DEFAULT ('') NOT NULL,
    [USERINFO]          VARCHAR (MAX) CONSTRAINT [DF__BomRefDel__USERI__28862BD9] DEFAULT ('') NOT NULL,
    [DELETEDTIME]       SMALLDATETIME CONSTRAINT [DF__BomRefDel__DELET__297A5012] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK__BomRefDe__DC408BF8864176D3] PRIMARY KEY CLUSTERED ([BomRefDeleteLogId] ASC)
);

