CREATE TABLE [dbo].[BUYERINI] (
    [INI]         CHAR (3)    CONSTRAINT [DF__BUYERINI__INI__1CDC41A7] DEFAULT ('') NOT NULL,
    [BUYNAME]     CHAR (20)   CONSTRAINT [DF__BUYERINI__BUYNAM__1DD065E0] DEFAULT ('') NOT NULL,
    [NUMBER]      NUMERIC (4) CONSTRAINT [DF__BUYERINI__NUMBER__1EC48A19] DEFAULT ((0)) NOT NULL,
    [UNIQUEBUYER] CHAR (10)   CONSTRAINT [DF__BUYERINI__UNIQUE__1FB8AE52] DEFAULT ('') NOT NULL,
    CONSTRAINT [BUYERINI_PK] PRIMARY KEY CLUSTERED ([UNIQUEBUYER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INI]
    ON [dbo].[BUYERINI]([INI] ASC);


GO
CREATE NONCLUSTERED INDEX [NUMBER]
    ON [dbo].[BUYERINI]([NUMBER] ASC);

