CREATE TABLE [dbo].[CASHBOOK] (
    [CBUNIQUE]         CHAR (10)       CONSTRAINT [DF__CASHBOOK__CBUNIQ__32D8D1C3] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [BK_UNIQ]          CHAR (10)       CONSTRAINT [DF__CASHBOOK__BK_UNI__33CCF5FC] DEFAULT ('') NOT NULL,
    [STMTDATE]         SMALLDATETIME   NULL,
    [FISCALYR]         CHAR (4)        CONSTRAINT [DF__CASHBOOK__FISCAL__34C11A35] DEFAULT ('') NOT NULL,
    [PERIOD]           NUMERIC (2)     CONSTRAINT [DF__CASHBOOK__PERIOD__35B53E6E] DEFAULT ((0)) NOT NULL,
    [PERSTART]         SMALLDATETIME   NULL,
    [PEREND]           SMALLDATETIME   NULL,
    [BEGBKBAL]         NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BEGBKB__36A962A7] DEFAULT ((0)) NOT NULL,
    [BEGBKBALFC]       NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BEGBKB__379D86E0] DEFAULT ((0)) NOT NULL,
    [BKDEPCLEARED]     NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKDEPC__3891AB19] DEFAULT ((0)) NOT NULL,
    [BKDEPCLEAREDFC]   NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKDEPC__3985CF52] DEFAULT ((0)) NOT NULL,
    [BKCKSCLEARED]     NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKCKSC__3A79F38B] DEFAULT ((0)) NOT NULL,
    [BKCKSCLEAREDFC]   NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKCKSC__3B6E17C4] DEFAULT ((0)) NOT NULL,
    [BKTRFRDEBITCL]    NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKTRFR__3C623BFD] DEFAULT ((0)) NOT NULL,
    [BKTRFRDEBITCLFC]  NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKTRFR__3D566036] DEFAULT ((0)) NOT NULL,
    [BKTRFRCREDITCL]   NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKTRFR__3E4A846F] DEFAULT ((0)) NOT NULL,
    [BKTRFRCREDITCLFC] NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKTRFR__3F3EA8A8] DEFAULT ((0)) NOT NULL,
    [ENDBAL]           NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__ENDBAL__4032CCE1] DEFAULT ((0)) NOT NULL,
    [ENDBALFC]         NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__ENDBAL__4126F11A] DEFAULT ((0)) NOT NULL,
    [BEGBKBALPR]       NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BEGBKB__7917DB30] DEFAULT ((0)) NOT NULL,
    [BKDEPCLEAREDPR]   NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKDEPC__7A0BFF69] DEFAULT ((0)) NOT NULL,
    [BKCKSCLEAREDPR]   NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKCKSC__7B0023A2] DEFAULT ((0)) NOT NULL,
    [BKTRFRDEBITCLPR]  NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKTRFR__7BF447DB] DEFAULT ((0)) NOT NULL,
    [BKTRFRCREDITCLPR] NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__BKTRFR__7CE86C14] DEFAULT ((0)) NOT NULL,
    [ENDBALPR]         NUMERIC (12, 2) CONSTRAINT [DF__CASHBOOK__ENDBAL__7DDC904D] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]    CHAR (10)       CONSTRAINT [DF__CASHBOOK__PRFCUS__7ED0B486] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ]  CHAR (10)       CONSTRAINT [DF__CASHBOOK__FUNCFC__7FC4D8BF] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK__CASHBOOK__1EC2D8333F3E577A] PRIMARY KEY CLUSTERED ([CBUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [cashbookBkUniq]
    ON [dbo].[CASHBOOK]([BK_UNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [CASHBOOKFY]
    ON [dbo].[CASHBOOK]([FISCALYR] ASC);


GO
CREATE NONCLUSTERED INDEX [CASHBOOKPeriod]
    ON [dbo].[CASHBOOK]([PERIOD] ASC);


GO
-- =============================================
-- Author:		Vicky Lu
-- Create date: 04/25/2017
-- Description:	Update PRFcused_uniq and FuncFcused_uniq
-- Modification:
-- =============================================
CREATE TRIGGER [dbo].[Cashbook_insert]
   ON  [dbo].[CashBook]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRANSACTION
	UPDATE CashBook SET PRFcused_uniq = CASE WHEN dbo.fn_IsFCInstalled() = 0 THEN SPACE(10) ELSE dbo.fn_GetPresentationCurrency() END,
						FuncFcused_uniq = CASE WHEN dbo.fn_IsFCInstalled() = 0 THEN SPACE(10) ELSE dbo.fn_GetFunctionalCurrency() END	
	FROM inserted I WHERE I.CBUnique=Cashbook.CBUnique
	COMMIT
    -- Insert statements for trigger here

END