CREATE TABLE [dbo].[CCRECORD] (
    [UNIQ_KEY]        CHAR (10)       CONSTRAINT [DF__CCRECORD__UNIQ_K__4C8B54C9] DEFAULT ('') NOT NULL,
    [UNIQCCNO]        CHAR (10)       CONSTRAINT [DF__CCRECORD__UNIQCC__4D7F7902] DEFAULT ('') NOT NULL,
    [W_KEY]           CHAR (10)       CONSTRAINT [DF__CCRECORD__W_KEY__4E739D3B] DEFAULT ('') NOT NULL,
    [LOCATION]        NVARCHAR (200)  CONSTRAINT [DF__CCRECORD__LOCATI__505BE5AD] DEFAULT ('') NOT NULL,
    [LOTCODE]         NVARCHAR (25)   CONSTRAINT [DF__CCRECORD__LOTCOD__542C7691] DEFAULT ('') NOT NULL,
    [REFERENCE]       CHAR (12)       CONSTRAINT [DF__CCRECORD__REFERE__55209ACA] DEFAULT ('') NOT NULL,
    [PONUM]           CHAR (15)       CONSTRAINT [DF__CCRECORD__PONUM__5614BF03] DEFAULT ('') NOT NULL,
    [QTY_OH]          NUMERIC (12, 2) CONSTRAINT [DF__CCRECORD__QTY_OH__5708E33C] DEFAULT ((0)) NOT NULL,
    [SYS_DATE]        SMALLDATETIME   NULL,
    [CCOUNT]          NUMERIC (12, 2) CONSTRAINT [DF__CCRECORD__CCOUNT__57FD0775] DEFAULT ((0)) NOT NULL,
    [CCINIT]          CHAR (8)        CONSTRAINT [DF__CCRECORD__CCINIT__58F12BAE] DEFAULT ('') NULL,
    [ABC]             CHAR (1)        CONSTRAINT [DF__CCRECORD__ABC__59E54FE7] DEFAULT ('') NOT NULL,
    [CCDATE]          SMALLDATETIME   NULL,
    [CCREASON]        CHAR (20)       CONSTRAINT [DF__CCRECORD__CCREAS__5AD97420] DEFAULT ('') NOT NULL,
    [CCRECNCL]        BIT             CONSTRAINT [DF__CCRECORD__CCRECN__5BCD9859] DEFAULT ((0)) NOT NULL,
    [CCQ]             BIT             CONSTRAINT [DF__CCRECORD__CCQ__5CC1BC92] DEFAULT ((0)) NOT NULL,
    [CCD]             BIT             CONSTRAINT [DF__CCRECORD__CCD__5DB5E0CB] DEFAULT ((0)) NOT NULL,
    [STDCOST]         NUMERIC (13, 5) CONSTRAINT [DF__CCRECORD__STDCOS__5EAA0504] DEFAULT ((0)) NOT NULL,
    [EXPDATE]         SMALLDATETIME   NULL,
    [POSTED]          BIT             CONSTRAINT [DF__CCRECORD__POSTED__5F9E293D] DEFAULT ((0)) NOT NULL,
    [UNIQ_LOT]        CHAR (10)       CONSTRAINT [DF__CCRECORD__UNIQ_L__60924D76] DEFAULT ('') NOT NULL,
    [IS_UPDATED]      BIT             CONSTRAINT [DF__CCRECORD__IS_UPD__618671AF] DEFAULT ((0)) NOT NULL,
    [UNIQWH]          CHAR (10)       NOT NULL,
    [UniqSupno]       CHAR (10)       CONSTRAINT [DF__CCRECORD__UniqSu__69B33A0A] DEFAULT ('') NOT NULL,
    [UniqMfgrHd]      CHAR (10)       CONSTRAINT [DF__CCRECORD__UniqMf__6AA75E43] DEFAULT ('') NOT NULL,
    [STDCOSTPR]       NUMERIC (13, 5) CONSTRAINT [DF__CCRECORD__STDCOS__2575805B] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__CCRECORD__PRFCUS__52F23248] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__CCRECORD__FUNCFC__53E65681] DEFAULT ('') NOT NULL,
    CONSTRAINT [CCRECORD_PK] PRIMARY KEY CLUSTERED ([UNIQCCNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[CCRECORD]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQWKEY]
    ON [dbo].[CCRECORD]([UNIQ_KEY] ASC, [W_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [W_KEY]
    ON [dbo].[CCRECORD]([W_KEY] ASC);

