CREATE TABLE [dbo].[CFGOTHER] (
    [UNIQ_KEY]    CHAR (10)       CONSTRAINT [DF__CFGOTHER__UNIQ_K__6462DE5A] DEFAULT ('') NOT NULL,
    [DESCRIPT]    CHAR (35)       CONSTRAINT [DF__CFGOTHER__DESCRI__65570293] DEFAULT ('') NOT NULL,
    [SALEPRICE]   NUMERIC (12, 5) CONSTRAINT [DF__CFGOTHER__SALEPR__664B26CC] DEFAULT ((0)) NOT NULL,
    [UNIQ_OTHER]  CHAR (10)       CONSTRAINT [DF__CFGOTHER__UNIQ_O__673F4B05] DEFAULT ('') NOT NULL,
    [SALEPRICEFC] NUMERIC (12, 5) CONSTRAINT [DF__CFGOTHER__SALEPR__371E63F3] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__CFGOTHER__FCUSED__3812882C] DEFAULT ('') NOT NULL,
    CONSTRAINT [CFGOTHER_PK] PRIMARY KEY CLUSTERED ([UNIQ_OTHER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[CFGOTHER]([UNIQ_KEY] ASC);

