CREATE TABLE [dbo].[CHECKLAYOUT] (
    [UNIQLAYOUT]  CHAR (10)   CONSTRAINT [DF__CHECKLAYO__UNIQL__6A1BB7B0] DEFAULT ('') NOT NULL,
    [FORMNAME]    CHAR (40)   CONSTRAINT [DF__CHECKLAYO__FORMN__6B0FDBE9] DEFAULT ('') NOT NULL,
    [FORMDESCR]   TEXT        CONSTRAINT [DF__CHECKLAYO__FORMD__6C040022] DEFAULT ('') NOT NULL,
    [NO_SECTION]  NUMERIC (1) CONSTRAINT [DF__CHECKLAYO__NO_SE__6CF8245B] DEFAULT ((0)) NOT NULL,
    [DETAILLINES] NUMERIC (2) CONSTRAINT [DF__CHECKLAYO__DETAI__6DEC4894] DEFAULT ((0)) NOT NULL,
    [LAYOUT]      TEXT        CONSTRAINT [DF__CHECKLAYO__LAYOU__6EE06CCD] DEFAULT ('') NOT NULL,
    [REPORTNAME]  CHAR (10)   CONSTRAINT [DF__CHECKLAYO__REPOR__6FD49106] DEFAULT ('') NOT NULL,
    [CHECKTYPE]   CHAR (4)    CONSTRAINT [DF__CHECKLAYO__CHECK__70C8B53F] DEFAULT ('') NOT NULL,
    CONSTRAINT [CHECKLAYOUT_PK] PRIMARY KEY CLUSTERED ([UNIQLAYOUT] ASC)
);

