CREATE TABLE [dbo].[CMADJ] (
    [PACKLISTNO]  CHAR (10)     CONSTRAINT [DF_CMADJ_PACKLISTNO] DEFAULT ('') NOT NULL,
    [UNIQUELN]    CHAR (10)     CONSTRAINT [DF_CMADJ_UNIQUELN] DEFAULT ('') NOT NULL,
    [SAVEDDATE]   SMALLDATETIME NULL,
    [RECVQTY]     NUMERIC (7)   CONSTRAINT [DF_CMADJ_RECVQTY] DEFAULT ((0)) NOT NULL,
    [UNIQUECMADJ] INT           IDENTITY (1, 1) NOT NULL,
    [CmUnique]    CHAR (10)     CONSTRAINT [DF__CMADJ__CmUnique__54582A71] DEFAULT (' ') NOT NULL,
    CONSTRAINT [CMADJ_PK] PRIMARY KEY CLUSTERED ([UNIQUECMADJ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PACKLISTNO]
    ON [dbo].[CMADJ]([PACKLISTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQUELN]
    ON [dbo].[CMADJ]([UNIQUELN] ASC);

