CREATE TABLE [dbo].[CMFREIGHTTAX] (
    [UNIQCMFREIGHTTAX] CHAR (10)      CONSTRAINT [DF__CMFREIGHT__UNIQC__07047126] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [CMUNIQUE]         CHAR (10)      CONSTRAINT [DF__CMFREIGHT__CMUNI__07F8955F] DEFAULT ('') NOT NULL,
    [TAX_ID]           CHAR (8)       CONSTRAINT [DF__CMFREIGHT__TAX_I__08ECB998] DEFAULT ('') NOT NULL,
    [TAX_RATE]         NUMERIC (8, 4) CONSTRAINT [DF__CMFREIGHT__TAX_R__09E0DDD1] DEFAULT ((0)) NOT NULL,
    [PTPROD]           BIT            CONSTRAINT [DF__CMFREIGHT__PTPRO__0AD5020A] DEFAULT ((0)) NOT NULL,
    [PTFRT]            BIT            CONSTRAINT [DF__CMFREIGHT__PTFRT__0BC92643] DEFAULT ((0)) NOT NULL,
    [STPROD]           BIT            CONSTRAINT [DF__CMFREIGHT__STPRO__0CBD4A7C] DEFAULT ((0)) NOT NULL,
    [STFRT]            BIT            CONSTRAINT [DF__CMFREIGHT__STFRT__0DB16EB5] DEFAULT ((0)) NOT NULL,
    [STTX]             BIT            CONSTRAINT [DF__CMFREIGHTT__STTX__0EA592EE] DEFAULT ((0)) NOT NULL,
    [TAXTYPE]          CHAR (1)       CONSTRAINT [DF__CMFREIGHT__TAXTY__0F99B727] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK__CMFREIGH__AB519026B5034A89] PRIMARY KEY CLUSTERED ([UNIQCMFREIGHTTAX] ASC)
);

