CREATE TABLE [dbo].[CMINVLOT] (
    [UKCMINVLOT] CHAR (10)       CONSTRAINT [DF__CMINVLOT__UKCMIN__1CA7377D] DEFAULT ('') NOT NULL,
    [UNIQ_ALLOC] CHAR (10)       CONSTRAINT [DF__CMINVLOT__UNIQ_A__1D9B5BB6] DEFAULT ('') NOT NULL,
    [W_KEY]      CHAR (10)       CONSTRAINT [DF__CMINVLOT__W_KEY__1E8F7FEF] DEFAULT ('') NOT NULL,
    [LOTCODE]    NVARCHAR (25)   CONSTRAINT [DF__CMINVLOT__LOTCOD__1F83A428] DEFAULT ('') NULL,
    [EXPDATE]    SMALLDATETIME   NULL,
    [REFERENCE]  CHAR (12)       CONSTRAINT [DF__CMINVLOT__REFERE__2077C861] DEFAULT ('') NOT NULL,
    [PONUM]      CHAR (15)       CONSTRAINT [DF__CMINVLOT__PONUM__216BEC9A] DEFAULT ('') NOT NULL,
    [ALLOCQTY]   NUMERIC (12, 2) CONSTRAINT [DF__CMINVLOT__ALLOCQ__226010D3] DEFAULT ((0)) NOT NULL,
    [CmUnique]   CHAR (10)       CONSTRAINT [DF__CMINVLOT__CmUniq__554C4EAA] DEFAULT (' ') NOT NULL,
    CONSTRAINT [CMINVLOT_PK] PRIMARY KEY CLUSTERED ([UKCMINVLOT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_ALLOC]
    ON [dbo].[CMINVLOT]([UNIQ_ALLOC] ASC);


GO
CREATE NONCLUSTERED INDEX [W_KEYLOT]
    ON [dbo].[CMINVLOT]([W_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [UNQWKEYLOT]
    ON [dbo].[CMINVLOT]([UNIQ_ALLOC] ASC, [W_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);

