CREATE TABLE [dbo].[CMPRICES] (
    [CMEMONO]      CHAR (10)       CONSTRAINT [DF__CMPRICES__CMEMON__7740A8A4] DEFAULT ('') NOT NULL,
    [PACKLISTNO]   CHAR (10)       CONSTRAINT [DF__CMPRICES__PACKLI__7834CCDD] DEFAULT ('') NOT NULL,
    [UNIQUELN]     CHAR (10)       CONSTRAINT [DF__CMPRICES__UNIQUE__7928F116] DEFAULT ('') NOT NULL,
    [DESCRIPT]     CHAR (45)       CONSTRAINT [DF__CMPRICES__DESCRI__7A1D154F] DEFAULT ('') NOT NULL,
    [CMQUANTITY]   NUMERIC (10, 2) CONSTRAINT [DF__CMPRICES__CMQUAN__7B113988] DEFAULT ((0)) NOT NULL,
    [CMPRICE]      NUMERIC (14, 5) CONSTRAINT [DF__CMPRICES__CMPRIC__7C055DC1] DEFAULT ((0)) NOT NULL,
    [CMEXTENDED]   NUMERIC (20, 2) CONSTRAINT [DF__CMPRICES__CMEXTE__7CF981FA] DEFAULT ((0)) NOT NULL,
    [TAXABLE]      BIT             CONSTRAINT [DF__CMPRICES__TAXABL__7EE1CA6C] DEFAULT ((0)) NOT NULL,
    [FLAT]         BIT             CONSTRAINT [DF__CMPRICES__FLAT__7FD5EEA5] DEFAULT ((0)) NOT NULL,
    [INV_LINK]     CHAR (10)       CONSTRAINT [DF__CMPRICES__INV_LI__00CA12DE] DEFAULT ('') NOT NULL,
    [RECORDTYPE]   CHAR (1)        CONSTRAINT [DF__CMPRICES__RECORD__01BE3717] DEFAULT ('') NOT NULL,
    [IS_RESTOCK]   BIT             CONSTRAINT [DF__CMPRICES__IS_RES__02B25B50] DEFAULT ((0)) NOT NULL,
    [RESTOCKQTY]   NUMERIC (9, 2)  CONSTRAINT [DF__CMPRICES__RESTOC__03A67F89] DEFAULT ((0)) NOT NULL,
    [SCRAPQTY]     NUMERIC (9, 2)  CONSTRAINT [DF__CMPRICES__SCRAPQ__049AA3C2] DEFAULT ((0)) NOT NULL,
    [AMORTFLAG]    CHAR (1)        CONSTRAINT [DF__CMPRICES__AMORTF__058EC7FB] DEFAULT ('') NOT NULL,
    [SALESTYPE]    CHAR (15)       CONSTRAINT [DF__CMPRICES__SALEST__0682EC34] DEFAULT ('') NOT NULL,
    [PL_GL_NBR]    CHAR (13)       CONSTRAINT [DF__CMPRICES__PL_GL___0777106D] DEFAULT ('') NOT NULL,
    [PLPRICELNK]   CHAR (10)       CONSTRAINT [DF__CMPRICES__PLPRIC__086B34A6] DEFAULT ('') NOT NULL,
    [PLUNIQLNK]    CHAR (10)       CONSTRAINT [DF__CMPRICES__PLUNIQ__095F58DF] DEFAULT ('') NOT NULL,
    [COG_GL_NBR]   CHAR (13)       CONSTRAINT [DF__CMPRICES__COG_GL__0A537D18] DEFAULT ('') NOT NULL,
    [CMPRICELNK]   CHAR (10)       CONSTRAINT [DF__CMPRICES__CMPRIC__0B47A151] DEFAULT ('') NOT NULL,
    [CMPRUNIQ]     CHAR (10)       CONSTRAINT [DF__CMPRICES__CMPRUN__0C3BC58A] DEFAULT ('') NOT NULL,
    [cmunique]     CHAR (10)       CONSTRAINT [DF_CMPRICES_cmunique] DEFAULT ('') NOT NULL,
    [CMPRICEFC]    NUMERIC (14, 5) CONSTRAINT [DF__CMPRICES__CMPRIC__1CF3B245] DEFAULT ((0)) NOT NULL,
    [CMEXTENDEDFC] NUMERIC (20, 2) CONSTRAINT [DF__CMPRICES__CMEXTE__1DE7D67E] DEFAULT ((0)) NOT NULL,
    [CMPRICEPR]    NUMERIC (14, 5) CONSTRAINT [DF__CMPRICES__CMPRIC__700D93E3] DEFAULT ((0)) NOT NULL,
    [CMEXTENDEDPR] NUMERIC (20, 2) CONSTRAINT [DF__CMPRICES__CMEXTE__7101B81C] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [CMPRICES_PK] PRIMARY KEY CLUSTERED ([CMPRUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CMEMONO]
    ON [dbo].[CMPRICES]([CMEMONO] ASC);


GO
CREATE NONCLUSTERED INDEX [CMPRICELNK]
    ON [dbo].[CMPRICES]([CMPRICELNK] ASC);


GO
CREATE NONCLUSTERED INDEX [cmunique]
    ON [dbo].[CMPRICES]([cmunique] ASC);


GO
CREATE NONCLUSTERED INDEX [INV_LINK]
    ON [dbo].[CMPRICES]([INV_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [PACKLISTNO]
    ON [dbo].[CMPRICES]([PACKLISTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [PKNO_UNIQ]
    ON [dbo].[CMPRICES]([PACKLISTNO] ASC, [UNIQUELN] ASC);


GO
CREATE NONCLUSTERED INDEX [PLPRICELNK]
    ON [dbo].[CMPRICES]([PLPRICELNK] ASC);


GO
CREATE NONCLUSTERED INDEX [PLUNIQLNK]
    ON [dbo].[CMPRICES]([PLUNIQLNK] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQUELN]
    ON [dbo].[CMPRICES]([UNIQUELN] ASC);

