CREATE TABLE [dbo].[CMPRICESTAX] (
    [UNIQCMPRICESTAX] CHAR (10)      CONSTRAINT [DF__CMPRICEST__UNIQC__78B651CF] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [CMUNIQUE]        CHAR (10)      CONSTRAINT [DF__CMPRICEST__CMUNI__79AA7608] DEFAULT ('') NOT NULL,
    [CMPRICELNK]      CHAR (10)      CONSTRAINT [DF__CMPRICEST__CMPRI__7A9E9A41] DEFAULT ('') NOT NULL,
    [CMPRUNIQ]        CHAR (10)      CONSTRAINT [DF__CMPRICEST__CMPRU__7B92BE7A] DEFAULT ('') NOT NULL,
    [TAX_ID]          CHAR (8)       CONSTRAINT [DF__CMPRICEST__TAX_I__7C86E2B3] DEFAULT ('') NOT NULL,
    [TAX_RATE]        NUMERIC (8, 4) CONSTRAINT [DF__CMPRICEST__TAX_R__7D7B06EC] DEFAULT ((0)) NOT NULL,
    [TAXTYPE]         CHAR (1)       CONSTRAINT [DF__CMPRICEST__TAXTY__7E6F2B25] DEFAULT ('') NOT NULL,
    [PTPROD]          BIT            CONSTRAINT [DF__CMPRICEST__PTPRO__7F634F5E] DEFAULT ((0)) NOT NULL,
    [PTFRT]           BIT            CONSTRAINT [DF__CMPRICEST__PTFRT__00577397] DEFAULT ((0)) NOT NULL,
    [STPROD]          BIT            CONSTRAINT [DF__CMPRICEST__STPRO__014B97D0] DEFAULT ((0)) NOT NULL,
    [STFRT]           BIT            CONSTRAINT [DF__CMPRICEST__STFRT__023FBC09] DEFAULT ((0)) NOT NULL,
    [STTX]            BIT            CONSTRAINT [DF__CMPRICESTA__STTX__0333E042] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__CMPRICES__2293EEE571B5E441] PRIMARY KEY CLUSTERED ([UNIQCMPRICESTAX] ASC)
);

