CREATE TABLE [dbo].[CMSER] (
    [UKCMSER]    CHAR (10) CONSTRAINT [DF__CMSER__UKCMSER__0F183235] DEFAULT ('') NOT NULL,
    [PACKLISTNO] CHAR (10) CONSTRAINT [DF__CMSER__PACKLISTN__100C566E] DEFAULT ('') NOT NULL,
    [SERIALNO]   CHAR (30) CONSTRAINT [DF__CMSER__SERIALNO__11007AA7] DEFAULT ('') NOT NULL,
    [UNIQUELN]   CHAR (10) CONSTRAINT [DF__CMSER__UNIQUELN__11F49EE0] DEFAULT ('') NOT NULL,
    [WONO]       CHAR (10) CONSTRAINT [DF__CMSER__WONO__12E8C319] DEFAULT ('') NOT NULL,
    [SERIALUNIQ] CHAR (10) CONSTRAINT [DF__CMSER__SERIALUNI__13DCE752] DEFAULT ('') NOT NULL,
    [UNIQ_ALLOC] CHAR (10) CONSTRAINT [DF__CMSER__UNIQ_ALLO__14D10B8B] DEFAULT ('') NOT NULL,
    [UKCMINVLOT] CHAR (10) CONSTRAINT [DF__CMSER__UKCMINVLO__15C52FC4] DEFAULT ('') NOT NULL,
    [CmUnique]   CHAR (10) CONSTRAINT [DF__CMSER__CmUnique__53640638] DEFAULT (' ') NOT NULL,
    CONSTRAINT [CMSER_PK] PRIMARY KEY CLUSTERED ([UKCMSER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PKNO_UKLN]
    ON [dbo].[CMSER]([PACKLISTNO] ASC, [UNIQUELN] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [PKSERUNIQ]
    ON [dbo].[CMSER]([PACKLISTNO] ASC, [SERIALUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [PKWOSERIAL]
    ON [dbo].[CMSER]([PACKLISTNO] ASC, [WONO] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIAL]
    ON [dbo].[CMSER]([SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIALNO]
    ON [dbo].[CMSER]([WONO] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UKCMINVLOT]
    ON [dbo].[CMSER]([UKCMINVLOT] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_ALLOC]
    ON [dbo].[CMSER]([UNIQ_ALLOC] ASC);

