CREATE TABLE [dbo].[CNFGFETR] (
    [UNIQ_KEY]   CHAR (10) CONSTRAINT [DF__CNFGFETR__UNIQ_K__18A19C6F] DEFAULT ('') NOT NULL,
    [ISREQUIRED] BIT       CONSTRAINT [DF__CNFGFETR__ISREQU__1995C0A8] DEFAULT ((0)) NOT NULL,
    [PDFETRUNIQ] CHAR (10) CONSTRAINT [DF__CNFGFETR__PDFETR__1A89E4E1] DEFAULT ('') NOT NULL,
    [UNIQ_FETR]  CHAR (10) CONSTRAINT [DF__CNFGFETR__UNIQ_F__1B7E091A] DEFAULT ('') NOT NULL,
    CONSTRAINT [CNFGFETR_PK] PRIMARY KEY CLUSTERED ([UNIQ_FETR] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PDFETRUNIQ]
    ON [dbo].[CNFGFETR]([PDFETRUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[CNFGFETR]([UNIQ_KEY] ASC);

