CREATE TABLE [dbo].[CONTRACT] (
    [CONTR_UNIQ]       CHAR (10)   CONSTRAINT [DF__CONTRACT__CONTR___4FF1D159] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]         CHAR (10)   CONSTRAINT [DF__CONTRACT__UNIQ_K__52CE3E04] DEFAULT ('') NOT NULL,
    [QTYLIMIT]         NUMERIC (7) CONSTRAINT [DF__CONTRACT__QTYLIM__54B68676] DEFAULT ((0)) NOT NULL,
    [contractItemNote] TEXT        CONSTRAINT [DF__CONTRACT__CONTR___569ECEE8] DEFAULT ('') NOT NULL,
    [contractH_unique] CHAR (10)   CONSTRAINT [DF_CONTRACT_contractH_unique] DEFAULT ('') NOT NULL,
    [MINQTY]           NUMERIC (7) CONSTRAINT [DF__CONTRACT__MINQTY__49FCF994] DEFAULT ((0)) NULL,
    CONSTRAINT [CONTRACT_PK] PRIMARY KEY CLUSTERED ([CONTR_UNIQ] ASC),
    CONSTRAINT [FK_CONTRACT_CONTRACTH] FOREIGN KEY ([contractH_unique]) REFERENCES [dbo].[contractHeader] ([ContractH_unique]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_CONTRACTH]
    ON [dbo].[CONTRACT]([contractH_unique] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[CONTRACT]([UNIQ_KEY] ASC);

