CREATE TABLE [dbo].[CONTMFGR] (
    [CONTR_UNIQ] CHAR (10) CONSTRAINT [DF__CONTMFGR__CONTR___438BFA74] DEFAULT ('') NOT NULL,
    [MFGR_UNIQ]  CHAR (10) CONSTRAINT [DF__CONTMFGR__MFGR_U__44801EAD] DEFAULT ('') NOT NULL,
    [PARTMFGR]   CHAR (8)  CONSTRAINT [DF__CONTMFGR__PARTMF__457442E6] DEFAULT ('') NOT NULL,
    [MFGR_PT_NO] CHAR (30) CONSTRAINT [DF__CONTMFGR__MFGR_P__4668671F] DEFAULT ('') NOT NULL,
    [Pur_ltime]  INT       CONSTRAINT [DF_CONTMFGR_Purl_time] DEFAULT ((0)) NOT NULL,
    [pur_lunit]  CHAR (2)  CONSTRAINT [DF_CONTMFGR_purl_unit] DEFAULT ('') NOT NULL,
    [PRIORITY]   INT       NULL,
    CONSTRAINT [CONTMFGR_PK] PRIMARY KEY CLUSTERED ([MFGR_UNIQ] ASC),
    CONSTRAINT [FK_CONTMFGR_CONTRACT] FOREIGN KEY ([CONTR_UNIQ]) REFERENCES [dbo].[CONTRACT] ([CONTR_UNIQ]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [CONTR_UNIQ]
    ON [dbo].[CONTMFGR]([CONTR_UNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [MFGR_PT_NO]
    ON [dbo].[CONTMFGR]([MFGR_PT_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [MPN]
    ON [dbo].[CONTMFGR]([PARTMFGR] ASC, [MFGR_PT_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [PARTMFGR]
    ON [dbo].[CONTMFGR]([PARTMFGR] ASC);

