CREATE TABLE [dbo].[contractHeader] (
    [ContractH_unique] CHAR (10)        CONSTRAINT [DF_contractHeader_CotractH_unique] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [Contr_no]         NVARCHAR (20)    CONSTRAINT [DF_contractHeader_Contr_no] DEFAULT ('') NOT NULL,
    [quote_no]         NVARCHAR (20)    CONSTRAINT [DF_contractHeader_quote_no] DEFAULT ('') NOT NULL,
    [startDate]        DATE             NULL,
    [expireDate]       DATE             NULL,
    [primSupplier]     BIT              CONSTRAINT [DF_contractHeader_primSupplier] DEFAULT ((0)) NOT NULL,
    [contractNote]     NVARCHAR (MAX)   CONSTRAINT [DF_contractHeader_contractNote] DEFAULT ('') NOT NULL,
    [uniqsupno]        CHAR (10)        CONSTRAINT [DF_contractHeader_uniqsupno] DEFAULT ('') NOT NULL,
    [fcused_uniq]      CHAR (10)        CONSTRAINT [DF_contractHeader_fcused_uniq] DEFAULT ('') NOT NULL,
    [fchist_key]       CHAR (10)        CONSTRAINT [DF_contractHeader_fchist_key] DEFAULT ('') NOT NULL,
    [prFcUsed_uniq]    CHAR (10)        CONSTRAINT [DF_contractHeader_prFcUsed_uniq] DEFAULT ('') NOT NULL,
    [funcFcused_uniq]  CHAR (10)        CONSTRAINT [DF_contractHeader_funcFcused_uniq] DEFAULT ('') NOT NULL,
    [AutoGenerated]    BIT              CONSTRAINT [DF_contractHeader_AutoGenerated] DEFAULT ((0)) NOT NULL,
    [contrGenDate]     SMALLDATETIME    CONSTRAINT [DF_contractHeader_contrGenDate] DEFAULT (getdate()) NULL,
    [contrUserId]      UNIQUEIDENTIFIER NULL,
    [contrUpdateDate]  SMALLDATETIME    NULL,
    [contrUpdatedby]   UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_contractHeader] PRIMARY KEY CLUSTERED ([ContractH_unique] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_contractSupplier]
    ON [dbo].[contractHeader]([uniqsupno] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_contractstartDt]
    ON [dbo].[contractHeader]([startDate] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_contractexpDate]
    ON [dbo].[contractHeader]([expireDate] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_contractQuote]
    ON [dbo].[contractHeader]([quote_no] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_contractHeader]
    ON [dbo].[contractHeader]([ContractH_unique] ASC);


GO
-- =============================================
-- Author:		<Rajendra K>
-- Create date: <8/18/2017>
-- Description:	<Update columns fchist_key,prFcUsed_uniq ,funcFcused_uniq from table ContractHeader when user insert new ContractHeader record>
-- Modification
   -- 09/19/2017 Rajendra K : removed statement updating FcHist_Key 
-- =============================================
CREATE TRIGGER [dbo].[ContractHeader_Insert]
	ON dbo.contractHeader
AFTER INSERT
AS
BEGIN
-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;
	DECLARE @FCInstalled BIT

	BEGIN TRY
		BEGIN TRANSACTION
		IF NOT EXISTS (select 1 from  ContractHeader CH inner join Inserted I on  CH.ContractH_unique = I.ContractH_unique)
			BEGIN
				RAISERROR ('Cannot Locate any Records in ContractHeader Table to update price.', -- Message text.
				   16, -- Severity.
					1 -- State.
				);

			END

  		SELECT @FCInstalled = dbo.fn_IsFCInstalled()  --Check for fc setting

		IF @FCInstalled=1
			BEGIN

				UPDATE ContractHeader SET FuncFcUsed_Uniq = dbo.fn_GetFunctionalCurrency() 
										 ,PrFcUsed_Uniq = dbo.fn_GetPresentationCurrency()
										 -- 09/19/2017 Rajendra K : removed statement updating FcHist_Key 
				FROM inserted UC WHERE UC.ContractH_unique = ContractHeader.ContractH_unique
			END
	  END TRY
   BEGIN CATCH
		IF @@TRANCOUNT>0
			ROLLBACK
			SELECT @ErrorMessage = ERROR_MESSAGE(),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE();
			RAISERROR (@ErrorMessage, -- Message text.
               @ErrorSeverity, -- Severity.
               @ErrorState -- State.
               );

  END CATCH
  IF @@TRANCOUNT>0
		COMMIT	
END