CREATE TABLE [dbo].[CRACTEAM] (
    [TMCARNO]   CHAR (10) CONSTRAINT [DF_CRACTEAM_TMCARNO] DEFAULT ('') NOT NULL,
    [CRMEMBER]  CHAR (8)  CONSTRAINT [DF_CRACTEAM_CRMEMBER] DEFAULT ('') NULL,
    [UNIQUENUM] INT       IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CRACTEAM_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CRTEAM]
    ON [dbo].[CRACTEAM]([TMCARNO] ASC, [CRMEMBER] ASC);

