CREATE TABLE [dbo].[CUDEFDET] (
    [DEF_CODE]  VARCHAR (20) NOT NULL,
    [DEPT_ID]   CHAR (4)     CONSTRAINT [DF__CUDEFDET1__DEPT___3B57727D] DEFAULT ('') NOT NULL,
    [UNIQUENUM] INT          IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CUDEFDET_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEF_CODE]
    ON [dbo].[CUDEFDET]([DEF_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [DEPT_ID]
    ON [dbo].[CUDEFDET]([DEPT_ID] ASC);

