CREATE TABLE [dbo].[CURRENCY] (
    [UNIQ_CURR]  CHAR (10)       CONSTRAINT [DF__CURRENCY__UNIQ_C__149C0161] DEFAULT ('') NOT NULL,
    [DEFAULT]    BIT             CONSTRAINT [DF__CURRENCY__DEFAUL__1590259A] DEFAULT ((0)) NOT NULL,
    [CURR_NAME]  CHAR (20)       CONSTRAINT [DF__CURRENCY__CURR_N__168449D3] DEFAULT ('') NOT NULL,
    [SYMBOL]     CHAR (8)        CONSTRAINT [DF__CURRENCY__SYMBOL__17786E0C] DEFAULT ('') NOT NULL,
    [BEFORE]     NUMERIC (1)     CONSTRAINT [DF__CURRENCY__BEFORE__186C9245] DEFAULT ((0)) NOT NULL,
    [THOU_SYM]   CHAR (1)        CONSTRAINT [DF__CURRENCY__THOU_S__1960B67E] DEFAULT ('') NOT NULL,
    [DEC_SYM]    CHAR (1)        CONSTRAINT [DF__CURRENCY__DEC_SY__1A54DAB7] DEFAULT ('') NOT NULL,
    [DEC_DIGITS] NUMERIC (1)     CONSTRAINT [DF__CURRENCY__DEC_DI__1B48FEF0] DEFAULT ((0)) NOT NULL,
    [OLDRATE]    NUMERIC (14, 5) CONSTRAINT [DF__CURRENCY__OLDRAT__1C3D2329] DEFAULT ((0)) NOT NULL,
    [OLDDATE]    SMALLDATETIME   NULL,
    [OLDINIT]    CHAR (8)        CONSTRAINT [DF__CURRENCY__OLDINI__1D314762] DEFAULT ('') NULL,
    [CURRRATE]   NUMERIC (14, 5) CONSTRAINT [DF__CURRENCY__CURRRA__1E256B9B] DEFAULT ((0)) NOT NULL,
    [CURRDATE]   SMALLDATETIME   NULL,
    [CURRINIT]   CHAR (8)        CONSTRAINT [DF__CURRENCY__CURRIN__1F198FD4] DEFAULT ('') NULL,
    [NEWRATE]    NUMERIC (14, 5) CONSTRAINT [DF__CURRENCY__NEWRAT__200DB40D] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [CURRENCY_PK] PRIMARY KEY CLUSTERED ([UNIQ_CURR] ASC)
);

