CREATE TABLE [dbo].[CUSTREPT] (
    [RPTTYPE]       CHAR (6)      CONSTRAINT [DF__CUSTREPT2__RPTTY__78958AE7] DEFAULT ('') NOT NULL,
    [OPTIONS]       CHAR (1)      CONSTRAINT [DF__CUSTREPT2__OPTIO__7989AF20] DEFAULT ('') NOT NULL,
    [TYPE]          CHAR (10)     CONSTRAINT [DF__CUSTREPT2__TYPE__7A7DD359] DEFAULT ('') NOT NULL,
    [SEQUENCE]      INT           CONSTRAINT [DF__CUSTREPT2__SEQUE__7B71F792] DEFAULT ((0)) NOT NULL,
    [TITLE]         CHAR (50)     CONSTRAINT [DF__CUSTREPT2__TITLE__7C661BCB] DEFAULT ('') NOT NULL,
    [COMMENTS]      VARCHAR (254) CONSTRAINT [DF__CUSTREPT2__COMME__7D5A4004] DEFAULT ('') NOT NULL,
    [RPTNAME]       CHAR (8)      CONSTRAINT [DF__CUSTREPT2__RPTNA__7E4E643D] DEFAULT ('') NOT NULL,
    [RPTDETAIL]     CHAR (8)      CONSTRAINT [DF__CUSTREPT2__RPTDE__7F428876] DEFAULT ('') NOT NULL,
    [TYPE2]         CHAR (10)     CONSTRAINT [DF__CUSTREPT2__TYPE2__0036ACAF] DEFAULT ('') NOT NULL,
    [TITLE2]        CHAR (30)     CONSTRAINT [DF__CUSTREPT2__TITLE__012AD0E8] DEFAULT ('') NOT NULL,
    [COMMENTS2]     VARCHAR (254) CONSTRAINT [DF__CUSTREPT2__COMME__021EF521] DEFAULT ('') NOT NULL,
    [ASKDATE]       BIT           CONSTRAINT [DF__CUSTREPT2__ASKDA__04073D93] DEFAULT ((0)) NOT NULL,
    [LABEL]         CHAR (1)      CONSTRAINT [DF__CUSTREPT2__LABEL__05EF8605] DEFAULT ('') NOT NULL,
    [FILEPATH]      VARCHAR (254) CONSTRAINT [DF__CUSTREPT2__FILEP__06E3AA3E] DEFAULT ('') NOT NULL,
    [SECTION]       CHAR (4)      CONSTRAINT [DF__CUSTREPT2__SECTI__07D7CE77] DEFAULT ('') NOT NULL,
    [MULTIPLEEMAIL] BIT           CONSTRAINT [DF__CUSTREPT2__MULTI__08CBF2B0] DEFAULT ((0)) NOT NULL,
    [UNIQUENUM]     INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CUSTREPT_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RPTNAME]
    ON [dbo].[CUSTREPT]([RPTNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [SEQUENCE]
    ON [dbo].[CUSTREPT]([TYPE] ASC, [SEQUENCE] ASC);


GO
CREATE NONCLUSTERED INDEX [TYPE]
    ON [dbo].[CUSTREPT]([TYPE] ASC);

