CREATE TABLE [dbo].[CUSTREPS] (
    [SREPNO]    CHAR (10) CONSTRAINT [DF__CUSTREPS__SREPNO__5EFF0ABF] DEFAULT ('') NOT NULL,
    [CUSTNO]    CHAR (10) CONSTRAINT [DF__CUSTREPS__CUSTNO__5FF32EF8] DEFAULT ('') NOT NULL,
    [SREPTYPE]  CHAR (10) CONSTRAINT [DF__CUSTREPS__SREPTY__60E75331] DEFAULT ('') NOT NULL,
    [SREPNAME]  CHAR (25) CONSTRAINT [DF__CUSTREPS__SREPNA__61DB776A] DEFAULT ('') NOT NULL,
    [UNIQUEREC] CHAR (10) CONSTRAINT [DF__CUSTREPS__UNIQUE__62CF9BA3] DEFAULT ('') NOT NULL,
    CONSTRAINT [CUSTREPS_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTOMERID]
    ON [dbo].[CUSTREPS]([CUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SREPNO]
    ON [dbo].[CUSTREPS]([SREPNO] ASC);

