CREATE TABLE [dbo].[CUSTFWUP] (
    [UNIQ_FWUP]  CHAR (10)     CONSTRAINT [DF__CUSTFWUP__UNIQ_F__22EA20B8] DEFAULT ('') NOT NULL,
    [CUSTNO]     CHAR (10)     CONSTRAINT [DF__CUSTFWUP__CUSTNO__23DE44F1] DEFAULT ('') NOT NULL,
    [FOLLOWDESC] CHAR (35)     CONSTRAINT [DF__CUSTFWUP__FOLLOW__24D2692A] DEFAULT ('') NOT NULL,
    [FOLLOWDATE] SMALLDATETIME NULL,
    [USERID]     CHAR (8)      CONSTRAINT [DF__CUSTFWUP__USERID__25C68D63] DEFAULT ('') NOT NULL,
    [FOLLOWNOTE] TEXT          CONSTRAINT [DF__CUSTFWUP__FOLLOW__26BAB19C] DEFAULT ('') NOT NULL,
    [COMPLETE]   BIT           CONSTRAINT [DF__CUSTFWUP__COMPLE__27AED5D5] DEFAULT ((0)) NOT NULL,
    [COMPDATE]   SMALLDATETIME NULL,
    [COMPINIT]   CHAR (8)      CONSTRAINT [DF__CUSTFWUP__COMPIN__28A2FA0E] DEFAULT ('') NULL,
    CONSTRAINT [CUSTFWUP_PK] PRIMARY KEY CLUSTERED ([UNIQ_FWUP] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[CUSTFWUP]([CUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [FOLLOWDATE]
    ON [dbo].[CUSTFWUP]([FOLLOWDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [USERID]
    ON [dbo].[CUSTFWUP]([USERID] ASC);

