CREATE TABLE [dbo].[DEFSETUP] (
    [ENTRYMODE]  NUMERIC (1) CONSTRAINT [DF__DEFSETUP1__ENTRY__3E33DF28] DEFAULT ((0)) NOT NULL,
    [XXRWKCOST]  NUMERIC (1) CONSTRAINT [DF__DEFSETUP1__XXRWK__3F280361] DEFAULT ((0)) NOT NULL,
    [XXSKIPLOC]  BIT         CONSTRAINT [DF__DEFSETUP1__XXSKI__401C279A] DEFAULT ((0)) NOT NULL,
    [XXSKIPNOTE] BIT         CONSTRAINT [DF__DEFSETUP1__XXSKI__41104BD3] DEFAULT ((0)) NOT NULL,
    [XXSKIPSER]  BIT         CONSTRAINT [DF__DEFSETUP1__XXSKI__4204700C] DEFAULT ((0)) NOT NULL,
    [XXSHOWDEPT] NUMERIC (1) CONSTRAINT [DF__DEFSETUP1__XXSHO__42F89445] DEFAULT ((0)) NOT NULL,
    [XXMAXNPF]   NUMERIC (3) CONSTRAINT [DF__DEFSETUP1__XXMAX__43ECB87E] DEFAULT ((0)) NOT NULL,
    [XXSKIPNPF]  BIT         CONSTRAINT [DF__DEFSETUP1__XXSKI__44E0DCB7] DEFAULT ((0)) NOT NULL,
    [XXMAXPASS]  NUMERIC (2) CONSTRAINT [DF__DEFSETUP1__XXMAX__45D500F0] DEFAULT ((0)) NOT NULL,
    [XXSKIPRWKT] BIT         CONSTRAINT [DF__DEFSETUP1__XXSKI__46C92529] DEFAULT ((0)) NOT NULL,
    [UNIQUENUM]  INT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [DEFSETUP_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);

