CREATE TABLE [dbo].[DELV_DFL] (
    [OVER_SHIP]  NUMERIC (1) CONSTRAINT [DF_DELV_DFL_OVER_SHIP] DEFAULT ((0)) NOT NULL,
    [UNDER_SHIP] NUMERIC (1) CONSTRAINT [DF_DELV_DFL_UNDER_SHIP] DEFAULT ((0)) NOT NULL,
    [UNIQUENUM]  INT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [DELV_DFL_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);

