CREATE TABLE [dbo].[DEPTSHFT] (
    [DEPT_ID]   CHAR (4)    CONSTRAINT [DF__DEPTSHFT__DEPT_I__3B80C458] DEFAULT ('') NOT NULL,
    [SHIFT_NO]  NUMERIC (3) CONSTRAINT [DF__DEPTSHFT__SHIFT___3C74E891] DEFAULT ((0)) NOT NULL,
    [GLDIVNO]   CHAR (2)    CONSTRAINT [DF__DEPTSHFT__GLDIVN__3D690CCA] DEFAULT ('') NOT NULL,
    [UNIQUEREC] CHAR (10)   CONSTRAINT [DF__DEPTSHFT__UNIQUE__3E5D3103] DEFAULT ('') NOT NULL,
    CONSTRAINT [DEPTSHFT_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEPT_ID]
    ON [dbo].[DEPTSHFT]([DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [DEPT_SHIFT]
    ON [dbo].[DEPTSHFT]([DEPT_ID] ASC, [SHIFT_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [DEPTDIV]
    ON [dbo].[DEPTSHFT]([DEPT_ID] ASC, [GLDIVNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SHIFT_NO]
    ON [dbo].[DEPTSHFT]([SHIFT_NO] ASC);

