CREATE TABLE [dbo].[DEPT_CUR] (
    [WONO]            CHAR (10)        CONSTRAINT [DF__DEPT_CUR__WONO__41399DAE] DEFAULT ('') NOT NULL,
    [DEPT_ID]         CHAR (4)         CONSTRAINT [DF__DEPT_CUR__DEPT_I__422DC1E7] DEFAULT ('') NOT NULL,
    [NUMBER]          NUMERIC (4)      CONSTRAINT [DF__DEPT_CUR__NUMBER__4321E620] DEFAULT ((0)) NOT NULL,
    [TIME_USED]       NUMERIC (6)      CONSTRAINT [DF__DEPT_CUR__TIME_U__45FE52CB] DEFAULT ((0)) NOT NULL,
    [originalDateIn]  DATETIME         CONSTRAINT [DF_Dept_Cur_originalDatein] DEFAULT (getdate()) NULL,
    [DATE_IN]         DATETIME         CONSTRAINT [DF_Dept_Cur_date_in] DEFAULT (getdate()) NULL,
    [originalDateOut] DATETIME         NULL,
    [DATE_OUT]        DATETIME         NULL,
    [inUserId]        UNIQUEIDENTIFIER CONSTRAINT [DF_DEPT_CUR_inUserId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [LOG_INIT]        CHAR (8)         CONSTRAINT [DF__DEPT_CUR__LOG_IN__46F27704] DEFAULT ('') NOT NULL,
    [outUserId]       UNIQUEIDENTIFIER CONSTRAINT [DF_DEPT_CUR_outUserId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [LOGOUT_INI]      CHAR (8)         CONSTRAINT [DF__DEPT_CUR__LOGOUT__47E69B3D] DEFAULT ('') NOT NULL,
    [TMLOGTPUK]       VARCHAR (10)     CONSTRAINT [DF__DEPT_CUR__TMLOG___48DABF76] DEFAULT ('') NOT NULL,
    [OVERTIME]        NUMERIC (6)      CONSTRAINT [DF__DEPT_CUR__OVERTI__49CEE3AF] DEFAULT ((0)) NOT NULL,
    [IS_HOLIDAY]      BIT              CONSTRAINT [DF__DEPT_CUR__IS_HOL__4AC307E8] DEFAULT ((0)) NOT NULL,
    [UNIQLOGIN]       CHAR (10)        CONSTRAINT [DF__DEPT_CUR__UNIQLO__4BB72C21] DEFAULT ('') NOT NULL,
    [uDeleted]        BIT              CONSTRAINT [DF_DEPT_CUR_uDeleted] DEFAULT ((0)) NOT NULL,
    [comment]         VARCHAR (MAX)    CONSTRAINT [DF_DEPT_CUR_comment] DEFAULT ('') NOT NULL,
    CONSTRAINT [DEPT_CUR_PK] PRIMARY KEY CLUSTERED ([UNIQLOGIN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LOG_INIT]
    ON [dbo].[DEPT_CUR]([LOG_INIT] ASC);


GO
CREATE NONCLUSTERED INDEX [WODEPTTMNO]
    ON [dbo].[DEPT_CUR]([LOG_INIT] ASC, [WONO] ASC, [DEPT_ID] ASC, [NUMBER] ASC, [TMLOGTPUK] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[DEPT_CUR]([LOG_INIT] ASC, [WONO] ASC, [DEPT_ID] ASC, [NUMBER] ASC);

