CREATE TABLE [dbo].[DEPTS] (
    [DEPT_ID]    CHAR (4)        CONSTRAINT [DF__DEPTS__DEPT_ID__2779CBAB] DEFAULT ('') NOT NULL,
    [DEPT_NAME]  CHAR (25)       CONSTRAINT [DF__DEPTS__DEPT_NAME__286DEFE4] DEFAULT ('') NOT NULL,
    [ACT_CAPCTY] NUMERIC (12)    CONSTRAINT [DF__DEPTS__ACT_CAPCT__2962141D] DEFAULT ((0)) NOT NULL,
    [WCNOTE]     TEXT            CONSTRAINT [DF__DEPTS__WCNOTE__2A563856] DEFAULT ('') NOT NULL,
    [INOUTSVS]   CHAR (1)        CONSTRAINT [DF__DEPTS__INOUTSVS__2B4A5C8F] DEFAULT ('') NOT NULL,
    [NUMBER]     NUMERIC (4)     CONSTRAINT [DF__DEPTS__NUMBER__2C3E80C8] DEFAULT ((0)) NOT NULL,
    [MO]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__MO__2D32A501] DEFAULT ((0)) NOT NULL,
    [TU]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__TU__2E26C93A] DEFAULT ((0)) NOT NULL,
    [WE]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__WE__2F1AED73] DEFAULT ((0)) NOT NULL,
    [TH]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__TH__300F11AC] DEFAULT ((0)) NOT NULL,
    [FR]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__FR__310335E5] DEFAULT ((0)) NOT NULL,
    [SA]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__SA__31F75A1E] DEFAULT ((0)) NOT NULL,
    [SU]         NUMERIC (13, 3) CONSTRAINT [DF__DEPTS__SU__32EB7E57] DEFAULT ((0)) NOT NULL,
    [SHOPRATE]   NUMERIC (7, 3)  CONSTRAINT [DF__DEPTS__SHOPRATE__33DFA290] DEFAULT ((0)) NOT NULL,
    [isTestWC]   BIT             CONSTRAINT [DF_DEPTS_isTestWC] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [DEPTS_PK] PRIMARY KEY CLUSTERED ([DEPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEPT_NAME]
    ON [dbo].[DEPTS]([DEPT_NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [NUMBER]
    ON [dbo].[DEPTS]([NUMBER] ASC);


GO
-- =============================================
-- Author:		Yelena Shmidt
-- Create date: 08/20/2009
-- Description:	After Delete trigger for the Depts table
-- =============================================
CREATE TRIGGER  [dbo].[Depts_Delete]
   ON  [dbo].[DEPTS] 
   AFTER DELETE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRANSACTION 
	DELETE FROM DeptsDet WHERE Dept_id IN (SELECT DEPT_ID FROM DELETED)
	DELETE FROM DeptShft WHERE Dept_id IN (SELECT DEpt_id FROM DELETED) 
	COMMIT

END
