CREATE TABLE [dbo].[DMOPEN] (
    [UNIQDMOPEN] CHAR (10)       CONSTRAINT [DF__DMOPEN__UNIQDMOP__05E3CDB6] DEFAULT ('') NOT NULL,
    [DMEMONO]    CHAR (10)       CONSTRAINT [DF__DMOPEN__DMEMONO__06D7F1EF] DEFAULT ('') NOT NULL,
    [DATE]       SMALLDATETIME   NULL,
    [INVNO]      CHAR (20)       CONSTRAINT [DF__DMOPEN__INVNO__07CC1628] DEFAULT ('') NOT NULL,
    [SUPID]      CHAR (10)       CONSTRAINT [DF__DMOPEN__SUPID__08C03A61] DEFAULT ('') NOT NULL,
    [DMAMOUNT]   NUMERIC (10, 2) CONSTRAINT [DF__DMOPEN__DMAMOUNT__09B45E9A] DEFAULT ((0)) NOT NULL,
    [UNIQDMHEAD] CHAR (10)       CONSTRAINT [DF__DMOPEN__UNIQDMHE__0AA882D3] DEFAULT ('') NOT NULL,
    [UNIQAPHEAD] CHAR (10)       CONSTRAINT [DF__DMOPEN__UNIQAPHE__0B9CA70C] DEFAULT ('') NOT NULL,
    CONSTRAINT [DMOPEN_PK] PRIMARY KEY CLUSTERED ([UNIQDMOPEN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DMEMONO]
    ON [dbo].[DMOPEN]([DMEMONO] ASC, [SUPID] ASC, [INVNO] ASC);

