CREATE TABLE [dbo].[DUE_DTS] (
    [SONO]       CHAR (10)      CONSTRAINT [DF__DUE_DTS__SONO__170E59B8] DEFAULT ('') NOT NULL,
    [DUE_DTS]    SMALLDATETIME  NULL,
    [SHIP_DTS]   SMALLDATETIME  NULL,
    [COMMIT_DTS] SMALLDATETIME  NULL,
    [QTY]        NUMERIC (9, 2) CONSTRAINT [DF__DUE_DTS__QTY__18027DF1] DEFAULT ((0)) NOT NULL,
    [STDCHG]     NUMERIC (7, 2) CONSTRAINT [DF__DUE_DTS__STDCHG__18F6A22A] DEFAULT ((0)) NOT NULL,
    [PRICHG]     NUMERIC (6, 2) CONSTRAINT [DF__DUE_DTS__PRICHG__19EAC663] DEFAULT ((0)) NOT NULL,
    [OTHCHG]     NUMERIC (6, 2) CONSTRAINT [DF__DUE_DTS__OTHCHG__1ADEEA9C] DEFAULT ((0)) NOT NULL,
    [JOBPRI]     CHAR (10)      CONSTRAINT [DF__DUE_DTS__JOBPRI__1BD30ED5] DEFAULT ('') NOT NULL,
    [DAYMIN]     NUMERIC (10)   CONSTRAINT [DF__DUE_DTS__DAYMIN__1CC7330E] DEFAULT ((0)) NOT NULL,
    [LOTNO]      CHAR (1)       CONSTRAINT [DF__DUE_DTS__LOTNO__1DBB5747] DEFAULT ('') NOT NULL,
    [QUOTE_SEL]  BIT            CONSTRAINT [DF__DUE_DTS__QUOTE_S__1EAF7B80] DEFAULT ((0)) NOT NULL,
    [START_DTS]  SMALLDATETIME  NULL,
    [ACT_SHP_QT] NUMERIC (9, 2) CONSTRAINT [DF__DUE_DTS__ACT_SHP__1FA39FB9] DEFAULT ((0)) NOT NULL,
    [ON_SCHED]   BIT            CONSTRAINT [DF__DUE_DTS__ON_SCHE__2097C3F2] DEFAULT ((0)) NOT NULL,
    [COMPL_DTS]  SMALLDATETIME  NULL,
    [UNIQUELN]   CHAR (10)      CONSTRAINT [DF__DUE_DTS__UNIQUEL__218BE82B] DEFAULT ('') NOT NULL,
    [DUEDT_UNIQ] CHAR (10)      CONSTRAINT [DF__DUE_DTS__DUEDT_U__22800C64] DEFAULT ('') NOT NULL,
    CONSTRAINT [DUE_DTS_PK] PRIMARY KEY CLUSTERED ([DUEDT_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DueDtsUniqueLn]
    ON [dbo].[DUE_DTS]([UNIQUELN] ASC)
    INCLUDE([QTY], [ACT_SHP_QT]);


GO
CREATE NONCLUSTERED INDEX [SHIP_DTS]
    ON [dbo].[DUE_DTS]([SHIP_DTS] ASC);


GO
CREATE NONCLUSTERED INDEX [SONO]
    ON [dbo].[DUE_DTS]([SONO] ASC, [UNIQUELN] ASC);


GO
CREATE NONCLUSTERED INDEX [SONOSHIPDT]
    ON [dbo].[DUE_DTS]([SONO] ASC, [UNIQUELN] ASC, [SHIP_DTS] ASC);


GO
CREATE NONCLUSTERED INDEX [SOSHIPDTUQ]
    ON [dbo].[DUE_DTS]([SONO] ASC, [UNIQUELN] ASC, [DUEDT_UNIQ] ASC);

