CREATE TABLE [dbo].[ECDEFLTS] (
    [UNIQECDEFLTS]  CHAR (10) CONSTRAINT [DF__ECDEFLTS__UNIQEC__349EBC9F] DEFAULT ('') NOT NULL,
    [RETAINSOPRICE] BIT       CONSTRAINT [DF__ECDEFLTS__RETAIN__3592E0D8] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ECDEFLTS_PK] PRIMARY KEY CLUSTERED ([UNIQECDEFLTS] ASC)
);

