CREATE TABLE [dbo].[ECDETL] (
    [UNIQECNO]   CHAR (10)       CONSTRAINT [DF__ECDETL__UNIQECNO__386F4D83] DEFAULT ('') NOT NULL,
    [UNIQECDET]  CHAR (10)       CONSTRAINT [DF__ECDETL__UNIQECDE__396371BC] DEFAULT ('') NOT NULL,
    [ITEM_NO]    NUMERIC (4)     CONSTRAINT [DF__ECDETL__ITEM_NO__3A5795F5] DEFAULT ((0)) NOT NULL,
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__ECDETL__UNIQ_KEY__3B4BBA2E] DEFAULT ('') NOT NULL,
    [DETSTATUS]  CHAR (10)       CONSTRAINT [DF__ECDETL__DETSTATU__3C3FDE67] DEFAULT ('') NOT NULL,
    [OLDQTY]     NUMERIC (9, 2)  CONSTRAINT [DF__ECDETL__OLDQTY__3D3402A0] DEFAULT ((0)) NOT NULL,
    [NEWQTY]     NUMERIC (9, 2)  CONSTRAINT [DF__ECDETL__NEWQTY__3E2826D9] DEFAULT ((0)) NOT NULL,
    [USED_INKIT] CHAR (1)        CONSTRAINT [DF__ECDETL__USED_INK__3F1C4B12] DEFAULT ('') NOT NULL,
    [CHGAMT]     NUMERIC (13, 5) CONSTRAINT [DF__ECDETL__CHGAMT__40106F4B] DEFAULT ((0)) NOT NULL,
    [SCRAPITEM]  BIT             CONSTRAINT [DF__ECDETL__SCRAPITE__41049384] DEFAULT ((0)) NOT NULL,
    [STDCOST]    NUMERIC (13, 5) CONSTRAINT [DF__ECDETL__STDCOST__41F8B7BD] DEFAULT ((0)) NOT NULL,
    [DEPT_ID]    CHAR (4)        CONSTRAINT [DF__ECDETL__DEPT_ID__42ECDBF6] DEFAULT ('') NOT NULL,
    [UNIQBOMNO]  CHAR (10)       CONSTRAINT [DF__ECDETL__UNIQBOMN__43E1002F] DEFAULT ('') NOT NULL,
    [STDCOSTPR]  NUMERIC (13, 5) CONSTRAINT [DF__ECDETL__STDCOSTP__2946113F] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ECDETL_PK] PRIMARY KEY CLUSTERED ([UNIQECDET] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECDETL]([UNIQECNO] ASC);

