CREATE TABLE [dbo].[ECMISC] (
    [UNIQECNO]   CHAR (10)       CONSTRAINT [DF__ECMISC__UNIQECNO__0F382DC6] DEFAULT ('') NOT NULL,
    [UNIQMISCNO] CHAR (10)       CONSTRAINT [DF__ECMISC__UNIQMISC__102C51FF] DEFAULT ('') NOT NULL,
    [DESCRIPT]   CHAR (60)       CONSTRAINT [DF__ECMISC__DESCRIPT__11207638] DEFAULT ('') NOT NULL,
    [COST]       NUMERIC (13, 5) CONSTRAINT [DF__ECMISC__COST__12149A71] DEFAULT ((0)) NOT NULL,
    [TYPE]       NVARCHAR (8)    CONSTRAINT [DF__ECMISC__TYPE__1308BEAA] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECMISC_PK] PRIMARY KEY CLUSTERED ([UNIQMISCNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECMISC]([UNIQECNO] ASC);

