CREATE TABLE [dbo].[ECNRE] (
    [UNIQECNO]          CHAR (10)       CONSTRAINT [DF__ECNRE__UNIQECNO__15E52B55] DEFAULT ('') NOT NULL,
    [UNIQNRENO]         CHAR (10)       CONSTRAINT [DF__ECNRE__UNIQNRENO__16D94F8E] DEFAULT ('') NOT NULL,
    [COSTAMT]           NUMERIC (13, 5) CONSTRAINT [DF__ECNRE__COSTAMT__18C19800] DEFAULT ((0)) NOT NULL,
    [CHARGEAMT]         NUMERIC (13, 5) CONSTRAINT [DF__ECNRE__CHARGEAMT__19B5BC39] DEFAULT ((0)) NOT NULL,
    [EFFECTIVEDT]       SMALLDATETIME   NULL,
    [TERMINATDT]        SMALLDATETIME   NULL,
    [DEPT_ID]           CHAR (4)        CONSTRAINT [DF__ECNRE__DEPT_ID__1AA9E072] DEFAULT ('') NOT NULL,
    [ToolsAndFixtureId] CHAR (10)       NOT NULL,
    [ToolFixtureNo]     CHAR (50)       CONSTRAINT [DF__ECNRE__ToolFixtu__3B7A9B6A] DEFAULT ('') NOT NULL,
    [PercentAmt]        CHAR (50)       CONSTRAINT [DF__ECNRE__PercentAm__3C6EBFA3] DEFAULT ('') NOT NULL,
    [NewRwk]            CHAR (50)       CONSTRAINT [DF__ECNRE__NewRwk__3D62E3DC] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECNRE_PK] PRIMARY KEY CLUSTERED ([UNIQNRENO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECNRE]([UNIQECNO] ASC);

