CREATE TABLE [dbo].[ECREFDES] (
    [UNIQBOMNO]  CHAR (10)   CONSTRAINT [DF__ECREFDES__UNIQBO__1D864D1D] DEFAULT ('') NOT NULL,
    [REF_DES]    CHAR (15)   CONSTRAINT [DF__ECREFDES__REF_DE__1E7A7156] DEFAULT ('') NOT NULL,
    [NBR]        NUMERIC (7) CONSTRAINT [DF__ECREFDES__NBR__1F6E958F] DEFAULT ((0)) NOT NULL,
    [UNIQECDET]  CHAR (10)   CONSTRAINT [DF__ECREFDES__UNIQEC__2062B9C8] DEFAULT ('') NOT NULL,
    [UNIQECRFNO] CHAR (10)   CONSTRAINT [DF__ECREFDES__UNIQEC__2156DE01] DEFAULT ('') NOT NULL,
    [UNIQECNO]   CHAR (10)   CONSTRAINT [DF__ECREFDES__UNIQEC__224B023A] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECREFDES_PK] PRIMARY KEY CLUSTERED ([UNIQECRFNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECDET]
    ON [dbo].[ECREFDES]([UNIQECDET] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECREFDES]([UNIQECNO] ASC);

