CREATE TABLE [dbo].[ECRELDOC] (
    [UNIQECNO] CHAR (10)     CONSTRAINT [DF__ECRELDOC__UNIQEC__25276EE5] DEFAULT ('') NOT NULL,
    [DOC_UNIQ] CHAR (10)     CONSTRAINT [DF__ECRELDOC__DOC_UN__261B931E] DEFAULT ('') NOT NULL,
    [UNIQ_KEY] CHAR (10)     CONSTRAINT [DF__ECRELDOC__UNIQ_K__270FB757] DEFAULT ('') NOT NULL,
    [DOCNO]    CHAR (25)     CONSTRAINT [DF__ECRELDOC__DOCNO__2803DB90] DEFAULT ('') NOT NULL,
    [DOCREVNO] CHAR (4)      CONSTRAINT [DF__ECRELDOC__DOCREV__28F7FFC9] DEFAULT ('') NOT NULL,
    [DOCDESCR] CHAR (45)     CONSTRAINT [DF__ECRELDOC__DOCDES__29EC2402] DEFAULT ('') NOT NULL,
    [DOCDATE]  SMALLDATETIME NULL,
    [DOCNOTE]  TEXT          CONSTRAINT [DF__ECRELDOC__DOCNOT__2AE0483B] DEFAULT ('') NOT NULL,
    [DOCEXEC]  CHAR (200)    CONSTRAINT [DF__ECRELDOC__DOCEXE__2BD46C74] DEFAULT ('') NOT NULL,
    [DOCPDF]   CHAR (200)    CONSTRAINT [DF__ECRELDOC__DOCPDF__2CC890AD] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECRELDOC_PK] PRIMARY KEY CLUSTERED ([DOC_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECRELDOC]([UNIQECNO] ASC);

