CREATE TABLE [dbo].[ECSO] (
    [UNIQECSONO] CHAR (10)      CONSTRAINT [DF__ECSO__UNIQECSONO__2FA4FD58] DEFAULT ('') NOT NULL,
    [UNIQECNO]   CHAR (10)      CONSTRAINT [DF__ECSO__UNIQECNO__30992191] DEFAULT ('') NOT NULL,
    [SONO]       CHAR (10)      CONSTRAINT [DF__ECSO__SONO__318D45CA] DEFAULT ('') NOT NULL,
    [UNIQUELN]   CHAR (10)      CONSTRAINT [DF__ECSO__UNIQUELN__32816A03] DEFAULT ('') NOT NULL,
    [CHANGE]     BIT            CONSTRAINT [DF__ECSO__CHANGE__33758E3C] DEFAULT ((0)) NOT NULL,
    [BALANCE]    NUMERIC (9, 2) CONSTRAINT [DF__ECSO__BALANCE__3469B275] DEFAULT ((0)) NOT NULL,
    [LINE_NO]    CHAR (7)       CONSTRAINT [DF__ECSO__LINE_NO__355DD6AE] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECSO_PK] PRIMARY KEY CLUSTERED ([UNIQECSONO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SONO]
    ON [dbo].[ECSO]([SONO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECSO]([UNIQECNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQUELN]
    ON [dbo].[ECSO]([UNIQUELN] ASC);

