CREATE TABLE [dbo].[ECWH] (
    [UNIQECWH]  CHAR (10)       CONSTRAINT [DF__ECWH__UNIQECWH__383A4359] DEFAULT ('') NOT NULL,
    [UNIQECNO]  CHAR (10)       CONSTRAINT [DF__ECWH__UNIQECNO__392E6792] DEFAULT ('') NOT NULL,
    [QTY_OH]    NUMERIC (10, 2) CONSTRAINT [DF__ECWH__QTY_OH__3A228BCB] DEFAULT ((0)) NOT NULL,
    [WAREHOUSE] CHAR (6)        CONSTRAINT [DF__ECWH__WAREHOUSE__3B16B004] DEFAULT ('') NOT NULL,
    [LOCATION]  NVARCHAR (200)  CONSTRAINT [DF__ECWH__LOCATION__3C0AD43D] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECWH_PK] PRIMARY KEY CLUSTERED ([UNIQECWH] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECWH]([UNIQECNO] ASC);

