CREATE TABLE [dbo].[ECWO] (
    [UNIQECNO]       CHAR (10)    CONSTRAINT [DF__ECWO__UNIQECNO__3FDB6521] DEFAULT ('') NOT NULL,
    [UNIQECWONO]     CHAR (10)    CONSTRAINT [DF__ECWO__UNIQECWONO__40CF895A] DEFAULT ('') NOT NULL,
    [WONO]           CHAR (10)    CONSTRAINT [DF__ECWO__WONO__41C3AD93] DEFAULT ('') NOT NULL,
    [CHANGE]         BIT          CONSTRAINT [DF__ECWO__CHANGE__42B7D1CC] DEFAULT ((0)) NOT NULL,
    [BALANCE]        NUMERIC (10) CONSTRAINT [DF__ECWO__BALANCE__43ABF605] DEFAULT ((0)) NOT NULL,
    [IS_SnLotIssued] BIT          CONSTRAINT [DF__ECWO__IS_SnLotIs__5E817E80] DEFAULT ((0)) NOT NULL,
    [NewWono]        CHAR (10)    CONSTRAINT [DF__ECWO__NewWono__5F75A2B9] DEFAULT ('') NOT NULL,
    CONSTRAINT [ECWO_PK] PRIMARY KEY CLUSTERED ([UNIQECWONO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQECNO]
    ON [dbo].[ECWO]([UNIQECNO] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[ECWO]([WONO] ASC);

