CREATE TABLE [dbo].[ECWRKCKLST] (
    [UNIQ_KEY]        CHAR (10)   CONSTRAINT [DF__ECWRKCKLST__UNIQ_K__7E836E67] DEFAULT ('') NOT NULL,
    [DEPT_ACTIV]      CHAR (4)    CONSTRAINT [DF__ECWRKCKLST__DEPT_A__7F7792A0] DEFAULT ('') NOT NULL,
    [UNIQNUMBER]      CHAR (10)   CONSTRAINT [DF__ECWRKCKLST__UNIQNU__006BB6D9] DEFAULT ('') NOT NULL,
    [NEW_UNIQNUMBER]  CHAR (10)   NOT NULL,
    [NUMBER]          NUMERIC (4) CONSTRAINT [DF__ECWRKCKLST__NUMBER__015FDB12] DEFAULT ((0)) NOT NULL,
    [CHKLST_TIT]      CHAR (100)  CONSTRAINT [DF__ECWRKCKLST__CHKLST__0253FF4B] DEFAULT ('') NOT NULL,
    [UNIQNBRA]        CHAR (10)   CONSTRAINT [DF__ECWRKCKLST__UNIQNB__03482384] DEFAULT ('') NOT NULL,
    [WRKCKUNIQ]       CHAR (10)   CONSTRAINT [DF__ECWRKCKLST__WRKCKU__043C47BD] DEFAULT ('') NOT NULL,
    [NEW_WRKCKUNIQ]   CHAR (10)   CONSTRAINT [DF__ECWRKCKLST__UNIQ_K__672B07C8] DEFAULT ([dbo].[fn_generateuniquenumber]()) NOT NULL,
    [TemplateId]      INT         NULL,
    [wccheckpriority] INT         CONSTRAINT [DF_ECWRKCKLST_wccheckpriority] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ECWRKCKLST_PK] PRIMARY KEY CLUSTERED ([NEW_WRKCKUNIQ] ASC),
    CONSTRAINT [FK_ECWRKCKLST_TemplateId] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[RoutingTemplate] ([TemplateID])
);

