CREATE TABLE [dbo].[EMAILSETUP] (
    [UNIQFIELD]  CHAR (10)    CONSTRAINT [DF__EMAILSETU__UNIQF__57B2EEB2] DEFAULT ('') NOT NULL,
    [SERVER]     VARCHAR (60) CONSTRAINT [DF__EMAILSETU__SERVE__58A712EB] DEFAULT ('') NOT NULL,
    [FROMADR]    VARCHAR (50) CONSTRAINT [DF__EMAILSETU__FROMA__599B3724] DEFAULT ('') NOT NULL,
    [FROMNAME]   VARCHAR (50) CONSTRAINT [DF__EMAILSETU__FROMN__5A8F5B5D] DEFAULT ('') NOT NULL,
    [IS_BLOCK]   BIT          CONSTRAINT [DF__EMAILSETU__IS_BL__5B837F96] DEFAULT ((0)) NOT NULL,
    [IS_ENABLED] BIT          CONSTRAINT [DF__EMAILSETU__IS_EN__5C77A3CF] DEFAULT ((0)) NOT NULL,
    [SMTPPORT]   NUMERIC (5)  CONSTRAINT [DF__EMAILSETU__SMTPP__5D6BC808] DEFAULT ((0)) NOT NULL,
    [USERID]     VARCHAR (50) CONSTRAINT [DF__EMAILSETU__USERI__5E5FEC41] DEFAULT ('') NOT NULL,
    [EPASSWORD]  VARCHAR (50) CONSTRAINT [DF__EMAILSETU__EPASS__5F54107A] DEFAULT ('') NOT NULL,
    [IS_SSL]     BIT          CONSTRAINT [DF_EMAILSETUP_IS_SSL] DEFAULT ((0)) NOT NULL,
    [IS_HTML]    BIT          CONSTRAINT [DF_EMAILSETUP_IS_HTML] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [EMAILSETUP_PK] PRIMARY KEY CLUSTERED ([UNIQFIELD] ASC)
);

