CREATE TABLE [dbo].[EMAILLOG] (
    [CSCREENNM]         CHAR (25)     CONSTRAINT [DF_EMAILLOG_CSCREENNM] DEFAULT ('') NOT NULL,
    [CREPORTNM]         CHAR (10)     CONSTRAINT [DF_EMAILLOG_CREPORTNM] DEFAULT ('') NOT NULL,
    [TEMAILTIME]        SMALLDATETIME NULL,
    [CRECIPIENTADDRESS] TEXT          CONSTRAINT [DF_EMAILLOG_CRECIPIENTADDRESS] DEFAULT ('') NOT NULL,
    [CSUBJECT]          TEXT          CONSTRAINT [DF_EMAILLOG_CSUBJECT] DEFAULT ('') NOT NULL,
    [CATTACHNM]         TEXT          CONSTRAINT [DF_EMAILLOG_CATTACHNM] DEFAULT ('') NOT NULL,
    [CSENDERADDRESS]    CHAR (10)     CONSTRAINT [DF_EMAILLOG_CSENDERADDRESS] DEFAULT ('') NOT NULL,
    [CUSERINIT]         CHAR (8)      CONSTRAINT [DF_EMAILLOG_CUSERINIT] DEFAULT ('') NULL,
    [UNIQUENUM]         INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [EMAILLOG_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CREPORTNM]
    ON [dbo].[EMAILLOG]([CREPORTNM] ASC);


GO
CREATE NONCLUSTERED INDEX [CSCREENNM]
    ON [dbo].[EMAILLOG]([CSCREENNM] ASC);


GO
CREATE NONCLUSTERED INDEX [TEMAILTIME]
    ON [dbo].[EMAILLOG]([TEMAILTIME] ASC);

