CREATE TABLE [dbo].[ERRSYS] (
    [USERID]       CHAR (8)      CONSTRAINT [DF__ERRSYS__USERID__62307D25] DEFAULT ('') NOT NULL,
    [ERR_DATE]     SMALLDATETIME NULL,
    [ERROR_DESC]   TEXT          CONSTRAINT [DF__ERRSYS__ERROR_DE__6418C597] DEFAULT ('') NOT NULL,
    [ISMAILED]     BIT           CONSTRAINT [DF__ERRSYS__ISMAILED__650CE9D0] DEFAULT ((0)) NOT NULL,
    [MMEMDUMP]     TEXT          CONSTRAINT [DF__ERRSYS__MMEMDUMP__66010E09] DEFAULT ('') NOT NULL,
    [MSTATUSDUMP]  TEXT          CONSTRAINT [DF__ERRSYS__MSTATUSD__66F53242] DEFAULT ('') NOT NULL,
    [MOBJECTSDUMP] TEXT          CONSTRAINT [DF__ERRSYS__MOBJECTS__67E9567B] DEFAULT ('') NOT NULL,
    [UNIQUEREC]    CHAR (10)     CONSTRAINT [DF__ERRSYS__UNIQUERE__68DD7AB4] DEFAULT ('') NOT NULL,
    CONSTRAINT [ERRSYS_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);

