CREATE TABLE [dbo].[FCSTHIS] (
    [CUNIQ_KEY]     CHAR (10)     CONSTRAINT [DF__FCSTHIS__CUNIQ_K__12D3B480] DEFAULT ('') NOT NULL,
    [CFCSTPER]      CHAR (7)      CONSTRAINT [DF__FCSTHIS__CFCSTPE__13C7D8B9] DEFAULT ('') NOT NULL,
    [NSHPDCONSMBL]  NUMERIC (7)   CONSTRAINT [DF__FCSTHIS__NSHPDCO__14BBFCF2] DEFAULT ((0)) NOT NULL,
    [WONO]          CHAR (10)     CONSTRAINT [DF__FCSTHIS__WONO__15B0212B] DEFAULT ('') NOT NULL,
    [UNIQUELN]      CHAR (10)     CONSTRAINT [DF__FCSTHIS__UNIQUEL__16A44564] DEFAULT ('') NOT NULL,
    [FCSTHISUNIQUE] CHAR (10)     CONSTRAINT [DF__FCSTHIS__FCSTHIS__1798699D] DEFAULT ('') NOT NULL,
    [DSHIPDT]       SMALLDATETIME NULL,
    CONSTRAINT [FCSTHIS_PK] PRIMARY KEY CLUSTERED ([FCSTHISUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PERIOD]
    ON [dbo].[FCSTHIS]([CFCSTPER] ASC);


GO
CREATE NONCLUSTERED INDEX [UKEY]
    ON [dbo].[FCSTHIS]([CUNIQ_KEY] ASC);

