CREATE TABLE [dbo].[FCSTCARRYHIS] (
    [CCARRYHISUNIQ] CHAR (10)     CONSTRAINT [DF__FCSTCARRY__CCARR__6BB9E75F] DEFAULT ('') NOT NULL,
    [CCUSTNO]       CHAR (10)     CONSTRAINT [DF__FCSTCARRY__CCUST__6CAE0B98] DEFAULT ('') NOT NULL,
    [CUNIQ_KEY]     CHAR (10)     CONSTRAINT [DF__FCSTCARRY__CUNIQ__6DA22FD1] DEFAULT ('') NOT NULL,
    [NCONSBLSO]     NUMERIC (7)   CONSTRAINT [DF__FCSTCARRY__NCONS__6E96540A] DEFAULT ((0)) NOT NULL,
    [NSHIPDCONSBL]  NUMERIC (7)   CONSTRAINT [DF__FCSTCARRY__NSHIP__6F8A7843] DEFAULT ((0)) NOT NULL,
    [NPLANQTY]      NUMERIC (7)   CONSTRAINT [DF__FCSTCARRY__NPLAN__707E9C7C] DEFAULT ((0)) NOT NULL,
    [NCARRY]        NUMERIC (7)   CONSTRAINT [DF__FCSTCARRY__NCARR__7172C0B5] DEFAULT ((0)) NOT NULL,
    [TCARRYRESETDT] SMALLDATETIME NULL,
    CONSTRAINT [FCSTCARRYHIS_PK] PRIMARY KEY CLUSTERED ([CCARRYHISUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTOMER]
    ON [dbo].[FCSTCARRYHIS]([CCUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [RESETDATE]
    ON [dbo].[FCSTCARRYHIS]([TCARRYRESETDT] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[FCSTCARRYHIS]([CUNIQ_KEY] ASC);

