CREATE TABLE [dbo].[FCSTDETL] (
    [CDETLUK]       CHAR (10)     CONSTRAINT [DF__FCSTDETL__CDETLU__744F2D60] DEFAULT ('') NOT NULL,
    [CFCSTUNIQKEY]  CHAR (10)     CONSTRAINT [DF__FCSTDETL__CFCSTU__75435199] DEFAULT ('') NOT NULL,
    [DFCSTWKEND]    SMALLDATETIME NULL,
    [NFCSTQTY]      NUMERIC (7)   CONSTRAINT [DF__FCSTDETL__NFCSTQ__763775D2] DEFAULT ((0)) NOT NULL,
    [CFCSTPER]      CHAR (7)      CONSTRAINT [DF__FCSTDETL__CFCSTP__772B9A0B] DEFAULT ('') NOT NULL,
    [NPLANQTY]      NUMERIC (7)   CONSTRAINT [DF__FCSTDETL__NPLANQ__781FBE44] DEFAULT ((0)) NOT NULL,
    [NCARRYOVER]    NUMERIC (7)   CONSTRAINT [DF_FCSTDETL_NCARRYOVER] DEFAULT ((0)) NOT NULL,
    [NCUMCARRYOVER] NUMERIC (7)   CONSTRAINT [DF_FCSTDETL_NCUMCARRYOVER] DEFAULT ((0)) NOT NULL,
    [NMIN]          NUMERIC (7)   CONSTRAINT [DF_FCSTDETL_NMIN] DEFAULT ((0)) NOT NULL,
    [NMAX]          NUMERIC (7)   CONSTRAINT [DF_FCSTDETL_NMAX] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FCSTDETL_PK] PRIMARY KEY CLUSTERED ([CDETLUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DFCSTWKEND]
    ON [dbo].[FCSTDETL]([DFCSTWKEND] ASC);


GO
CREATE NONCLUSTERED INDEX [FCSTUKEY]
    ON [dbo].[FCSTDETL]([CDETLUK] ASC);


GO
CREATE NONCLUSTERED INDEX [FCSTUNIQK]
    ON [dbo].[FCSTDETL]([CFCSTUNIQKEY] ASC);

