CREATE TABLE [dbo].[FCSTGRP] (
    [CFCSTGRPKEY]      CHAR (10)      CONSTRAINT [DF__FCSTGRP__CFCSTGR__029D4CB7] DEFAULT ('') NOT NULL,
    [CFCSTUNIQKEY]     CHAR (10)      CONSTRAINT [DF__FCSTGRP__CFCSTUN__039170F0] DEFAULT ('') NOT NULL,
    [CUNIQ_KEY]        CHAR (10)      CONSTRAINT [DF__FCSTGRP__CUNIQ_K__04859529] DEFAULT ('') NOT NULL,
    [CFCSTPER]         CHAR (7)       CONSTRAINT [DF__FCSTGRP__CFCSTPE__0579B962] DEFAULT ('') NOT NULL,
    [NFCSTQTY]         NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NFCSTQT__066DDD9B] DEFAULT ((0)) NOT NULL,
    [NPRIORFCSTPERTOT] NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NPRIORF__076201D4] DEFAULT ((0)) NOT NULL,
    [NFCST2FAT]        NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NFCST2F__0856260D] DEFAULT ((0)) NOT NULL,
    [NCARRY]           NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NCARRY__094A4A46] DEFAULT ((0)) NOT NULL,
    [NCUMCARRY]        NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NCUMCAR__0A3E6E7F] DEFAULT ((0)) NOT NULL,
    [NCONSMING]        NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NCONSMI__0B3292B8] DEFAULT ((0)) NOT NULL,
    [NINVTYSHIPS]      NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NINVTYS__0C26B6F1] DEFAULT ((0)) NOT NULL,
    [NPLANNETFCST]     NUMERIC (7)    CONSTRAINT [DF__FCSTGRP__NPLANNE__0D1ADB2A] DEFAULT ((0)) NOT NULL,
    [NNETDELTAPC]      NUMERIC (5, 2) CONSTRAINT [DF__FCSTGRP__NNETDEL__0E0EFF63] DEFAULT ((0)) NOT NULL,
    [LREADYFORMRP]     BIT            CONSTRAINT [DF__FCSTGRP__LREADYF__0F03239C] DEFAULT ((0)) NOT NULL,
    [CREASON]          CHAR (254)     CONSTRAINT [DF__FCSTGRP__CREASON__0FF747D5] DEFAULT ('') NOT NULL,
    CONSTRAINT [FCSTGRP_PK] PRIMARY KEY CLUSTERED ([CFCSTGRPKEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[FCSTGRP]([CUNIQ_KEY] ASC);

