CREATE TABLE [dbo].[FCSTMAIN] (
    [CFCSTUNIQKEY]  CHAR (10)      CONSTRAINT [DF__FCSTMAIN__CFCSTU__1A74D648] DEFAULT ('') NOT NULL,
    [CUNIQ_KEY]     CHAR (10)      CONSTRAINT [DF__FCSTMAIN__CUNIQ___1B68FA81] DEFAULT ('') NOT NULL,
    [CPRIORFCSTKEY] CHAR (10)      CONSTRAINT [DF__FCSTMAIN__CPRIOR__1C5D1EBA] DEFAULT ('') NOT NULL,
    [CCUSTNO]       CHAR (10)      CONSTRAINT [DF__FCSTMAIN__CCUSTN__1D5142F3] DEFAULT ('') NOT NULL,
    [LACTIVE]       BIT            CONSTRAINT [DF__FCSTMAIN__LACTIV__1E45672C] DEFAULT ((0)) NOT NULL,
    [LDELETED]      BIT            CONSTRAINT [DF__FCSTMAIN__LDELET__1F398B65] DEFAULT ((0)) NOT NULL,
    [creason]       CHAR (10)      CONSTRAINT [DF_FCSTMAIN_creason] DEFAULT ('') NOT NULL,
    [DFCSTDT]       SMALLDATETIME  NULL,
    [CUSERINIT]     CHAR (8)       CONSTRAINT [DF__FCSTMAIN__CUSERI__2121D3D7] DEFAULT ('') NULL,
    [DENTRYDT]      SMALLDATETIME  NULL,
    [CAPPVID]       CHAR (4)       CONSTRAINT [DF__FCSTMAIN__CAPPVI__2215F810] DEFAULT ('') NOT NULL,
    [DAPPVD]        SMALLDATETIME  NULL,
    [NPRICE]        NUMERIC (9, 2) CONSTRAINT [DF__FCSTMAIN__NPRICE__230A1C49] DEFAULT ((0)) NOT NULL,
    [CCOPYFROM]     CHAR (10)      CONSTRAINT [DF__FCSTMAIN__CCOPYF__23FE4082] DEFAULT ('') NOT NULL,
    [CW_KEY]        CHAR (10)      CONSTRAINT [DF__FCSTMAIN__CW_KEY__24F264BB] DEFAULT ('') NOT NULL,
    [UNIQMFGRHD]    CHAR (10)      CONSTRAINT [DF_FCSTMAIN_UNIQMFGRHD] DEFAULT ('') NOT NULL,
    CONSTRAINT [FCSTMAIN_PK] PRIMARY KEY CLUSTERED ([CFCSTUNIQKEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACTIVE]
    ON [dbo].[FCSTMAIN]([LACTIVE] ASC);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[FCSTMAIN]([CCUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [FCSTUKEY]
    ON [dbo].[FCSTMAIN]([CFCSTUNIQKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [PFCSTUKEY]
    ON [dbo].[FCSTMAIN]([CPRIORFCSTKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UKEY]
    ON [dbo].[FCSTMAIN]([CUNIQ_KEY] ASC);

