CREATE TABLE [dbo].[FCSTMRP] (
    [CCUSTNO]      CHAR (10)     CONSTRAINT [DF__FCSTMRP__CCUSTNO__361CF0BD] DEFAULT ('') NOT NULL,
    [CUNIQ_KEY]    CHAR (10)     CONSTRAINT [DF__FCSTMRP__CUNIQ_K__371114F6] DEFAULT ('') NOT NULL,
    [DFCSTWKEND]   SMALLDATETIME NULL,
    [NCONSBLSO]    NUMERIC (7)   CONSTRAINT [DF__FCSTMRP__NCONSBL__3805392F] DEFAULT ((0)) NOT NULL,
    [NNETPLAN]     NUMERIC (7)   CONSTRAINT [DF__FCSTMRP__NNETPLA__38F95D68] DEFAULT ((0)) NOT NULL,
    [NSHIPDCONSBL] NUMERIC (7)   CONSTRAINT [DF__FCSTMRP__NSHIPDC__39ED81A1] DEFAULT ((0)) NOT NULL,
    [TLASTMRPDT]   SMALLDATETIME NULL,
    [NPLANQTY]     NUMERIC (7)   CONSTRAINT [DF__FCSTMRP__NPLANQT__3AE1A5DA] DEFAULT ((0)) NOT NULL,
    [NCUMCARRY]    NUMERIC (7)   CONSTRAINT [DF__FCSTMRP__NCUMCAR__3BD5CA13] DEFAULT ((0)) NOT NULL,
    [UNIQUEREC]    CHAR (10)     CONSTRAINT [DF__FCSTMRP__UNIQUER__3CC9EE4C] DEFAULT ('') NOT NULL,
    CONSTRAINT [FCSTMRP_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTUNIQ]
    ON [dbo].[FCSTMRP]([CCUSTNO] ASC, [CUNIQ_KEY] ASC);

