CREATE TABLE [dbo].[FEATURE] (
    [PRODFEUNIQ] CHAR (10) CONSTRAINT [DF__FEATURE__PRODFEU__7231DAC4] DEFAULT ('') NOT NULL,
    [DESCRIPT]   CHAR (45) CONSTRAINT [DF__FEATURE__DESCRIP__7325FEFD] DEFAULT ('') NOT NULL,
    CONSTRAINT [FEATURE_PK] PRIMARY KEY CLUSTERED ([PRODFEUNIQ] ASC)
);

