CREATE TABLE [dbo].[FSTARTDISP] (
    [FRSTARTDISP] CHAR (15) CONSTRAINT [DF__FSTARTDIS__FRSTA__21E0EDE6] DEFAULT ('') NOT NULL,
    [FRSTUNIQUE]  CHAR (10) CONSTRAINT [DF__FSTARTDIS__FRSTU__22D5121F] DEFAULT ('') NOT NULL,
    CONSTRAINT [FSTARTDISP_PK] PRIMARY KEY CLUSTERED ([FRSTUNIQUE] ASC)
);

