CREATE TABLE [dbo].[FTAXDFLT] (
    [UQFTAXDFLT] CHAR (10) CONSTRAINT [DF__FTAXDFLT__UQFTAX__25B17ECA] DEFAULT ('') NOT NULL,
    [PTPROD]     BIT       CONSTRAINT [DF__FTAXDFLT__PTPROD__26A5A303] DEFAULT ((0)) NOT NULL,
    [PTFRT]      BIT       CONSTRAINT [DF__FTAXDFLT__PTFRT__2799C73C] DEFAULT ((0)) NOT NULL,
    [STPROD]     BIT       CONSTRAINT [DF__FTAXDFLT__STPROD__288DEB75] DEFAULT ((0)) NOT NULL,
    [STFRT]      BIT       CONSTRAINT [DF__FTAXDFLT__STFRT__29820FAE] DEFAULT ((0)) NOT NULL,
    [STTX]       BIT       CONSTRAINT [DF__FTAXDFLT__STTX__2A7633E7] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FTAXDFLT_PK] PRIMARY KEY CLUSTERED ([UQFTAXDFLT] ASC)
);

