CREATE TABLE [dbo].[GL_ACCT] (
    [GL_NBR]          CHAR (13)        CONSTRAINT [DF__GL_ACCT__GL_NBR__652CE561] DEFAULT ('') NOT NULL,
    [BEG_BAL]         NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__BEG_BAL__68FD7645] DEFAULT ((0)) NOT NULL,
    [DEBIT]           NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__DEBIT__69F19A7E] DEFAULT ((0)) NOT NULL,
    [CREDIT]          NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__CREDIT__6AE5BEB7] DEFAULT ((0)) NOT NULL,
    [END_BAL]         NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__END_BAL__6BD9E2F0] DEFAULT ((0)) NOT NULL,
    [FK_FYDTLUNIQ]    UNIQUEIDENTIFIER NULL,
    [Uniquerec]       UNIQUEIDENTIFIER CONSTRAINT [DF_GL_ACCT_Uniquerec] DEFAULT (newsequentialid()) NOT NULL,
    [BEG_BALPR]       NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__BEG_BAL__03AA783C] DEFAULT ((0)) NOT NULL,
    [DEBITPR]         NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__DEBITPR__049E9C75] DEFAULT ((0)) NOT NULL,
    [CREDITPR]        NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__CREDITP__0592C0AE] DEFAULT ((0)) NOT NULL,
    [END_BALPR]       NUMERIC (14, 2)  CONSTRAINT [DF__GL_ACCT__END_BAL__0686E4E7] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)        CONSTRAINT [DF__GL_ACCT__PRFCUSE__00B8FCF8] DEFAULT ([dbo].[fn_GetPresentationCurrency]()) NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)        CONSTRAINT [DF__GL_ACCT__FUNCFCU__01AD2131] DEFAULT ([dbo].[fn_GetFunctionalCurrency]()) NOT NULL,
    CONSTRAINT [PK_GL_ACCT] PRIMARY KEY CLUSTERED ([Uniquerec] ASC)
);


GO
CREATE NONCLUSTERED INDEX [fk_fydtluniq]
    ON [dbo].[GL_ACCT]([FK_FYDTLUNIQ] ASC) WITH (ALLOW_PAGE_LOCKS = OFF);


GO
CREATE NONCLUSTERED INDEX [GL_NBR]
    ON [dbo].[GL_ACCT]([GL_NBR] ASC);

