CREATE TABLE [dbo].[GLADDET] (
    [GL_NBR]    CHAR (13)       CONSTRAINT [DF__GLADDET__GL_NBR__443605EA] DEFAULT ('') NOT NULL,
    [DEBIT]     NUMERIC (14, 2) CONSTRAINT [DF__GLADDET__DEBIT__452A2A23] DEFAULT ((0)) NOT NULL,
    [CREDIT]    NUMERIC (14, 2) CONSTRAINT [DF__GLADDET__CREDIT__461E4E5C] DEFAULT ((0)) NOT NULL,
    [FKGLAHDR]  CHAR (10)       CONSTRAINT [DF__GLADDET__FKGLAHD__47127295] DEFAULT ('') NOT NULL,
    [GLADETKEY] CHAR (10)       CONSTRAINT [DF__GLADDET__GLADETK__480696CE] DEFAULT ('') NOT NULL,
    [DEBITPR]   NUMERIC (14, 2) CONSTRAINT [DF__GLADDET__DEBITPR__077B0920] DEFAULT ((0)) NOT NULL,
    [CREDITPR]  NUMERIC (14, 2) CONSTRAINT [DF__GLADDET__CREDITP__086F2D59] DEFAULT ((0)) NOT NULL,
    [DEBITFC]   NUMERIC (14, 2) CONSTRAINT [DF__GLADDET__DEBITFC__22A400A8] DEFAULT ((0)) NOT NULL,
    [CREDITFC]  NUMERIC (14, 2) CONSTRAINT [DF__GLADDET__CREDITF__239824E1] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLADDET_PK] PRIMARY KEY CLUSTERED ([GLADETKEY] ASC),
    CONSTRAINT [FK_GLADHDR_GLADDET] FOREIGN KEY ([FKGLAHDR]) REFERENCES [dbo].[GLADHDR] ([GLAHDRKEY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [FKGLAHDR]
    ON [dbo].[GLADDET]([FKGLAHDR] ASC);

