CREATE TABLE [dbo].[GLADHDR] (
    [ADREF]           CHAR (10)     CONSTRAINT [DF__GLADHDR__ADREF__4AE30379] DEFAULT ('') NOT NULL,
    [REASON]          TEXT          CONSTRAINT [DF__GLADHDR__REASON__4BD727B2] DEFAULT ('') NOT NULL,
    [ADDESCR]         CHAR (30)     CONSTRAINT [DF__GLADHDR__ADDESCR__4CCB4BEB] DEFAULT ('') NOT NULL,
    [LAST_POST]       NUMERIC (2)   CONSTRAINT [DF__GLADHDR__LAST_PO__4DBF7024] DEFAULT ((0)) NOT NULL,
    [POST_FY]         CHAR (4)      CONSTRAINT [DF__GLADHDR__POST_FY__4EB3945D] DEFAULT ('') NOT NULL,
    [POST_DT]         SMALLDATETIME NULL,
    [GLAHDRKEY]       CHAR (10)     CONSTRAINT [DF__GLADHDR__GLAHDRK__4FA7B896] DEFAULT ('') NOT NULL,
    [SAVEINIT]        CHAR (8)      CONSTRAINT [DF__GLADHDR__SAVEINI__509BDCCF] DEFAULT ('') NULL,
    [SAVEDATE]        SMALLDATETIME CONSTRAINT [DF_GLADHDR_SAVEDATE] DEFAULT (getdate()) NULL,
    [FCUSED_UNIQ]     CHAR (10)     CONSTRAINT [DF__GLADHDR__FCUSED___1ED36FC4] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]      CHAR (10)     CONSTRAINT [DF__GLADHDR__FCHIST___1FC793FD] DEFAULT ('') NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)     CONSTRAINT [DF__GLADHDR__PRFCUSE__20BBB836] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)     CONSTRAINT [DF__GLADHDR__FUNCFCU__21AFDC6F] DEFAULT ('') NOT NULL,
    CONSTRAINT [GLADHDR_PK] PRIMARY KEY CLUSTERED ([GLAHDRKEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ADREF]
    ON [dbo].[GLADHDR]([ADREF] ASC);

