CREATE TABLE [dbo].[GLJEHDRO] (
    [JE_NO]           NUMERIC (6)      CONSTRAINT [DF__GLJEHDRO__JE_NO__388F4914] DEFAULT ((0)) NOT NULL,
    [TRANSDATE]       SMALLDATETIME    NULL,
    [SAVEINIT]        CHAR (8)         CONSTRAINT [DF__GLJEHDRO__SAVEIN__39836D4D] DEFAULT ('') NULL,
    [APP_DT]          SMALLDATETIME    NULL,
    [REASON]          VARCHAR (MAX)    CONSTRAINT [DF__GLJEHDRO__REASON__3A779186] DEFAULT ('') NOT NULL,
    [STATUS]          CHAR (12)        CONSTRAINT [DF__GLJEHDRO__STATUS__3B6BB5BF] DEFAULT ('') NOT NULL,
    [JETYPE]          CHAR (10)        CONSTRAINT [DF__GLJEHDRO__JETYPE__3C5FD9F8] DEFAULT ('') NOT NULL,
    [REVERSE]         BIT              CONSTRAINT [DF__GLJEHDRO__REVERS__3D53FE31] DEFAULT ((0)) NOT NULL,
    [PERIOD]          NUMERIC (2)      CONSTRAINT [DF__GLJEHDRO__PERIOD__3E48226A] DEFAULT ((0)) NOT NULL,
    [FY]              CHAR (4)         CONSTRAINT [DF__GLJEHDRO__FY__3F3C46A3] DEFAULT ('') NOT NULL,
    [REVERSED]        BIT              CONSTRAINT [DF__GLJEHDRO__REVERS__40306ADC] DEFAULT ((0)) NOT NULL,
    [REVPERIOD]       NUMERIC (2)      CONSTRAINT [DF__GLJEHDRO__REVPER__41248F15] DEFAULT ((0)) NOT NULL,
    [REV_FY]          CHAR (4)         CONSTRAINT [DF__GLJEHDRO__REV_FY__4218B34E] DEFAULT ('') NOT NULL,
    [JEOHKEY]         CHAR (10)        CONSTRAINT [DF__GLJEHDRO__JEOHKE__430CD787] DEFAULT ('') NOT NULL,
    [APP_INIT]        CHAR (8)         CONSTRAINT [DF__GLJEHDRO__APP_IN__4400FBC0] DEFAULT ('') NULL,
    [IS_REL_GL]       BIT              CONSTRAINT [DF__GLJEHDRO__LIS_RE__44F51FF9] DEFAULT ((0)) NOT NULL,
    [FCUSED_UNIQ]     CHAR (10)        CONSTRAINT [DF__GLJEHDRO__FCUSED__2B6CBA25] DEFAULT ('') NOT NULL,
    [ADJUSTENTRY]     BIT              CONSTRAINT [DF__GLJEHDRO__ADJUST__4FCA162C] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)        CONSTRAINT [DF__GLJEHDRO__PRFCUS__0F1C2AE8] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)        CONSTRAINT [DF__GLJEHDRO__FUNCFC__10104F21] DEFAULT ('') NOT NULL,
    [FCHIST_KEY]      CHAR (10)        CONSTRAINT [DF__GLJEHDRO__FCHIST__2689A025] DEFAULT ('') NOT NULL,
    [ENTERCURRBY]     CHAR (1)         CONSTRAINT [DF__GLJEHDRO__ENTERC__4F76A71F] DEFAULT ('B') NOT NULL,
    [SaveUserId]      UNIQUEIDENTIFIER NULL,
    CONSTRAINT [GLJEHDRO_PK] PRIMARY KEY CLUSTERED ([JEOHKEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JE_NO]
    ON [dbo].[GLJEHDRO]([JE_NO] ASC);

