CREATE TABLE [dbo].[GLJEDETO] (
    [GL_NBR]   CHAR (13)       CONSTRAINT [DF__GLJEDETO__GL_NBR__1FC39B4A] DEFAULT ('') NOT NULL,
    [DEBIT]    NUMERIC (14, 2) CONSTRAINT [DF__GLJEDETO__DEBIT__20B7BF83] DEFAULT ((0)) NOT NULL,
    [CREDIT]   NUMERIC (14, 2) CONSTRAINT [DF__GLJEDETO__CREDIT__21ABE3BC] DEFAULT ((0)) NOT NULL,
    [JEODKEY]  CHAR (10)       CONSTRAINT [DF__GLJEDETO__JEODKE__22A007F5] DEFAULT ('') NOT NULL,
    [FKJEOH]   CHAR (10)       CONSTRAINT [DF__GLJEDETO__FKJEOH__23942C2E] DEFAULT ('') NOT NULL,
    [DEBITPR]  NUMERIC (14, 2) CONSTRAINT [DF__GLJEDETO__DEBITP__0B4B9A04] DEFAULT ((0)) NOT NULL,
    [CREDITPR] NUMERIC (14, 2) CONSTRAINT [DF__GLJEDETO__CREDIT__0C3FBE3D] DEFAULT ((0)) NOT NULL,
    [DEBITFC]  NUMERIC (14, 2) CONSTRAINT [DF__GLJEDETO__DEBITF__0710F4CC] DEFAULT ((0)) NOT NULL,
    [CREDITFC] NUMERIC (14, 2) CONSTRAINT [DF__GLJEDETO__CREDIT__08051905] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLJEDETO_PK] PRIMARY KEY CLUSTERED ([JEODKEY] ASC),
    CONSTRAINT [FK_GLJEDETO_GLJEHDRO] FOREIGN KEY ([FKJEOH]) REFERENCES [dbo].[GLJEHDRO] ([JEOHKEY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [FKJEOH]
    ON [dbo].[GLJEDETO]([FKJEOH] ASC);

