CREATE TABLE [dbo].[GLPOSTDEF] (
    [UNIQRECORD]             CHAR (10)    CONSTRAINT [DF__GLPOSTDEF__UNIQR__5AE46118] DEFAULT ('') NOT NULL,
    [DISPORDER]              NUMERIC (2)  CONSTRAINT [DF__GLPOSTDEF__DISPO__5BD88551] DEFAULT ((0)) NOT NULL,
    [POSTTYPE]               CHAR (10)    CONSTRAINT [DF__GLPOSTDEF__POSTT__5CCCA98A] DEFAULT ('') NOT NULL,
    [DIRECTPOST]             NUMERIC (1)  CONSTRAINT [DF__GLPOSTDEF__DIREC__5DC0CDC3] DEFAULT ((0)) NOT NULL,
    [cTRANSACTIONDESCR]      VARCHAR (50) CONSTRAINT [DF_GLPOSTDEF_cTRANSACTIONDESCR] DEFAULT ('') NOT NULL,
    [lAllowImmediateRelPost] BIT          CONSTRAINT [DF_GLPOSTDEF_lAllowImmediateRelPost] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLPOSTDEF_PK] PRIMARY KEY CLUSTERED ([UNIQRECORD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DISPORDER]
    ON [dbo].[GLPOSTDEF]([DISPORDER] ASC);


GO
CREATE NONCLUSTERED INDEX [POSTTYPE]
    ON [dbo].[GLPOSTDEF]([POSTTYPE] ASC);

