CREATE TABLE [dbo].[GLSETUP] (
    [UNIQGLSET]  CHAR (10) CONSTRAINT [DF__GLSETUP__UNIQGLS__01FE2E39] DEFAULT ('') NOT NULL,
    [UNIQSEG1]   CHAR (10) CONSTRAINT [DF__GLSETUP__UNIQSEG__02F25272] DEFAULT ('') NOT NULL,
    [UNIQSEG2]   CHAR (10) CONSTRAINT [DF__GLSETUP__UNIQSEG__03E676AB] DEFAULT ('') NOT NULL,
    [UNIQSEG3]   CHAR (10) CONSTRAINT [DF__GLSETUP__UNIQSEG__04DA9AE4] DEFAULT ('') NOT NULL,
    [RET_LINK]   CHAR (10) CONSTRAINT [DF__GLSETUP__RET_LIN__05CEBF1D] DEFAULT ('') NOT NULL,
    [CUR_LINK]   CHAR (10) CONSTRAINT [DF__GLSETUP__CUR_LIN__06C2E356] DEFAULT ('') NOT NULL,
    [INTRA_LINK] CHAR (10) CONSTRAINT [DF__GLSETUP__INTRA_L__07B7078F] DEFAULT ('') NOT NULL,
    [SUSP_LINK]  CHAR (10) CONSTRAINT [DF__GLSETUP__SUSP_LI__08AB2BC8] DEFAULT ('') NOT NULL,
    [FORCURLINK] CHAR (10) CONSTRAINT [DF__GLSETUP__FORCURL__099F5001] DEFAULT ('') NOT NULL,
    CONSTRAINT [GLSETUP_PK] PRIMARY KEY CLUSTERED ([UNIQGLSET] ASC)
);

