CREATE TABLE [dbo].[GLSJDet] (
    [gl_nbr]       CHAR (13)       CONSTRAINT [DF_GLSJDet_gl_nbr] DEFAULT ('') NOT NULL,
    [debit]        NUMERIC (14, 2) CONSTRAINT [DF_GLSJDet_debit] DEFAULT ((0.00)) NOT NULL,
    [credit]       NUMERIC (12, 2) CONSTRAINT [DF_GLSJDet_credit] DEFAULT ((0.00)) NOT NULL,
    [fkglstndhkey] CHAR (10)       CONSTRAINT [DF_GLSJDet_fkglstndhkey] DEFAULT ('') NOT NULL,
    [glstnddkey]   CHAR (10)       CONSTRAINT [DF_GLSJDet_glstnddkey] DEFAULT ('') NOT NULL,
    [DEBITFC]      NUMERIC (14, 2) CONSTRAINT [DF__GLSJDet__DEBITFC__4D3958F2] DEFAULT ((0)) NOT NULL,
    [CREDITFC]     NUMERIC (14, 2) CONSTRAINT [DF__GLSJDet__CREDITF__4E2D7D2B] DEFAULT ((0)) NOT NULL,
    [DEBITPR]      NUMERIC (14, 2) CONSTRAINT [DF__GLSJDet__DEBITPR__4F21A164] DEFAULT ((0)) NOT NULL,
    [CREDITPR]     NUMERIC (14, 2) CONSTRAINT [DF__GLSJDet__CREDITP__5015C59D] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_GLSJDet] PRIMARY KEY CLUSTERED ([glstnddkey] ASC),
    CONSTRAINT [FK_GlSJDet_GlSJHdr] FOREIGN KEY ([fkglstndhkey]) REFERENCES [dbo].[glsjhdr] ([glstndhkey]) ON DELETE CASCADE
);

