CREATE TABLE [dbo].[GLTRANS] (
    [GLUNIQ_KEY]       CHAR (10)       CONSTRAINT [DF__GLTRANS__GLUNIQ___3F073C79] DEFAULT ('') NOT NULL,
    [GL_NBR]           CHAR (13)       CONSTRAINT [DF__GLTRANS__GL_NBR__43CBF196] DEFAULT ('') NOT NULL,
    [DEBIT]            NUMERIC (14, 2) CONSTRAINT [DF__GLTRANS__DEBIT__44C015CF] DEFAULT ((0)) NOT NULL,
    [CREDIT]           NUMERIC (14, 2) CONSTRAINT [DF__GLTRANS__CREDIT__45B43A08] DEFAULT ((0)) NOT NULL,
    [CIDENTIFIER]      CHAR (30)       CONSTRAINT [DF__GLTRANS__CIDENTI__4B6D135E] DEFAULT ('') NOT NULL,
    [SourceTable]      VARCHAR (25)    CONSTRAINT [DF__GLTRANS__CTRANST__4A78EF25] DEFAULT ('') NOT NULL,
    [SourceSubTable]   VARCHAR (25)    CONSTRAINT [DF_GLTRANS_SourceSubTable] DEFAULT ('') NOT NULL,
    [cSubIdentifier]   CHAR (30)       CONSTRAINT [DF_GLTRANS_cSubIdentifier] DEFAULT ('') NOT NULL,
    [Fk_GLTRansUnique] CHAR (10)       CONSTRAINT [DF_GLTRANS_fk_gltransheader] DEFAULT ('') NOT NULL,
    [DebitPR]          NUMERIC (14, 2) CONSTRAINT [DF_GLTRANS_DebitPR] DEFAULT ((0.00)) NOT NULL,
    [CreditPR]         NUMERIC (14, 2) CONSTRAINT [DF_GLTRANS_CreditPR] DEFAULT ((0.00)) NOT NULL,
    CONSTRAINT [GLTRANS_PK] PRIMARY KEY CLUSTERED ([GLUNIQ_KEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [fk_gltransUnique]
    ON [dbo].[GLTRANS]([Fk_GLTRansUnique] ASC);


GO
CREATE NONCLUSTERED INDEX [GL_NBR]
    ON [dbo].[GLTRANS]([GL_NBR] ASC);


GO
CREATE NONCLUSTERED INDEX [GlTransXTabIndex]
    ON [dbo].[GLTRANS]([GL_NBR] ASC)
    INCLUDE([DEBIT], [CREDIT], [Fk_GLTRansUnique]);

