CREATE TABLE [dbo].[GLTYPES] (
    [UNIQGLTYPE]      CHAR (10) CONSTRAINT [DF__GLTYPES__UNIQGLT__59BB32B5] DEFAULT ('') NOT NULL,
    [GLTYPE]          CHAR (3)  CONSTRAINT [DF__GLTYPES__GLTYPE__5AAF56EE] DEFAULT ('') NOT NULL,
    [GLTYPEDESC]      CHAR (20) CONSTRAINT [DF__GLTYPES__GLTYPED__5BA37B27] DEFAULT ('') NOT NULL,
    [LO_LIMIT]        CHAR (13) CONSTRAINT [DF__GLTYPES__LO_LIMI__5C979F60] DEFAULT ('') NOT NULL,
    [HI_LIMIT]        CHAR (13) CONSTRAINT [DF__GLTYPES__HI_LIMI__5D8BC399] DEFAULT ('') NOT NULL,
    [GTNOTE]          TEXT      CONSTRAINT [DF__GLTYPES__GTNOTE__5E7FE7D2] DEFAULT ('') NOT NULL,
    [STMT]            CHAR (3)  CONSTRAINT [DF__GLTYPES__STMT__5F740C0B] DEFAULT ('') NOT NULL,
    [NORM_BAL]        CHAR (2)  CONSTRAINT [DF__GLTYPES__NORM_BA__60683044] DEFAULT ('') NOT NULL,
    [COMPANY]         CHAR (2)  CONSTRAINT [DF__GLTYPES__COMPANY__615C547D] DEFAULT ('') NOT NULL,
    [cashFlowActCode] INT       CONSTRAINT [DF_GLTYPES_cashActCode] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLTYPES_PK] PRIMARY KEY CLUSTERED ([UNIQGLTYPE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GLTYPE]
    ON [dbo].[GLTYPES]([GLTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [LO_LIMIT]
    ON [dbo].[GLTYPES]([LO_LIMIT] ASC);

