CREATE TABLE [dbo].[HOLIDAYS] (
    [HOLIDAY]     NCHAR (50)    CONSTRAINT [DF__HOLIDAYS__HOLIDA__26068485] DEFAULT ('') NOT NULL,
    [DATE]        SMALLDATETIME NULL,
    [iHolidaysUk] INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_HOLIDAYS] PRIMARY KEY CLUSTERED ([iHolidaysUk] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DATE]
    ON [dbo].[HOLIDAYS]([DATE] ASC);

