CREATE TABLE [dbo].[ImportPOMain] (
    [POImportId]      UNIQUEIDENTIFIER CONSTRAINT [DF__ImportPOM__POImp__4EED6291] DEFAULT (newsequentialid()) NOT NULL,
    [CompleteDate]    SMALLDATETIME    NULL,
    [CompletedBy]     VARCHAR (5)      NOT NULL,
    [PONumber]        VARCHAR (15)     NOT NULL,
    [Status]          VARCHAR (10)     NOT NULL,
    [Supplier]        VARCHAR (60)     NULL,
    [Terms]           VARCHAR (30)     NULL,
    [Buyer]           VARCHAR (256)    NULL,
    [Priority]        VARCHAR (10)     NULL,
    [PODate]          SMALLDATETIME    NULL,
    [ConfTo]          VARCHAR (20)     NULL,
    [LfreightInclude] BIT              CONSTRAINT [DF__ImportPOM__Lfrei__4FE186CA] DEFAULT ((0)) NOT NULL,
    [PONote]          VARCHAR (MAX)    NULL,
    [ShipChgAMT]      NUMERIC (20)     NULL,
    [IS_SCTAX]        BIT              CONSTRAINT [DF__ImportPOM__IS_SC__50D5AB03] DEFAULT ((0)) NULL,
    [SC_TAXPCT]       NUMERIC (20)     NULL,
    [ShipCharge]      VARCHAR (20)     NULL,
    [ShipVia]         VARCHAR (20)     NULL,
    [Fob]             VARCHAR (20)     NULL,
    [CLINK]           VARCHAR (10)     NULL,
    [RLINK]           VARCHAR (10)     NULL,
    [ILINK]           VARCHAR (10)     NULL,
    [BLINK]           VARCHAR (10)     NULL,
    [Message]         VARCHAR (MAX)    NULL,
    [IsValidated]     BIT              CONSTRAINT [DF__ImportPOM__IsVal__51C9CF3C] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__ImportPO__3443D71934FAC773] PRIMARY KEY CLUSTERED ([POImportId] ASC)
);

