CREATE TABLE [dbo].[ImportMFGRHeader] (
    [ImportId]      UNIQUEIDENTIFIER NOT NULL,
    [WorkSheetName] NVARCHAR (500)   NOT NULL,
    [UploadDate]    SMALLDATETIME    NOT NULL,
    [UploadBy]      UNIQUEIDENTIFIER NOT NULL,
    [CompleteDate]  SMALLDATETIME    CONSTRAINT [DF__ImportMFG__Compl__423D72E9] DEFAULT (NULL) NULL,
    [CompletedBy]   UNIQUEIDENTIFIER CONSTRAINT [DF__ImportMFG__Compl__43319722] DEFAULT (NULL) NULL,
    CONSTRAINT [PK__ImportMF__869767EA874D14B8] PRIMARY KEY CLUSTERED ([ImportId] ASC)
);

