CREATE TABLE [dbo].[importBeginningInventoryDetails] (
    [uniq_key]          CHAR (10)       CONSTRAINT [DF_importBeginningInventory_uniq_key] DEFAULT ('') NOT NULL,
    [part_no]           CHAR (25)       CONSTRAINT [DF_importBeginningInventory_part_no] DEFAULT ('') NOT NULL,
    [revision]          CHAR (8)        CONSTRAINT [DF_importBeginningInventory_revision] DEFAULT ('') NOT NULL,
    [w_key]             CHAR (10)       CONSTRAINT [DF_importBeginningInventory_w_key] DEFAULT ('') NOT NULL,
    [partmfgr]          CHAR (8)        CONSTRAINT [DF_importBeginningInventory_partmfgr] DEFAULT ('') NOT NULL,
    [mfgr_pt_no]        CHAR (30)       CONSTRAINT [DF_importBeginningInventory_mfgr_pt_no] DEFAULT ('') NOT NULL,
    [uniqwh]            CHAR (10)       CONSTRAINT [DF_importBeginningInventory_uniqwh] DEFAULT ('') NOT NULL,
    [location]          VARCHAR (17)    CONSTRAINT [DF_importBeginningInventory_location] DEFAULT ('') NOT NULL,
    [warehouse]         CHAR (10)       CONSTRAINT [DF_importBeginningInventory_warehouse] DEFAULT ('') NOT NULL,
    [qty_oh]            NUMERIC (12, 2) CONSTRAINT [DF_importBeginningInventory_qty_oh] DEFAULT ((0.00)) NOT NULL,
    [lotcode]           CHAR (15)       CONSTRAINT [DF_importBeginningInventoryDetails_lotcode] DEFAULT ('') NOT NULL,
    [expDate]           SMALLDATETIME   NULL,
    [reference]         CHAR (12)       CONSTRAINT [DF_importBeginningInventoryDetails_reference] DEFAULT ('') NULL,
    [Ponum]             CHAR (15)       CONSTRAINT [DF_importBeginningInventoryDetails_Ponum] DEFAULT ('') NOT NULL,
    [qtyImportId]       CHAR (10)       NOT NULL,
    [qtyImportDetailId] CHAR (10)       CONSTRAINT [DF_importBeginningInventoryDetails_qtyImportDetailId] DEFAULT ([dbo].[fn_generateuniquenumber]()) NOT NULL,
    [isgroup]           BIT             CONSTRAINT [DF__importBeg__isgro__1CBF7372] DEFAULT ((0)) NOT NULL,
    [custno]            CHAR (10)       CONSTRAINT [DF__importBeg__custn__1DB397AB] DEFAULT ('') NOT NULL,
    [custname]          CHAR (35)       CONSTRAINT [DF__importBeg__custn__1EA7BBE4] DEFAULT ('') NOT NULL,
    [uniqmfgrhd]        CHAR (10)       CONSTRAINT [DF__importBeg__uniqm__1F9BE01D] DEFAULT ('') NOT NULL,
    [recv_qty]          NUMERIC (12, 2) CONSTRAINT [DF__importBeg__recv___20900456] DEFAULT ((0)) NOT NULL,
    [custpart_no]       CHAR (25)       CONSTRAINT [DF__importBeg__custp__2184288F] DEFAULT ('') NOT NULL,
    [custrev]           CHAR (8)        CONSTRAINT [DF__importBeg__custr__22784CC8] DEFAULT ('') NOT NULL,
    [Wono]              CHAR (10)       CONSTRAINT [DF__importBegi__Wono__236C7101] DEFAULT ('') NOT NULL,
    [PrjNumber]         CHAR (10)       CONSTRAINT [DF__importBeg__PrjNu__2460953A] DEFAULT ('') NOT NULL,
    [WoAlloc]           NUMERIC (12, 2) CONSTRAINT [DF__importBeg__WoAll__2554B973] DEFAULT ((0)) NOT NULL,
    [ProjAlloc]         NUMERIC (12, 2) CONSTRAINT [DF__importBeg__ProjA__2648DDAC] DEFAULT ((0)) NOT NULL,
    [IsError]           BIT             CONSTRAINT [DF__importBeg__IsErr__4B7A625B] DEFAULT ((0)) NOT NULL,
    [ErrorMessage]      VARCHAR (MAX)   CONSTRAINT [DF__importBeg__Error__4C6E8694] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_importBeginningInventoryDetails] PRIMARY KEY CLUSTERED ([qtyImportDetailId] ASC),
    CONSTRAINT [FK_importBeginningInventoryDetails_importBeginningInventoryHeader] FOREIGN KEY ([qtyImportId]) REFERENCES [dbo].[importBeginningInventoryHeader] ([qtyImportId]) ON DELETE CASCADE
);

