CREATE TABLE [dbo].[ImportBOMToKitMTC] (
    [MTCId]        UNIQUEIDENTIFIER NOT NULL,
    [FKAvlRowId]   UNIQUEIDENTIFIER NOT NULL,
    [FkLotRowId]   UNIQUEIDENTIFIER NULL,
    [FKFieldDefId] UNIQUEIDENTIFIER NOT NULL,
    [MTCRowId]     UNIQUEIDENTIFIER NOT NULL,
    [Original]     NVARCHAR (MAX)   NULL,
    [Adjusted]     NVARCHAR (MAX)   NULL,
    [Status]       NVARCHAR (50)    NULL,
    [Message]      NVARCHAR (MAX)   NOT NULL,
    CONSTRAINT [PK__ImportBO__B4A2577DFBC0990A] PRIMARY KEY CLUSTERED ([MTCId] ASC)
);

