CREATE TABLE [dbo].[ImportBillShipAddressLink] (
    [BSAddrLinkDetId]  UNIQUEIDENTIFIER NOT NULL,
    [FkImportId]       UNIQUEIDENTIFIER NOT NULL,
    [CustRowId]        UNIQUEIDENTIFIER NOT NULL,
    [BillAddressRowId] UNIQUEIDENTIFIER NOT NULL,
    [ShipAddressRowId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__ImportBi__7BC668561F0B0DF6] PRIMARY KEY CLUSTERED ([BSAddrLinkDetId] ASC)
);

