CREATE TABLE [dbo].[INVSETUP] (
    [UNIQINVSET]       CHAR (10) CONSTRAINT [DF__INVSETUP__UNIQIN__3F914C5E] DEFAULT ('') NOT NULL,
    [DIVNO]            CHAR (2)  CONSTRAINT [DF__INVSETUP__DIVNO__40857097] DEFAULT ('') NOT NULL,
    [UNIQSEG1]         CHAR (10) CONSTRAINT [DF__INVSETUP__UNIQSE__417994D0] DEFAULT ('') NOT NULL,
    [UNIQSEG2]         CHAR (10) CONSTRAINT [DF__INVSETUP__UNIQSE__426DB909] DEFAULT ('') NOT NULL,
    [UNIQSEG3]         CHAR (10) CONSTRAINT [DF__INVSETUP__UNIQSE__4361DD42] DEFAULT ('') NOT NULL,
    [RAWMLINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__RAWMLI__4456017B] DEFAULT ('') NOT NULL,
    [WORKLINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__WORKLI__454A25B4] DEFAULT ('') NOT NULL,
    [FINILINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__FINILI__463E49ED] DEFAULT ('') NOT NULL,
    [PURCLINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__PURCLI__47326E26] DEFAULT ('') NOT NULL,
    [CONFIGLINK]       CHAR (10) CONSTRAINT [DF__INVSETUP__CONFIG__4826925F] DEFAULT ('') NOT NULL,
    [MANULINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__MANULI__491AB698] DEFAULT ('') NOT NULL,
    [SHRINKLINK]       CHAR (10) CONSTRAINT [DF__INVSETUP__SHRINK__4A0EDAD1] DEFAULT ('') NOT NULL,
    [IADJLINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__IADJLI__4B02FF0A] DEFAULT ('') NOT NULL,
    [INSTLINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__INSTLI__4BF72343] DEFAULT ('') NOT NULL,
    [UIPKLINK]         CHAR (10) CONSTRAINT [DF__INVSETUP__UIPKLI__4CEB477C] DEFAULT ('') NOT NULL,
    [RAWM_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__RAWM_G__4DDF6BB5] DEFAULT ('') NOT NULL,
    [WORK_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__WORK_G__4ED38FEE] DEFAULT ('') NOT NULL,
    [FINI_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__FINI_G__4FC7B427] DEFAULT ('') NOT NULL,
    [PURC_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__PURC_G__50BBD860] DEFAULT ('') NOT NULL,
    [CONF_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__CONF_G__51AFFC99] DEFAULT ('') NOT NULL,
    [MANU_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__MANU_G__52A420D2] DEFAULT ('') NOT NULL,
    [SHRI_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__SHRI_G__5398450B] DEFAULT ('') NOT NULL,
    [IADJ_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__IADJ_G__548C6944] DEFAULT ('') NOT NULL,
    [INST_GL_NO]       CHAR (13) CONSTRAINT [DF__INVSETUP__INST_G__55808D7D] DEFAULT ('') NOT NULL,
    [MAT_V_GL]         CHAR (13) CONSTRAINT [DF__INVSETUP__MAT_V___5674B1B6] DEFAULT ('') NOT NULL,
    [LAB_V_GL]         CHAR (13) CONSTRAINT [DF__INVSETUP__LAB_V___5768D5EF] DEFAULT ('') NOT NULL,
    [OVER_V_GL]        CHAR (13) CONSTRAINT [DF__INVSETUP__OVER_V__585CFA28] DEFAULT ('') NOT NULL,
    [OTH_V_GL]         CHAR (13) CONSTRAINT [DF__INVSETUP__OTH_V___59511E61] DEFAULT ('') NOT NULL,
    [USER_FIELD]       CHAR (30) CONSTRAINT [DF__INVSETUP__USER_F__5A45429A] DEFAULT ('') NOT NULL,
    [UNRECON_GL_NO]    CHAR (13) CONSTRAINT [DF__INVSETUP__UNRECO__5B3966D3] DEFAULT ('') NOT NULL,
    [USERDEF_GL]       CHAR (13) CONSTRAINT [DF__INVSETUP__USERDE__5C2D8B0C] DEFAULT ('') NOT NULL,
    [STDCOSTADJGLNO]   CHAR (13) CONSTRAINT [DF__INVSETUP__STDCOS__5D21AF45] DEFAULT ('') NOT NULL,
    [RUNDVAR_GL]       CHAR (13) CONSTRAINT [DF_INVSETUP_RUNDVAR_GL] DEFAULT ('') NOT NULL,
    [STDCOSTERADJGLNO] CHAR (13) CONSTRAINT [DF__INVSETUP__STDCOS__1361BD18] DEFAULT ('') NOT NULL,
    CONSTRAINT [INVSETUP_PK] PRIMARY KEY CLUSTERED ([UNIQINVSET] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DIVNO]
    ON [dbo].[INVSETUP]([DIVNO] ASC);

