CREATE TABLE [dbo].[INVSTDTX] (
    [PACKLISTNO]   CHAR (10)       CONSTRAINT [DF__INVSTDTX__PACKLI__5FFE1BF0] DEFAULT ('') NOT NULL,
    [INVOICENO]    CHAR (10)       CONSTRAINT [DF__INVSTDTX__INVOIC__60F24029] DEFAULT ('') NOT NULL,
    [PLUNIQLNK]    CHAR (10)       CONSTRAINT [DF__INVSTDTX__PLUNIQ__61E66462] DEFAULT ('') NOT NULL,
    [LINKADD]      CHAR (10)       CONSTRAINT [DF__INVSTDTX__LINKAD__62DA889B] DEFAULT ('') NOT NULL,
    [TAX_ID]       CHAR (8)        CONSTRAINT [DF__INVSTDTX__TAX_ID__63CEACD4] DEFAULT ('') NOT NULL,
    [TAXDESC]      CHAR (25)       CONSTRAINT [DF__INVSTDTX__TAXDES__64C2D10D] DEFAULT ('') NOT NULL,
    [GL_NBR_IN]    CHAR (13)       CONSTRAINT [DF__INVSTDTX__GL_NBR__65B6F546] DEFAULT ('') NOT NULL,
    [GL_NBR_OUT]   CHAR (13)       CONSTRAINT [DF__INVSTDTX__GL_NBR__66AB197F] DEFAULT ('') NOT NULL,
    [TAX_RATE]     NUMERIC (8, 4)  CONSTRAINT [DF__INVSTDTX__TAX_RA__679F3DB8] DEFAULT ((0)) NOT NULL,
    [TAX_AMT]      NUMERIC (12, 4) CONSTRAINT [DF__INVSTDTX__TAX_AM__689361F1] DEFAULT ((0)) NOT NULL,
    [TAX_TYPE]     CHAR (1)        CONSTRAINT [DF__INVSTDTX__TAX_TY__6987862A] DEFAULT ('') NOT NULL,
    [GLLIBUNIQ]    CHAR (10)       CONSTRAINT [DF__INVSTDTX__GLLIBU__6A7BAA63] DEFAULT ('') NOT NULL,
    [GLASUNIQ]     CHAR (10)       CONSTRAINT [DF__INVSTDTX__GLASUN__6B6FCE9C] DEFAULT ('') NOT NULL,
    [TXTYPEFORN]   CHAR (1)        CONSTRAINT [DF__INVSTDTX__TXTYPE__6C63F2D5] DEFAULT ('') NOT NULL,
    [INVSTDTXUNIQ] CHAR (10)       CONSTRAINT [DF__INVSTDTX__INVSTD__6D58170E] DEFAULT ('') NOT NULL,
    [CMPRUNIQ]     CHAR (10)       CONSTRAINT [DF_INVSTDTX_CMPRUNIQ] DEFAULT ('') NOT NULL,
    [Tax_AmtFC]    NUMERIC (12, 4) CONSTRAINT [DF__INVSTDTX__Tax_Am__705615F8] DEFAULT ((0)) NOT NULL,
    [PTPROD]       BIT             CONSTRAINT [DF__INVSTDTX__PTPROD__5A31CAAF] DEFAULT ((0)) NOT NULL,
    [PTFRT]        BIT             CONSTRAINT [DF__INVSTDTX__PTFRT__5B25EEE8] DEFAULT ((0)) NOT NULL,
    [STPROD]       BIT             CONSTRAINT [DF__INVSTDTX__STPROD__5C1A1321] DEFAULT ((0)) NOT NULL,
    [STFRT]        BIT             CONSTRAINT [DF__INVSTDTX__STFRT__5D0E375A] DEFAULT ((0)) NOT NULL,
    [STTX]         BIT             CONSTRAINT [DF__INVSTDTX__STTX__5E025B93] DEFAULT ((0)) NOT NULL,
    [Tax_AmtPR]    NUMERIC (12, 4) CONSTRAINT [DF__INVSTDTX__Tax_Am__24B6664C] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [INVSTDTX_PK] PRIMARY KEY CLUSTERED ([INVSTDTXUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PACKLISTNO]
    ON [dbo].[INVSTDTX]([PACKLISTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [PLUNIQLNK]
    ON [dbo].[INVSTDTX]([PLUNIQLNK] ASC);

