CREATE TABLE [dbo].[INVTSER] (
    [SERIALUNIQ]   CHAR (10)     CONSTRAINT [DF__INVTSER__SERIALU__09BF4B92] DEFAULT ('') NOT NULL,
    [SERIALNO]     CHAR (30)     CONSTRAINT [DF__INVTSER__SERIALN__0AB36FCB] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]     CHAR (10)     CONSTRAINT [DF__INVTSER__UNIQ_KE__0BA79404] DEFAULT ('') NOT NULL,
    [UNIQMFGRHD]   CHAR (10)     CONSTRAINT [DF__INVTSER__UNIQMFG__0C9BB83D] DEFAULT ('') NOT NULL,
    [UNIQ_LOT]     CHAR (10)     CONSTRAINT [DF__INVTSER__UNIQ_LO__0D8FDC76] DEFAULT ('') NOT NULL,
    [ID_KEY]       CHAR (10)     CONSTRAINT [DF__INVTSER__ID_KEY__0E8400AF] DEFAULT ('') NOT NULL,
    [ID_VALUE]     CHAR (10)     CONSTRAINT [DF__INVTSER__ID_VALU__0F7824E8] DEFAULT ('') NOT NULL,
    [SAVEDTTM]     SMALLDATETIME NULL,
    [SAVEINIT]     CHAR (8)      CONSTRAINT [DF__INVTSER__SAVEINI__106C4921] DEFAULT ('') NULL,
    [LOTCODE]      NVARCHAR (25) CONSTRAINT [DF__INVTSER__LOTCODE__11606D5A] DEFAULT ('') NOT NULL,
    [EXPDATE]      SMALLDATETIME NULL,
    [REFERENCE]    CHAR (12)     CONSTRAINT [DF__INVTSER__REFEREN__12549193] DEFAULT ('') NOT NULL,
    [PONUM]        CHAR (15)     CONSTRAINT [DF__INVTSER__PONUM__1348B5CC] DEFAULT ('') NOT NULL,
    [ISRESERVED]   BIT           CONSTRAINT [DF__INVTSER__ISRESER__143CDA05] DEFAULT ((0)) NOT NULL,
    [ACTVKEY]      CHAR (10)     CONSTRAINT [DF__INVTSER__ACTVKEY__1530FE3E] DEFAULT ('') NOT NULL,
    [OLDWONO]      CHAR (10)     CONSTRAINT [DF__INVTSER__OLDWONO__16252277] DEFAULT ('') NOT NULL,
    [WONO]         CHAR (10)     CONSTRAINT [DF__INVTSER__WONO__171946B0] DEFAULT ('') NOT NULL,
    [RESERVEDFLAG] CHAR (10)     CONSTRAINT [DF__INVTSER__RESERVE__180D6AE9] DEFAULT ('') NOT NULL,
    [RESERVEDNO]   CHAR (10)     CONSTRAINT [DF__INVTSER__RESERVE__19018F22] DEFAULT ('') NOT NULL,
    [ipkeyunique]  CHAR (10)     CONSTRAINT [DF_INVTSER_ipkeyunique] DEFAULT ('') NOT NULL,
    CONSTRAINT [INVTSER_PK] PRIMARY KEY CLUSTERED ([SERIALUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ID_KEY]
    ON [dbo].[INVTSER]([ID_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [MFGRLOT]
    ON [dbo].[INVTSER]([UNIQMFGRHD] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [MFGRSER]
    ON [dbo].[INVTSER]([UNIQMFGRHD] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [ipkey]
    ON [dbo].[INVTSER]([ipkeyunique] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIALNO]
    ON [dbo].[INVTSER]([SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UKEYSERNO]
    ON [dbo].[INVTSER]([UNIQ_KEY] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[INVTSER]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRHD]
    ON [dbo].[INVTSER]([UNIQMFGRHD] ASC);


GO
CREATE NONCLUSTERED INDEX [WOALL]
    ON [dbo].[INVTSER]([WONO] ASC, [ID_KEY] ASC, [ID_VALUE] ASC, [ACTVKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [WODEPTACT]
    ON [dbo].[INVTSER]([WONO] ASC, [ID_VALUE] ASC, [ACTVKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [WODEPTKEY]
    ON [dbo].[INVTSER]([WONO] ASC, [ID_VALUE] ASC);


GO
CREATE NONCLUSTERED INDEX [WOSERIALNO]
    ON [dbo].[INVTSER]([WONO] ASC, [SERIALNO] ASC);


GO
-- =============================================
-- Author:		Vicky Lu	
-- Create date: 08/31/2010
-- Description:	After Delete trigger for the InvtSer table
-- =============================================
CREATE TRIGGER  [dbo].[InvtSer_Delete]
   ON  [dbo].[INVTSER] 
   AFTER DELETE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRANSACTION 
	DELETE FROM SerlConf WHERE SerialUniq IN (SELECT SerialUniq FROM DELETED)
	COMMIT
END
