CREATE TABLE [dbo].[INVTSETUP] (
    [UNIQINVTST]        CHAR (10)       CONSTRAINT [DF__INVTSETUP__UNIQI__1BDDFBCD] DEFAULT ('') NOT NULL,
    [SKIPZERO]          BIT             CONSTRAINT [DF__INVTSETUP__SKIPZ__1CD22006] DEFAULT ((0)) NOT NULL,
    [ALLOWCHGWT]        BIT             CONSTRAINT [DF__INVTSETUP__ALLOW__1DC6443F] DEFAULT ((0)) NOT NULL,
    [WEIGHTEDPO]        NUMERIC (3)     CONSTRAINT [DF__INVTSETUP__WEIGH__1EBA6878] DEFAULT ((5)) NOT NULL,
    [LUSEIPKEY]         BIT             CONSTRAINT [DF__INVTSETUP__LUSEI__1FAE8CB1] DEFAULT ((0)) NOT NULL,
    [LINLEVEL]          BIT             CONSTRAINT [DF__INVTSETUP__LINLE__20A2B0EA] DEFAULT ((0)) NOT NULL,
    [CLEVELBY]          CHAR (3)        CONSTRAINT [DF__INVTSETUP__CLEVE__2196D523] DEFAULT ('') NOT NULL,
    [DLEVELTIME]        SMALLDATETIME   CONSTRAINT [DF_INVTSETUP_DLEVELTIME] DEFAULT ('') NOT NULL,
    [cmattpcontrol]     CHAR (1)        CONSTRAINT [DF_INVTSETUP_cmattpcontrol] DEFAULT ('') NOT NULL,
    [lSuppressZeroInvt] BIT             CONSTRAINT [DF_INVTSETUP_lSupressZeroInvt] DEFAULT ((0)) NOT NULL,
    [lNoAutoAvl]        BIT             CONSTRAINT [DF_INVTSETUP_lNoAutoAvl] DEFAULT ((0)) NOT NULL,
    [lAutoMakeNo]       BIT             CONSTRAINT [DF_INVTSETUP_lAutoMakeNo] DEFAULT ((0)) NOT NULL,
    [nPoHistBy]         SMALLINT        CONSTRAINT [DF_INVTSETUP_nPoHistBy] DEFAULT ((1)) NOT NULL,
    [nPoStatus]         SMALLINT        CONSTRAINT [DF_INVTSETUP_nPoStatus] DEFAULT ((1)) NOT NULL,
    [nLastPos]          SMALLINT        CONSTRAINT [DF_INVTSETUP_nLastnPos] DEFAULT ((10)) NOT NULL,
    [NCOSTDIFFPCT]      NUMERIC (3)     CONSTRAINT [DF__INVTSETUP__NCOST__46E920BA] DEFAULT ((0)) NOT NULL,
    [NCOSTDIFFAMT]      NUMERIC (13, 5) CONSTRAINT [DF__INVTSETUP__NCOST__47DD44F3] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [INVTSETUP_PK] PRIMARY KEY CLUSTERED ([UNIQINVTST] ASC)
);

