CREATE TABLE [dbo].[INVTGLS] (
    [UNIQFIELD] CHAR (10) CONSTRAINT [DF__INVTGLS__UNIQFIE__7F76C749] DEFAULT ('') NOT NULL,
    [DESCRIPT]  CHAR (30) CONSTRAINT [DF__INVTGLS__DESCRIP__006AEB82] DEFAULT ('') NOT NULL,
    [GL_NBR]    CHAR (13) CONSTRAINT [DF__INVTGLS__GL_NBR__015F0FBB] DEFAULT ('') NOT NULL,
    [REC_TYPE]  CHAR (1)  CONSTRAINT [DF__INVTGLS__REC_TYP__025333F4] DEFAULT ('') NOT NULL,
    CONSTRAINT [INVTGLS_PK] PRIMARY KEY CLUSTERED ([UNIQFIELD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [REC_TYPE]
    ON [dbo].[INVTGLS]([REC_TYPE] ASC);

