CREATE TABLE [dbo].[INVTHIST] (
    [DBFS]       CHAR (8)      CONSTRAINT [DF_INVTHIST_DBFS] DEFAULT ('') NOT NULL,
    [DEL_USERID] CHAR (8)      CONSTRAINT [DF_INVTHIST_DEL_USERID] DEFAULT ('') NOT NULL,
    [del_date]   SMALLDATETIME NULL,
    [key]        CHAR (20)     CONSTRAINT [DF_INVTHIST_key] DEFAULT ('') NOT NULL,
    [note]       TEXT          CONSTRAINT [DF_INVTHIST_note] DEFAULT ('') NOT NULL,
    [UNIQUEHIST] INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [INVTHIST_PK] PRIMARY KEY CLUSTERED ([UNIQUEHIST] ASC)
);

