CREATE TABLE [dbo].[INVTRELDOC] (
    [DOC_UNIQ]    CHAR (10)     CONSTRAINT [DF__INVTRELDO__DOC_U__0035E158] DEFAULT ('') NOT NULL,
    [FK_UNIQUEID] CHAR (10)     CONSTRAINT [DF__INVTRELDO__HDUNI__7F41BD1F] DEFAULT ('') NOT NULL,
    [DOCNO]       CHAR (25)     CONSTRAINT [DF__INVTRELDO__DOCNO__021E29CA] DEFAULT ('') NOT NULL,
    [DOCREVNO]    CHAR (4)      CONSTRAINT [DF__INVTRELDO__DOCRE__03124E03] DEFAULT ('') NOT NULL,
    [DOCDESCR]    CHAR (45)     CONSTRAINT [DF__INVTRELDO__DOCDE__0406723C] DEFAULT ('') NOT NULL,
    [DOCDATE]     SMALLDATETIME NULL,
    [DOCNOTE]     TEXT          CONSTRAINT [DF__INVTRELDO__DOCNO__04FA9675] DEFAULT ('') NOT NULL,
    [DOCEXEC]     VARCHAR (254) CONSTRAINT [DF__INVTRELDO__DOCEX__05EEBAAE] DEFAULT ('') NOT NULL,
    CONSTRAINT [INVTRELDOC_PK] PRIMARY KEY CLUSTERED ([DOC_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [HDUNIQ_KEY]
    ON [dbo].[INVTRELDOC]([FK_UNIQUEID] ASC);

