CREATE TABLE [dbo].[IPKEY] (
    [IPKEYUNIQUE]         CHAR (10)        CONSTRAINT [DF__IPKEY__IPKEYUNIQ__1D913A15] DEFAULT ([dbo].[fn_generateUniqueNumber]()) NOT NULL,
    [UNIQ_KEY]            CHAR (10)        CONSTRAINT [DF__IPKEY__UNIQ_KEY__1E855E4E] DEFAULT ('') NOT NULL,
    [UNIQMFGRHD]          CHAR (10)        CONSTRAINT [DF__IPKEY__UNIQMFGRH__1F798287] DEFAULT ('') NOT NULL,
    [LOTCODE]             NVARCHAR (25)    CONSTRAINT [DF__IPKEY__LOTCODE__206DA6C0] DEFAULT ('') NOT NULL,
    [REFERENCE]           CHAR (12)        CONSTRAINT [DF__IPKEY__REFERENCE__2161CAF9] DEFAULT ('') NOT NULL,
    [EXPDATE]             SMALLDATETIME    NULL,
    [PONUM]               CHAR (15)        CONSTRAINT [DF__IPKEY__PONUM__2255EF32] DEFAULT ('') NOT NULL,
    [UNIQMFSP]            CHAR (10)        CONSTRAINT [DF__IPKEY__UNIQMFSP__243E37A4] DEFAULT ('') NOT NULL,
    [RecordId]            CHAR (10)        CONSTRAINT [DF__IPKEY__UNIQRECDT__25325BDD] DEFAULT ('') NOT NULL,
    [TRANSTYPE]           CHAR (1)         CONSTRAINT [DF__IPKEY__CTRANSTYP__26268016] DEFAULT ('') NOT NULL,
    [originalPkgQty]      NUMERIC (12, 2)  CONSTRAINT [DF__IPKEY__NORIGPKGQ__280EC888] DEFAULT ((0)) NOT NULL,
    [pkgBalance]          NUMERIC (12, 2)  CONSTRAINT [DF__IPKEY__NPKGBALAN__2902ECC1] DEFAULT ((0)) NOT NULL,
    [fk_userid]           UNIQUEIDENTIFIER NULL,
    [recordCreated]       SMALLDATETIME    NULL,
    [W_KEY]               CHAR (10)        CONSTRAINT [DF__IPKEY__W_KEY__2AEB3533] DEFAULT ('') NOT NULL,
    [qtyAllocatedTotal]   NUMERIC (12, 2)  CONSTRAINT [DF_IPKEY_LISALLOC] DEFAULT ((0)) NOT NULL,
    [QtyAllocatedOver]    NUMERIC (12, 2)  CONSTRAINT [DF_IPKEY_QtyAllocatedOver] DEFAULT ((0.00)) NOT NULL,
    [originalIpkeyUnique] CHAR (10)        CONSTRAINT [DF_IPKEY_originalIpkeyUnique] DEFAULT ('') NOT NULL,
    CONSTRAINT [IPKEY_PK] PRIMARY KEY CLUSTERED ([IPKEYUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LOTCODE]
    ON [dbo].[IPKEY]([W_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [RECLOT]
    ON [dbo].[IPKEY]([RecordId] ASC, [UNIQMFGRHD] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC, [W_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [RecordId]
    ON [dbo].[IPKEY]([RecordId] ASC);


GO
CREATE NONCLUSTERED INDEX [RecordLink]
    ON [dbo].[IPKEY]([TRANSTYPE] ASC, [RecordId] ASC);


GO
CREATE NONCLUSTERED INDEX [TCRTDT]
    ON [dbo].[IPKEY]([recordCreated] ASC);


GO
CREATE NONCLUSTERED INDEX [TRANSTYPE]
    ON [dbo].[IPKEY]([TRANSTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[IPKEY]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRHD]
    ON [dbo].[IPKEY]([UNIQMFGRHD] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFSP]
    ON [dbo].[IPKEY]([UNIQMFSP] ASC);


GO
CREATE NONCLUSTERED INDEX [W_KEY]
    ON [dbo].[IPKEY]([W_KEY] ASC);

