CREATE TABLE [dbo].[ISO9000] (
    [REF_ID]  CHAR (7)  CONSTRAINT [DF__ISO9000__REF_ID__3B219CFC] DEFAULT ('') NOT NULL,
    [ISODESC] CHAR (35) CONSTRAINT [DF__ISO9000__ISODESC__3C15C135] DEFAULT ('') NOT NULL,
    [ISO_ID]  CHAR (6)  CONSTRAINT [DF__ISO9000__ISO_ID__3D09E56E] DEFAULT ('') NOT NULL,
    [ISOREF]  CHAR (33) CONSTRAINT [DF__ISO9000__ISOREF__3DFE09A7] DEFAULT ('') NOT NULL,
    CONSTRAINT [ISO9000_PK] PRIMARY KEY CLUSTERED ([REF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ISO_ID]
    ON [dbo].[ISO9000]([ISO_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [ISODESC]
    ON [dbo].[ISO9000]([ISODESC] ASC);

