CREATE TABLE [dbo].[JBSHPCHK] (
    [WONO]       CHAR (10)        CONSTRAINT [DF__JBSHPCHK__WONO__7A12F3AE] DEFAULT ('') NOT NULL,
    [SHOPFL_CHK] NVARCHAR (50)    CONSTRAINT [DF__JBSHPCHK__SHOPFL__7B0717E7] DEFAULT ('') NOT NULL,
    [CHKFLAG]    BIT              CONSTRAINT [DF__JBSHPCHK__CHKFLA__7BFB3C20] DEFAULT ((0)) NOT NULL,
    [CHKINIT]    CHAR (8)         CONSTRAINT [DF__JBSHPCHK__CHKINI__7CEF6059] DEFAULT ('') NULL,
    [CHKDATE]    SMALLDATETIME    NULL,
    [JBSHPCHKUK] CHAR (10)        CONSTRAINT [DF__JBSHPCHK__JBSHPC__7ED7A8CB] DEFAULT ('') NOT NULL,
    [isMnxCheck] BIT              CONSTRAINT [DF_JBSHPCHK_isMnxCheck] DEFAULT ((0)) NOT NULL,
    [chkUserId]  UNIQUEIDENTIFIER NULL,
    [DEPTKEY]    CHAR (10)        CONSTRAINT [DF__JBSHPCHK__DEPTKE__25F4A348] DEFAULT (NULL) NULL,
    CONSTRAINT [JBSHPCHK_PK] PRIMARY KEY CLUSTERED ([JBSHPCHKUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[JBSHPCHK]([WONO] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO_TITLE]
    ON [dbo].[JBSHPCHK]([WONO] ASC, [SHOPFL_CHK] ASC);

