CREATE TABLE [dbo].[JOBCOSTM] (
    [UNIQ_MISC] CHAR (10)       CONSTRAINT [DF__JOBCOSTM__UNIQ_M__01B41576] DEFAULT ('') NOT NULL,
    [WONO]      CHAR (10)       CONSTRAINT [DF__JOBCOSTM__WONO__02A839AF] DEFAULT ('') NOT NULL,
    [OTHDESCR]  CHAR (20)       CONSTRAINT [DF__JOBCOSTM__OTHDES__039C5DE8] DEFAULT ('') NOT NULL,
    [OTHAMNT]   NUMERIC (10, 2) CONSTRAINT [DF__JOBCOSTM__OTHAMN__04908221] DEFAULT ((0)) NOT NULL,
    [SAVEDATE]  SMALLDATETIME   NULL,
    [SAVEINIT]  CHAR (8)        CONSTRAINT [DF__JOBCOSTM__SAVEIN__0584A65A] DEFAULT ('') NULL,
    CONSTRAINT [JOBCOSTM_PK] PRIMARY KEY CLUSTERED ([UNIQ_MISC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[JOBCOSTM]([WONO] ASC);

