CREATE TABLE [dbo].[KADETAIL] (
    [KASEQNUM]   CHAR (10)        CONSTRAINT [DF__KADETAIL__KASEQN__13D2C5B1] DEFAULT ('') NOT NULL,
    [AUDITBY]    CHAR (8)         CONSTRAINT [DF__KADETAIL__AUDITB__14C6E9EA] DEFAULT ('') NOT NULL,
    [AUDITDATE]  SMALLDATETIME    CONSTRAINT [DF_KADETAIL_AUDITDATE] DEFAULT (getdate()) NULL,
    [SHORTBAL]   NUMERIC (12, 2)  CONSTRAINT [DF__KADETAIL__SHORTB__15BB0E23] DEFAULT ((0)) NOT NULL,
    [SHQUALIFY]  CHAR (3)         CONSTRAINT [DF__KADETAIL__SHQUAL__16AF325C] DEFAULT ('') NOT NULL,
    [SHORTQTY]   NUMERIC (12, 2)  CONSTRAINT [DF__KADETAIL__SHORTQ__17A35695] DEFAULT ((0)) NOT NULL,
    [SHREASON]   CHAR (15)        CONSTRAINT [DF__KADETAIL__SHREAS__18977ACE] DEFAULT ('') NOT NULL,
    [UNIQUEREC]  CHAR (10)        CONSTRAINT [DF__KADETAIL__UNIQUE__198B9F07] DEFAULT ([dbo].[fn_generateuniquenumber]()) NOT NULL,
    [Wono]       CHAR (10)        CONSTRAINT [DF__KADETAIL__Wono__332C40D0] DEFAULT ('') NOT NULL,
    [editUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [KADETAIL_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AUDITDATE]
    ON [dbo].[KADETAIL]([AUDITDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [KASEQNUM]
    ON [dbo].[KADETAIL]([KASEQNUM] ASC);

