CREATE TABLE [dbo].[MATTPLOGIC] (
    [UQMTLOGIC]  CHAR (10)   CONSTRAINT [DF__MATTPLOGI__UQMTL__601E1781] DEFAULT ('') NOT NULL,
    [UQINVMATTP] CHAR (10)   CONSTRAINT [DF__MATTPLOGI__UQINV__61123BBA] DEFAULT ('') NOT NULL,
    [UQAVLMATTP] CHAR (10)   CONSTRAINT [DF__MATTPLOGI__UQAVL__62065FF3] DEFAULT ('') NOT NULL,
    [LOGIC]      NUMERIC (1) CONSTRAINT [DF__MATTPLOGI__LOGIC__62FA842C] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [MATTPLOGIC_PK] PRIMARY KEY CLUSTERED ([UQMTLOGIC] ASC)
);

