CREATE TABLE [dbo].[MFGRVAR] (
    [UNIQMFGVAR]      CHAR (10)        CONSTRAINT [DF__MFGRVAR__UNIQMFG__69A781BB] DEFAULT ('') NOT NULL,
    [WONO]            CHAR (10)        CONSTRAINT [DF__MFGRVAR__WONO__6A9BA5F4] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]        CHAR (10)        CONSTRAINT [DF__MFGRVAR__UNIQ_KE__6B8FCA2D] DEFAULT ('') NOT NULL,
    [MAN_GL_NBR]      CHAR (13)        CONSTRAINT [DF__MFGRVAR__MAN_GL___6C83EE66] DEFAULT ('') NOT NULL,
    [WIP_GL_NBR]      CHAR (13)        CONSTRAINT [DF__MFGRVAR__WIP_GL___6D78129F] DEFAULT ('') NOT NULL,
    [ISSUECOST]       NUMERIC (13, 5)  CONSTRAINT [DF__MFGRVAR__ISSUECO__6E6C36D8] DEFAULT ((0)) NOT NULL,
    [BOMCOST]         NUMERIC (13, 5)  CONSTRAINT [DF__MFGRVAR__BOMCOST__6F605B11] DEFAULT ((0)) NOT NULL,
    [TOTALVAR]        NUMERIC (13, 5)  CONSTRAINT [DF__MFGRVAR__TOTALVA__70547F4A] DEFAULT ((0)) NOT NULL,
    [DATETIME]        SMALLDATETIME    CONSTRAINT [DF_MFGRVAR_DATETIME] DEFAULT (getdate()) NULL,
    [INITIALS]        CHAR (8)         CONSTRAINT [DF__MFGRVAR__INITIAL__7148A383] DEFAULT ('') NULL,
    [IS_REL_GL]       BIT              CONSTRAINT [DF__MFGRVAR__IS_REL___77017CD9] DEFAULT ((0)) NOT NULL,
    [VARTYPE]         CHAR (5)         CONSTRAINT [DF_MFGRVAR_VARTYPE] DEFAULT ('') NOT NULL,
    [userId]          UNIQUEIDENTIFIER NULL,
    [ISSUECOSTPR]     NUMERIC (13, 5)  CONSTRAINT [DF__MFGRVAR__ISSUECO__2AC4455D] DEFAULT ((0)) NOT NULL,
    [BOMCOSTPR]       NUMERIC (13, 5)  CONSTRAINT [DF__MFGRVAR__BOMCOST__2BB86996] DEFAULT ((0)) NOT NULL,
    [TOTALVARPR]      NUMERIC (13, 5)  CONSTRAINT [DF__MFGRVAR__TOTALVA__2CAC8DCF] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)        CONSTRAINT [DF__MFGRVAR__PRFCUSE__2DA0B208] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)        CONSTRAINT [DF__MFGRVAR__FUNCFCU__2E94D641] DEFAULT ('') NOT NULL,
    [isKitClosed]     BIT              CONSTRAINT [DF__MFGRVAR__isKitCl__3F8101CF] DEFAULT ((0)) NOT NULL,
    [refUniqMfgVar]   CHAR (10)        CONSTRAINT [DF__MFGRVAR__refUniq__40752608] DEFAULT ('') NOT NULL,
    CONSTRAINT [MFGRVAR_PK] PRIMARY KEY CLUSTERED ([UNIQMFGVAR] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IS_REL_GL_VAR]
    ON [dbo].[MFGRVAR]([IS_REL_GL] ASC, [VARTYPE] ASC, [TOTALVAR] ASC)
    INCLUDE([UNIQMFGVAR], [WONO], [UNIQ_KEY], [MAN_GL_NBR], [WIP_GL_NBR], [DATETIME]);


GO
CREATE NONCLUSTERED INDEX [mfgrdate]
    ON [dbo].[MFGRVAR]([DATETIME] ASC);


GO
CREATE NONCLUSTERED INDEX [uniq_key]
    ON [dbo].[MFGRVAR]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [vartype]
    ON [dbo].[MFGRVAR]([VARTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [wono]
    ON [dbo].[MFGRVAR]([WONO] ASC);


GO
-- =============================================
-- Author:		Yelena Shmidt
-- Create date: 06/29/2012
-- Description:	Insert trigger will check if TotalVar=0 auto fill is_rel_gl with .t.
-- Modification:
-- 04/17/17 VL added to update functional currency fields
-- =============================================
CREATE TRIGGER [dbo].[MfgrVar_Insert]
   ON  [dbo].[MFGRVAR] 
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for trigger here
    BEGIN TRANSACTION
	--UPDATE MFGRVAR SET IS_REL_GL = CASE WHEN I.TOTALVAR =0 THEN 1 ELSE MfgrVar.IS_REL_GL END FROM inserted I WHERE I.UNIQMFGVAR=MFGRVAR.UNIQMFGVAR  
		UPDATE MFGRVAR SET IS_REL_GL = CASE WHEN I.TOTALVAR =0 THEN 1 ELSE MfgrVar.IS_REL_GL END,
							PRFcused_uniq = CASE WHEN dbo.fn_IsFCInstalled() = 0 THEN SPACE(10) ELSE dbo.fn_GetPresentationCurrency() END,
							FuncFcused_uniq = CASE WHEN dbo.fn_IsFCInstalled() = 0 THEN SPACE(10) ELSE dbo.fn_GetFunctionalCurrency() END	
		 FROM inserted I WHERE I.UNIQMFGVAR=MFGRVAR.UNIQMFGVAR  
	COMMIT
END