CREATE TABLE [dbo].[mnxCheckList] (
    [SHOPFL_CHK] NVARCHAR (50) CONSTRAINT [DF__SHOPFL_CHK] DEFAULT ('') NOT NULL,
    [UNIQUENUM]  INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [mnxCheckList_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);

