CREATE TABLE [dbo].[MnxECOCopy] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [CopyCriteria] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK__MnxECOCo__3214EC27E518A00F] PRIMARY KEY CLUSTERED ([ID] ASC)
);

