CREATE TABLE [dbo].[MnxReports] (
    [rptId]                   CHAR (10)     NOT NULL,
    [fkrptGroupId]            VARCHAR (50)  CONSTRAINT [DF_rptReports_rptGroup] DEFAULT ('') NOT NULL,
    [rptTitle]                VARCHAR (100) CONSTRAINT [DF_rptReports_rptTitle] DEFAULT ('') NOT NULL,
    [rptTitleLong]            VARCHAR (100) CONSTRAINT [DF_rptReports_rptTitleLong] DEFAULT ('') NOT NULL,
    [rptDescription]          VARCHAR (500) CONSTRAINT [DF_rptReports_reportDescription] DEFAULT ('') NOT NULL,
    [sequence]                INT           NOT NULL,
    [label]                   BIT           CONSTRAINT [DF_rptReports_label] DEFAULT ((0)) NOT NULL,
    [filePath]                VARCHAR (200) CONSTRAINT [DF_rptReports_filePath] DEFAULT ('') NOT NULL,
    [display]                 BIT           CONSTRAINT [DF_rptReports_display] DEFAULT ((0)) NOT NULL,
    [dataSource]              VARCHAR (50)  CONSTRAINT [DF_rptReports_dataSource] DEFAULT ('Report') NOT NULL,
    [reportType]              VARCHAR (50)  CONSTRAINT [DF_rptReports_reportType] DEFAULT ('quickView') NOT NULL,
    [paramGroup]              VARCHAR (50)  CONSTRAINT [DF_rptReports_paramGroup] DEFAULT ('') NOT NULL,
    [groupedCol]              VARCHAR (100) CONSTRAINT [DF_rptReports_groupedCol] DEFAULT ('') NOT NULL,
    [custReportReplace]       CHAR (10)     CONSTRAINT [DF_rptReports_custReportReplace] DEFAULT ('') NOT NULL,
    [emailBody]               VARCHAR (MAX) CONSTRAINT [DF_MnxReports_emailBody] DEFAULT ('') NOT NULL,
    [emailSubject]            VARCHAR (100) CONSTRAINT [DF_MnxReports_emailSubject] DEFAULT ('') NOT NULL,
    [showGroupSummary]        BIT           CONSTRAINT [DF_MnxReports_showGroupSummary] DEFAULT ((0)) NOT NULL,
    [showSummaryOnHide]       BIT           CONSTRAINT [DF_MnxReports_showSummaryOnHide] DEFAULT ((0)) NOT NULL,
    [maxSqlTimeout]           INT           CONSTRAINT [DF_MnxReports_maxSqlTimeout] DEFAULT ((30)) NOT NULL,
    [dateLastRun]             SMALLDATETIME NULL,
    [reportCount]             INT           CONSTRAINT [DF_MnxReports_runCount] DEFAULT ((0)) NOT NULL,
    [quickViewCount]          INT           CONSTRAINT [DF_MnxReports_quickViewCount] DEFAULT ((0)) NOT NULL,
    [exportCount]             INT           CONSTRAINT [DF_MnxReports_exportCount] DEFAULT ((0)) NOT NULL,
    [sendreportCount]         INT           CONSTRAINT [DF_MnxReports_sendreportCount] DEFAULT ((0)) NOT NULL,
    [rowLinkId]               VARCHAR (50)  CONSTRAINT [DF_MnxReports_rowId] DEFAULT ('') NOT NULL,
    [rowLink]                 VARCHAR (200) CONSTRAINT [DF_MnxReports_rowLink] DEFAULT ('') NOT NULL,
    [quickViewTitleTemplate]  VARCHAR (200) CONSTRAINT [DF_MnxReports_quickViewTitleTemplate] DEFAULT ('') NOT NULL,
    [quickViewHeaderTemplate] VARCHAR (200) CONSTRAINT [DF_MnxReports_quickViewHeaderTemplate] DEFAULT ('') NOT NULL,
    [isBigDataRpt]            BIT           CONSTRAINT [DF__MnxReport__isBig__3AFB787D] DEFAULT ((0)) NOT NULL,
    [RptEmailBodySetting]     VARCHAR (150) CONSTRAINT [DF__MnxReport__RptEm__13C27B22] DEFAULT ('') NULL,
    CONSTRAINT [PK_rptReports] PRIMARY KEY CLUSTERED ([rptId] ASC)
);

