CREATE TABLE [dbo].[MODULES] (
    [MOD_ID]    CHAR (2)    CONSTRAINT [DF__MODULES__MOD_ID__30F91444] DEFAULT ('') NOT NULL,
    [MOD_NAME]  CHAR (20)   CONSTRAINT [DF__MODULES__MOD_NAM__31ED387D] DEFAULT ('') NOT NULL,
    [APP]       CHAR (8)    CONSTRAINT [DF__MODULES__APP__32E15CB6] DEFAULT ('') NOT NULL,
    [INSTALLED] BIT         CONSTRAINT [DF__MODULES__INSTALL__33D580EF] DEFAULT ((0)) NOT NULL,
    [NUMBER]    NUMERIC (2) CONSTRAINT [DF__MODULES__NUMBER__34C9A528] DEFAULT ((0)) NOT NULL,
    [MOD_RLOCK] BIT         CONSTRAINT [DF__MODULES__MOD_RLO__35BDC961] DEFAULT ((0)) NOT NULL,
    [ADMIN]     BIT         CONSTRAINT [DF__MODULES__ADMIN__36B1ED9A] DEFAULT ((0)) NOT NULL
);

