CREATE TABLE [dbo].[MPFORSCH] (
    [FORECASTNO] NUMERIC (6)     CONSTRAINT [DF__MPFORSCH__FORECA__389A360C] DEFAULT ((0)) NOT NULL,
    [SHIP_DTS]   SMALLDATETIME   NULL,
    [QTY]        NUMERIC (12, 2) CONSTRAINT [DF__MPFORSCH__QTY__398E5A45] DEFAULT ((0)) NOT NULL,
    [QTY_CONSUM] NUMERIC (12, 2) CONSTRAINT [DF__MPFORSCH__QTY_CO__3A827E7E] DEFAULT ((0)) NOT NULL,
    [UNIQUEREC]  CHAR (10)       CONSTRAINT [DF__MPFORSCH__UNIQUE__3B76A2B7] DEFAULT ('') NOT NULL,
    CONSTRAINT [MPFORSCH_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FORECASTNO]
    ON [dbo].[MPFORSCH]([FORECASTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SHIP_DTS]
    ON [dbo].[MPFORSCH]([SHIP_DTS] ASC);

