CREATE TABLE [dbo].[MPSBUCKM] (
    [UNIQ_KEY] CHAR (10)    CONSTRAINT [DF__MPSBUCKM__UNIQ_K__3E530F62] DEFAULT ('') NOT NULL,
    [GLDIVNO]  CHAR (2)     CONSTRAINT [DF__MPSBUCKM__GLDIVN__3F47339B] DEFAULT ('') NOT NULL,
    [TOTALQTY] NUMERIC (11) CONSTRAINT [DF__MPSBUCKM__TOTALQ__403B57D4] DEFAULT ((0)) NOT NULL,
    [PASTDUE]  NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__PASTDU__412F7C0D] DEFAULT ((0)) NOT NULL,
    [OUT]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__OUT__4223A046] DEFAULT ((0)) NOT NULL,
    [MO1]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO1__4317C47F] DEFAULT ((0)) NOT NULL,
    [MO2]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO2__440BE8B8] DEFAULT ((0)) NOT NULL,
    [MO3]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO3__45000CF1] DEFAULT ((0)) NOT NULL,
    [MO4]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO4__45F4312A] DEFAULT ((0)) NOT NULL,
    [MO5]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO5__46E85563] DEFAULT ((0)) NOT NULL,
    [MO6]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO6__47DC799C] DEFAULT ((0)) NOT NULL,
    [MO7]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO7__48D09DD5] DEFAULT ((0)) NOT NULL,
    [MO8]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO8__49C4C20E] DEFAULT ((0)) NOT NULL,
    [MO9]      NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO9__4AB8E647] DEFAULT ((0)) NOT NULL,
    [MO10]     NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO10__4BAD0A80] DEFAULT ((0)) NOT NULL,
    [MO11]     NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO11__4CA12EB9] DEFAULT ((0)) NOT NULL,
    [MO12]     NUMERIC (9)  CONSTRAINT [DF__MPSBUCKM__MO12__4D9552F2] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [MPSBUCKM_PK] PRIMARY KEY CLUSTERED ([UNIQ_KEY] ASC)
);

