CREATE TABLE [dbo].[MPSSCH] (
    [UNIQ_KEY]  CHAR (10)       CONSTRAINT [DF__MPSSCH__UNIQ_KEY__6FEA6AF6] DEFAULT ('') NOT NULL,
    [REQDATE]   SMALLDATETIME   NULL,
    [REQQTY]    NUMERIC (12, 2) CONSTRAINT [DF__MPSSCH__REQQTY__70DE8F2F] DEFAULT ((0)) NOT NULL,
    [REF]       CHAR (25)       CONSTRAINT [DF__MPSSCH__REF__71D2B368] DEFAULT ('') NOT NULL,
    [GLDIVNO]   CHAR (2)        CONSTRAINT [DF__MPSSCH__GLDIVNO__72C6D7A1] DEFAULT ('') NOT NULL,
    [UNIQUEREC] CHAR (10)       CONSTRAINT [DF__MPSSCH__UNIQUERE__73BAFBDA] DEFAULT ('') NOT NULL,
    CONSTRAINT [MPSSCH_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[MPSSCH]([UNIQ_KEY] ASC);

