CREATE TABLE [dbo].[MRPACT] (
    [UNIQ_KEY]     CHAR (10)        CONSTRAINT [DF__MRPACT__UNIQ_KEY__03F163A3] DEFAULT ('') NOT NULL,
    [DUE_DATE]     SMALLDATETIME    NULL,
    [STARTDATE]    SMALLDATETIME    NULL,
    [BALANCE]      NUMERIC (9)      CONSTRAINT [DF__MRPACT__BALANCE__04E587DC] DEFAULT ((0)) NOT NULL,
    [REQQTY]       NUMERIC (9)      CONSTRAINT [DF__MRPACT__REQQTY__05D9AC15] DEFAULT ((0)) NOT NULL,
    [REF]          CHAR (25)        CONSTRAINT [DF__MRPACT__REF__06CDD04E] DEFAULT ('') NOT NULL,
    [ACTION]       CHAR (15)        CONSTRAINT [DF__MRPACT__ACTION__07C1F487] DEFAULT ('') NOT NULL,
    [PARENTPT]     CHAR (20)        CONSTRAINT [DF__MRPACT__PARENTPT__08B618C0] DEFAULT ('') NOT NULL,
    [DTTAKEACT]    SMALLDATETIME    NULL,
    [REQDATE]      SMALLDATETIME    NULL,
    [MFGRS]        TEXT             CONSTRAINT [DF__MRPACT__MFGRS__09AA3CF9] DEFAULT ('') NOT NULL,
    [DAYS]         NUMERIC (4)      CONSTRAINT [DF__MRPACT__DAYS__0A9E6132] DEFAULT ((0)) NOT NULL,
    [WONO]         CHAR (10)        CONSTRAINT [DF__MRPACT__WONO__0B92856B] DEFAULT ('') NOT NULL,
    [UNIQMRPACT]   CHAR (10)        CONSTRAINT [DF__MRPACT__UNIQMRPA__0D7ACDDD] DEFAULT ('') NOT NULL,
    [UNIQMRPSCH]   CHAR (10)        CONSTRAINT [DF__MRPACT__UNIQMRPS__0E6EF216] DEFAULT ('') NOT NULL,
    [PRJUNIQUE]    CHAR (10)        CONSTRAINT [DF__MRPACT__PRJUNIQU__0F63164F] DEFAULT ('') NOT NULL,
    [PREFAVL]      CHAR (40)        CONSTRAINT [DF__MRPACT__PREFAVL__10573A88] DEFAULT ('') NOT NULL,
    [POUNIQLNNO]   CHAR (10)        CONSTRAINT [DF__MRPACT__POUNIQLN__114B5EC1] DEFAULT ('') NOT NULL,
    [MATLTYPE]     CHAR (10)        CONSTRAINT [DF__MRPACT__MATLTYPE__123F82FA] DEFAULT ('') NOT NULL,
    [is_forecast]  INT              CONSTRAINT [DF_MRPACT_is_forecast] DEFAULT ((0)) NOT NULL,
    [ActionStatus] VARCHAR (15)     NULL,
    [MrpRunDt]     SMALLDATETIME    CONSTRAINT [DF__MRPACT__MrpRunDt__059DADA6] DEFAULT (NULL) NULL,
    [UserReqQty]   NUMERIC (9)      CONSTRAINT [DF__MRPACT__UserReqQ__46231266] DEFAULT ((0)) NOT NULL,
    [UserPrice]    NUMERIC (15, 7)  CONSTRAINT [DF__MRPACT__UserPric__4717369F] DEFAULT ((0)) NOT NULL,
    [UserPartMfgr] VARCHAR (8)      CONSTRAINT [DF__MRPACT__UserPart__480B5AD8] DEFAULT ('') NOT NULL,
    [UserMfgrPtNo] VARCHAR (30)     CONSTRAINT [DF__MRPACT__UserMfgr__48FF7F11] DEFAULT ('') NOT NULL,
    [UniqSupNo]    CHAR (10)        CONSTRAINT [DF__MRPACT__UniqSupN__49F3A34A] DEFAULT ('') NOT NULL,
    [ActionNotes]  VARCHAR (MAX)    CONSTRAINT [DF__MRPACT__ActionNo__4AE7C783] DEFAULT ('') NOT NULL,
    [ActDate]      SMALLDATETIME    CONSTRAINT [DF__MRPACT__ActDate__2F158FDC] DEFAULT (NULL) NULL,
    [ActUserId]    UNIQUEIDENTIFIER CONSTRAINT [DF__MRPACT__ActUserI__3009B415] DEFAULT (NULL) NULL,
    CONSTRAINT [MRPACT_PK] PRIMARY KEY CLUSTERED ([UNIQMRPACT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MRPACTACTION]
    ON [dbo].[MRPACT]([ACTION] ASC, [POUNIQLNNO] ASC)
    INCLUDE([UNIQMRPACT]);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[MRPACT]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [is_forecast]
    ON [dbo].[MRPACT]([is_forecast] ASC);

