CREATE TABLE [dbo].[MRPPO] (
    [PONUM]      CHAR (15)       CONSTRAINT [DF__MRPPO__PONUM__76625E5B] DEFAULT ('') NOT NULL,
    [COSTEACH]   NUMERIC (13, 5) CONSTRAINT [DF__MRPPO__COSTEACH__77568294] DEFAULT ((0)) NOT NULL,
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__MRPPO__UNIQ_KEY__784AA6CD] DEFAULT ('') NOT NULL,
    [REQDATE]    SMALLDATETIME   NULL,
    [REQQTY]     NUMERIC (12, 2) CONSTRAINT [DF__MRPPO__REQQTY__793ECB06] DEFAULT ((0)) NOT NULL,
    [UNIQSUPNO]  CHAR (10)       CONSTRAINT [DF__MRPPO__SUPID__7A32EF3F] DEFAULT ('') NOT NULL,
    [PARTMFGR]   CHAR (8)        CONSTRAINT [DF__MRPPO__PARTMFGR__7B271378] DEFAULT ('') NOT NULL,
    [DUE_DATE]   SMALLDATETIME   NULL,
    [BALANCE]    NUMERIC (13, 2) CONSTRAINT [DF__MRPPO__BALANCE__7C1B37B1] DEFAULT ((0)) NOT NULL,
    [SCHD_QTY]   NUMERIC (12, 2) CONSTRAINT [DF__MRPPO__SCHD_QTY__7D0F5BEA] DEFAULT ((0)) NOT NULL,
    [UNIQMRPACT] CHAR (10)       CONSTRAINT [DF__MRPPO__UNIQMRPAC__7E038023] DEFAULT ('') NOT NULL,
    [MFGR_PT_NO] CHAR (30)       CONSTRAINT [DF__MRPPO__MFGR_PT_N__7EF7A45C] DEFAULT ('') NOT NULL,
    [UNIQUEREC]  CHAR (10)       CONSTRAINT [DF__MRPPO__UNIQUEREC__7FEBC895] DEFAULT ('') NOT NULL,
    CONSTRAINT [MRPPO_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MRPPO]
    ON [dbo].[MRPPO]([PONUM] ASC, [UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMRPACT]
    ON [dbo].[MRPPO]([UNIQMRPACT] ASC);

