CREATE TABLE [dbo].[MRPPOHST] (
    [PONUM]     CHAR (15)       CONSTRAINT [DF__MRPPOHST__PONUM__02C83540] DEFAULT ('') NOT NULL,
    [UNIQSUPNO] CHAR (10)       CONSTRAINT [DF__MRPPOHST__SUPID__03BC5979] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]  CHAR (10)       CONSTRAINT [DF__MRPPOHST__UNIQ_K__04B07DB2] DEFAULT ('') NOT NULL,
    [REQ_DATE]  SMALLDATETIME   NULL,
    [SCHD_QTY]  NUMERIC (12, 2) CONSTRAINT [DF__MRPPOHST__SCHD_Q__05A4A1EB] DEFAULT ((0)) NOT NULL,
    [COSTEACH]  NUMERIC (13, 5) CONSTRAINT [DF__MRPPOHST__COSTEA__0698C624] DEFAULT ((0)) NOT NULL,
    [ACPT_QTY]  NUMERIC (12, 2) CONSTRAINT [DF__MRPPOHST__ACPT_Q__078CEA5D] DEFAULT ((0)) NOT NULL,
    [DATE]      SMALLDATETIME   NULL,
    [PARTMFGR]  CHAR (8)        CONSTRAINT [DF__MRPPOHST__PARTMF__08810E96] DEFAULT ('') NOT NULL,
    [UNIQUEREC] CHAR (10)       CONSTRAINT [DF__MRPPOHST__UNIQUE__097532CF] DEFAULT ('') NOT NULL,
    CONSTRAINT [MRPPOHST_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MRPPOHST]
    ON [dbo].[MRPPOHST]([PONUM] ASC, [UNIQ_KEY] ASC);

