CREATE TABLE [dbo].[MRPSCH2] (
    [UNIQ_KEY]   CHAR (10)     CONSTRAINT [DF__MRPSCH2__UNIQ_KE__0C519F7A] DEFAULT ('') NOT NULL,
    [REQSTART]   SMALLDATETIME NULL,
    [REQQTY]     NUMERIC (9)   CONSTRAINT [DF__MRPSCH2__REQQTY__0D45C3B3] DEFAULT ((0)) NOT NULL,
    [REF]        CHAR (24)     CONSTRAINT [DF__MRPSCH2__REF__0E39E7EC] DEFAULT ('') NOT NULL,
    [BALANCE]    NUMERIC (10)  CONSTRAINT [DF__MRPSCH2__BALANCE__0F2E0C25] DEFAULT ((0)) NOT NULL,
    [PARENTPT]   CHAR (20)     CONSTRAINT [DF__MRPSCH2__PARENTP__1022305E] DEFAULT ('') NOT NULL,
    [REQDATE]    SMALLDATETIME NULL,
    [ORD_NBR]    INT           CONSTRAINT [DF__MRPSCH2__ORD_NBR__11165497] DEFAULT ((0)) NOT NULL,
    [WONO]       CHAR (15)     CONSTRAINT [DF__MRPSCH2__WONO__120A78D0] DEFAULT ('') NOT NULL,
    [ACTION]     CHAR (13)     CONSTRAINT [DF__MRPSCH2__ACTION__12FE9D09] DEFAULT ('') NOT NULL,
    [MFGRS]      TEXT          CONSTRAINT [DF__MRPSCH2__MFGRS__13F2C142] DEFAULT ('') NOT NULL,
    [GLDIVNO]    CHAR (2)      CONSTRAINT [DF__MRPSCH2__GLDIVNO__14E6E57B] DEFAULT ('') NOT NULL,
    [UNIQMRPSCH] CHAR (10)     CONSTRAINT [DF__MRPSCH2__UNIQMRP__15DB09B4] DEFAULT ('') NOT NULL,
    [UNIQMRPACT] CHAR (10)     CONSTRAINT [DF__MRPSCH2__UNIQMRP__16CF2DED] DEFAULT ('') NOT NULL,
    [MRPACTREF]  CHAR (10)     CONSTRAINT [DF__MRPSCH2__MRPACTR__17C35226] DEFAULT ('') NOT NULL,
    [PRJUNIQUE]  CHAR (10)     CONSTRAINT [DF__MRPSCH2__PRJUNIQ__18B7765F] DEFAULT ('') NOT NULL,
    CONSTRAINT [MRPSCH2_PK] PRIMARY KEY CLUSTERED ([UNIQMRPSCH] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MRPSCH2]
    ON [dbo].[MRPSCH2]([UNIQ_KEY] ASC, [GLDIVNO] ASC, [REQDATE] ASC, [ORD_NBR] ASC);


GO
CREATE NONCLUSTERED INDEX [REQSTART]
    ON [dbo].[MRPSCH2]([REQSTART] ASC);

