CREATE TABLE [dbo].[MRPSUPPL] (
    [KEYFIELD]  CHAR (10)       CONSTRAINT [DF__MRPSUPPL__KEYFIE__1B93E30A] DEFAULT ('') NOT NULL,
    [PONUM]     CHAR (15)       CONSTRAINT [DF__MRPSUPPL__PONUM__1D7C2B7C] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]  CHAR (10)       CONSTRAINT [DF__MRPSUPPL__UNIQ_K__1F6473EE] DEFAULT ('') NOT NULL,
    [PARTMFGR]  CHAR (8)        CONSTRAINT [DF__MRPSUPPL__PARTMF__20589827] DEFAULT ('') NOT NULL,
    [REQDATE]   SMALLDATETIME   NULL,
    [BALANCE]   NUMERIC (13, 2) CONSTRAINT [DF__MRPSUPPL__BALANC__214CBC60] DEFAULT ((0)) NOT NULL,
    [WONO]      CHAR (10)       CONSTRAINT [DF__MRPSUPPL__WONO__2240E099] DEFAULT ('') NOT NULL,
    [UNIQSUPNO] CHAR (10)       CONSTRAINT [DF__MRPSUPPL__SUPID__1E704FB5] DEFAULT ('') NOT NULL,
    CONSTRAINT [MRPSUPPL_PK] PRIMARY KEY CLUSTERED ([KEYFIELD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[MRPSUPPL]([UNIQ_KEY] ASC);

