CREATE TABLE [dbo].[MRPUSED] (
    [UNIQUSED]  CHAR (10)     CONSTRAINT [DF__MRPUSED__UNIQUSE__251D4D44] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]  CHAR (10)     CONSTRAINT [DF__MRPUSED__UNIQ_KE__2611717D] DEFAULT ('') NOT NULL,
    [W_KEY]     CHAR (10)     CONSTRAINT [DF__MRPUSED__W_KEY__270595B6] DEFAULT ('') NOT NULL,
    [QTYUSED]   NUMERIC (8)   CONSTRAINT [DF__MRPUSED__QTYUSED__27F9B9EF] DEFAULT ((0)) NOT NULL,
    [REQDATE]   SMALLDATETIME NULL,
    [PONUM]     CHAR (15)     CONSTRAINT [DF__MRPUSED__PONUM__28EDDE28] DEFAULT ('') NOT NULL,
    [WONO]      CHAR (10)     CONSTRAINT [DF__MRPUSED__WONO__29E20261] DEFAULT ('') NOT NULL,
    [MFGR_PART] CHAR (40)     CONSTRAINT [DF__MRPUSED__MFGR_PA__2AD6269A] DEFAULT ('') NOT NULL,
    [REQQTY]    NUMERIC (9)   CONSTRAINT [DF__MRPUSED__REQQTY__2BCA4AD3] DEFAULT ((0)) NOT NULL,
    [DEMANDS]   CHAR (25)     CONSTRAINT [DF__MRPUSED__DEMANDS__2CBE6F0C] DEFAULT ('') NOT NULL,
    CONSTRAINT [MRPUSED_PK] PRIMARY KEY CLUSTERED ([UNIQUSED] ASC)
);

