CREATE TABLE [dbo].[NOTEASSIGN] (
    [FKNOTEUNIQUE] CHAR (10)        CONSTRAINT [DF__NOTEASSIG__FKNOT__3C00B29C] DEFAULT ('') NOT NULL,
    [TABLENAME]    CHAR (20)        CONSTRAINT [DF__NOTEASSIG__TABLE__3CF4D6D5] DEFAULT ('') NOT NULL,
    [TABLEUNIQUE]  CHAR (15)        CONSTRAINT [DF__NOTEASSIG__TABLE__3DE8FB0E] DEFAULT ('') NOT NULL,
    [ASSIGNUNIQUE] CHAR (10)        CONSTRAINT [DF__NOTEASSIG__ASSIG__3EDD1F47] DEFAULT ('') NOT NULL,
    [dAssignDT]    SMALLDATETIME    CONSTRAINT [DF_NOTEASSIGN_cAssignDT] DEFAULT (getdate()) NULL,
    [cAssignId]    UNIQUEIDENTIFIER NULL,
    CONSTRAINT [NOTEASSIGN_PK] PRIMARY KEY CLUSTERED ([ASSIGNUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NOTEUNIQUE]
    ON [dbo].[NOTEASSIGN]([FKNOTEUNIQUE] ASC);


GO
CREATE NONCLUSTERED INDEX [TABLENAME]
    ON [dbo].[NOTEASSIGN]([TABLENAME] ASC);


GO
CREATE NONCLUSTERED INDEX [TABLEUNIQ]
    ON [dbo].[NOTEASSIGN]([TABLEUNIQUE] ASC);

