CREATE TABLE [dbo].[oldKALOCIPKEY] (
    [UNIQKALOCIPKEY]  CHAR (10)       CONSTRAINT [DF_KALOCIPKEY_UNIQKALOCIPKEY] DEFAULT ('') NOT NULL,
    [UNIQKALOCATE]    CHAR (10)       CONSTRAINT [DF_KALOCIPKEY_UNIQKALOCATE] DEFAULT ('') NOT NULL,
    [FK_IPKEYUNIQUE]  CHAR (10)       CONSTRAINT [DF_KALOCIPKEY_FK_IPKEYUNIQUE] DEFAULT ('') NULL,
    [NPICK_QTY]       NUMERIC (12, 2) CONSTRAINT [DF_KALOCIPKEY_NPICK_QTY] DEFAULT ((0)) NOT NULL,
    [NOVERISSQTY]     NUMERIC (12, 2) CONSTRAINT [DF_KALOCIPKEY_NOVERISSQTY] DEFAULT ((0)) NOT NULL,
    [OVERIPKEYUNIQUE] CHAR (10)       CONSTRAINT [DF_KALOCIPKEY_OVERIPKEYUNIQUE] DEFAULT ('') NULL,
    [allocatedQty]    NUMERIC (12, 2) CONSTRAINT [DF_KALOCIPKEY_allocateQty] DEFAULT ((0.00)) NOT NULL,
    CONSTRAINT [KALOCIPKEY_PK] PRIMARY KEY CLUSTERED ([UNIQKALOCIPKEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UQLCOVIPKY]
    ON [dbo].[oldKALOCIPKEY]([UNIQKALOCATE] ASC, [OVERIPKEYUNIQUE] ASC);


GO
CREATE NONCLUSTERED INDEX [UQLCFKIPKY]
    ON [dbo].[oldKALOCIPKEY]([UNIQKALOCATE] ASC, [FK_IPKEYUNIQUE] ASC);

