CREATE TABLE [dbo].[oldKALOCSER] (
    [UNIQKALOCSER]  CHAR (10) CONSTRAINT [DF__KALOCSER__UNIQKA__27D9BE5E] DEFAULT ('') NOT NULL,
    [UNIQKALOCATE]  CHAR (10) CONSTRAINT [DF__KALOCSER__UNIQKA__28CDE297] DEFAULT ('') NOT NULL,
    [SERIALNO]      CHAR (30) CONSTRAINT [DF__KALOCSER__SERIAL__29C206D0] DEFAULT ('') NOT NULL,
    [SERIALUNIQ]    CHAR (10) CONSTRAINT [DF__KALOCSER__SERIAL__2AB62B09] DEFAULT ('') NOT NULL,
    [IS_OVERISSUED] BIT       CONSTRAINT [DF__KALOCSER__IS_OVE__2BAA4F42] DEFAULT ((0)) NOT NULL,
    [Wono]          CHAR (10) CONSTRAINT [DF__KALOCSER__Wono__35148942] DEFAULT ('') NOT NULL,
    [IPKEYUNIQUE]   CHAR (10) CONSTRAINT [DF_KALOCSER_IPKEYUNIQUE] DEFAULT ('') NOT NULL,
    CONSTRAINT [KALOCSER_PK] PRIMARY KEY CLUSTERED ([UNIQKALOCSER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [KALOCSER]
    ON [dbo].[oldKALOCSER]([UNIQKALOCATE] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [KALOCSERUN]
    ON [dbo].[oldKALOCSER]([UNIQKALOCATE] ASC, [SERIALUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIALNO]
    ON [dbo].[oldKALOCSER]([SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIALUNIQ]
    ON [dbo].[oldKALOCSER]([SERIALUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [UQKALOCATE]
    ON [dbo].[oldKALOCSER]([UNIQKALOCATE] ASC);

