CREATE TABLE [dbo].[oldKALOCATE] (
    [UNIQKALOCATE] CHAR (10)       CONSTRAINT [DF__KALOCATE__UNIQKA__1C680BB2] DEFAULT ('') NOT NULL,
    [KASEQNUM]     CHAR (10)       CONSTRAINT [DF__KALOCATE__KASEQN__1D5C2FEB] DEFAULT ('') NOT NULL,
    [W_KEY]        CHAR (10)       CONSTRAINT [DF__KALOCATE__W_KEY__1E505424] DEFAULT ('') NOT NULL,
    [PICK_QTY]     NUMERIC (12, 2) CONSTRAINT [DF__KALOCATE__PICK_Q__1F44785D] DEFAULT ((0)) NOT NULL,
    [LOTCODE]      CHAR (15)       CONSTRAINT [DF__KALOCATE__LOTCOD__20389C96] DEFAULT ('') NOT NULL,
    [EXPDATE]      SMALLDATETIME   NULL,
    [REFERENCE]    CHAR (12)       CONSTRAINT [DF__KALOCATE__REFERE__212CC0CF] DEFAULT ('') NOT NULL,
    [OVERISSQTY]   NUMERIC (12, 2) CONSTRAINT [DF__KALOCATE__OVERIS__2220E508] DEFAULT ((0)) NOT NULL,
    [OVERW_KEY]    CHAR (10)       CONSTRAINT [DF__KALOCATE__OVERW___23150941] DEFAULT ('') NOT NULL,
    [PONUM]        CHAR (15)       CONSTRAINT [DF__KALOCATE__PONUM__24092D7A] DEFAULT ('') NOT NULL,
    [UNIQMFGRHD]   CHAR (10)       CONSTRAINT [DF__KALOCATE__UNIQMF__24FD51B3] DEFAULT ('') NOT NULL,
    [Wono]         CHAR (10)       CONSTRAINT [DF__KALOCATE__Wono__34206509] DEFAULT ('') NOT NULL,
    [allocatedQty] NUMERIC (12, 2) CONSTRAINT [DF_KALOCATE_allocateQty] DEFAULT ((0.00)) NOT NULL,
    CONSTRAINT [KALOCATE_PK] PRIMARY KEY CLUSTERED ([UNIQKALOCATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [KAOWKEYLOT]
    ON [dbo].[oldKALOCATE]([KASEQNUM] ASC, [OVERW_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [KASEQNUM]
    ON [dbo].[oldKALOCATE]([KASEQNUM] ASC);


GO
CREATE NONCLUSTERED INDEX [PARTLOCAT]
    ON [dbo].[oldKALOCATE]([KASEQNUM] ASC, [W_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRHD]
    ON [dbo].[oldKALOCATE]([UNIQMFGRHD] ASC);


GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
    ON [dbo].[oldKALOCATE]([Wono] ASC, [OVERISSQTY] ASC, [OVERW_KEY] ASC)
    INCLUDE([UNIQKALOCATE], [KASEQNUM], [LOTCODE], [EXPDATE], [REFERENCE], [PONUM], [UNIQMFGRHD]);

