CREATE TABLE [dbo].[OUTSVSPR] (
    [SVSKEY]     CHAR (10)       CONSTRAINT [DF__OUTSVSPR__SVSKEY__4F138710] DEFAULT ('') NOT NULL,
    [OUTCQTY]    NUMERIC (7)     CONSTRAINT [DF__OUTSVSPR__OUTCQT__5007AB49] DEFAULT ((0)) NOT NULL,
    [PRICECH]    NUMERIC (13, 5) CONSTRAINT [DF__OUTSVSPR__PRICEC__50FBCF82] DEFAULT ((0)) NOT NULL,
    [MARGIN]     NUMERIC (6, 2)  CONSTRAINT [DF__OUTSVSPR__MARGIN__51EFF3BB] DEFAULT ((0)) NOT NULL,
    [CHARGE]     NUMERIC (13, 5) CONSTRAINT [DF__OUTSVSPR__CHARGE__52E417F4] DEFAULT ((0)) NOT NULL,
    [OUTSVSPRUK] CHAR (10)       CONSTRAINT [DF__OUTSVSPR__OUTSVS__53D83C2D] DEFAULT ('') NOT NULL,
    CONSTRAINT [OUTSVSPR_PK] PRIMARY KEY CLUSTERED ([OUTSVSPRUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OUTCQTY]
    ON [dbo].[OUTSVSPR]([OUTCQTY] ASC);


GO
CREATE NONCLUSTERED INDEX [SVSKEY]
    ON [dbo].[OUTSVSPR]([SVSKEY] ASC);

