CREATE TABLE [dbo].[OUTSVS] (
    [UNIQ_KEY]   CHAR (10)   CONSTRAINT [DF__OUTSVS__UNIQ_KEY__467E410F] DEFAULT ('') NOT NULL,
    [DEPT_ID]    CHAR (4)    CONSTRAINT [DF__OUTSVS__DEPT_ID__47726548] DEFAULT ('') NOT NULL,
    [SUPID]      CHAR (10)   CONSTRAINT [DF__OUTSVS__SUPID__48668981] DEFAULT ('') NOT NULL,
    [SVSKEY]     CHAR (10)   CONSTRAINT [DF__OUTSVS__SVSKEY__495AADBA] DEFAULT ('') NOT NULL,
    [LTIME]      NUMERIC (2) CONSTRAINT [DF__OUTSVS__LTIME__4A4ED1F3] DEFAULT ((0)) NOT NULL,
    [PREFERNO]   NUMERIC (2) CONSTRAINT [DF__OUTSVS__PREFERNO__4B42F62C] DEFAULT ((0)) NOT NULL,
    [UNIQNUMBER] CHAR (10)   CONSTRAINT [DF__OUTSVS__UNIQNUMB__4C371A65] DEFAULT ('') NOT NULL,
    CONSTRAINT [OUTSVS_PK] PRIMARY KEY CLUSTERED ([SVSKEY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEPT_ID]
    ON [dbo].[OUTSVS]([DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [SUPID]
    ON [dbo].[OUTSVS]([SUPID] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_DEPT]
    ON [dbo].[OUTSVS]([UNIQ_KEY] ASC, [UNIQNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[OUTSVS]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQNUMBER]
    ON [dbo].[OUTSVS]([UNIQNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQSUPID]
    ON [dbo].[OUTSVS]([UNIQ_KEY] ASC, [SUPID] ASC, [UNIQNUMBER] ASC);


GO
-- =============================================
-- Author:		Vicky Lu
-- Create date: 04/30/2010
-- Description:	Run after OutSvs record is deleted
-- =============================================
CREATE TRIGGER [dbo].[OutSvs_Delete]
   ON  [dbo].[OutSvs]
   AFTER DELETE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	BEGIN TRANSACTION 
	DELETE FROM OutSvsPr WHERE SvsKey IN (SELECT SvsKey FROM DELETED)
	COMMIT

END
