CREATE TABLE [dbo].[PACKLSER] (
    [UKPACKLSER]  CHAR (10)     CONSTRAINT [DF__PACKLSER__UKPACK__56B4A8D8] DEFAULT ('') NOT NULL,
    [PACKLISTNO]  CHAR (10)     CONSTRAINT [DF__PACKLSER__PACKLI__57A8CD11] DEFAULT ('') NOT NULL,
    [SERIALNO]    NVARCHAR (30) CONSTRAINT [DF__PACKLSER__SERIAL__589CF14A] DEFAULT ('') NOT NULL,
    [UNIQUELN]    CHAR (10)     CONSTRAINT [DF__PACKLSER__UNIQUE__59911583] DEFAULT ('') NOT NULL,
    [WONO]        CHAR (10)     CONSTRAINT [DF__PACKLSER__WONO__5A8539BC] DEFAULT ('') NOT NULL,
    [SERIALUNIQ]  CHAR (10)     CONSTRAINT [DF__PACKLSER__SERIAL__5B795DF5] DEFAULT ('') NOT NULL,
    [IS_ARC]      BIT           CONSTRAINT [DF__PACKLSER__IS_ARC__5C6D822E] DEFAULT ((0)) NOT NULL,
    [UNIQ_ALLOC]  CHAR (10)     CONSTRAINT [DF__PACKLSER__UNIQ_A__5D61A667] DEFAULT ('') NOT NULL,
    [UKPKINVLOT]  CHAR (10)     CONSTRAINT [DF__PACKLSER__UKPKIN__5E55CAA0] DEFAULT ('') NOT NULL,
    [IPKEYUNIQUE] CHAR (10)     NULL,
    CONSTRAINT [PACKLSER_PK] PRIMARY KEY CLUSTERED ([UKPACKLSER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PKNO_UKLN]
    ON [dbo].[PACKLSER]([PACKLISTNO] ASC, [UNIQUELN] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [PKSERUNIQ]
    ON [dbo].[PACKLSER]([PACKLISTNO] ASC, [SERIALUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [PKWOSERIAL]
    ON [dbo].[PACKLSER]([PACKLISTNO] ASC, [WONO] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIAL]
    ON [dbo].[PACKLSER]([SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [SERIALNO]
    ON [dbo].[PACKLSER]([WONO] ASC, [SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UKPKINVLOT]
    ON [dbo].[PACKLSER]([UKPKINVLOT] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_ALLOC]
    ON [dbo].[PACKLSER]([UNIQ_ALLOC] ASC);

