CREATE TABLE [dbo].[PARTTYPE] (
    [UNIQPTYPE]          CHAR (10)       CONSTRAINT [DF__PARTTYPE__UNIQPT__6132374B] DEFAULT ([dbo].[fn_generateuniquenumber]()) NOT NULL,
    [PART_CLASS]         CHAR (8)        CONSTRAINT [DF__PARTTYPE__PART_C__62265B84] DEFAULT ('') NOT NULL,
    [PART_TYPE]          CHAR (8)        CONSTRAINT [DF__PARTTYPE__PART_T__631A7FBD] DEFAULT ('') NOT NULL,
    [PREFIX]             CHAR (20)       CONSTRAINT [DF__PARTTYPE__PREFIX__640EA3F6] DEFAULT ('') NOT NULL,
    [TEMPLATE]           NVARCHAR (100)  CONSTRAINT [DF__PARTTYPE__TEMPLA__6502C82F] DEFAULT ('') NOT NULL,
    [PART_PKG]           CHAR (6)        CONSTRAINT [DF__PARTTYPE__PART_P__65F6EC68] DEFAULT ('') NOT NULL,
    [U_OF_MEAS]          CHAR (4)        CONSTRAINT [DF__PARTTYPE__U_OF_M__66EB10A1] DEFAULT ('') NOT NULL,
    [PUR_UOFM]           CHAR (4)        CONSTRAINT [DF__PARTTYPE__PUR_UO__67DF34DA] DEFAULT ('') NOT NULL,
    [ORD_POLICY]         CHAR (12)       CONSTRAINT [DF__PARTTYPE__ORD_PO__68D35913] DEFAULT ('') NOT NULL,
    [PACKAGE]            CHAR (15)       CONSTRAINT [DF__PARTTYPE__PACKAG__69C77D4C] DEFAULT ('') NOT NULL,
    [BUYER_TYPE]         CHAR (3)        CONSTRAINT [DF__PARTTYPE__BUYER___6ABBA185] DEFAULT ('') NOT NULL,
    [REORDPOINT]         NUMERIC (7)     CONSTRAINT [DF__PARTTYPE__REORDP__6BAFC5BE] DEFAULT ((0)) NOT NULL,
    [MINORD]             NUMERIC (7)     CONSTRAINT [DF__PARTTYPE__MINORD__6CA3E9F7] DEFAULT ((0)) NOT NULL,
    [ORDMULT]            NUMERIC (7)     CONSTRAINT [DF__PARTTYPE__ORDMUL__6D980E30] DEFAULT ((0)) NOT NULL,
    [ABC]                CHAR (1)        CONSTRAINT [DF__PARTTYPE__ABC__6E8C3269] DEFAULT ('') NOT NULL,
    [REORDERQTY]         NUMERIC (7)     CONSTRAINT [DF__PARTTYPE__REORDE__6F8056A2] DEFAULT ((0)) NOT NULL,
    [INSP_REQ]           BIT             CONSTRAINT [DF__PARTTYPE__INSP_R__70747ADB] DEFAULT ((0)) NOT NULL,
    [CERT_REQ]           BIT             CONSTRAINT [DF__PARTTYPE__CERT_R__71689F14] DEFAULT ((0)) NOT NULL,
    [CERT_TYPE]          CHAR (10)       CONSTRAINT [DF__PARTTYPE__CERT_T__725CC34D] DEFAULT ('') NOT NULL,
    [SCRAP]              NUMERIC (6, 2)  CONSTRAINT [DF__PARTTYPE__SCRAP__7350E786] DEFAULT ((0)) NOT NULL,
    [SETUPSCRAP]         NUMERIC (4)     CONSTRAINT [DF__PARTTYPE__SETUPS__74450BBF] DEFAULT ((0)) NOT NULL,
    [LOC_TYPE]           CHAR (10)       CONSTRAINT [DF__PARTTYPE__LOC_TY__75392FF8] DEFAULT ('') NOT NULL,
    [NUMBER]             NUMERIC (4)     CONSTRAINT [DF__PARTTYPE__NUMBER__762D5431] DEFAULT ((0)) NOT NULL,
    [PUR_LTIME]          NUMERIC (3)     CONSTRAINT [DF__PARTTYPE__PUR_LT__7721786A] DEFAULT ((0)) NOT NULL,
    [PUR_LUNIT]          CHAR (2)        CONSTRAINT [DF__PARTTYPE__PUR_LU__78159CA3] DEFAULT ('') NOT NULL,
    [KIT_LTIME]          NUMERIC (3)     CONSTRAINT [DF__PARTTYPE__KIT_LT__7909C0DC] DEFAULT ((0)) NOT NULL,
    [KIT_LUNIT]          CHAR (2)        CONSTRAINT [DF__PARTTYPE__KIT_LU__79FDE515] DEFAULT ('') NOT NULL,
    [PROD_LTIME]         NUMERIC (3)     CONSTRAINT [DF__PARTTYPE__PROD_L__7AF2094E] DEFAULT ((0)) NOT NULL,
    [PROD_LUNIT]         CHAR (2)        CONSTRAINT [DF__PARTTYPE__PROD_L__7BE62D87] DEFAULT ('') NOT NULL,
    [PULL_IN]            NUMERIC (3)     CONSTRAINT [DF__PARTTYPE__PULL_I__7CDA51C0] DEFAULT ((0)) NOT NULL,
    [PUSH_OUT]           NUMERIC (3)     CONSTRAINT [DF__PARTTYPE__PUSH_O__7DCE75F9] DEFAULT ((0)) NOT NULL,
    [ORD_FREQ]           CHAR (12)       CONSTRAINT [DF__PARTTYPE__ORD_FR__7EC29A32] DEFAULT ('') NOT NULL,
    [DAY]                NUMERIC (1)     CONSTRAINT [DF__PARTTYPE__DAY__7FB6BE6B] DEFAULT ((0)) NOT NULL,
    [DAYOFMO]            NUMERIC (2)     CONSTRAINT [DF__PARTTYPE__DAYOFM__00AAE2A4] DEFAULT ((0)) NOT NULL,
    [DAYOFMO2]           NUMERIC (2)     CONSTRAINT [DF__PARTTYPE__DAYOFM__019F06DD] DEFAULT ((0)) NOT NULL,
    [LOTDETAIL]          BIT             CONSTRAINT [DF__PARTTYPE__LOTDET__02932B16] DEFAULT ((0)) NOT NULL,
    [AUTODT]             BIT             CONSTRAINT [DF__PARTTYPE__AUTODT__03874F4F] DEFAULT ((0)) NOT NULL,
    [FGIEXPDAYS]         NUMERIC (4)     CONSTRAINT [DF__PARTTYPE__FGIEXP__047B7388] DEFAULT ((0)) NOT NULL,
    [STDCOST]            NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__STDCOS__056F97C1] DEFAULT ((0)) NOT NULL,
    [MATL_COST]          NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__MATL_C__0663BBFA] DEFAULT ((0)) NOT NULL,
    [LABORCOST]          NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__LABORC__0757E033] DEFAULT ((0)) NOT NULL,
    [OTHER_COST]         NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__OTHER___084C046C] DEFAULT ((0)) NOT NULL,
    [OVERHEAD]           NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__OVERHE__094028A5] DEFAULT ((0)) NOT NULL,
    [AUTONUM]            BIT             CONSTRAINT [DF__PARTTYPE__AUTONU__0A344CDE] DEFAULT ((0)) NOT NULL,
    [MRC]                CHAR (15)       CONSTRAINT [DF__PARTTYPE__MRC__0B287117] DEFAULT ('') NOT NULL,
    [AUTOLOCATION]       BIT             CONSTRAINT [DF__PARTTYPE__AUTOLO__0C1C9550] DEFAULT ((0)) NOT NULL,
    [OTHERCOST2]         NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__OTHERC__0D10B989] DEFAULT ((0)) NOT NULL,
    [TARGETPRICE]        NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__TARGET__0E04DDC2] DEFAULT ((0)) NOT NULL,
    [IsSynchronizedFlag] BIT             CONSTRAINT [DF__PARTTYPE__IsSync__76A4B782] DEFAULT ((0)) NULL,
    [taxable]            BIT             CONSTRAINT [DF_PARTTYPE_taxable] DEFAULT ((0)) NOT NULL,
    [lblSize]            VARCHAR (50)    CONSTRAINT [DF_PARTTYPE_lblSize] DEFAULT ('') NOT NULL,
    [STDCOSTPR]          NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__STDCOS__30E73307] DEFAULT ((0)) NOT NULL,
    [dept_id]            NVARCHAR (4)    CONSTRAINT [DF_PARTTYPE_dept_id] DEFAULT ('') NOT NULL,
    [MATL_COSTPR]        NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__MATL_C__7082952F] DEFAULT ((0)) NOT NULL,
    [LABORCOSTPR]        NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__LABORC__7176B968] DEFAULT ((0)) NOT NULL,
    [OTHER_COSTPR]       NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__OTHER___726ADDA1] DEFAULT ((0)) NOT NULL,
    [OVERHEADPR]         NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__OVERHE__735F01DA] DEFAULT ((0)) NOT NULL,
    [TARGETPRICEPR]      NUMERIC (13, 5) CONSTRAINT [DF__PARTTYPE__TARGET__74532613] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]      CHAR (10)       CONSTRAINT [DF__PARTTYPE__PRFCUS__75474A4C] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ]    CHAR (10)       CONSTRAINT [DF__PARTTYPE__FUNCFC__763B6E85] DEFAULT ('') NOT NULL,
    [Location]           NVARCHAR (200)  CONSTRAINT [DF__PARTTYPE__Locati__437AE48E] DEFAULT ('') NOT NULL,
    [UniqAisle]          VARCHAR (20)    CONSTRAINT [DF__PARTTYPE__UniqAi__446F08C7] DEFAULT ('') NOT NULL,
    [UniqRack]           VARCHAR (20)    CONSTRAINT [DF__PARTTYPE__UniqRa__45632D00] DEFAULT ('') NOT NULL,
    [UniqShelf]          VARCHAR (20)    CONSTRAINT [DF__PARTTYPE__UniqSh__46575139] DEFAULT ('') NOT NULL,
    [UseCustPFX]         BIT             CONSTRAINT [DF__PARTTYPE__UseCus__1FFC9E27] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PARTTYPE_PK] PRIMARY KEY CLUSTERED ([UNIQPTYPE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CLASSNUMB]
    ON [dbo].[PARTTYPE]([PART_CLASS] ASC, [NUMBER] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CLASSTYPE]
    ON [dbo].[PARTTYPE]([PART_CLASS] ASC, [PART_TYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [PART_CLASS]
    ON [dbo].[PARTTYPE]([PART_CLASS] ASC);


GO
CREATE NONCLUSTERED INDEX [PART_TYPE]
    ON [dbo].[PARTTYPE]([PART_TYPE] ASC);


GO
-- =============================================
-- Author:		Sachin Shevale
-- Create date: 10/28/2015
-- Description:	Update trigger for IsSynchronization flag
-- =============================================
CREATE TRIGGER [dbo].[PartType_UPDATE]
   ON  dbo.PARTTYPE
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	UPDATE PartType SET		
	  IsSynchronizedFlag= CASE WHEN (I.IsSynchronizedFlag = 1 and D.IsSynchronizedFlag = 1) 		
								THEN 0
						       WHEN (I.IsSynchronizedFlag = 1 and D.IsSynchronizedFlag = 0) THEN 1					 
						ELSE 0 END						
	 FROM inserted I inner join deleted D on i.UNIQPTYPE=d.UNIQPTYPE
	 where I.UNIQPTYPE = PartType.UNIQPTYPE
				     
			IF EXISTS (SELECT 1 FROM inserted where IsSynchronizedFlag=0)
			BEGIN
			DELETE FROM SynchronizationMultiLocationLog 
				where EXISTS (Select 1 from Inserted where IsSynchronizedFlag=0 and Inserted.UNIQPTYPE=SynchronizationMultiLocationLog.Uniquenum);
			END									 
END
GO
-- =============================================
-- Author:	sachin s
-- Create date: 10-30-2015
-- Description:	Insert the records in to the SynchronizationDeletedRecords tables for synchronization
 
-- =============================================
CREATE TRIGGER [dbo].[PartType_delete] 
   ON dbo.PARTTYPE
   AFTER DELETE
AS 
BEGIN
	 --Sachins s-Insert the records in to the SynchronizationDeletedRecords tables
	INSERT INTO [dbo].[SynchronizationDeletedRecords]
           ([TableName]
           ,[TableKey]
           ,[TableKeyValue])
     SELECT
           'PartType'
           ,'UNIQPTYPE'
           ,Deleted.UNIQPTYPE from Deleted
		    
		   
END
