CREATE TABLE [dbo].[PCONTACT] (
    [CID]        CHAR (10) CONSTRAINT [DF__PCONTACT__CID__10E14A6D] DEFAULT ('') NOT NULL,
    [LASTNAME]   CHAR (15) CONSTRAINT [DF__PCONTACT__LASTNA__11D56EA6] DEFAULT ('') NOT NULL,
    [FIRSTNAME]  CHAR (15) CONSTRAINT [DF__PCONTACT__FIRSTN__12C992DF] DEFAULT ('') NOT NULL,
    [CUSTNO]     CHAR (10) CONSTRAINT [DF__PCONTACT__CUSTNO__13BDB718] DEFAULT ('') NOT NULL,
    [TITLE]      CHAR (20) CONSTRAINT [DF__PCONTACT__TITLE__14B1DB51] DEFAULT ('') NOT NULL,
    [WORKPHONE]  CHAR (19) CONSTRAINT [DF__PCONTACT__WORKPH__15A5FF8A] DEFAULT ('') NOT NULL,
    [EMAIL]      CHAR (50) CONSTRAINT [DF__PCONTACT__EMAIL__169A23C3] DEFAULT ('') NOT NULL,
    [CONTACTFAX] CHAR (19) CONSTRAINT [DF__PCONTACT__CONTAC__178E47FC] DEFAULT ('') NOT NULL,
    CONSTRAINT [PCONTACT_PK] PRIMARY KEY CLUSTERED ([CID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[PCONTACT]([CUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [LASTNAME]
    ON [dbo].[PCONTACT]([LASTNAME] ASC);

