CREATE TABLE [dbo].[PHYHDTL] (
    [UNIQPIHEAD] CHAR (10) CONSTRAINT [DF__PHYHDTL__UNIQPIH__1A6AB4A7] DEFAULT ('') NOT NULL,
    [UNIQPIHDTL] CHAR (10) CONSTRAINT [DF__PHYHDTL__UNIQPIH__1B5ED8E0] DEFAULT ('') NOT NULL,
    [PART_CLASS] CHAR (8)  CONSTRAINT [DF__PHYHDTL__PART_CL__1D472152] DEFAULT ('') NOT NULL,
    [uniqwh]     CHAR (10) CONSTRAINT [DF__PHYHDTL__WHNO__1C52FD19] DEFAULT ('') NOT NULL,
    CONSTRAINT [PHYHDTL_PK] PRIMARY KEY CLUSTERED ([UNIQPIHDTL] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQPIHEAD]
    ON [dbo].[PHYHDTL]([UNIQPIHEAD] ASC);

