CREATE TABLE [dbo].[PHYINVTH] (
    [UNIQPIHEAD]      CHAR (10)        CONSTRAINT [DF__PHYINVTH__UNIQPI__2F65D18D] DEFAULT ('') NOT NULL,
    [INVTTYPE]        NUMERIC (1)      CONSTRAINT [DF__PHYINVTH__INVTTY__3059F5C6] DEFAULT ((0)) NOT NULL,
    [DETAILNAME]      CHAR (30)        CONSTRAINT [DF__PHYINVTH__DETAIL__314E19FF] DEFAULT ('') NOT NULL,
    [DETAILNO]        CHAR (10)        CONSTRAINT [DF__PHYINVTH__DETAIL__32423E38] DEFAULT ('') NOT NULL,
    [STARTNO]         CHAR (25)        CONSTRAINT [DF__PHYINVTH__STARTN__33366271] DEFAULT ('') NULL,
    [ENDNO]           CHAR (25)        CONSTRAINT [DF__PHYINVTH__ENDNO__342A86AA] DEFAULT ('') NULL,
    [STARTTIME]       SMALLDATETIME    CONSTRAINT [DF__PHYINVTH__STARTT__351EAAE3] DEFAULT ((0)) NULL,
    [PISTATUS]        CHAR (10)        CONSTRAINT [DF__PHYINVTH__PISTAT__3612CF1C] DEFAULT ('') NOT NULL,
    [CXLREASON]       TEXT             CONSTRAINT [DF__PHYINVTH__CXLREA__3706F355] DEFAULT ('') NOT NULL,
    [CXLINIT]         CHAR (8)         CONSTRAINT [DF__PHYINVTH__CXLINI__37FB178E] DEFAULT ('') NULL,
    [CXLDATE]         SMALLDATETIME    NULL,
    [CXLuserId]       UNIQUEIDENTIFIER NULL,
    [CountType]       CHAR (1)         CONSTRAINT [DF_PHYINVTH_CountType] DEFAULT ('P') NOT NULL,
    [instanceName]    VARCHAR (100)    CONSTRAINT [DF_PHYINVTH_instanceName] DEFAULT ('') NOT NULL,
    [instanceOwnerid] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PHYINVTH_PK] PRIMARY KEY CLUSTERED ([UNIQPIHEAD] ASC)
);

