CREATE TABLE [dbo].[PHYINVTSER] (
    [PHSERUNIQUE] CHAR (10) CONSTRAINT [DF__PHYINVTSE__PHSER__3AD78439] DEFAULT ('') NOT NULL,
    [UNIQPHYNO]   CHAR (10) CONSTRAINT [DF__PHYINVTSE__UNIQP__3BCBA872] DEFAULT ('') NOT NULL,
    [SERIALNO]    CHAR (30) CONSTRAINT [DF__PHYINVTSE__SERIA__3CBFCCAB] DEFAULT ('') NOT NULL,
    [UNIQMFGRHD]  CHAR (10) CONSTRAINT [DF__PHYINVTSE__UNIQM__3DB3F0E4] DEFAULT ('') NOT NULL,
    [UNIQPIHEAD]  CHAR (10) CONSTRAINT [DF__PHYINVTSE__UNIQP__70DF5A86] DEFAULT ('') NOT NULL,
    CONSTRAINT [PHYINVTSER_PK] PRIMARY KEY CLUSTERED ([PHSERUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SERIALNO]
    ON [dbo].[PHYINVTSER]([SERIALNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRHD]
    ON [dbo].[PHYINVTSER]([UNIQMFGRHD] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQPHYNO]
    ON [dbo].[PHYINVTSER]([UNIQPHYNO] ASC);

