CREATE TABLE [dbo].[PHYTRANS] (
    [UNIQPIHEAD]      CHAR (10)       CONSTRAINT [DF__PHYTRANS__UNIQPI__40905D8F] DEFAULT ('') NOT NULL,
    [UNIQPITRAN]      CHAR (10)       CONSTRAINT [DF__PHYTRANS__UNIQPI__418481C8] DEFAULT ('') NOT NULL,
    [W_KEY]           CHAR (10)       CONSTRAINT [DF__PHYTRANS__W_KEY__4278A601] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]        CHAR (10)       CONSTRAINT [DF__PHYTRANS__UNIQ_K__436CCA3A] DEFAULT ('') NOT NULL,
    [DATE]            SMALLDATETIME   NULL,
    [GL_NBR]          CHAR (13)       CONSTRAINT [DF__PHYTRANS__GL_NBR__4460EE73] DEFAULT ('') NOT NULL,
    [GL_NBR_INV]      CHAR (13)       CONSTRAINT [DF__PHYTRANS__GL_NBR__455512AC] DEFAULT ('') NOT NULL,
    [STDCOST]         NUMERIC (13, 5) CONSTRAINT [DF__PHYTRANS__STDCOS__464936E5] DEFAULT ((0)) NOT NULL,
    [LOTCODE]         NVARCHAR (25)   CONSTRAINT [DF__PHYTRANS__LOTCOD__473D5B1E] DEFAULT ('') NOT NULL,
    [EXPDATE]         SMALLDATETIME   NULL,
    [REFERENCE]       CHAR (12)       CONSTRAINT [DF__PHYTRANS__REFERE__48317F57] DEFAULT ('') NOT NULL,
    [SAVEINIT]        CHAR (8)        CONSTRAINT [DF__PHYTRANS__SAVEIN__4925A390] DEFAULT ('') NULL,
    [SAVETIME]        CHAR (5)        CONSTRAINT [DF__PHYTRANS__SAVETI__4A19C7C9] DEFAULT ('') NOT NULL,
    [REASON]          CHAR (20)       CONSTRAINT [DF__PHYTRANS__REASON__4B0DEC02] DEFAULT ('') NOT NULL,
    [ADJ_QTY]         NUMERIC (10, 2) CONSTRAINT [DF__PHYTRANS__ADJ_QT__4C02103B] DEFAULT ((0)) NOT NULL,
    [PONUM]           CHAR (15)       CONSTRAINT [DF__PHYTRANS__PONUM__4CF63474] DEFAULT ('') NOT NULL,
    [UNIQ_LOT]        CHAR (10)       CONSTRAINT [DF__PHYTRANS__UNIQ_L__4DEA58AD] DEFAULT ('') NOT NULL,
    [STDCOSTPR]       NUMERIC (13, 5) CONSTRAINT [DF__PHYTRANS__STDCOS__2B2E59B1] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__PHYTRANS__PRFCUS__02A1456A] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__PHYTRANS__FUNCFC__039569A3] DEFAULT ('') NOT NULL,
    CONSTRAINT [PHYTRANS_PK] PRIMARY KEY CLUSTERED ([UNIQPITRAN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQPIHEAD]
    ON [dbo].[PHYTRANS]([UNIQPIHEAD] ASC);

