CREATE TABLE [dbo].[PJCTMAIN] (
    [PRJUNIQUE]  CHAR (10)     CONSTRAINT [DF__PJCTMAIN__PRJUNI__50C6C558] DEFAULT ('') NOT NULL,
    [PRJNUMBER]  CHAR (10)     CONSTRAINT [DF__PJCTMAIN__PRJNUM__51BAE991] DEFAULT ('') NOT NULL,
    [CUSTNO]     CHAR (10)     CONSTRAINT [DF__PJCTMAIN__CUSTNO__52AF0DCA] DEFAULT ('') NOT NULL,
    [PRJDESCRP]  CHAR (50)     CONSTRAINT [DF__PJCTMAIN__PRJDES__53A33203] DEFAULT ('') NOT NULL,
    [PRJREFERNO] CHAR (50)     CONSTRAINT [DF__PJCTMAIN__PRJREF__5497563C] DEFAULT ('') NOT NULL,
    [PRJGENDT]   SMALLDATETIME NULL,
    [PRJCOMPLD]  SMALLDATETIME NULL,
    [PRJPARUNIQ] CHAR (10)     CONSTRAINT [DF__PJCTMAIN__PRJPAR__558B7A75] DEFAULT ('') NOT NULL,
    [PRJSTATUS]  CHAR (10)     CONSTRAINT [DF__PJCTMAIN__PRJSTA__567F9EAE] DEFAULT ('') NOT NULL,
    [PRJNOTE]    TEXT          CONSTRAINT [DF__PJCTMAIN__PRJNOT__5773C2E7] DEFAULT ('') NOT NULL,
    CONSTRAINT [PJCTMAIN_PK] PRIMARY KEY CLUSTERED ([PRJUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[PJCTMAIN]([CUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [PRJCOMPLD]
    ON [dbo].[PJCTMAIN]([PRJCOMPLD] ASC);


GO
CREATE NONCLUSTERED INDEX [PRJNO4CUST]
    ON [dbo].[PJCTMAIN]([CUSTNO] ASC, [PRJNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [PRJNUMBER]
    ON [dbo].[PJCTMAIN]([PRJNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [PRJPARUNIQ]
    ON [dbo].[PJCTMAIN]([PRJPARUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [PRJSTATUS]
    ON [dbo].[PJCTMAIN]([PRJSTATUS] ASC);

