CREATE TABLE [dbo].[PKALLOC] (
    [PACKLISTNO] CHAR (10)      CONSTRAINT [DF__PKALLOC__PACKLIS__5A502F92] DEFAULT ('') NOT NULL,
    [UNIQUELN]   CHAR (10)      CONSTRAINT [DF__PKALLOC__UNIQUEL__5B4453CB] DEFAULT ('') NOT NULL,
    [W_KEY]      CHAR (10)      CONSTRAINT [DF__PKALLOC__W_KEY__5C387804] DEFAULT ('') NOT NULL,
    [ALLOCQTY]   NUMERIC (9, 2) CONSTRAINT [DF__PKALLOC__ALLOCQT__5D2C9C3D] DEFAULT ((0)) NOT NULL,
    [UOM]        CHAR (4)       CONSTRAINT [DF__PKALLOC__UOM__5E20C076] DEFAULT ('') NOT NULL,
    [UNIQ_ALLOC] CHAR (10)      CONSTRAINT [DF__PKALLOC__UNIQ_AL__5F14E4AF] DEFAULT ('') NOT NULL,
    CONSTRAINT [PKALLOC_PK] PRIMARY KEY CLUSTERED ([UNIQ_ALLOC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PKNOUKLNWK]
    ON [dbo].[PKALLOC]([PACKLISTNO] ASC, [UNIQUELN] ASC, [W_KEY] ASC);

