CREATE TABLE [dbo].[PKINVLOT] (
    [UKPKINVLOT] CHAR (10)       CONSTRAINT [DF__PKINVLOT__UKPKIN__74100195] DEFAULT ('') NOT NULL,
    [UNIQ_ALLOC] CHAR (10)       CONSTRAINT [DF__PKINVLOT__UNIQ_A__750425CE] DEFAULT ('') NOT NULL,
    [W_KEY]      CHAR (10)       CONSTRAINT [DF__PKINVLOT__W_KEY__75F84A07] DEFAULT ('') NOT NULL,
    [LOTCODE]    NVARCHAR (25)   CONSTRAINT [DF__PKINVLOT__LOTCOD__76EC6E40] DEFAULT ('') NOT NULL,
    [EXPDATE]    SMALLDATETIME   NULL,
    [REFERENCE]  CHAR (12)       CONSTRAINT [DF__PKINVLOT__REFERE__77E09279] DEFAULT ('') NOT NULL,
    [PONUM]      CHAR (15)       CONSTRAINT [DF__PKINVLOT__PONUM__78D4B6B2] DEFAULT ('') NOT NULL,
    [ALLOCQTY]   NUMERIC (12, 2) CONSTRAINT [DF__PKINVLOT__ALLOCQ__79C8DAEB] DEFAULT ((0)) NOT NULL,
    [packlistno] CHAR (10)       CONSTRAINT [DF_PKINVLOT_packlistno] DEFAULT ('') NOT NULL,
    CONSTRAINT [PKINVLOT_PK] PRIMARY KEY CLUSTERED ([UKPKINVLOT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQ_ALLOC]
    ON [dbo].[PKINVLOT]([UNIQ_ALLOC] ASC);


GO
CREATE NONCLUSTERED INDEX [UNQWKEYLOT]
    ON [dbo].[PKINVLOT]([UNIQ_ALLOC] ASC, [W_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [W_KEYLOT]
    ON [dbo].[PKINVLOT]([W_KEY] ASC, [LOTCODE] ASC, [EXPDATE] ASC, [REFERENCE] ASC, [PONUM] ASC);

