CREATE TABLE [dbo].[PLADJ] (
    [PACKLISTNO]  CHAR (10)        CONSTRAINT [DF__PLADJ__PACKLISTN__7CA54796] DEFAULT ('') NOT NULL,
    [UNIQUELN]    CHAR (10)        CONSTRAINT [DF__PLADJ__UNIQUELN__7D996BCF] DEFAULT ('') NOT NULL,
    [SAVEDDATE]   DATETIME         NULL,
    [SHIPPEDQTY]  NUMERIC (7)      CONSTRAINT [DF__PLADJ__SHIPPEDQT__7E8D9008] DEFAULT ((0)) NOT NULL,
    [PLADJUNIQUE] CHAR (10)        CONSTRAINT [DF__PLADJ__PLADJUNIQ__7F81B441] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [AdjustQty]   NUMERIC (7)      CONSTRAINT [DF_PLADJ_AdjustQty] DEFAULT ((0)) NOT NULL,
    [fk_userId]   UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PLADJ_PK] PRIMARY KEY CLUSTERED ([PLADJUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PACKLISTNO]
    ON [dbo].[PLADJ]([PACKLISTNO] ASC);

