CREATE TABLE [dbo].[PODEFAUTOPRICE] (
    [CMETHODNM]  CHAR (35) CONSTRAINT [DF__PODEFAUTO__CMETH__0040CE50] DEFAULT ('') NOT NULL,
    [NSEQNUMBER] INT       CONSTRAINT [DF__PODEFAUTO__NSEQN__0134F289] DEFAULT ((0)) NOT NULL,
    [CUNIQMETH]  CHAR (10) CONSTRAINT [DF__PODEFAUTO__CUNIQ__022916C2] DEFAULT ('') NOT NULL,
    CONSTRAINT [PODEFAUTOPRICE_PK] PRIMARY KEY CLUSTERED ([CUNIQMETH] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CMETHODNM]
    ON [dbo].[PODEFAUTOPRICE]([CMETHODNM] ASC);


GO
CREATE NONCLUSTERED INDEX [SEQUENCE]
    ON [dbo].[PODEFAUTOPRICE]([NSEQNUMBER] ASC);

