CREATE TABLE [dbo].[POITEMSTAX] (
    [UNIQPOITEMSTAX] CHAR (10)      CONSTRAINT [DF__POITEMSTA__UNIQP__7DB01116] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [PONUM]          CHAR (15)      CONSTRAINT [DF__POITEMSTA__PONUM__7EA4354F] DEFAULT ('') NOT NULL,
    [UNIQLNNO]       CHAR (10)      CONSTRAINT [DF__POITEMSTA__UNIQL__7F985988] DEFAULT ('') NOT NULL,
    [TAX_ID]         CHAR (8)       CONSTRAINT [DF__POITEMSTA__TAX_I__008C7DC1] DEFAULT ('') NOT NULL,
    [TAX_RATE]       NUMERIC (8, 4) CONSTRAINT [DF__POITEMSTA__TAX_R__0180A1FA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__POITEMST__E11792697BC7C8A4] PRIMARY KEY CLUSTERED ([UNIQPOITEMSTAX] ASC)
);

