CREATE TABLE [dbo].[PORECMRB] (
    [TRANSNO]       NUMERIC (8)     CONSTRAINT [DF__PORECMRB__TRANSN__347F8C65] DEFAULT ((0)) NOT NULL,
    [DMR_NO]        CHAR (10)       CONSTRAINT [DF__PORECMRB__DMR_NO__3573B09E] DEFAULT ('') NOT NULL,
    [RMA_NO]        CHAR (15)       CONSTRAINT [DF__PORECMRB__RMA_NO__3667D4D7] DEFAULT ('') NOT NULL,
    [RET_QTY]       NUMERIC (10, 2) CONSTRAINT [DF__PORECMRB__RET_QT__375BF910] DEFAULT ((0)) NOT NULL,
    [CONFIRMBY]     CHAR (30)       CONSTRAINT [DF__PORECMRB__CONFIR__38501D49] DEFAULT ('') NOT NULL,
    [INITIAL]       CHAR (8)        CONSTRAINT [DF__PORECMRB__INITIA__39444182] DEFAULT ('') NULL,
    [REJ_DATE]      SMALLDATETIME   NULL,
    [RMA_DATE]      SMALLDATETIME   NULL,
    [DMRPLNO]       CHAR (10)       CONSTRAINT [DF__PORECMRB__DMRPLN__3A3865BB] DEFAULT ('') NOT NULL,
    [SHIPVIA]       CHAR (15)       CONSTRAINT [DF__PORECMRB__SHIPVI__3B2C89F4] DEFAULT ('') NOT NULL,
    [SHIPCHARGE]    CHAR (15)       CONSTRAINT [DF__PORECMRB__SHIPCH__3C20AE2D] DEFAULT ('') NOT NULL,
    [FOB]           CHAR (15)       CONSTRAINT [DF__PORECMRB__FOB__3D14D266] DEFAULT ('') NOT NULL,
    [TERMS]         CHAR (15)       CONSTRAINT [DF__PORECMRB__TERMS__3E08F69F] DEFAULT ('') NOT NULL,
    [FREIGHTAMT]    CHAR (15)       CONSTRAINT [DF__PORECMRB__FREIGH__3EFD1AD8] DEFAULT ('') NOT NULL,
    [WAYBILL]       CHAR (20)       CONSTRAINT [DF__PORECMRB__WAYBIL__3FF13F11] DEFAULT ('') NOT NULL,
    [LINKADD]       CHAR (10)       CONSTRAINT [DF__PORECMRB__LINKAD__40E5634A] DEFAULT ('') NOT NULL,
    [FK_UNIQRECDTL] CHAR (10)       CONSTRAINT [DF__PORECMRB__FK_UNI__41D98783] DEFAULT ('') NOT NULL,
    [DMRUNIQUE]     CHAR (10)       CONSTRAINT [DF__PORECMRB__DMRUNI__42CDABBC] DEFAULT ('') NOT NULL,
    [PRINTDMR]      BIT             CONSTRAINT [DF__PORECMRB__PRINTD__43C1CFF5] DEFAULT ((0)) NOT NULL,
    [DMR_DATE]      SMALLDATETIME   NULL,
    [dmrNote]       VARCHAR (MAX)   CONSTRAINT [DF_PORECMRB_dmrNote] DEFAULT ('') NOT NULL,
    CONSTRAINT [PORECMRB_PK] PRIMARY KEY CLUSTERED ([DMRUNIQUE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DMR]
    ON [dbo].[PORECMRB]([TRANSNO] ASC, [DMR_NO] ASC, [DMRPLNO] ASC);


GO
CREATE NONCLUSTERED INDEX [DMR_NO]
    ON [dbo].[PORECMRB]([DMR_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [FKUNQRCDTL]
    ON [dbo].[PORECMRB]([FK_UNIQRECDTL] ASC);

