CREATE TABLE [dbo].[PORECRELGL] (
    [UNIQRECREL]      INT             IDENTITY (1, 1) NOT NULL,
    [LOC_UNIQ]        CHAR (10)       CONSTRAINT [DF_PORECRELGL_LOC_UNIQ] DEFAULT ('') NOT NULL,
    [RAW_GL_NBR]      CHAR (13)       CONSTRAINT [DF_PORECRELGL_RAW_GL_NBR] DEFAULT ('') NOT NULL,
    [UNRECON_GL_NBR]  CHAR (13)       CONSTRAINT [DF_PORECRELGL_UNRECON_GL_NBR] DEFAULT ('') NOT NULL,
    [DEBITRAWACCT]    BIT             CONSTRAINT [DF_PORECRELGL_DEBITRAWACCT] DEFAULT ((0)) NOT NULL,
    [IS_REL_GL]       BIT             CONSTRAINT [DF_PORECRELGL_IS_REL_GL] DEFAULT ((0)) NOT NULL,
    [POSTED]          BIT             CONSTRAINT [DF_PORECRELGL_POSTED] DEFAULT ((0)) NOT NULL,
    [TRANS_NO]        NUMERIC (11)    CONSTRAINT [DF_PORECRELGL_TRANS_NO] DEFAULT ((0)) NOT NULL,
    [TRANS_DATE]      SMALLDATETIME   NULL,
    [TRANSINIT]       CHAR (8)        CONSTRAINT [DF_PORECRELGL_TRANSINIT] DEFAULT ('') NULL,
    [POSTE_DATE]      SMALLDATETIME   NULL,
    [POSTINIT]        CHAR (8)        CONSTRAINT [DF_PORECRELGL_POSTINIT] DEFAULT ('') NULL,
    [TRANSQTY]        NUMERIC (10, 2) CONSTRAINT [DF_PORECRELGL_TRANSQTY] DEFAULT ((0)) NOT NULL,
    [STDCOST]         NUMERIC (13, 5) CONSTRAINT [DF_PORECRELGL_STDCOST] DEFAULT ((0)) NOT NULL,
    [TOTALCOST]       NUMERIC (13, 5) CONSTRAINT [DF_PORECRELGL_TOTALCOST] DEFAULT ((0)) NOT NULL,
    [STDCOSTPR]       NUMERIC (13, 5) CONSTRAINT [DF__PORECRELG__STDCO__2851ED06] DEFAULT ((0)) NOT NULL,
    [TOTALCOSTPR]     NUMERIC (13, 5) CONSTRAINT [DF__PORECRELG__TOTAL__44EE2BB4] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__PORECRELG__PRFCU__381E407B] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__PORECRELG__FUNCF__391264B4] DEFAULT ('') NOT NULL,
    CONSTRAINT [PORECRELGL_PK] PRIMARY KEY CLUSTERED ([UNIQRECREL] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LOC_UNIQ]
    ON [dbo].[PORECRELGL]([LOC_UNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [TRANS_DATE]
    ON [dbo].[PORECRELGL]([TRANS_DATE] ASC);


GO
-- =============================================
-- Author:		Yelena Shmidt
-- Create date: 06/29/2012
-- Description:	Mark as reslease if TotalCost=0.00
-- Modification:
-- 04/17/17 VL added to update functional currency fields
-- =============================================
CREATE TRIGGER [dbo].[PorecRelGl_insert]
   ON  [dbo].[PORECRELGL]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for trigger here
    BEGIN TRANSACTION
	--UPDATE PoRecRelGl SET IS_REL_GL = CASE WHEN I.TotalCost =0.00 THEN 1 ELSE PoRecRelGl.IS_REL_GL END FROM inserted I WHERE I.UNIQRECREL =POrecRelGl.UNIQRECREL   
	UPDATE PoRecRelGl SET IS_REL_GL = CASE WHEN I.TotalCost =0.00 THEN 1 ELSE PoRecRelGl.IS_REL_GL END,
							PRFcused_uniq = CASE WHEN dbo.fn_IsFCInstalled() = 0 THEN SPACE(10) ELSE dbo.fn_GetPresentationCurrency() END,
							FuncFcused_uniq = CASE WHEN dbo.fn_IsFCInstalled() = 0 THEN SPACE(10) ELSE dbo.fn_GetFunctionalCurrency() END	
		 FROM inserted I WHERE I.UNIQRECREL =POrecRelGl.UNIQRECREL     
	COMMIT
    

END