CREATE TABLE [dbo].[PORECONRELDOC] (
    [SINV_UNIQ] CHAR (10)     CONSTRAINT [DF__PORECONRE__SINV___520FEF4C] DEFAULT ('') NOT NULL,
    [DOC_UNIQ]  CHAR (10)     CONSTRAINT [DF__PORECONRE__DOC_U__53041385] DEFAULT ('') NOT NULL,
    [SDET_UNIQ] CHAR (10)     CONSTRAINT [DF__PORECONRE__SDET___53F837BE] DEFAULT ('') NOT NULL,
    [DOCNO]     CHAR (25)     CONSTRAINT [DF__PORECONRE__DOCNO__54EC5BF7] DEFAULT ('') NOT NULL,
    [DOCREVNO]  CHAR (4)      CONSTRAINT [DF__PORECONRE__DOCRE__55E08030] DEFAULT ('') NOT NULL,
    [DOCDESCR]  CHAR (45)     CONSTRAINT [DF__PORECONRE__DOCDE__56D4A469] DEFAULT ('') NOT NULL,
    [DOCDATE]   SMALLDATETIME NULL,
    [DOCNOTE]   TEXT          CONSTRAINT [DF__PORECONRE__DOCNO__57C8C8A2] DEFAULT ('') NOT NULL,
    [DOCEXEC]   CHAR (200)    CONSTRAINT [DF__PORECONRE__DOCEX__58BCECDB] DEFAULT ('') NOT NULL,
    [DOCPDF]    CHAR (200)    CONSTRAINT [DF__PORECONRE__DOCPD__59B11114] DEFAULT ('') NOT NULL,
    CONSTRAINT [PORECONRELDOC_PK] PRIMARY KEY CLUSTERED ([DOC_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SDET_UNIQ]
    ON [dbo].[PORECONRELDOC]([SDET_UNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [SINV_UNIQ]
    ON [dbo].[PORECONRELDOC]([SINV_UNIQ] ASC);

