CREATE TABLE [dbo].[PORECMRBIPKEY] (
    [mrbIpKeyUnique] CHAR (10)       CONSTRAINT [DF__PORECMRBI__UNIQU__479260D9] DEFAULT ('') NOT NULL,
    [DMRUNIQUE]      CHAR (10)       CONSTRAINT [DF__PORECMRBI__FK_DM__469E3CA0] DEFAULT ('') NOT NULL,
    [QtyRet]         NUMERIC (12, 2) CONSTRAINT [DF__PORECMRBI__NPKGQ__497AA94B] DEFAULT ((0)) NOT NULL,
    [IPKEYUNIQUE]    CHAR (9)        CONSTRAINT [DF__PORECMRBI__IPKEY__48868512] DEFAULT ('') NOT NULL,
    CONSTRAINT [mrbIpKeyUnique_PK] PRIMARY KEY CLUSTERED ([mrbIpKeyUnique] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DMRUNIQUE]
    ON [dbo].[PORECMRBIPKEY]([DMRUNIQUE] ASC);


GO
CREATE NONCLUSTERED INDEX [IPKEYUNIQ]
    ON [dbo].[PORECMRBIPKEY]([IPKEYUNIQUE] ASC);

