CREATE TABLE [dbo].[POSTORE] (
    [DATE_ISU]   SMALLDATETIME    NULL,
    [UNIQ_KEY]   CHAR (10)        CONSTRAINT [DF__POSTORE__UNIQ_KE__727CBEDE] DEFAULT ('') NOT NULL,
    [QTY_ISU]    NUMERIC (12, 2)  CONSTRAINT [DF__POSTORE__QTY_ISU__7370E317] DEFAULT ((0)) NOT NULL,
    [PARTMFGR]   CHAR (8)         CONSTRAINT [DF__POSTORE__PARTMFG__74650750] DEFAULT ('') NOT NULL,
    [MFGR_PT_NO] CHAR (30)        CONSTRAINT [DF__POSTORE__MFGR_PT__75592B89] DEFAULT ('') NOT NULL,
    [PONUM]      CHAR (15)        CONSTRAINT [DF__POSTORE__PONUM__764D4FC2] DEFAULT ('') NOT NULL,
    [CONTR_UNIQ] CHAR (10)        CONSTRAINT [DF__POSTORE__CONTR_U__78359834] DEFAULT ('') NOT NULL,
    [UNIQRECORD] CHAR (10)        CONSTRAINT [DF__POSTORE__UNIQREC__7929BC6D] DEFAULT ('') NOT NULL,
    [LOTCODE]    NVARCHAR (25)    CONSTRAINT [DF__POSTORE__LOTCODE__7A1DE0A6] DEFAULT ('') NOT NULL,
    [EXPDATE]    SMALLDATETIME    NULL,
    [REFERENCE]  CHAR (12)        CONSTRAINT [DF__POSTORE__REFEREN__7B1204DF] DEFAULT ('') NOT NULL,
    [UNIQLNNO]   CHAR (10)        CONSTRAINT [DF__POSTORE__UNIQLNN__7C062918] DEFAULT ('') NOT NULL,
    [USEDBY]     CHAR (20)        CONSTRAINT [DF__POSTORE__USEDBY__7CFA4D51] DEFAULT ('') NOT NULL,
    [serialno]   CHAR (30)        CONSTRAINT [DF_POSTORE_serialno] DEFAULT ('') NOT NULL,
    [serialuniq] CHAR (10)        CONSTRAINT [DF_POSTORE_serialuniq] DEFAULT ('') NOT NULL,
    [UNIQSUPNO]  CHAR (10)        CONSTRAINT [DF__POSTORE__UNIQSUP__7DEE718A] DEFAULT ('') NOT NULL,
    [UNIQMFGRHD] CHAR (10)        CONSTRAINT [DF__POSTORE__UNIQMFG__7EE295C3] DEFAULT ('') NOT NULL,
    [UNIQWH]     CHAR (10)        CONSTRAINT [DF__POSTORE__UNIQWH__7FD6B9FC] DEFAULT ('') NOT NULL,
    [LOCATION]   NVARCHAR (200)   CONSTRAINT [DF__POSTORE__LOCATIO__00CADE35] DEFAULT ('') NOT NULL,
    [RecVer]     ROWVERSION       NOT NULL,
    [lPrinted]   BIT              CONSTRAINT [DF__POSTORE__lPrinte__3C0F9847] DEFAULT ((0)) NOT NULL,
    [fk_userid]  UNIQUEIDENTIFIER NULL,
    CONSTRAINT [POSTORE_PK] PRIMARY KEY CLUSTERED ([UNIQRECORD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CONTR_UNIQ]
    ON [dbo].[POSTORE]([CONTR_UNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [PARTNOMFGR]
    ON [dbo].[POSTORE]([UNIQ_KEY] ASC, [PARTMFGR] ASC);


GO
CREATE NONCLUSTERED INDEX [rptPoStorePonumIndex]
    ON [dbo].[POSTORE]([PONUM] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[POSTORE]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRHD]
    ON [dbo].[POSTORE]([UNIQMFGRHD] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQSUPNO]
    ON [dbo].[POSTORE]([UNIQSUPNO] ASC);

