CREATE TABLE [dbo].[PREVSTAT] (
    [FIELDTYPE] CHAR (10) CONSTRAINT [DF_PREVSTAT_FIELDTYPE] DEFAULT ('') NOT NULL,
    [FIELDKEY]  CHAR (10) CONSTRAINT [DF_PREVSTAT_FIELDKEY] DEFAULT ('') NOT NULL,
    [UNIQUENUM] INT       IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PREVSTAT_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIELDTPKEY]
    ON [dbo].[PREVSTAT]([FIELDTYPE] ASC, [FIELDKEY] ASC);

