CREATE TABLE [dbo].[PRICDETL] (
    [UNIQPRHEAD] CHAR (10)       CONSTRAINT [DF__PRICDETL__UNIQPR__0D30B51A] DEFAULT ('') NOT NULL,
    [UNIQPRDETL] CHAR (10)       CONSTRAINT [DF__PRICDETL__UNIQPR__0E24D953] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__PRICDETL__UNIQ_K__0F18FD8C] DEFAULT ('') NOT NULL,
    [CATEGORY]   CHAR (10)       CONSTRAINT [DF__PRICDETL__CATEGO__100D21C5] DEFAULT ('') NOT NULL,
    [FROMQTY]    NUMERIC (7)     CONSTRAINT [DF__PRICDETL__FROMQT__110145FE] DEFAULT ((0)) NOT NULL,
    [TOQTY]      NUMERIC (7)     CONSTRAINT [DF__PRICDETL__TOQTY__11F56A37] DEFAULT ((0)) NOT NULL,
    [PRICE1]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE1__12E98E70] DEFAULT ((0)) NOT NULL,
    [PRICE2]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE2__13DDB2A9] DEFAULT ((0)) NOT NULL,
    [PRICE3]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE3__14D1D6E2] DEFAULT ((0)) NOT NULL,
    [PRICE4]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE4__15C5FB1B] DEFAULT ((0)) NOT NULL,
    [PRICE5]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE5__16BA1F54] DEFAULT ((0)) NOT NULL,
    [PRICE6]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE6__17AE438D] DEFAULT ((0)) NOT NULL,
    [PRICE7]     NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__PRICE7__18A267C6] DEFAULT ((0)) NOT NULL,
    [TOTALPRICE] NUMERIC (12, 5) CONSTRAINT [DF__PRICDETL__TOTALP__19968BFF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PRICDETL_PK] PRIMARY KEY CLUSTERED ([UNIQPRDETL] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRICDETL]
    ON [dbo].[PRICDETL]([UNIQ_KEY] ASC, [CATEGORY] ASC, [FROMQTY] ASC, [TOQTY] ASC);

