CREATE TABLE [dbo].[PRICHEAD] (
    [UNIQPRHEAD]  CHAR (10)       CONSTRAINT [DF__PRICHEAD__UNIQPR__2137ADC7] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]    CHAR (10)       CONSTRAINT [DF__PRICHEAD__UNIQ_K__222BD200] DEFAULT ('') NOT NULL,
    [CATEGORY]    CHAR (10)       CONSTRAINT [DF__PRICHEAD__CATEGO__231FF639] DEFAULT ('') NOT NULL,
    [NUMBER]      NUMERIC (3)     CONSTRAINT [DF__PRICHEAD__NUMBER__24141A72] DEFAULT ((0)) NOT NULL,
    [INVQTY]      NUMERIC (6)     CONSTRAINT [DF__PRICHEAD__INVQTY__25083EAB] DEFAULT ((0)) NOT NULL,
    [SETUPCHG]    NUMERIC (6)     CONSTRAINT [DF__PRICHEAD__SETUPC__25FC62E4] DEFAULT ((0)) NOT NULL,
    [AMORTCHG]    NUMERIC (12, 5) CONSTRAINT [DF__PRICHEAD__AMORTC__26F0871D] DEFAULT ((0)) NOT NULL,
    [INV1]        BIT             CONSTRAINT [DF__PRICHEAD__INV1__27E4AB56] DEFAULT ((0)) NOT NULL,
    [PL1]         BIT             CONSTRAINT [DF__PRICHEAD__PL1__28D8CF8F] DEFAULT ((0)) NOT NULL,
    [TPCHG4]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG4__29CCF3C8] DEFAULT ('') NOT NULL,
    [TPCHG3]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG3__2AC11801] DEFAULT ('') NOT NULL,
    [TPCHG2]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG2__2BB53C3A] DEFAULT ('') NOT NULL,
    [TPCHG1]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG1__2CA96073] DEFAULT ('') NOT NULL,
    [TPCHG6]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG6__2D9D84AC] DEFAULT ('') NOT NULL,
    [TPCHG5]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG5__2E91A8E5] DEFAULT ('') NOT NULL,
    [TPCHG7]      CHAR (10)       CONSTRAINT [DF__PRICHEAD__TPCHG7__2F85CD1E] DEFAULT ('') NOT NULL,
    [AMORTAMT]    NUMERIC (8, 2)  CONSTRAINT [DF__PRICHEAD__AMORTA__3079F157] DEFAULT ((0)) NOT NULL,
    [AMYQTY]      NUMERIC (6)     CONSTRAINT [DF__PRICHEAD__AMYQTY__316E1590] DEFAULT ((0)) NOT NULL,
    [WARRANTY]    NUMERIC (3)     CONSTRAINT [DF__PRICHEAD__WARRAN__326239C9] DEFAULT ((0)) NOT NULL,
    [MARKUP]      NUMERIC (6, 2)  CONSTRAINT [DF__PRICHEAD__MARKUP__33565E02] DEFAULT ((0)) NOT NULL,
    [Fcused_uniq] CHAR (10)       CONSTRAINT [DF__PRICHEAD__Fcused__1899DCD3] DEFAULT ('') NOT NULL,
    CONSTRAINT [PRICHEAD_PK] PRIMARY KEY CLUSTERED ([UNIQPRHEAD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NUMBER]
    ON [dbo].[PRICHEAD]([NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [PARTCAT]
    ON [dbo].[PRICHEAD]([UNIQ_KEY] ASC, [CATEGORY] ASC);


GO
-- =============================================
-- Author:		Vicky Lu
-- Create date: 09/24/2010
-- Description:	After Delete trigger for the Prichead table
-- =============================================
CREATE TRIGGER  [dbo].[PricHead_Delete]
   ON  [dbo].[PricHead] 
   AFTER DELETE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRANSACTION 
	DELETE FROM PricDetl WHERE Uniq_key+Category IN (SELECT Uniq_key+Category FROM DELETED)
	DELETE FROM PricSrep WHERE Uniq_key+Custno IN (SELECT Uniq_key+Category FROM DELETED)
	COMMIT

END




