CREATE TABLE [dbo].[PRICEBRK] (
    [BREAK_NO]   CHAR (3)  CONSTRAINT [DF__PRICEBRK__BREAK___1C72F8AA] DEFAULT ('') NOT NULL,
    [BREAK_ITEM] CHAR (20) CONSTRAINT [DF__PRICEBRK__BREAK___1D671CE3] DEFAULT ('') NOT NULL,
    [PRICEBRKUK] CHAR (10) CONSTRAINT [DF__PRICEBRK__PRICEB__1E5B411C] DEFAULT ('') NOT NULL,
    CONSTRAINT [PRICEBRK_PK] PRIMARY KEY CLUSTERED ([PRICEBRKUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [BREAK_ITEM]
    ON [dbo].[PRICEBRK]([BREAK_ITEM] ASC);


GO
CREATE NONCLUSTERED INDEX [BREAK_NO]
    ON [dbo].[PRICEBRK]([BREAK_NO] ASC);

