CREATE TABLE [dbo].[PROD_DTS] (
    [WONO]           CHAR (10)        CONSTRAINT [DF__PROD_DTS__WONO__63F9955D] DEFAULT ('') NOT NULL,
    [COMPL_DTS]      SMALLDATETIME    NULL,
    [QTY]            NUMERIC (7)      CONSTRAINT [DF__PROD_DTS__QTY__64EDB996] DEFAULT ((0)) NOT NULL,
    [DAYMIN]         NUMERIC (10)     CONSTRAINT [DF__PROD_DTS__DAYMIN__65E1DDCF] DEFAULT ((0)) NOT NULL,
    [START_DTS]      SMALLDATETIME    NULL,
    [SLACKPRI]       NUMERIC (10, 5)  CONSTRAINT [DF__PROD_DTS__SLACKP__66D60208] DEFAULT ((0)) NOT NULL,
    [PROCESSTM]      NUMERIC (10, 5)  CONSTRAINT [DF__PROD_DTS__PROCES__67CA2641] DEFAULT ((0)) NOT NULL,
    [PRODSCHUNQ]     CHAR (10)        CONSTRAINT [DF__PROD_DTS__PRODSC__68BE4A7A] DEFAULT ('') NOT NULL,
    [AutoScheduled]  BIT              CONSTRAINT [DF_PROD_DTS_AutoScheduled] DEFAULT ((0)) NOT NULL,
    [fk_aspnetUsers] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PROD_DTS_PK] PRIMARY KEY CLUSTERED ([PRODSCHUNQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SLACKPRI]
    ON [dbo].[PROD_DTS]([SLACKPRI] ASC);


GO
CREATE NONCLUSTERED INDEX [WOLOTCOMDT]
    ON [dbo].[PROD_DTS]([WONO] ASC, [COMPL_DTS] ASC);


GO
CREATE NONCLUSTERED INDEX [WOLOTSLACK]
    ON [dbo].[PROD_DTS]([WONO] ASC, [SLACKPRI] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[PROD_DTS]([WONO] ASC);

