CREATE TABLE [dbo].[PROSPECT] (
    [CUSTNO]    CHAR (10) CONSTRAINT [DF__PROSPECT__CUSTNO__6B9AB725] DEFAULT ('') NOT NULL,
    [CUSTNAME]  CHAR (35) CONSTRAINT [DF__PROSPECT__CUSTNA__6C8EDB5E] DEFAULT ('') NOT NULL,
    [PHONE]     CHAR (19) CONSTRAINT [DF__PROSPECT__PHONE__6D82FF97] DEFAULT ('') NOT NULL,
    [FAX]       CHAR (19) CONSTRAINT [DF__PROSPECT__FAX__6E7723D0] DEFAULT ('') NOT NULL,
    [SADDRESS1] CHAR (50) CONSTRAINT [DF__PROSPECT__SADDRE__6F6B4809] DEFAULT ('') NULL,
    [SADDRESS2] CHAR (50) CONSTRAINT [DF__PROSPECT__SADDRE__705F6C42] DEFAULT ('') NULL,
    [SCITY]     CHAR (50) CONSTRAINT [DF__PROSPECT__SCITY__7153907B] DEFAULT ('') NULL,
    [SSTATE]    CHAR (3)  CONSTRAINT [DF__PROSPECT__SSTATE__7247B4B4] DEFAULT ('') NOT NULL,
    [SZIP]      CHAR (10) CONSTRAINT [DF__PROSPECT__SZIP__733BD8ED] DEFAULT ('') NOT NULL,
    [SCOUNTRY]  CHAR (50) CONSTRAINT [DF__PROSPECT__SCOUNT__742FFD26] DEFAULT ('') NULL,
    [BADDRESS1] CHAR (50) CONSTRAINT [DF__PROSPECT__BADDRE__7524215F] DEFAULT ('') NULL,
    [BADDRESS2] CHAR (50) CONSTRAINT [DF__PROSPECT__BADDRE__76184598] DEFAULT ('') NULL,
    [BCITY]     CHAR (50) CONSTRAINT [DF__PROSPECT__BCITY__770C69D1] DEFAULT ('') NULL,
    [BSTATE]    CHAR (3)  CONSTRAINT [DF__PROSPECT__BSTATE__78008E0A] DEFAULT ('') NOT NULL,
    [BZIP]      CHAR (10) CONSTRAINT [DF__PROSPECT__BZIP__78F4B243] DEFAULT ('') NOT NULL,
    [BCOUNTRY]  CHAR (50) CONSTRAINT [DF__PROSPECT__BCOUNT__79E8D67C] DEFAULT ('') NULL,
    [SADDRESS3] CHAR (50) CONSTRAINT [DF__PROSPECT__SADDRE__3BE31910] DEFAULT ('') NOT NULL,
    [SADDRESS4] CHAR (50) CONSTRAINT [DF__PROSPECT__SADDRE__3CD73D49] DEFAULT ('') NOT NULL,
    [BADDRESS3] CHAR (50) CONSTRAINT [DF__PROSPECT__BADDRE__3DCB6182] DEFAULT ('') NOT NULL,
    [BADDRESS4] CHAR (50) CONSTRAINT [DF__PROSPECT__BADDRE__3EBF85BB] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK__PROSPECT__3D9DE38A6B46F69C] PRIMARY KEY CLUSTERED ([CUSTNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUSTNAME]
    ON [dbo].[PROSPECT]([CUSTNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[PROSPECT]([CUSTNO] ASC);

