CREATE TABLE [dbo].[QADEFLOC] (
    [LOCSEQNO]          CHAR (10)        CONSTRAINT [DF__QADEFLOC__LOCSEQ__481C70BE] DEFAULT ('') NOT NULL,
    [LOCATION]          CHAR (30)        CONSTRAINT [DF__QADEFLOC__LOCATI__491094F7] DEFAULT ('') NOT NULL,
    [PARTMFGR]          CHAR (8)         CONSTRAINT [DF__QADEFLOC__PARTMF__4A04B930] DEFAULT ('') NOT NULL,
    [LOCQTY]            NUMERIC (4)      CONSTRAINT [DF__QADEFLOC__LOCQTY__4AF8DD69] DEFAULT ((0)) NOT NULL,
    [CHECK]             BIT              CONSTRAINT [DF__QADEFLOC__CHECK__4BED01A2] DEFAULT ((0)) NOT NULL,
    [CHK_NOTE]          VARCHAR (80)     CONSTRAINT [DF__QADEFLOC__CHK_NO__4CE125DB] DEFAULT ('') NOT NULL,
    [CHK_DATE]          SMALLDATETIME    NULL,
    [CHK_TIME]          CHAR (10)        CONSTRAINT [DF__QADEFLOC__CHK_TI__4DD54A14] DEFAULT ('') NOT NULL,
    [CHK_ID]            CHAR (8)         CONSTRAINT [DF__QADEFLOC__CHK_ID__4EC96E4D] DEFAULT ('') NOT NULL,
    [UNIQ_LOC]          CHAR (10)        CONSTRAINT [DF__QADEFLOC__UNIQ_L__4FBD9286] DEFAULT ('') NOT NULL,
    [DEF_CODE]          CHAR (10)        CONSTRAINT [DF__QADEFLOC__DEF_CO__50B1B6BF] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]          CHAR (10)        CONSTRAINT [DF__QADEFLOC__UNIQ_K__51A5DAF8] DEFAULT ('') NOT NULL,
    [NEEDREPLAC]        BIT              CONSTRAINT [DF__QADEFLOC__NEEDRE__5299FF31] DEFAULT ((0)) NOT NULL,
    [FIXSTATUS]         CHAR (10)        CONSTRAINT [DF__QADEFLOC__FIXSTA__538E236A] DEFAULT ('') NOT NULL,
    [CHGDEPT_ID]        CHAR (4)         CONSTRAINT [DF__QADEFLOC__CHGDEP__548247A3] DEFAULT ('') NOT NULL,
    [REWORKINIT]        CHAR (8)         CONSTRAINT [DF__QADEFLOC__REWORK__55766BDC] DEFAULT ('') NULL,
    [REQ_QTY]           NUMERIC (4)      CONSTRAINT [DF__QADEFLOC__REQ_QT__566A9015] DEFAULT ((0)) NOT NULL,
    [qaseqmain]         CHAR (10)        CONSTRAINT [DF_QADEFLOC_qaseqmain] DEFAULT ('') NOT NULL,
    [uniqmfgrhd]        CHAR (10)        CONSTRAINT [DF_QADEFLOC_uniqmfgrhd] DEFAULT ('') NOT NULL,
    [USERID]            UNIQUEIDENTIFIER NULL,
    [LastChangedUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [QADEFLOC_PK] PRIMARY KEY CLUSTERED ([UNIQ_LOC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LOCSEQNO]
    ON [dbo].[QADEFLOC]([LOCSEQNO] ASC);


GO
CREATE NONCLUSTERED INDEX [qaseqmain]
    ON [dbo].[QADEFLOC]([qaseqmain] ASC);

