CREATE TABLE [dbo].[QAINSP] (
    [WONO]              CHAR (10)        CONSTRAINT [DF__QAINSP__WONO__5A3B20F9] DEFAULT ('') NOT NULL,
    [DEPT_ID]           CHAR (4)         CONSTRAINT [DF__QAINSP__DEPT_ID__5B2F4532] DEFAULT ('') NOT NULL,
    [QASEQMAIN]         CHAR (10)        CONSTRAINT [DF__QAINSP__QASEQMAI__5C23696B] DEFAULT ('') NOT NULL,
    [LOTSIZE]           NUMERIC (7)      CONSTRAINT [DF__QAINSP__LOTSIZE__5D178DA4] DEFAULT ((0)) NOT NULL,
    [INSPQTY]           NUMERIC (7)      CONSTRAINT [DF__QAINSP__INSPQTY__5E0BB1DD] DEFAULT ((0)) NOT NULL,
    [FAILQTY]           NUMERIC (7)      CONSTRAINT [DF__QAINSP__FAILQTY__5EFFD616] DEFAULT ((0)) NOT NULL,
    [PASSQTY]           NUMERIC (7)      CONSTRAINT [DF__QAINSP__PASSQTY__5FF3FA4F] DEFAULT ((0)) NOT NULL,
    [INSPBY]            CHAR (10)        CONSTRAINT [DF__QAINSP__INSPBY__60E81E88] DEFAULT ('') NOT NULL,
    [ACTPLAN]           TEXT             CONSTRAINT [DF__QAINSP__ACTPLAN__61DC42C1] DEFAULT ('') NOT NULL,
    [RESOLUTION]        TEXT             CONSTRAINT [DF__QAINSP__RESOLUTI__62D066FA] DEFAULT ('') NOT NULL,
    [YIELD]             NUMERIC (6, 2)   CONSTRAINT [DF__QAINSP__YIELD__63C48B33] DEFAULT ((0)) NOT NULL,
    [DATE]              DATETIME         NULL,
    [RWKTIME]           NUMERIC (10, 2)  CONSTRAINT [DF__QAINSP__RWKTIME__65ACD3A5] DEFAULT ((0)) NOT NULL,
    [SCRAP]             NUMERIC (10, 2)  CONSTRAINT [DF__QAINSP__SCRAP__66A0F7DE] DEFAULT ((0)) NOT NULL,
    [SCRAP_QTY]         NUMERIC (7)      CONSTRAINT [DF__QAINSP__SCRAP_QT__67951C17] DEFAULT ((0)) NOT NULL,
    [PPM_DETL]          NUMERIC (7)      CONSTRAINT [DF__QAINSP__PPM_DETL__68894050] DEFAULT ((0)) NOT NULL,
    [PPM_UNIT]          NUMERIC (7)      CONSTRAINT [DF__QAINSP__PPM_UNIT__697D6489] DEFAULT ((0)) NOT NULL,
    [RWKHRS]            NUMERIC (4)      CONSTRAINT [DF__QAINSP__RWKHRS__6A7188C2] DEFAULT ((0)) NOT NULL,
    [RWKMIN]            NUMERIC (3)      CONSTRAINT [DF__QAINSP__RWKMIN__6B65ACFB] DEFAULT ((0)) NOT NULL,
    [UserId]            UNIQUEIDENTIFIER NULL,
    [LastChangedUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [QAINSP_PK] PRIMARY KEY CLUSTERED ([QASEQMAIN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [QADEPTWONO]
    ON [dbo].[QAINSP]([DEPT_ID] ASC, [WONO] ASC);


GO
CREATE NONCLUSTERED INDEX [QAWONO]
    ON [dbo].[QAINSP]([WONO] ASC, [DEPT_ID] ASC, [QASEQMAIN] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[QAINSP]([WONO] ASC);


GO
CREATE NONCLUSTERED INDEX [WONODPTDTE]
    ON [dbo].[QAINSP]([WONO] ASC, [DEPT_ID] ASC, [DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [DateWonoDeptQaseqLot]
    ON [dbo].[QAINSP]([DATE] ASC)
    INCLUDE([WONO], [DEPT_ID], [QASEQMAIN], [LOTSIZE], [INSPQTY], [FAILQTY], [PASSQTY], [INSPBY]);


GO
-- =============================================
-- Author:		Vicky Lu
-- Create date: 10/04/2011
-- Description:	After Delete trigger for the Qainsp table
-- =============================================
CREATE TRIGGER  [dbo].[Qainsp_Delete]
   ON  [dbo].[Qainsp] 
   AFTER DELETE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRANSACTION 
	DELETE FROM Qadef WHERE Qaseqmain IN (SELECT Qaseqmain FROM DELETED)
	DELETE FROM Qadefloc WHERE Qaseqmain IN (SELECT Qaseqmain FROM DELETED) 
	COMMIT

END








