CREATE TABLE [dbo].[QAMAXPAS] (
    [UQQAMAXPAS] CHAR (10)   CONSTRAINT [DF__QAMAXPAS__UQQAMA__6E4219A6] DEFAULT ('') NOT NULL,
    [WONO]       CHAR (10)   CONSTRAINT [DF__QAMAXPAS__WONO__6F363DDF] DEFAULT ('') NOT NULL,
    [DEPT_ID]    CHAR (4)    CONSTRAINT [DF__QAMAXPAS__DEPT_I__702A6218] DEFAULT ('') NOT NULL,
    [NUMBER]     NUMERIC (4) CONSTRAINT [DF__QAMAXPAS__NUMBER__711E8651] DEFAULT ((0)) NOT NULL,
    [SERIALNO]   CHAR (30)   CONSTRAINT [DF__QAMAXPAS__SERIAL__7212AA8A] DEFAULT ('') NOT NULL,
    [SERIALUNIQ] CHAR (10)   CONSTRAINT [DF__QAMAXPAS__SERIAL__7306CEC3] DEFAULT ('') NOT NULL,
    [MAXPASSNUM] NUMERIC (2) CONSTRAINT [DF__QAMAXPAS__MAXPAS__73FAF2FC] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QAMAXPAS_PK] PRIMARY KEY CLUSTERED ([UQQAMAXPAS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MAXPASSNUM]
    ON [dbo].[QAMAXPAS]([WONO] ASC, [DEPT_ID] ASC, [SERIALNO] ASC);

