CREATE TABLE [dbo].[QASCRPDT] (
    [QASEQMAIN] CHAR (7)  CONSTRAINT [DF__QASCRPDT__QASEQM__76D75FA7] DEFAULT ('') NOT NULL,
    [SCRPDEF]   CHAR (10) CONSTRAINT [DF__QASCRPDT__SCRPDE__77CB83E0] DEFAULT ('') NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [QASEQMAIN]
    ON [dbo].[QASCRPDT]([QASEQMAIN] ASC);

