CREATE TABLE [dbo].[QATEMPLT] (
    [TEMPLDESCR] CHAR (70)       CONSTRAINT [DF__QATEMPLT__TEMPLD__79B3CC52] DEFAULT ('') NOT NULL,
    [SELECTEDBY] NUMERIC (1)     CONSTRAINT [DF__QATEMPLT__SELECT__7AA7F08B] DEFAULT ((0)) NOT NULL,
    [SELECTEDPT] NUMERIC (1)     CONSTRAINT [DF__QATEMPLT__SELECT__7B9C14C4] DEFAULT ((0)) NOT NULL,
    [SELECTEDCT] NUMERIC (1)     CONSTRAINT [DF__QATEMPLT__SELECT__7C9038FD] DEFAULT ((0)) NOT NULL,
    [SELECTEDDF] NUMERIC (1)     CONSTRAINT [DF__QATEMPLT__SELECT__7D845D36] DEFAULT ((0)) NOT NULL,
    [SELECTEDDP] NUMERIC (1)     CONSTRAINT [DF__QATEMPLT__SELECT__7E78816F] DEFAULT ((0)) NOT NULL,
    [SELECTEDWO] NUMERIC (1)     CONSTRAINT [DF__QATEMPLT__SELECT__7F6CA5A8] DEFAULT ((0)) NOT NULL,
    [TEMPLUNIQ]  CHAR (10)       CONSTRAINT [DF__QATEMPLT__TEMPLU__0060C9E1] DEFAULT ('') NOT NULL,
    [STARTDATE]  SMALLDATETIME   NULL,
    [ENDDATE]    SMALLDATETIME   NULL,
    [PCENTRAL]   NUMERIC (5, 3)  CONSTRAINT [DF__QATEMPLT__PCENTR__0154EE1A] DEFAULT ((0)) NOT NULL,
    [PCONTRLINE] CHAR (1)        CONSTRAINT [DF__QATEMPLT__PCONTR__02491253] DEFAULT ('') NOT NULL,
    [DPMCENTRAL] NUMERIC (10, 3) CONSTRAINT [DF__QATEMPLT__DPMCEN__033D368C] DEFAULT ((0)) NOT NULL,
    [DPMCONTRL]  CHAR (1)        CONSTRAINT [DF__QATEMPLT__DPMCON__04315AC5] DEFAULT ('') NOT NULL,
    [DATERANGE]  CHAR (1)        CONSTRAINT [DF__QATEMPLT__DATERA__05257EFE] DEFAULT ('') NOT NULL,
    [YIELDGOAL]  NUMERIC (3)     CONSTRAINT [DF__QATEMPLT__YIELDG__0619A337] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QATEMPLT_PK] PRIMARY KEY CLUSTERED ([TEMPLUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TEMPLDESCR]
    ON [dbo].[QATEMPLT]([TEMPLDESCR] ASC);

