CREATE TABLE [dbo].[QATMPLWO] (
    [TEMPLUNIQ]  CHAR (10) CONSTRAINT [DF__QATMPLWO__TEMPLU__1EE55101] DEFAULT ('') NOT NULL,
    [WONO]       CHAR (10) CONSTRAINT [DF__QATMPLWO__WONO__1FD9753A] DEFAULT ('') NOT NULL,
    [QATMPLWOUK] CHAR (10) CONSTRAINT [DF__QATMPLWO__QATMPL__20CD9973] DEFAULT ('') NOT NULL,
    CONSTRAINT [QATMPLWO_PK] PRIMARY KEY CLUSTERED ([QATMPLWOUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TEMPLUNIQ]
    ON [dbo].[QATMPLWO]([TEMPLUNIQ] ASC);

