CREATE TABLE [dbo].[QATMPLCU] (
    [TEMPLUNIQ]   CHAR (10) CONSTRAINT [DF__QATMPLCU__TEMPLU__08F60FE2] DEFAULT ('') NOT NULL,
    [CUSTNO]      CHAR (10) CONSTRAINT [DF__QATMPLCU__CUSTNO__09EA341B] DEFAULT ('') NOT NULL,
    [QATEMPLCUUK] CHAR (10) CONSTRAINT [DF__QATMPLCU__QATEMP__0ADE5854] DEFAULT ('') NOT NULL,
    CONSTRAINT [QATMPLCU_PK] PRIMARY KEY CLUSTERED ([QATEMPLCUUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TEMPLUNIQ]
    ON [dbo].[QATMPLCU]([TEMPLUNIQ] ASC);

