CREATE TABLE [dbo].[QATMPLWC] (
    [TEMPLUNIQ]  CHAR (10) CONSTRAINT [DF__QATMPLWC__TEMPLU__1A209BE4] DEFAULT ('') NOT NULL,
    [DEPT_ID]    CHAR (4)  CONSTRAINT [DF__QATMPLWC__DEPT_I__1B14C01D] DEFAULT ('') NOT NULL,
    [QATMPLWCUK] CHAR (10) CONSTRAINT [DF__QATMPLWC__QATMPL__1C08E456] DEFAULT ('') NOT NULL,
    CONSTRAINT [QATMPLWC_PK] PRIMARY KEY CLUSTERED ([QATMPLWCUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TEMPLUNIQ]
    ON [dbo].[QATMPLWC]([TEMPLUNIQ] ASC);

