CREATE TABLE [dbo].[QATMPLPT] (
    [TEMPLUNIQ]  CHAR (10) CONSTRAINT [DF__QATMPLPT__TEMPLU__127F7A1C] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]   CHAR (10) CONSTRAINT [DF__QATMPLPT__UNIQ_K__16500B00] DEFAULT ('') NOT NULL,
    [QATMPLPTUK] CHAR (10) CONSTRAINT [DF__QATMPLPT__QATMPL__17442F39] DEFAULT ('') NOT NULL,
    CONSTRAINT [QATMPLPT_PK] PRIMARY KEY CLUSTERED ([QATMPLPTUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TEMPLUNIQ]
    ON [dbo].[QATMPLPT]([TEMPLUNIQ] ASC);

