CREATE TABLE [dbo].[QATMPLDF] (
    [TEMPLUNIQ]  CHAR (10) CONSTRAINT [DF__QATMPLDF__TEMPLU__0DBAC4FF] DEFAULT ('') NOT NULL,
    [DEF_CODE]   CHAR (10) CONSTRAINT [DF__QATMPLDF__DEF_CO__0EAEE938] DEFAULT ('') NOT NULL,
    [QATMPLDFUK] CHAR (10) CONSTRAINT [DF__QATMPLDF__QATMPL__0FA30D71] DEFAULT ('') NOT NULL,
    CONSTRAINT [QATMPLDF_PK] PRIMARY KEY CLUSTERED ([QATMPLDFUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TEMPLUNIQ]
    ON [dbo].[QATMPLDF]([TEMPLUNIQ] ASC);

