CREATE TABLE [dbo].[QTAPPROV] (
    [QUOTEUNIQ]  CHAR (10)     CONSTRAINT [DF__QTAPPROV__QUOTEU__23AA061E] DEFAULT ('') NOT NULL,
    [UNIQLINENO] CHAR (10)     CONSTRAINT [DF__QTAPPROV__UNIQLI__249E2A57] DEFAULT ('') NOT NULL,
    [UNIQAPPNO]  CHAR (10)     CONSTRAINT [DF__QTAPPROV__UNIQAP__25924E90] DEFAULT ('') NOT NULL,
    [DEPT]       CHAR (25)     CONSTRAINT [DF__QTAPPROV__DEPT__268672C9] DEFAULT ('') NOT NULL,
    [INIT]       CHAR (8)      CONSTRAINT [DF__QTAPPROV__INIT__277A9702] DEFAULT ('') NULL,
    [DATE]       SMALLDATETIME NULL,
    [COMMENT]    TEXT          CONSTRAINT [DF__QTAPPROV__COMMEN__286EBB3B] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTAPPROV_PK] PRIMARY KEY CLUSTERED ([UNIQAPPNO] ASC)
);

