CREATE TABLE [dbo].[QTDETL] (
    [UNIQLINENO] CHAR (10)       CONSTRAINT [DF__QTDETL__UNIQLINE__2B4B27E6] DEFAULT ('') NOT NULL,
    [UNIQDETLNO] CHAR (10)       CONSTRAINT [DF__QTDETL__UNIQDETL__2C3F4C1F] DEFAULT ('') NOT NULL,
    [PART_SOURC] CHAR (10)       CONSTRAINT [DF__QTDETL__PART_SOU__2D337058] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__QTDETL__UNIQ_KEY__2E279491] DEFAULT ('') NOT NULL,
    [ITEMNO]     NUMERIC (4)     CONSTRAINT [DF__QTDETL__ITEMNO__2F1BB8CA] DEFAULT ((0)) NOT NULL,
    [QTYEA]      NUMERIC (9, 2)  CONSTRAINT [DF__QTDETL__QTYEA__300FDD03] DEFAULT ((0)) NOT NULL,
    [PART_NO]    CHAR (25)       CONSTRAINT [DF__QTDETL__PART_NO__3104013C] DEFAULT ('') NOT NULL,
    [REVISION]   CHAR (4)        CONSTRAINT [DF__QTDETL__REVISION__31F82575] DEFAULT ('') NOT NULL,
    [CUSTPARTNO] CHAR (25)       CONSTRAINT [DF__QTDETL__CUSTPART__32EC49AE] DEFAULT ('') NOT NULL,
    [CUSTREV]    CHAR (4)        CONSTRAINT [DF__QTDETL__CUSTREV__33E06DE7] DEFAULT ('') NOT NULL,
    [PART_CLASS] CHAR (8)        CONSTRAINT [DF__QTDETL__PART_CLA__34D49220] DEFAULT ('') NOT NULL,
    [PART_TYPE]  CHAR (8)        CONSTRAINT [DF__QTDETL__PART_TYP__35C8B659] DEFAULT ('') NOT NULL,
    [DESCRIPT]   CHAR (45)       CONSTRAINT [DF__QTDETL__DESCRIPT__36BCDA92] DEFAULT ('') NOT NULL,
    [MATLMARKUP] NUMERIC (6, 2)  CONSTRAINT [DF__QTDETL__MATLMARK__37B0FECB] DEFAULT ((0)) NOT NULL,
    [INV_NOTE]   TEXT            CONSTRAINT [DF__QTDETL__INV_NOTE__38A52304] DEFAULT ('') NOT NULL,
    [COSTTYPE]   NUMERIC (1)     CONSTRAINT [DF__QTDETL__COSTTYPE__3999473D] DEFAULT ((0)) NOT NULL,
    [U_OF_MEAS]  CHAR (4)        CONSTRAINT [DF__QTDETL__U_OF_MEA__3A8D6B76] DEFAULT ('') NOT NULL,
    [COST]       NUMERIC (13, 5) CONSTRAINT [DF__QTDETL__COST__3B818FAF] DEFAULT ((0)) NOT NULL,
    [SCRAP]      NUMERIC (6, 2)  CONSTRAINT [DF__QTDETL__SCRAP__3C75B3E8] DEFAULT ((0)) NOT NULL,
    [MINORDDEF]  BIT             CONSTRAINT [DF__QTDETL__MINORDDE__3D69D821] DEFAULT ((0)) NOT NULL,
    [MINORD]     NUMERIC (7)     CONSTRAINT [DF__QTDETL__MINORD__3E5DFC5A] DEFAULT ((0)) NOT NULL,
    [UNIQBOMNO]  CHAR (10)       CONSTRAINT [DF__QTDETL__UNIQBOMN__3F522093] DEFAULT ('') NOT NULL,
    [DLASTPODT]  SMALLDATETIME   NULL,
    [DEPT_ID]    CHAR (4)        CONSTRAINT [DF__QTDETL__DEPT_ID__404644CC] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTDETL_PK] PRIMARY KEY CLUSTERED ([UNIQDETLNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTDETL]([UNIQLINENO] ASC);

