CREATE TABLE [dbo].[QTMFGR] (
    [UNIQLINENO] CHAR (10) CONSTRAINT [DF__QTMFGR__UNIQLINE__5264F507] DEFAULT ('') NOT NULL,
    [UNIQDETLNO] CHAR (10) CONSTRAINT [DF__QTMFGR__UNIQDETL__53591940] DEFAULT ('') NOT NULL,
    [UNIQMFGRNO] CHAR (10) CONSTRAINT [DF__QTMFGR__UNIQMFGR__544D3D79] DEFAULT ('') NOT NULL,
    [PARTMFGR]   CHAR (8)  CONSTRAINT [DF__QTMFGR__PARTMFGR__554161B2] DEFAULT ('') NOT NULL,
    [MFGR_PT_NO] CHAR (30) CONSTRAINT [DF__QTMFGR__MFGR_PT___563585EB] DEFAULT ('') NOT NULL,
    [SELECTED]   BIT       CONSTRAINT [DF__QTMFGR__SELECTED__5729AA24] DEFAULT ((0)) NOT NULL,
    [CHECKUSE]   BIT       CONSTRAINT [DF__QTMFGR__CHECKUSE__581DCE5D] DEFAULT ((0)) NOT NULL,
    [MATLTYPE]   CHAR (10) CONSTRAINT [DF__QTMFGR__MATLTYPE__5911F296] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTMFGR_PK] PRIMARY KEY CLUSTERED ([UNIQMFGRNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQDETNO]
    ON [dbo].[QTMFGR]([UNIQDETLNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTMFGR]([UNIQLINENO] ASC);

