CREATE TABLE [dbo].[QTNRE] (
    [UNIQLINENO] CHAR (10)       CONSTRAINT [DF__QTNRE__UNIQLINEN__5BEE5F41] DEFAULT ('') NOT NULL,
    [UNIQNRENO]  CHAR (10)       CONSTRAINT [DF__QTNRE__UNIQNRENO__5CE2837A] DEFAULT ('') NOT NULL,
    [DESCRIPT]   CHAR (35)       CONSTRAINT [DF__QTNRE__DESCRIPT__5DD6A7B3] DEFAULT ('') NOT NULL,
    [CHARGEAMT]  NUMERIC (10, 2) CONSTRAINT [DF__QTNRE__CHARGEAMT__5ECACBEC] DEFAULT ((0)) NOT NULL,
    [COST]       NUMERIC (10, 2) CONSTRAINT [DF__QTNRE__COST__5FBEF025] DEFAULT ((0)) NOT NULL,
    [MARKUPAMT]  NUMERIC (10, 2) CONSTRAINT [DF__QTNRE__MARKUPAMT__60B3145E] DEFAULT ((0)) NOT NULL,
    [NEWFLD]     CHAR (10)       CONSTRAINT [DF__QTNRE__NEWFLD__61A73897] DEFAULT ('') NOT NULL,
    [DEPT_ID]    CHAR (4)        CONSTRAINT [DF__QTNRE__DEPT_ID__629B5CD0] DEFAULT ('') NOT NULL,
    [USE_PCT]    BIT             CONSTRAINT [DF__QTNRE__USE_PCT__638F8109] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QTNRE_PK] PRIMARY KEY CLUSTERED ([UNIQNRENO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTNRE]([UNIQLINENO] ASC);

