CREATE TABLE [dbo].[QTOTHER] (
    [UNIQLINENO] CHAR (10)       CONSTRAINT [DF__QTOTHER__UNIQLIN__666BEDB4] DEFAULT ('') NOT NULL,
    [UNIQOTHER]  CHAR (10)       CONSTRAINT [DF__QTOTHER__UNIQOTH__676011ED] DEFAULT ('') NOT NULL,
    [OTHERDESCR] CHAR (25)       CONSTRAINT [DF__QTOTHER__OTHERDE__68543626] DEFAULT ('') NOT NULL,
    [CHARGEAMT]  NUMERIC (10, 2) CONSTRAINT [DF__QTOTHER__CHARGEA__69485A5F] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QTOTHER_PK] PRIMARY KEY CLUSTERED ([UNIQOTHER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTOTHER]([UNIQLINENO] ASC);

