CREATE TABLE [dbo].[QTPRODRELDOC] (
    [UNIQLINENO] CHAR (10)     CONSTRAINT [DF__QTPRODREL__UNIQL__1432B864] DEFAULT ('') NOT NULL,
    [DOC_UNIQ]   CHAR (10)     CONSTRAINT [DF__QTPRODREL__DOC_U__1526DC9D] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]   CHAR (10)     CONSTRAINT [DF__QTPRODREL__UNIQ___161B00D6] DEFAULT ('') NOT NULL,
    [DOCNO]      CHAR (25)     CONSTRAINT [DF__QTPRODREL__DOCNO__170F250F] DEFAULT ('') NOT NULL,
    [DOCREVNO]   CHAR (4)      CONSTRAINT [DF__QTPRODREL__DOCRE__18034948] DEFAULT ('') NOT NULL,
    [DOCDESCR]   CHAR (45)     CONSTRAINT [DF__QTPRODREL__DOCDE__18F76D81] DEFAULT ('') NOT NULL,
    [DOCDATE]    SMALLDATETIME NULL,
    [DOCNOTE]    TEXT          CONSTRAINT [DF__QTPRODREL__DOCNO__19EB91BA] DEFAULT ('') NOT NULL,
    [DOCEXEC]    CHAR (200)    CONSTRAINT [DF__QTPRODREL__DOCEX__1ADFB5F3] DEFAULT ('') NOT NULL,
    [DOCPDF]     CHAR (200)    CONSTRAINT [DF__QTPRODREL__DOCPD__1BD3DA2C] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTPRODRELDOC_PK] PRIMARY KEY CLUSTERED ([DOC_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTPRODRELDOC]([UNIQLINENO] ASC);

