CREATE TABLE [dbo].[QTREF] (
    [UNIQLINENO] CHAR (10)   CONSTRAINT [DF__QTREF__UNIQLINEN__31C31B4B] DEFAULT ('') NOT NULL,
    [UNIQDETLNO] CHAR (10)   CONSTRAINT [DF__QTREF__UNIQDETLN__32B73F84] DEFAULT ('') NOT NULL,
    [UNIQQTREF]  CHAR (10)   CONSTRAINT [DF__QTREF__UNIQQTREF__33AB63BD] DEFAULT ('') NOT NULL,
    [REF_DES]    CHAR (15)   CONSTRAINT [DF__QTREF__REF_DES__349F87F6] DEFAULT ('') NOT NULL,
    [NBR]        NUMERIC (7) CONSTRAINT [DF__QTREF__NBR__3593AC2F] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QTREF_PK] PRIMARY KEY CLUSTERED ([UNIQQTREF] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQDETLNO]
    ON [dbo].[QTREF]([UNIQDETLNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTREF]([UNIQLINENO] ASC);

