CREATE TABLE [dbo].[QTRELDOC] (
    [QUOTEUNIQ] CHAR (10)     CONSTRAINT [DF__QTRELDOC__QUOTEU__387018DA] DEFAULT ('') NOT NULL,
    [DOC_UNIQ]  CHAR (10)     CONSTRAINT [DF__QTRELDOC__DOC_UN__39643D13] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]  CHAR (10)     CONSTRAINT [DF__QTRELDOC__UNIQ_K__3A58614C] DEFAULT ('') NOT NULL,
    [DOCNO]     CHAR (25)     CONSTRAINT [DF__QTRELDOC__DOCNO__3B4C8585] DEFAULT ('') NOT NULL,
    [DOCREVNO]  CHAR (4)      CONSTRAINT [DF__QTRELDOC__DOCREV__3C40A9BE] DEFAULT ('') NOT NULL,
    [DOCDESCR]  CHAR (45)     CONSTRAINT [DF__QTRELDOC__DOCDES__3D34CDF7] DEFAULT ('') NOT NULL,
    [DOCDATE]   SMALLDATETIME NULL,
    [DOCNOTE]   TEXT          CONSTRAINT [DF__QTRELDOC__DOCNOT__3E28F230] DEFAULT ('') NOT NULL,
    [DOCEXEC]   CHAR (200)    CONSTRAINT [DF__QTRELDOC__DOCEXE__3F1D1669] DEFAULT ('') NOT NULL,
    [DOCPDF]    CHAR (200)    CONSTRAINT [DF__QTRELDOC__DOCPDF__40113AA2] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTRELDOC_PK] PRIMARY KEY CLUSTERED ([DOC_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [QUOTEUNIQ]
    ON [dbo].[QTRELDOC]([QUOTEUNIQ] ASC);

