CREATE TABLE [dbo].[QTSALESREP] (
    [UNIQQTSREP] CHAR (10)      CONSTRAINT [DF__QTSALESRE__UNIQQ__42EDA74D] DEFAULT ('') NOT NULL,
    [CID]        CHAR (10)      CONSTRAINT [DF__QTSALESREP__CID__43E1CB86] DEFAULT ('') NOT NULL,
    [UNIQLINENO] CHAR (10)      CONSTRAINT [DF__QTSALESRE__UNIQL__44D5EFBF] DEFAULT ('') NOT NULL,
    [CUSTNO]     CHAR (10)      CONSTRAINT [DF__QTSALESRE__CUSTN__45CA13F8] DEFAULT ('') NOT NULL,
    [COMMISSION] NUMERIC (9, 4) CONSTRAINT [DF__QTSALESRE__COMMI__46BE3831] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QTSALESREP_PK] PRIMARY KEY CLUSTERED ([UNIQQTSREP] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CID]
    ON [dbo].[QTSALESREP]([CID] ASC);


GO
CREATE NONCLUSTERED INDEX [CUSTNO]
    ON [dbo].[QTSALESREP]([CUSTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTSALESREP]([UNIQLINENO] ASC);

