CREATE TABLE [dbo].[QTSUPDTL] (
    [SUPDTLUNIQ]   CHAR (10)       CONSTRAINT [DF__QTSUPDTL__SUPDTL__499AA4DC] DEFAULT ('') NOT NULL,
    [UNIQLINENO]   CHAR (10)       CONSTRAINT [DF__QTSUPDTL__UNIQLI__4A8EC915] DEFAULT ('') NOT NULL,
    [UNIQSUPLNO]   CHAR (10)       CONSTRAINT [DF__QTSUPDTL__UNIQSU__4B82ED4E] DEFAULT ('') NOT NULL,
    [UNIQDETLNO]   CHAR (10)       CONSTRAINT [DF__QTSUPDTL__UNIQDE__4C771187] DEFAULT ('') NOT NULL,
    [UNIQMFGRNO]   CHAR (10)       CONSTRAINT [DF__QTSUPDTL__UNIQMF__4D6B35C0] DEFAULT ('') NOT NULL,
    [UNIQQTYNO]    CHAR (10)       CONSTRAINT [DF__QTSUPDTL__UNIQQT__4E5F59F9] DEFAULT ('') NOT NULL,
    [QTY]          NUMERIC (8)     CONSTRAINT [DF__QTSUPDTL__QTY__4F537E32] DEFAULT ((0)) NOT NULL,
    [QUOTEQTY]     NUMERIC (8)     CONSTRAINT [DF__QTSUPDTL__QUOTEQ__5047A26B] DEFAULT ((0)) NOT NULL,
    [PRICEEA]      NUMERIC (13, 5) CONSTRAINT [DF__QTSUPDTL__PRICEE__513BC6A4] DEFAULT ((0)) NOT NULL,
    [LEADTIME]     NUMERIC (3)     CONSTRAINT [DF__QTSUPDTL__LEADTI__522FEADD] DEFAULT ((0)) NOT NULL,
    [MINQTY]       NUMERIC (8)     CONSTRAINT [DF__QTSUPDTL__MINQTY__53240F16] DEFAULT ((0)) NOT NULL,
    [ORDMULT]      NUMERIC (8)     CONSTRAINT [DF__QTSUPDTL__ORDMUL__5418334F] DEFAULT ((0)) NOT NULL,
    [RFQNO]        CHAR (10)       CONSTRAINT [DF__QTSUPDTL__RFQNO__550C5788] DEFAULT ('') NOT NULL,
    [PR_SOURCE]    CHAR (13)       CONSTRAINT [DF__QTSUPDTL__PR_SOU__56007BC1] DEFAULT ('') NOT NULL,
    [CORRECTED_PN] CHAR (25)       CONSTRAINT [DF__QTSUPDTL__CORREC__56F49FFA] DEFAULT ('') NOT NULL,
    [ALTPN]        CHAR (25)       CONSTRAINT [DF__QTSUPDTL__ALTPN__57E8C433] DEFAULT ('') NOT NULL,
    [ALMFGR]       CHAR (8)        CONSTRAINT [DF__QTSUPDTL__ALMFGR__58DCE86C] DEFAULT ('') NOT NULL,
    [VQOH]         NUMERIC (12, 2) CONSTRAINT [DF__QTSUPDTL__VQOH__59D10CA5] DEFAULT ((0)) NOT NULL,
    [COMMENTS]     CHAR (50)       CONSTRAINT [DF__QTSUPDTL__COMMEN__5AC530DE] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTSUPDTL_PK] PRIMARY KEY CLUSTERED ([SUPDTLUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQDETLNO]
    ON [dbo].[QTSUPDTL]([UNIQDETLNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTSUPDTL]([UNIQLINENO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRNO]
    ON [dbo].[QTSUPDTL]([UNIQMFGRNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQQTYNO]
    ON [dbo].[QTSUPDTL]([UNIQQTYNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQSUPLNO]
    ON [dbo].[QTSUPDTL]([UNIQSUPLNO] ASC);

