CREATE TABLE [dbo].[QTSUPL] (
    [UNIQLINENO] CHAR (10) CONSTRAINT [DF__QTSUPL__UNIQLINE__5DA19D89] DEFAULT ('') NOT NULL,
    [UNIQSUPLNO] CHAR (10) CONSTRAINT [DF__QTSUPL__UNIQSUPL__5E95C1C2] DEFAULT ('') NOT NULL,
    [UNIQDETLNO] CHAR (10) CONSTRAINT [DF__QTSUPL__UNIQDETL__5F89E5FB] DEFAULT ('') NOT NULL,
    [UNIQMFGRNO] CHAR (10) CONSTRAINT [DF__QTSUPL__UNIQMFGR__607E0A34] DEFAULT ('') NOT NULL,
    [SELECTED]   BIT       CONSTRAINT [DF__QTSUPL__SELECTED__61722E6D] DEFAULT ((0)) NOT NULL,
    [SUPID]      CHAR (10) CONSTRAINT [DF__QTSUPL__SUPID__626652A6] DEFAULT ('') NOT NULL,
    [RFQNO]      CHAR (10) CONSTRAINT [DF__QTSUPL__RFQNO__635A76DF] DEFAULT ('') NOT NULL,
    [RFQUNIQ]    CHAR (10) CONSTRAINT [DF__QTSUPL__RFQUNIQ__644E9B18] DEFAULT ('') NOT NULL,
    CONSTRAINT [QTSUPL_PK] PRIMARY KEY CLUSTERED ([UNIQSUPLNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SUPID]
    ON [dbo].[QTSUPL]([SUPID] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQDETNO]
    ON [dbo].[QTSUPL]([UNIQDETLNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQLINENO]
    ON [dbo].[QTSUPL]([UNIQLINENO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQMFGRNO]
    ON [dbo].[QTSUPL]([UNIQMFGRNO] ASC);

