CREATE TABLE [dbo].[QUOTDPDT] (
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__QUOTDPDT__UNIQ_K__7E0E6D1B] DEFAULT ('') NOT NULL,
    [ACTIV_ID]   CHAR (4)        CONSTRAINT [DF__QUOTDPDT__ACTIV___7F029154] DEFAULT ('') NOT NULL,
    [RUNTIMASEC] NUMERIC (11, 3) CONSTRAINT [DF__QUOTDPDT__RUNTIM__7FF6B58D] DEFAULT ((0)) NOT NULL,
    [SETUPASEC]  NUMERIC (11, 3) CONSTRAINT [DF__QUOTDPDT__SETUPA__00EAD9C6] DEFAULT ((0)) NOT NULL,
    [NUMBERA]    NUMERIC (4)     CONSTRAINT [DF__QUOTDPDT__NUMBER__01DEFDFF] DEFAULT ((0)) NOT NULL,
    [UNIQNUMBER] CHAR (10)       CONSTRAINT [DF__QUOTDPDT__UNIQNU__02D32238] DEFAULT ('') NOT NULL,
    [STD_INSTR]  TEXT            CONSTRAINT [DF__QUOTDPDT__STD_IN__03C74671] DEFAULT ('') NOT NULL,
    [SPEC_INSTR] TEXT            CONSTRAINT [DF__QUOTDPDT__SPEC_I__04BB6AAA] DEFAULT ('') NOT NULL,
    [PROC_NOTE]  TEXT            CONSTRAINT [DF__QUOTDPDT__PROC_N__05AF8EE3] DEFAULT ('') NOT NULL,
    [STDIN_PICT] CHAR (200)      CONSTRAINT [DF__QUOTDPDT__STDIN___06A3B31C] DEFAULT ('') NOT NULL,
    [SPEC_PICT]  CHAR (200)      CONSTRAINT [DF__QUOTDPDT__SPEC_P__0797D755] DEFAULT ('') NOT NULL,
    [UNIQNBRA]   CHAR (10)       CONSTRAINT [DF__QUOTDPDT__UNIQNB__088BFB8E] DEFAULT ([dbo].[fn_generateuniquenumber]()) NOT NULL,
    [ACTSETTPID] CHAR (10)       CONSTRAINT [DF__QUOTDPDT__ACTSET__09801FC7] DEFAULT ('') NOT NULL,
    CONSTRAINT [QUOTDPDT_PK] PRIMARY KEY CLUSTERED ([UNIQNBRA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ASSYIDACNO]
    ON [dbo].[QUOTDPDT]([UNIQ_KEY] ASC, [UNIQNUMBER] ASC, [ACTIV_ID] ASC, [NUMBERA] ASC);


GO
CREATE NONCLUSTERED INDEX [ASSYIDACT]
    ON [dbo].[QUOTDPDT]([UNIQ_KEY] ASC, [UNIQNUMBER] ASC, [UNIQNBRA] ASC);


GO
CREATE NONCLUSTERED INDEX [ASSYIDNUMB]
    ON [dbo].[QUOTDPDT]([UNIQ_KEY] ASC, [UNIQNUMBER] ASC, [NUMBERA] ASC);


GO
CREATE NONCLUSTERED INDEX [ASSYNO]
    ON [dbo].[QUOTDPDT]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQNUMBER]
    ON [dbo].[QUOTDPDT]([UNIQNUMBER] ASC, [NUMBERA] ASC);


GO
CREATE NONCLUSTERED INDEX [UNNOACTV]
    ON [dbo].[QUOTDPDT]([UNIQ_KEY] ASC, [ACTIV_ID] ASC);

