CREATE TABLE [dbo].[QUOTDEPT] (
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__QUOTDEPT__UNIQ_K__672B07C3] DEFAULT ('') NOT NULL,
    [DEPT_ID]    CHAR (4)        CONSTRAINT [DF__QUOTDEPT__DEPT_I__681F2BFC] DEFAULT ('') NOT NULL,
    [RUNTIMESEC] NUMERIC (11, 3) CONSTRAINT [DF__QUOTDEPT__RUNTIM__69135035] DEFAULT ((0)) NOT NULL,
    [SETUPSEC]   NUMERIC (11, 3) CONSTRAINT [DF__QUOTDEPT__SETUPS__6A07746E] DEFAULT ((0)) NOT NULL,
    [NUMBER]     NUMERIC (4)     CONSTRAINT [DF__QUOTDEPT__NUMBER__6AFB98A7] DEFAULT ((0)) NOT NULL,
    [UNIQNUMBER] CHAR (10)       CONSTRAINT [DF__QUOTDEPT__UNIQNU__6BEFBCE0] DEFAULT ([dbo].[fn_generateuniquenumber]()) NOT NULL,
    [STD_INSTR]  TEXT            CONSTRAINT [DF__QUOTDEPT__STD_IN__6CE3E119] DEFAULT ('') NOT NULL,
    [SPEC_INSTR] TEXT            CONSTRAINT [DF__QUOTDEPT__SPEC_I__6DD80552] DEFAULT ('') NOT NULL,
    [PROC_NOTE]  TEXT            CONSTRAINT [DF__QUOTDEPT__PROC_N__6ECC298B] DEFAULT ('') NOT NULL,
    [REVDATE]    SMALLDATETIME   NULL,
    [REVINIT]    CHAR (8)        CONSTRAINT [DF__QUOTDEPT__REVINI__6FC04DC4] DEFAULT ('') NULL,
    [PEREVNO]    CHAR (4)        CONSTRAINT [DF__QUOTDEPT__PEREVN__70B471FD] DEFAULT ('') NOT NULL,
    [MARG_AMT]   NUMERIC (12, 2) CONSTRAINT [DF__QUOTDEPT__MARG_A__71A89636] DEFAULT ((0)) NOT NULL,
    [TOT_AMOUNT] NUMERIC (12, 2) CONSTRAINT [DF__QUOTDEPT__TOT_AM__729CBA6F] DEFAULT ((0)) NOT NULL,
    [MARG_PERC]  NUMERIC (6, 2)  CONSTRAINT [DF__QUOTDEPT__MARG_P__7390DEA8] DEFAULT ((0)) NOT NULL,
    [WCSETUPID]  CHAR (10)       CONSTRAINT [DF__QUOTDEPT__WCSETU__748502E1] DEFAULT ('') NOT NULL,
    [STDIN_PICT] CHAR (200)      CONSTRAINT [DF__QUOTDEPT__STDIN___7579271A] DEFAULT ('') NOT NULL,
    [SPEC_PICT]  CHAR (200)      CONSTRAINT [DF__QUOTDEPT__SPEC_P__766D4B53] DEFAULT ('') NOT NULL,
    [CERTIFICAT] BIT             CONSTRAINT [DF__QUOTDEPT__CERTIF__77616F8C] DEFAULT ((0)) NOT NULL,
    [OUTSFOOTNT] TEXT            CONSTRAINT [DF__QUOTDEPT__OUTSFO__785593C5] DEFAULT ('') NOT NULL,
    [PARTPERUNT] NUMERIC (6)     CONSTRAINT [DF__QUOTDEPT__PARTPE__7949B7FE] DEFAULT ((0)) NOT NULL,
    [SERIALSTRT] BIT             CONSTRAINT [DF__QUOTDEPT__SERIAL__7A3DDC37] DEFAULT ((0)) NOT NULL,
    [SPEC_NO]    CHAR (10)       CONSTRAINT [DF__QUOTDEPT__SPEC_N__7B320070] DEFAULT ('') NOT NULL,
    [uniqueRout] CHAR (10)       CONSTRAINT [DF_QUOTDEPT_uniqueRout] DEFAULT ('') NOT NULL,
    [IsOptional] BIT             CONSTRAINT [DF__QUOTDEPT__IsOpti__788DCB4B] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [QUOTDEPT_PK] PRIMARY KEY CLUSTERED ([UNIQNUMBER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INVENTOR]
    ON [dbo].[QUOTDEPT]([UNIQ_KEY] ASC, [NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [NUMBER]
    ON [dbo].[QUOTDEPT]([NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [PART]
    ON [dbo].[QUOTDEPT]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [PARTNODEPT]
    ON [dbo].[QUOTDEPT]([UNIQ_KEY] ASC, [DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQNUMBER]
    ON [dbo].[QUOTDEPT]([UNIQ_KEY] ASC, [UNIQNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [uniquerout]
    ON [dbo].[QUOTDEPT]([uniqueRout] ASC);

