CREATE TABLE [dbo].[REPORTS] (
    [RPTTYPE]       CHAR (6)      CONSTRAINT [DF_REPORTS_RPTTYPE] DEFAULT ('') NOT NULL,
    [OPTIONS]       CHAR (1)      CONSTRAINT [DF_REPORTS_OPTIONS] DEFAULT ('') NOT NULL,
    [TYPE]          CHAR (15)     CONSTRAINT [DF_REPORTS_TYPE] DEFAULT ('') NOT NULL,
    [SEQUENCE]      NUMERIC (2)   CONSTRAINT [DF_REPORTS_SEQUENCE] DEFAULT ((0)) NOT NULL,
    [TITLE]         CHAR (50)     CONSTRAINT [DF_REPORTS_TITLE] DEFAULT ('') NOT NULL,
    [COMMENTS]      VARCHAR (254) CONSTRAINT [DF_REPORTS_COMMENTS] DEFAULT ('') NOT NULL,
    [RPTNAME]       CHAR (15)     CONSTRAINT [DF_REPORTS_RPTNAME] DEFAULT ('') NOT NULL,
    [RPTDETAIL]     CHAR (15)     CONSTRAINT [DF_REPORTS_RPTDETAIL] DEFAULT ('') NOT NULL,
    [TYPE2]         CHAR (15)     CONSTRAINT [DF_REPORTS_TYPE2] DEFAULT ('') NOT NULL,
    [TITLE2]        CHAR (50)     CONSTRAINT [DF_REPORTS_TITLE2] DEFAULT ('') NOT NULL,
    [COMMENTS2]     VARCHAR (254) CONSTRAINT [DF_REPORTS_COMMENTS2] DEFAULT ('') NOT NULL,
    [ASKDATE]       BIT           CONSTRAINT [DF_REPORTS_ASKDATE] DEFAULT ((0)) NOT NULL,
    [LABEL]         CHAR (1)      CONSTRAINT [DF_REPORTS_LABEL] DEFAULT ('') NOT NULL,
    [SECTION]       CHAR (4)      CONSTRAINT [DF_REPORTS_SECTION] DEFAULT ('') NOT NULL,
    [SHOW]          BIT           CONSTRAINT [DF_REPORTS_SHOW] DEFAULT ((0)) NOT NULL,
    [MULTIPLEEMAIL] BIT           CONSTRAINT [DF_REPORTS_MULTIPLEEMAIL] DEFAULT ((0)) NOT NULL,
    [ROLLLABEL]     BIT           CONSTRAINT [DF_REPORTS_ROLLLABEL] DEFAULT ((0)) NOT NULL,
    [UNIQUENUM]     INT           IDENTITY (1, 1) NOT NULL,
    [filepath]      VARCHAR (254) CONSTRAINT [DF_REPORTS_filepath] DEFAULT ('') NOT NULL,
    [lIS_cr]        BIT           CONSTRAINT [DF_REPORTS_LIS_CR] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [REPORTS_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RPTDETAIL]
    ON [dbo].[REPORTS]([RPTDETAIL] ASC);


GO
CREATE NONCLUSTERED INDEX [RPTNAME]
    ON [dbo].[REPORTS]([RPTNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [SEQUENCE]
    ON [dbo].[REPORTS]([TYPE] ASC, [SEQUENCE] ASC);


GO
CREATE NONCLUSTERED INDEX [TYPE]
    ON [dbo].[REPORTS]([TYPE] ASC);

