CREATE TABLE [dbo].[RFQQTY] (
    [RFQUNIQ]      CHAR (10)       CONSTRAINT [DF__RFQQTY__RFQUNIQ__3EE80C3F] DEFAULT ('') NOT NULL,
    [RFQDTLUNIQ]   CHAR (10)       CONSTRAINT [DF__RFQQTY__RFQDTLUN__3FDC3078] DEFAULT ('') NOT NULL,
    [RFQQTYUNIQ]   CHAR (10)       CONSTRAINT [DF__RFQQTY__RFQQTYUN__40D054B1] DEFAULT ('') NOT NULL,
    [NEEDQTY]      NUMERIC (8)     CONSTRAINT [DF__RFQQTY__NEEDQTY__41C478EA] DEFAULT ((0)) NOT NULL,
    [QUOTEQTY]     NUMERIC (8)     CONSTRAINT [DF__RFQQTY__QUOTEQTY__42B89D23] DEFAULT ((0)) NOT NULL,
    [PRICEEA]      NUMERIC (13, 5) CONSTRAINT [DF__RFQQTY__PRICEEA__43ACC15C] DEFAULT ((0)) NOT NULL,
    [LEADTIME]     NUMERIC (3)     CONSTRAINT [DF__RFQQTY__LEADTIME__44A0E595] DEFAULT ((0)) NOT NULL,
    [MINQTY]       NUMERIC (8)     CONSTRAINT [DF__RFQQTY__MINQTY__459509CE] DEFAULT ((0)) NOT NULL,
    [ORDMULT]      NUMERIC (8)     CONSTRAINT [DF__RFQQTY__ORDMULT__46892E07] DEFAULT ((0)) NOT NULL,
    [SUPDTLUNIQ]   CHAR (10)       CONSTRAINT [DF__RFQQTY__SUPDTLUN__477D5240] DEFAULT ('') NOT NULL,
    [CORRECTED_PN] CHAR (25)       CONSTRAINT [DF__RFQQTY__CORRECTE__48717679] DEFAULT ('') NOT NULL,
    [ALTPN]        CHAR (25)       CONSTRAINT [DF__RFQQTY__ALTPN__49659AB2] DEFAULT ('') NOT NULL,
    [ALMFGR]       CHAR (8)        CONSTRAINT [DF__RFQQTY__ALMFGR__4A59BEEB] DEFAULT ('') NOT NULL,
    [VQOH]         NUMERIC (12, 2) CONSTRAINT [DF__RFQQTY__VQOH__4B4DE324] DEFAULT ((0)) NOT NULL,
    [COMMENTS]     CHAR (50)       CONSTRAINT [DF__RFQQTY__COMMENTS__4C42075D] DEFAULT ('') NOT NULL,
    CONSTRAINT [RFQQTY_PK] PRIMARY KEY CLUSTERED ([RFQQTYUNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RFQDTLUNIQ]
    ON [dbo].[RFQQTY]([RFQDTLUNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [RFQUNIQ]
    ON [dbo].[RFQQTY]([RFQUNIQ] ASC);

