CREATE TABLE [dbo].[RIGHTS] (
    [SVIEW]        BIT       CONSTRAINT [DF__RIGHTS__SVIEW__51FAE0B3] DEFAULT ((0)) NOT NULL,
    [SEDIT]        BIT       CONSTRAINT [DF__RIGHTS__SEDIT__52EF04EC] DEFAULT ((0)) NOT NULL,
    [SCOPY]        BIT       CONSTRAINT [DF__RIGHTS__SCOPY__53E32925] DEFAULT ((0)) NOT NULL,
    [SADD]         BIT       CONSTRAINT [DF__RIGHTS__SADD__54D74D5E] DEFAULT ((0)) NOT NULL,
    [SDELETE]      BIT       CONSTRAINT [DF__RIGHTS__SDELETE__55CB7197] DEFAULT ((0)) NOT NULL,
    [RVIEW]        BIT       CONSTRAINT [DF__RIGHTS__RVIEW__56BF95D0] DEFAULT ((0)) NOT NULL,
    [RPRINT]       BIT       CONSTRAINT [DF__RIGHTS__RPRINT__57B3BA09] DEFAULT ((0)) NOT NULL,
    [RFAX]         BIT       CONSTRAINT [DF__RIGHTS__RFAX__58A7DE42] DEFAULT ((0)) NOT NULL,
    [RCREATE]      BIT       CONSTRAINT [DF__RIGHTS__RCREATE__599C027B] DEFAULT ((0)) NOT NULL,
    [FINANCDATA]   BIT       CONSTRAINT [DF__RIGHTS__FINANCDA__5A9026B4] DEFAULT ((0)) NOT NULL,
    [SALL]         BIT       CONSTRAINT [DF__RIGHTS__SALL__5B844AED] DEFAULT ((0)) NOT NULL,
    [RALL]         BIT       CONSTRAINT [DF__RIGHTS__RALL__5C786F26] DEFAULT ((0)) NOT NULL,
    [DEPTS]        CHAR (4)  CONSTRAINT [DF__RIGHTS__DEPTS__5D6C935F] DEFAULT ('') NOT NULL,
    [REMAIL]       BIT       CONSTRAINT [DF__RIGHTS__REMAIL__5E60B798] DEFAULT ((0)) NOT NULL,
    [RFILE]        BIT       CONSTRAINT [DF__RIGHTS__RFILE__5F54DBD1] DEFAULT ((0)) NOT NULL,
    [UNIQ_RIGHT]   CHAR (10) CONSTRAINT [DF__RIGHTS__UNIQ_RIG__6049000A] DEFAULT ('') NOT NULL,
    [FK_uniqUser]  CHAR (10) CONSTRAINT [DF_RIGHTS_FK_uniqUser] DEFAULT ('') NOT NULL,
    [Fk_Uniquenum] INT       CONSTRAINT [DF_RIGHTS_Fk_Uniquenum] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [RIGHTS_PK] PRIMARY KEY CLUSTERED ([UNIQ_RIGHT] ASC)
);

