CREATE TABLE [dbo].[SALETYPE] (
    [SALETYPEID] CHAR (10) CONSTRAINT [DF_SALETYPE_SALETYPEID] DEFAULT ('') NOT NULL,
    [GL_NBR]     CHAR (13) CONSTRAINT [DF_SALETYPE_GL_NBR] DEFAULT ('') NOT NULL,
    [COG_GL_NBR] CHAR (13) CONSTRAINT [DF_SALETYPE_COG_GL_NBR] DEFAULT ('') NOT NULL,
    [UNIQUENUM]  INT       IDENTITY (1, 1) NOT NULL,
    [IsQbSync]   BIT       CONSTRAINT [DF__SALETYPE__IsQbSy__36BF3C97] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SALETYPE_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SALETYPEID]
    ON [dbo].[SALETYPE]([SALETYPEID] ASC);

