CREATE TABLE [dbo].[SALEDSCT] (
    [SALEDSCTID] CHAR (10)      CONSTRAINT [DF__SALEDSCT__SALEDS__7FC1AB63] DEFAULT ('') NOT NULL,
    [SALEDSCTNM] CHAR (25)      CONSTRAINT [DF__SALEDSCT__SALEDS__00B5CF9C] DEFAULT ('') NOT NULL,
    [DISCOUNT]   NUMERIC (5, 2) CONSTRAINT [DF__SALEDSCT__DISCOU__01A9F3D5] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SALEDSCT_PK] PRIMARY KEY CLUSTERED ([SALEDSCTID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SALEDSCTNM]
    ON [dbo].[SALEDSCT]([SALEDSCTNM] ASC);

