CREATE TABLE [dbo].[SALEDFLT] (
    [SREPCOMMBY] CHAR (1)  CONSTRAINT [DF__SALEDFLT__SREPCO__7AFCF646] DEFAULT ('') NOT NULL,
    [PRINTPRDT]  BIT       CONSTRAINT [DF__SALEDFLT__PRINTP__7BF11A7F] DEFAULT ((0)) NOT NULL,
    [UNIQUEREC]  CHAR (10) CONSTRAINT [DF__SALEDFLT__UNIQUE__7CE53EB8] DEFAULT ('') NOT NULL,
    CONSTRAINT [SALEDFLT_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);

