CREATE TABLE [dbo].[SCREENHLP] (
    [SCREENNAME]  CHAR (25)  CONSTRAINT [DF__SCREENHLP__SCREE__49A591D4] DEFAULT ('') NOT NULL,
    [HELPADDRESS] CHAR (250) CONSTRAINT [DF__SCREENHLP__HELPA__4A99B60D] DEFAULT ('') NOT NULL,
    [UNIQUENUM]   INT        IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [SCREENHLP_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SCREENNAME]
    ON [dbo].[SCREENHLP]([SCREENNAME] ASC);

