CREATE TABLE [dbo].[SECURITYSET] (
    [NMINPASSWORD]   INT       CONSTRAINT [DF__SECURITYS__NMINP__2BA02DA1] DEFAULT ((1)) NOT NULL,
    [NPRIORTOEXPIRE] INT       CONSTRAINT [DF__SECURITYS__NPRIO__2C9451DA] DEFAULT ((0)) NOT NULL,
    [UNIQUEREC]      CHAR (10) CONSTRAINT [DF__SECURITYS__UNIQU__2D887613] DEFAULT ('') NOT NULL,
    CONSTRAINT [SECURITYSET_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);

