CREATE TABLE [dbo].[SERLCONF] (
    [SERIALNO]   CHAR (30) CONSTRAINT [DF__SERLCONF__SERIAL__3064E2BE] DEFAULT ('') NOT NULL,
    [WONO]       CHAR (10) CONSTRAINT [DF__SERLCONF__WONO__315906F7] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]   CHAR (10) CONSTRAINT [DF__SERLCONF__UNIQ_K__324D2B30] DEFAULT ('') NOT NULL,
    [TRACKNO]    CHAR (30) CONSTRAINT [DF__SERLCONF__TRACKN__33414F69] DEFAULT ('') NOT NULL,
    [COMMENT]    CHAR (30) CONSTRAINT [DF__SERLCONF__COMMEN__343573A2] DEFAULT ('') NOT NULL,
    [PART_NO]    CHAR (25) CONSTRAINT [DF__SERLCONF__PART_N__352997DB] DEFAULT ('') NOT NULL,
    [REVISION]   CHAR (8)  CONSTRAINT [DF__SERLCONF__REVISI__361DBC14] DEFAULT ('') NOT NULL,
    [UNIQCONFIG] CHAR (10) CONSTRAINT [DF__SERLCONF__UNIQCO__3711E04D] DEFAULT ('') NOT NULL,
    [SerialUniq] CHAR (10) CONSTRAINT [DF_SERLCONF_SerialUniq] DEFAULT ('') NOT NULL,
    CONSTRAINT [SERLCONF_PK] PRIMARY KEY CLUSTERED ([UNIQCONFIG] ASC)
);

