CREATE TABLE [dbo].[SERLNPF] (
    [SERIALUNIQ] CHAR (10)   CONSTRAINT [DF__SERLNPF__SERIALU__39EE4CF8] DEFAULT ('') NOT NULL,
    [DEPT_ID]    CHAR (4)    CONSTRAINT [DF__SERLNPF__DEPT_ID__3AE27131] DEFAULT ('') NOT NULL,
    [NPFNO]      NUMERIC (3) CONSTRAINT [DF__SERLNPF__NPFNO__3BD6956A] DEFAULT ((0)) NOT NULL,
    [SERLNPFUK]  CHAR (10)   CONSTRAINT [DF__SERLNPF__SERLNPF__3CCAB9A3] DEFAULT ('') NOT NULL,
    [Wono]       CHAR (10)   CONSTRAINT [DF__SERLNPF__Wono__4CA1FA10] DEFAULT ('') NOT NULL,
    CONSTRAINT [SERLNPF_PK] PRIMARY KEY CLUSTERED ([SERLNPFUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SERLDEPTID]
    ON [dbo].[SERLNPF]([SERIALUNIQ] ASC, [DEPT_ID] ASC);

