CREATE TABLE [dbo].[SHOPFSET] (
    [XXSHPPRINT] BIT              CONSTRAINT [DF__SHOPFSET__XXSHPP__6F563970] DEFAULT ((0)) NOT NULL,
    [XXQTY_PANL] BIT              CONSTRAINT [DF__SHOPFSET__XXQTY___704A5DA9] DEFAULT ((0)) NOT NULL,
    [XXSHPRINST] BIT              CONSTRAINT [DF__SHOPFSET__XXSHPR__713E81E2] DEFAULT ((0)) NOT NULL,
    [XXPRCSTIME] NUMERIC (1)      CONSTRAINT [DF__SHOPFSET__XXPRCS__7232A61B] DEFAULT ((0)) NOT NULL,
    [XXLBLPRNT]  BIT              CONSTRAINT [DF__SHOPFSET__XXLBLP__7326CA54] DEFAULT ((0)) NOT NULL,
    [XPRIMODFLD] CHAR (10)        CONSTRAINT [DF__SHOPFSET__XPRIMO__741AEE8D] DEFAULT ('') NOT NULL,
    [XXAVGDAY]   NUMERIC (2)      CONSTRAINT [DF__SHOPFSET__XXAVGD__750F12C6] DEFAULT ((0)) NOT NULL,
    [XXBARCODE]  NUMERIC (1)      CONSTRAINT [DF__SHOPFSET__XXBARC__760336FF] DEFAULT ((0)) NOT NULL,
    [INTERVALTM] NUMERIC (4, 1)   CONSTRAINT [DF__SHOPFSET__INTERV__76F75B38] DEFAULT ((0)) NOT NULL,
    [XXOVERHEAD] BIT              CONSTRAINT [DF__SHOPFSET__XXOVER__77EB7F71] DEFAULT ((0)) NOT NULL,
    [XXSNASSIGN] CHAR (1)         CONSTRAINT [DF__SHOPFSET__XXSNAS__78DFA3AA] DEFAULT ('') NOT NULL,
    [XXWCORACTV] CHAR (1)         CONSTRAINT [DF__SHOPFSET__XXWCOR__79D3C7E3] DEFAULT ('') NOT NULL,
    [INUPDATE]   BIT              CONSTRAINT [DF__SHOPFSET__INUPDA__7AC7EC1C] DEFAULT ((0)) NOT NULL,
    [UPDATEBY]   UNIQUEIDENTIFIER NULL,
    [UPDATETIME] SMALLDATETIME    NULL,
    [UPDSCREEN]  CHAR (20)        CONSTRAINT [DF__SHOPFSET__UPDSCR__7CB0348E] DEFAULT ('') NOT NULL,
    [XXPOPPRINT] BIT              CONSTRAINT [DF__SHOPFSET__XXPOPP__7DA458C7] DEFAULT ((0)) NOT NULL,
    [XXUSEWOCHK] BIT              CONSTRAINT [DF__SHOPFSET__XXUSEW__7E987D00] DEFAULT ((0)) NOT NULL,
    [UNIQUEREC]  CHAR (10)        CONSTRAINT [DF__SHOPFSET__UNIQUE__7F8CA139] DEFAULT ('') NOT NULL,
    CONSTRAINT [SHOPFSET_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);

