CREATE TABLE [dbo].[SHOPFCHK] (
    [SHOPFL_CHK] CHAR (25) CONSTRAINT [DF__SHOPFCHK1__SHOPF__3692BD60] DEFAULT ('') NOT NULL,
    [UNIQUENUM]  INT       IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [SHOPFCHK_PK] PRIMARY KEY CLUSTERED ([UNIQUENUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SHOPFL_CHK]
    ON [dbo].[SHOPFCHK]([SHOPFL_CHK] ASC);

