CREATE TABLE [dbo].[SICCODES] (
    [SIC_CODE]  CHAR (5)  CONSTRAINT [DF__SICCODES__SIC_CO__02690DE4] DEFAULT ('') NOT NULL,
    [SIC_DESC]  CHAR (25) CONSTRAINT [DF__SICCODES__SIC_DE__035D321D] DEFAULT ('') NOT NULL,
    [SICCODEUK] CHAR (10) CONSTRAINT [DF__SICCODES__SICCOD__04515656] DEFAULT ('') NOT NULL,
    CONSTRAINT [SICCODES_PK] PRIMARY KEY CLUSTERED ([SICCODEUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SIC_CODE]
    ON [dbo].[SICCODES]([SIC_CODE] ASC);

