CREATE TABLE [dbo].[SINVDETL] (
    [SDET_UNIQ]    CHAR (10)       CONSTRAINT [DF__SINVDETL__SDET_U__072DC301] DEFAULT ('') NOT NULL,
    [SINV_UNIQ]    CHAR (10)       CONSTRAINT [DF__SINVDETL__SINV_U__0821E73A] DEFAULT ('') NOT NULL,
    [UNIQLNNO]     CHAR (10)       CONSTRAINT [DF__SINVDETL__UNIQLN__09160B73] DEFAULT ('') NOT NULL,
    [TRANSNO]      NUMERIC (8)     CONSTRAINT [DF__SINVDETL__TRANSN__0A0A2FAC] DEFAULT ((0)) NOT NULL,
    [UNIQDETNO]    CHAR (10)       CONSTRAINT [DF__SINVDETL__UNIQDE__0AFE53E5] DEFAULT ('') NOT NULL,
    [TRANS_DATE]   SMALLDATETIME   NULL,
    [ACPT_QTY]     NUMERIC (12, 2) CONSTRAINT [DF__SINVDETL__ACPT_Q__1B34BBAE] DEFAULT ((0)) NOT NULL,
    [COSTEACH]     NUMERIC (13, 5) CONSTRAINT [DF__SINVDETL__COSTEA__1D1D0420] DEFAULT ((0)) NOT NULL,
    [IS_TAX]       BIT             CONSTRAINT [DF__SINVDETL__IS_TAX__1E112859] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTAL]   NUMERIC (12, 2) CONSTRAINT [DF__SINVDETL__ITEM_T__1F054C92] DEFAULT ((0)) NOT NULL,
    [TRANS_NO]     NUMERIC (10)    CONSTRAINT [DF__SINVDETL__TRANS___20ED9504] DEFAULT ((0)) NOT NULL,
    [GL_NBR]       CHAR (13)       CONSTRAINT [DF__SINVDETL__GL_NBR__21E1B93D] DEFAULT ('') NOT NULL,
    [DMR_NO]       CHAR (10)       CONSTRAINT [DF__SINVDETL__DMR_NO__2982DB05] DEFAULT ('') NOT NULL,
    [RMA_DATE]     SMALLDATETIME   NULL,
    [RET_QTY]      NUMERIC (12)    CONSTRAINT [DF__SINVDETL__RET_QT__2A76FF3E] DEFAULT ((0)) NOT NULL,
    [LOC_UNIQ]     CHAR (10)       CONSTRAINT [DF__SINVDETL__LOC_UN__2B6B2377] DEFAULT ('') NOT NULL,
    [ORGACPTQTY]   NUMERIC (12, 2) CONSTRAINT [DF__SINVDETL__ORGACP__2C5F47B0] DEFAULT ((0)) NOT NULL,
    [COSTEACHFC]   NUMERIC (13, 5) CONSTRAINT [DF__SINVDETL__COSTEA__1B4073FD] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTALFC] NUMERIC (12, 2) CONSTRAINT [DF__SINVDETL__ITEM_T__1C349836] DEFAULT ((0)) NOT NULL,
    [item_desc]    VARCHAR (45)    CONSTRAINT [DF_SINVDETL_item_desc] DEFAULT ('') NOT NULL,
    [COSTEACHPR]   NUMERIC (13, 5) CONSTRAINT [DF__SINVDETL__COSTEA__338E9588] DEFAULT ((0)) NOT NULL,
    [ITEM_TOTALPR] NUMERIC (12, 2) CONSTRAINT [DF__SINVDETL__ITEM_T__3482B9C1] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SINVDETL_PK] PRIMARY KEY CLUSTERED ([SDET_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SINV_UNIQ]
    ON [dbo].[SINVDETL]([SINV_UNIQ] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQLNNO]
    ON [dbo].[SINVDETL]([UNIQLNNO] ASC);


GO
CREATE TRIGGER dbo.Sinvdetl_Insert
   ON  sinvdetl
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for trigger here
    UPDATE PORECLOC set SINV_UNIQ=INSERTED.Sinv_uniq,SDET_UNIQ =Inserted.sdet_uniq from inserted WHERE Inserted.LOC_UNIQ=Porecloc.LOC_UNIQ 
END