CREATE TABLE [dbo].[SINVOICE] (
    [SINV_UNIQ]       CHAR (10)       CONSTRAINT [DF__SINVOICE__SINV_U__2F3BB45B] DEFAULT ('') NOT NULL,
    [TRANSNO]         CHAR (8)        CONSTRAINT [DF__SINVOICE__TRANSN__302FD894] DEFAULT ('') NOT NULL,
    [TRANS_DT]        SMALLDATETIME   NULL,
    [INVNO]           CHAR (20)       CONSTRAINT [DF__SINVOICE__INVNO__34006978] DEFAULT ('') NOT NULL,
    [SUPPKNO]         CHAR (15)       CONSTRAINT [DF__SINVOICE__SUPPKN__34F48DB1] DEFAULT ('') NOT NULL,
    [TERMS]           CHAR (15)       CONSTRAINT [DF__SINVOICE__TERMS__36DCD623] DEFAULT ('') NOT NULL,
    [DUE_DATE]        SMALLDATETIME   NULL,
    [SUBTOTAL]        NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__SUBTOT__37D0FA5C] DEFAULT ((0)) NOT NULL,
    [TAX]             NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__TAX__38C51E95] DEFAULT ((0)) NOT NULL,
    [FREIGHT]         NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__FREIGH__39B942CE] DEFAULT ((0)) NOT NULL,
    [INVDATE]         SMALLDATETIME   NULL,
    [INVAMOUNT]       NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__INVAMO__3AAD6707] DEFAULT ((0)) NOT NULL,
    [FREIGHTGL]       CHAR (13)       CONSTRAINT [DF__SINVOICE__FREIGH__3BA18B40] DEFAULT ('') NOT NULL,
    [APTYPE]          CHAR (10)       CONSTRAINT [DF__SINVOICE__APTYPE__3C95AF79] DEFAULT ('') NOT NULL,
    [IS_REL_GL]       BIT             CONSTRAINT [DF__SINVOICE__IS_REL__3D89D3B2] DEFAULT ((0)) NOT NULL,
    [RECON_DATE]      SMALLDATETIME   NULL,
    [SAVEINIT]        CHAR (8)        CONSTRAINT [DF__SINVOICE__SAVEIN__3E7DF7EB] DEFAULT ('') NULL,
    [DISCOUNT]        NUMERIC (10, 2) CONSTRAINT [DF__SINVOICE__DISCOU__3F721C24] DEFAULT ((0)) NOT NULL,
    [VDISC_GL_N]      CHAR (13)       CONSTRAINT [DF__SINVOICE__VDISC___4066405D] DEFAULT ('') NOT NULL,
    [FOB]             CHAR (15)       CONSTRAINT [DF__SINVOICE__FOB__415A6496] DEFAULT ('') NOT NULL,
    [SHIPVIA]         CHAR (15)       CONSTRAINT [DF__SINVOICE__SHIPVI__424E88CF] DEFAULT ('') NOT NULL,
    [INVNOTE]         TEXT            CONSTRAINT [DF__SINVOICE__INVNOT__4342AD08] DEFAULT ('') NOT NULL,
    [FRTTAXAMT]       NUMERIC (10, 2) CONSTRAINT [DF__SINVOICE__FRTTAX__4436D141] DEFAULT ((0)) NOT NULL,
    [FRTTAXGL]        CHAR (13)       CONSTRAINT [DF__SINVOICE__FRTTAX__452AF57A] DEFAULT ('') NOT NULL,
    [IS_REL_AP]       BIT             CONSTRAINT [DF__SINVOICE__IS_REL__461F19B3] DEFAULT ((0)) NOT NULL,
    [TAX_PCT]         NUMERIC (8, 2)  CONSTRAINT [DF__SINVOICE__TAX_PC__4CCC1742] DEFAULT ((0)) NOT NULL,
    [fk_uniqaphead]   CHAR (10)       CONSTRAINT [DF_SINVOICE_fk_uniqaphead] DEFAULT ('') NOT NULL,
    [ENTRYDATE]       SMALLDATETIME   NULL,
    [receiverno]      CHAR (10)       CONSTRAINT [DF_SINVOICE_receiverno] DEFAULT ('') NOT NULL,
    [RecVer]          ROWVERSION      NOT NULL,
    [SUBTOTALFC]      NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__SUBTOT__1D28BC6F] DEFAULT ((0)) NOT NULL,
    [TAXFC]           NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__TAXFC__1E1CE0A8] DEFAULT ((0)) NOT NULL,
    [FREIGHTFC]       NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__FREIGH__1F1104E1] DEFAULT ((0)) NOT NULL,
    [INVAMOUNTFC]     NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__INVAMO__2005291A] DEFAULT ((0)) NOT NULL,
    [DISCOUNTFC]      NUMERIC (10, 2) CONSTRAINT [DF__SINVOICE__DISCOU__20F94D53] DEFAULT ((0)) NOT NULL,
    [FRTTAXAMTFC]     NUMERIC (10, 2) CONSTRAINT [DF__SINVOICE__FRTTAX__21ED718C] DEFAULT ((0)) NOT NULL,
    [FcUsed_uniq]     CHAR (10)       CONSTRAINT [DF__SINVOICE__FcUsed__22E195C5] DEFAULT ('') NOT NULL,
    [Fchist_key]      CHAR (10)       CONSTRAINT [DF__SINVOICE__Fchist__23D5B9FE] DEFAULT ('') NOT NULL,
    [SUBTOTALPR]      NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__SUBTOT__2A052B4E] DEFAULT ((0)) NOT NULL,
    [TAXPR]           NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__TAXPR__2AF94F87] DEFAULT ((0)) NOT NULL,
    [FREIGHTPR]       NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__FREIGH__2BED73C0] DEFAULT ((0)) NOT NULL,
    [INVAMOUNTPR]     NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__INVAMO__2CE197F9] DEFAULT ((0)) NOT NULL,
    [DISCOUNTPR]      NUMERIC (10, 2) CONSTRAINT [DF__SINVOICE__DISCOU__2DD5BC32] DEFAULT ((0)) NOT NULL,
    [FRTTAXAMTPR]     NUMERIC (12, 2) CONSTRAINT [DF__SINVOICE__FRTTAX__2EC9E06B] DEFAULT ((0)) NOT NULL,
    [PRFcused_Uniq]   CHAR (10)       CONSTRAINT [DF__SINVOICE__PRFcus__2FBE04A4] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__SINVOICE__FUNCFC__30B228DD] DEFAULT ('') NOT NULL,
    CONSTRAINT [SINVOICE_PK] PRIMARY KEY CLUSTERED ([SINV_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INVNO]
    ON [dbo].[SINVOICE]([INVNO] ASC);


GO
CREATE NONCLUSTERED INDEX [receiverno]
    ON [dbo].[SINVOICE]([receiverno] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQAPHEAD]
    ON [dbo].[SINVOICE]([fk_uniqaphead] ASC);

