CREATE TABLE [dbo].[SINVDETLTAX] (
    [UNIQSINVDETLTAX] CHAR (10)      CONSTRAINT [DF__SINVDETLT__UNIQS__15879AA7] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [SINV_UNIQ]       CHAR (10)      CONSTRAINT [DF__SINVDETLT__SINV___167BBEE0] DEFAULT ('') NOT NULL,
    [SDET_UNIQ]       CHAR (10)      CONSTRAINT [DF__SINVDETLT__SDET___176FE319] DEFAULT ('') NOT NULL,
    [TAX_ID]          CHAR (8)       CONSTRAINT [DF__SINVDETLT__TAX_I__18640752] DEFAULT ('') NOT NULL,
    [TAX_RATE]        NUMERIC (8, 4) CONSTRAINT [DF__SINVDETLT__TAX_R__19582B8B] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__SINVDETL__36C17F54139F5235] PRIMARY KEY CLUSTERED ([UNIQSINVDETLTAX] ASC)
);

