CREATE TABLE [dbo].[SOHIST] (
    [UNIQHISTNO] CHAR (10)       CONSTRAINT [DF__SOHIST__UNIQHIST__6F212F46] DEFAULT ('') NOT NULL,
    [SONO]       CHAR (10)       CONSTRAINT [DF__SOHIST__SONO__7015537F] DEFAULT ('') NOT NULL,
    [UNIQUELN]   CHAR (10)       CONSTRAINT [DF__SOHIST__UNIQUELN__710977B8] DEFAULT ('') NOT NULL,
    [LINE_NO]    CHAR (2)        CONSTRAINT [DF__SOHIST__LINE_NO__71FD9BF1] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]   CHAR (10)       CONSTRAINT [DF__SOHIST__UNIQ_KEY__72F1C02A] DEFAULT ('') NOT NULL,
    [UOFMEAS]    CHAR (4)        CONSTRAINT [DF__SOHIST__UOFMEAS__73E5E463] DEFAULT ('') NOT NULL,
    [ORD_QTY]    NUMERIC (9, 2)  CONSTRAINT [DF__SOHIST__ORD_QTY__74DA089C] DEFAULT ((0)) NOT NULL,
    [SHIPPEDQTY] NUMERIC (9, 2)  CONSTRAINT [DF__SOHIST__SHIPPEDQ__75CE2CD5] DEFAULT ((0)) NOT NULL,
    [BALANCE]    NUMERIC (9, 2)  CONSTRAINT [DF__SOHIST__BALANCE__76C2510E] DEFAULT ((0)) NOT NULL,
    [DESC]       CHAR (30)       CONSTRAINT [DF__SOHIST__DESC__77B67547] DEFAULT ('') NOT NULL,
    [TRANS_DAYS] NUMERIC (3)     CONSTRAINT [DF__SOHIST__TRANS_DA__78AA9980] DEFAULT ((0)) NOT NULL,
    [NOTE]       CHAR (40)       CONSTRAINT [DF__SOHIST__NOTE__799EBDB9] DEFAULT ('') NOT NULL,
    [EXTENDED]   NUMERIC (16, 2) CONSTRAINT [DF__SOHIST__EXTENDED__7A92E1F2] DEFAULT ((0)) NOT NULL,
    [BULLETIN]   TEXT            CONSTRAINT [DF__SOHIST__BULLETIN__7B87062B] DEFAULT ('') NOT NULL,
    [QTYFROMINV] NUMERIC (9, 2)  CONSTRAINT [DF__SOHIST__QTYFROMI__7C7B2A64] DEFAULT ((0)) NOT NULL,
    [STATUS]     CHAR (10)       CONSTRAINT [DF__SOHIST__STATUS__7D6F4E9D] DEFAULT ('') NOT NULL,
    [W_KEY]      CHAR (10)       CONSTRAINT [DF__SOHIST__W_KEY__7E6372D6] DEFAULT ('') NOT NULL,
    [SAVEDTTM]   SMALLDATETIME   NULL,
    [SAVEINIT]   CHAR (8)        CONSTRAINT [DF__SOHIST__SAVEINIT__7F57970F] DEFAULT ('') NULL,
    [EXTENDEDFC] NUMERIC (16, 2) CONSTRAINT [DF__SOHIST__EXTENDED__2E692261] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SOHIST_PK] PRIMARY KEY CLUSTERED ([UNIQHISTNO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SAVEDTTM]
    ON [dbo].[SOHIST]([SAVEDTTM] ASC);

