CREATE TABLE [dbo].[SOPHIS] (
    [UNIQPHISNO] CHAR (10)       CONSTRAINT [DF__SOPHIS__UNIQPHIS__2D1E61BF] DEFAULT ('') NOT NULL,
    [UNIQHISTNO] CHAR (10)       CONSTRAINT [DF__SOPHIS__UNIQHIST__2E1285F8] DEFAULT ('') NOT NULL,
    [SONO]       CHAR (10)       CONSTRAINT [DF__SOPHIS__SONO__2F06AA31] DEFAULT ('') NOT NULL,
    [DESCRIPTIO] CHAR (40)       CONSTRAINT [DF__SOPHIS__DESCRIPT__2FFACE6A] DEFAULT ('') NOT NULL,
    [QUANTITY]   NUMERIC (10, 2) CONSTRAINT [DF__SOPHIS__QUANTITY__30EEF2A3] DEFAULT ((0)) NOT NULL,
    [PRICE]      NUMERIC (14, 5) CONSTRAINT [DF__SOPHIS__PRICE__31E316DC] DEFAULT ((0)) NOT NULL,
    [EXTENDED]   NUMERIC (20, 2) CONSTRAINT [DF__SOPHIS__EXTENDED__32D73B15] DEFAULT ((0)) NOT NULL,
    [TAXABLE]    BIT             CONSTRAINT [DF__SOPHIS__TAXABLE__33CB5F4E] DEFAULT ((0)) NOT NULL,
    [FLAT]       BIT             CONSTRAINT [DF__SOPHIS__FLAT__34BF8387] DEFAULT ((0)) NOT NULL,
    [RECORDTYPE] CHAR (1)        CONSTRAINT [DF__SOPHIS__RECORDTY__35B3A7C0] DEFAULT ('') NOT NULL,
    [SALETYPEID] CHAR (10)       CONSTRAINT [DF__SOPHIS__SALETYPE__36A7CBF9] DEFAULT ('') NOT NULL,
    [PLPRICELNK] CHAR (10)       CONSTRAINT [DF__SOPHIS__PLPRICEL__379BF032] DEFAULT ('') NOT NULL,
    [UNIQUELN]   CHAR (10)       CONSTRAINT [DF__SOPHIS__UNIQUELN__3890146B] DEFAULT ('') NOT NULL,
    [PL_GL_NBR]  CHAR (13)       CONSTRAINT [DF__SOPHIS__PL_GL_NB__398438A4] DEFAULT ('') NOT NULL,
    [COG_GL_NBR] CHAR (13)       CONSTRAINT [DF__SOPHIS__COG_GL_N__3A785CDD] DEFAULT ('') NOT NULL,
    [UNIQGLDET]  CHAR (10)       CONSTRAINT [DF__SOPHIS__UNIQGLDE__3B6C8116] DEFAULT ('') NOT NULL,
    [UNIQCOGDET] CHAR (10)       CONSTRAINT [DF__SOPHIS__UNIQCOGD__3C60A54F] DEFAULT ('') NOT NULL,
    [PRICEFC]    NUMERIC (14, 5) CONSTRAINT [DF__SOPHIS__PRICEFC__2F5D469A] DEFAULT ((0)) NOT NULL,
    [EXTENDEDFC] NUMERIC (20, 2) CONSTRAINT [DF__SOPHIS__EXTENDED__30516AD3] DEFAULT ((0)) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [UNIQHISTNO]
    ON [dbo].[SOPHIS]([UNIQHISTNO] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQPHISNO]
    ON [dbo].[SOPHIS]([UNIQPHISNO] ASC);

