CREATE TABLE [dbo].[SOPRICESTAX] (
    [UNIQSOPRICESTAX] CHAR (10)      CONSTRAINT [DF__SOPRICEST__UNIQS__4EF5222D] DEFAULT ([dbo].[fn_GenerateUniqueNumber]()) NOT NULL,
    [SONO]            CHAR (10)      CONSTRAINT [DF__SOPRICESTA__SONO__4FE94666] DEFAULT ('') NOT NULL,
    [UNIQUELN]        CHAR (10)      CONSTRAINT [DF__SOPRICEST__UNIQU__50DD6A9F] DEFAULT ('') NOT NULL,
    [PLPRICELNK]      CHAR (10)      CONSTRAINT [DF__SOPRICEST__PLPRI__51D18ED8] DEFAULT ('') NOT NULL,
    [TAX_ID]          CHAR (8)       CONSTRAINT [DF__SOPRICEST__TAX_I__52C5B311] DEFAULT ('') NOT NULL,
    [TAX_RATE]        NUMERIC (8, 4) CONSTRAINT [DF__SOPRICEST__TAX_R__53B9D74A] DEFAULT ((0)) NOT NULL,
    [TAXTYPE]         CHAR (1)       CONSTRAINT [DF__SOPRICEST__TAXTY__54ADFB83] DEFAULT ('') NOT NULL,
    [PTPROD]          BIT            CONSTRAINT [DF__SOPRICEST__PTPRO__50A86075] DEFAULT ((0)) NOT NULL,
    [PTFRT]           BIT            CONSTRAINT [DF__SOPRICEST__PTFRT__519C84AE] DEFAULT ((0)) NOT NULL,
    [STPROD]          BIT            CONSTRAINT [DF__SOPRICEST__STPRO__5290A8E7] DEFAULT ((0)) NOT NULL,
    [STFRT]           BIT            CONSTRAINT [DF__SOPRICEST__STFRT__5384CD20] DEFAULT ((0)) NOT NULL,
    [STTX]            BIT            CONSTRAINT [DF__SOPRICESTA__STTX__5478F159] DEFAULT ((0)) NOT NULL,
    [SetupTaxType]    CHAR (15)      CONSTRAINT [DF_SOPRICESTAX_SetupTaxType] DEFAULT ('') NOT NULL,
    [TaxApplicableTo] CHAR (10)      CONSTRAINT [DF_SOPRICESTAX_TaxApplicableTo] DEFAULT ('') NOT NULL,
    [IsFreightTotals] BIT            CONSTRAINT [DF_SOPRICESTAX_IsFreightTotals] DEFAULT ((0)) NOT NULL,
    [IsProductTotal]  BIT            CONSTRAINT [DF_SOPRICESTAX_IsProductTotal] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__SOPRICES__D0A79F964D0CD9BB] PRIMARY KEY CLUSTERED ([UNIQSOPRICESTAX] ASC)
);

