CREATE TABLE [dbo].[SOPRSREP] (
    [SONO]       CHAR (10)      CONSTRAINT [DF__SOPRSREP__SONO__4E7F558A] DEFAULT ('') NOT NULL,
    [CID]        CHAR (10)      CONSTRAINT [DF__SOPRSREP__CID__4F7379C3] DEFAULT ('') NOT NULL,
    [CUSTNO]     CHAR (10)      CONSTRAINT [DF__SOPRSREP__CUSTNO__50679DFC] DEFAULT ('') NOT NULL,
    [COMMISSION] NUMERIC (9, 4) CONSTRAINT [DF__SOPRSREP__COMMIS__515BC235] DEFAULT ((0)) NOT NULL,
    [UNIQUELN]   CHAR (10)      CONSTRAINT [DF__SOPRSREP__UNIQUE__524FE66E] DEFAULT ('') NOT NULL,
    [SOPRSREPUK] CHAR (10)      CONSTRAINT [DF__SOPRSREP__SOPRSR__53440AA7] DEFAULT ('') NOT NULL,
    CONSTRAINT [SOPRSREP_PK] PRIMARY KEY CLUSTERED ([SOPRSREPUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CID]
    ON [dbo].[SOPRSREP]([CID] ASC);


GO
CREATE NONCLUSTERED INDEX [SONOSREP]
    ON [dbo].[SOPRSREP]([SONO] ASC, [UNIQUELN] ASC, [CID] ASC);

