CREATE TABLE [dbo].[SOSETUP] (
    [APPRV_REQD]       BIT       CONSTRAINT [DF__SOSETUP__APPRV_R__56207752] DEFAULT ((0)) NOT NULL,
    [LMRPIGNORED]      BIT       CONSTRAINT [DF__SOSETUP__LMRPIGN__57149B8B] DEFAULT ((0)) NOT NULL,
    [LAUTOAPPR4UPLOAD] BIT       CONSTRAINT [DF__SOSETUP__LAUTOAP__5808BFC4] DEFAULT ((0)) NOT NULL,
    [LAUTOACKN4UPLOAD] BIT       CONSTRAINT [DF__SOSETUP__LAUTOAC__58FCE3FD] DEFAULT ((0)) NOT NULL,
    [UNIQUEREC]        CHAR (10) CONSTRAINT [DF__SOSETUP__UNIQUER__59F10836] DEFAULT ('') NOT NULL,
    [SrepCommby]       CHAR (1)  CONSTRAINT [DF__SOSETUP__SrepCom__69885181] DEFAULT ('') NOT NULL,
    [PrintPrdt]        BIT       CONSTRAINT [DF__SOSETUP__PrintPr__6A7C75BA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SOSETUP_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);

