CREATE TABLE [dbo].[STNDSPEC] (
    [SPEC_NO]   CHAR (10)  CONSTRAINT [DF__STNDSPEC__SPEC_N__5CCD74E1] DEFAULT ('') NOT NULL,
    [SPEC_DESC] CHAR (25)  CONSTRAINT [DF__STNDSPEC__SPEC_D__5DC1991A] DEFAULT ('') NOT NULL,
    [SPEC_NOTE] TEXT       CONSTRAINT [DF__STNDSPEC__SPEC_N__5EB5BD53] DEFAULT ('') NOT NULL,
    [DEPT_ID]   CHAR (4)   CONSTRAINT [DF__STNDSPEC__DEPT_I__5FA9E18C] DEFAULT ('') NOT NULL,
    [SPECPICT]  CHAR (200) CONSTRAINT [DF__STNDSPEC__SPECPI__609E05C5] DEFAULT ('') NOT NULL,
    CONSTRAINT [STNDSPEC_PK] PRIMARY KEY CLUSTERED ([SPEC_NO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEPT_ID]
    ON [dbo].[STNDSPEC]([DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [SPEC_DESC]
    ON [dbo].[STNDSPEC]([SPEC_DESC] ASC);


GO
CREATE NONCLUSTERED INDEX [WCSPECNO]
    ON [dbo].[STNDSPEC]([DEPT_ID] ASC, [SPEC_NO] ASC);

