CREATE TABLE [dbo].[SUPCLASS] (
    [PART_CLASS] CHAR (8)  CONSTRAINT [DF__SUPCLASS__PART_C__646E96A9] DEFAULT ('') NOT NULL,
    [UNQSUPCLAS] CHAR (10) CONSTRAINT [DF__SUPCLASS__UNQSUP__6562BAE2] DEFAULT ('') NOT NULL,
    [UniqSupno]  CHAR (10) NULL,
    CONSTRAINT [SUPCLASS_PK] PRIMARY KEY CLUSTERED ([UNQSUPCLAS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UQSUPNOCLS]
    ON [dbo].[SUPCLASS]([UniqSupno] ASC, [PART_CLASS] ASC);

