CREATE TABLE [dbo].[SUPMFGR] (
    [PARTMFGR]   CHAR (8)  CONSTRAINT [DF__SUPMFGR__PARTMFG__010AD557] DEFAULT ('') NOT NULL,
    [UNQSUPMFGR] CHAR (10) CONSTRAINT [DF__SUPMFGR__UNQSUPM__01FEF990] DEFAULT ('') NOT NULL,
    [UniqSupno]  CHAR (10) NULL,
    CONSTRAINT [SUPMFGR_PK] PRIMARY KEY CLUSTERED ([UNQSUPMFGR] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UQSUPNOMGR]
    ON [dbo].[SUPMFGR]([UniqSupno] ASC, [PARTMFGR] ASC);

