CREATE TABLE [dbo].[SUPTYPE] (
    [UNQSUPTYPE] CHAR (10) NOT NULL,
    [UNQSUPCLAS] CHAR (10) NOT NULL,
    [UNIQPTYPE]  CHAR (10) NOT NULL,
    CONSTRAINT [PK__SUPTYPE__B4D4256A8F56948D] PRIMARY KEY CLUSTERED ([UNQSUPTYPE] ASC),
    CONSTRAINT [FK__SUPTYPE__UNIQPTY__5796EBD4] FOREIGN KEY ([UNIQPTYPE]) REFERENCES [dbo].[PARTTYPE] ([UNIQPTYPE]),
    CONSTRAINT [FK__SUPTYPE__UNQSUPC__56A2C79B] FOREIGN KEY ([UNQSUPCLAS]) REFERENCES [dbo].[SUPCLASS] ([UNQSUPCLAS])
);

