CREATE TABLE [dbo].[T_C] (
    [SUPPORT]   TEXT      CONSTRAINT [DF__T_C__SUPPORT__232AE331] DEFAULT ('') NOT NULL,
    [SOFTWARE]  TEXT      CONSTRAINT [DF__T_C__SOFTWARE__241F076A] DEFAULT ('') NOT NULL,
    [SUBSCRIPT] TEXT      CONSTRAINT [DF__T_C__SUBSCRIPT__25132BA3] DEFAULT ('') NOT NULL,
    [UNIQUEREC] CHAR (10) CONSTRAINT [DF__T_C__UNIQUEREC__26074FDC] DEFAULT ('') NOT NULL,
    CONSTRAINT [T_C_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);

