CREATE TABLE [dbo].[TEMPABC] (
    [UNIQ_KEY]     CHAR (10)        CONSTRAINT [DF__TEMPABC__UNIQ_KE__32A230EB] DEFAULT ('') NOT NULL,
    [ABC]          CHAR (1)         CONSTRAINT [DF__TEMPABC__ABC__33965524] DEFAULT ('') NOT NULL,
    [REASON]       CHAR (15)        CONSTRAINT [DF__TEMPABC__REASON__348A795D] DEFAULT ('') NOT NULL,
    [PurLtDays]    NUMERIC (4)      CONSTRAINT [DF_TEMPABC_PurLtDays] DEFAULT ((0)) NOT NULL,
    [ProdLtDays]   NUMERIC (4)      CONSTRAINT [DF_TEMPABC_ProdLtDays] DEFAULT ((0)) NOT NULL,
    [ExtCost]      NUMERIC (10)     CONSTRAINT [DF_TEMPABC_ExtCost] DEFAULT ((0)) NOT NULL,
    [RankPct]      NUMERIC (6, 2)   CONSTRAINT [DF_TEMPABC_RankPct] DEFAULT ((0)) NOT NULL,
    [Runningtotal] NUMERIC (6, 2)   CONSTRAINT [DF_TEMPABC_Runningtotal] DEFAULT ((0)) NOT NULL,
    [part_sourc]   CHAR (10)        CONSTRAINT [DF_TEMPABC_part_sourc] DEFAULT ('') NOT NULL,
    [TMPABCUK]     UNIQUEIDENTIFIER CONSTRAINT [DF_TEMPABC_TMPABCUK] DEFAULT (newsequentialid()) NOT NULL,
    CONSTRAINT [TEMPABC_PK] PRIMARY KEY CLUSTERED ([TMPABCUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PART_SOURC]
    ON [dbo].[TEMPABC]([part_sourc] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[TEMPABC]([UNIQ_KEY] ASC);

