CREATE TABLE [dbo].[TMLOGTP] (
    [TMLOG_NO]                   VARCHAR (10) CONSTRAINT [DF__TMLOGTP__TMLOG_N__41E4747B] DEFAULT ('') NOT NULL,
    [TMLOG_DESC]                 CHAR (20)    CONSTRAINT [DF__TMLOGTP__TMLOG_D__42D898B4] DEFAULT ('') NOT NULL,
    [NUMBER]                     NUMERIC (4)  CONSTRAINT [DF__TMLOGTP__NUMBER__43CCBCED] DEFAULT ((0)) NOT NULL,
    [IS_PAY]                     BIT          CONSTRAINT [DF__TMLOGTP__IS_PAY__44C0E126] DEFAULT ((0)) NOT NULL,
    [TM_GL_NBR]                  CHAR (13)    CONSTRAINT [DF__TMLOGTP__TM_GL_N__45B5055F] DEFAULT ('') NOT NULL,
    [ALLOWENTERHOUR]             BIT          CONSTRAINT [DF__TMLOGTP__ALLOWEN__46A92998] DEFAULT ((0)) NOT NULL,
    [TMLOGTPUK]                  CHAR (10)    CONSTRAINT [DF__TMLOGTP__TMLOGTP__479D4DD1] DEFAULT ('') NOT NULL,
    [AdminLog]                   BIT          CONSTRAINT [DF_TMLOGTP_Admin] DEFAULT ((1)) NOT NULL,
    [DoNotRemove]                BIT          CONSTRAINT [DF_TMLOGTP_DoNotRemove] DEFAULT ((0)) NOT NULL,
    [IsWorkOrder]                BIT          CONSTRAINT [DF__TMLOGTP__IsWorkO__7413FA48] DEFAULT ((0)) NOT NULL,
    [DisallowEnterHrsForLogType] BIT          CONSTRAINT [DF_TMLOGTP_DisallowEnterHrsType] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [TMLOGTP_PK] PRIMARY KEY CLUSTERED ([TMLOGTPUK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NUMBER]
    ON [dbo].[TMLOGTP]([NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [TMLOG_NO]
    ON [dbo].[TMLOGTP]([TMLOG_NO] ASC);

