CREATE TABLE [dbo].[TOOLING] (
    [TOOLID]            CHAR (10)     CONSTRAINT [DF__TOOLING__TOOLID__4A79BA7C] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]          CHAR (10)     CONSTRAINT [DF__TOOLING__UNIQ_KE__4B6DDEB5] DEFAULT ('') NOT NULL,
    [DEPT_ID]           CHAR (4)      CONSTRAINT [DF__TOOLING__DEPT_ID__4C6202EE] DEFAULT ('') NOT NULL,
    [ToolsAndFixtureId] CHAR (10)     CONSTRAINT [DF__TOOLING__ToolsAn__72D4F1F5] DEFAULT ('0') NULL,
    [UNIQNUMBER]        CHAR (10)     CONSTRAINT [DF__TOOLING__UNIQNUM__73C9162E] DEFAULT ('0') NULL,
    [TemplateId]        INT           NULL,
    [Description]       CHAR (200)    CONSTRAINT [DF__TOOLING__Descrip__468D26BA] DEFAULT ('') NOT NULL,
    [CalibrationDate]   SMALLDATETIME NULL,
    [Location]          NVARCHAR (50) CONSTRAINT [DF__TOOLING__Locatio__138D70F8] DEFAULT ('') NOT NULL,
    [ToolSerialNumber]  NVARCHAR (50) CONSTRAINT [DF__TOOLING__ToolSer__14819531] DEFAULT ('') NOT NULL,
    [ToolCustomerID]    NVARCHAR (50) CONSTRAINT [DF__TOOLING__ToolCus__1575B96A] DEFAULT ('') NOT NULL,
    [DateofPurchase]    SMALLDATETIME NULL,
    [ExpirationDate]    SMALLDATETIME NULL,
    CONSTRAINT [TOOLING_PK] PRIMARY KEY CLUSTERED ([TOOLID] ASC),
    CONSTRAINT [FK_TOOLING_TemplateId] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[RoutingTemplate] ([TemplateID])
);


GO
CREATE NONCLUSTERED INDEX [DEPT_ID]
    ON [dbo].[TOOLING]([DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [PRODWC]
    ON [dbo].[TOOLING]([UNIQ_KEY] ASC, [DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQ_KEY]
    ON [dbo].[TOOLING]([UNIQ_KEY] ASC);

