CREATE TABLE [dbo].[TRANSFER] (
    [DATE]       DATETIME         NULL,
    [FR_DEPT_ID] CHAR (4)         CONSTRAINT [DF__TRANSFER__FR_DEP__530F007D] DEFAULT ('') NOT NULL,
    [TO_DEPT_ID] CHAR (4)         CONSTRAINT [DF__TRANSFER__TO_DEP__540324B6] DEFAULT ('') NOT NULL,
    [QTY]        NUMERIC (7)      CONSTRAINT [DF__TRANSFER__QTY__54F748EF] DEFAULT ((0)) NOT NULL,
    [XFERC_QTY]  NUMERIC (7)      CONSTRAINT [DF__TRANSFER__XFERC___55EB6D28] DEFAULT ((0)) NOT NULL,
    [HRS]        NUMERIC (4)      CONSTRAINT [DF__TRANSFER__HRS__56DF9161] DEFAULT ((0)) NOT NULL,
    [MIN]        NUMERIC (6)      CONSTRAINT [DF__TRANSFER__MIN__57D3B59A] DEFAULT ((0)) NOT NULL,
    [WONO]       CHAR (10)        CONSTRAINT [DF__TRANSFER__WONO__59BBFE0C] DEFAULT ('') NOT NULL,
    [FTNOTE]     TEXT             CONSTRAINT [DF__TRANSFER__FTNOTE__5AB02245] DEFAULT ('') NOT NULL,
    [CREDIT_QTY] NUMERIC (7)      CONSTRAINT [DF__TRANSFER__CREDIT__5BA4467E] DEFAULT ((0)) NOT NULL,
    [FR_NUMBER]  NUMERIC (4)      CONSTRAINT [DF__TRANSFER__FR_NUM__5C986AB7] DEFAULT ((0)) NOT NULL,
    [TO_NUMBER]  NUMERIC (4)      CONSTRAINT [DF__TRANSFER__TO_NUM__5D8C8EF0] DEFAULT ((0)) NOT NULL,
    [FR_DEPTKEY] CHAR (10)        CONSTRAINT [DF__TRANSFER__FR_DEP__5E80B329] DEFAULT ('') NOT NULL,
    [TO_DEPTKEY] CHAR (10)        CONSTRAINT [DF__TRANSFER__TO_DEP__5F74D762] DEFAULT ('') NOT NULL,
    [FR_ACTVKEY] CHAR (10)        CONSTRAINT [DF__TRANSFER__FR_ACT__615D1FD4] DEFAULT ('') NOT NULL,
    [TO_ACTVKEY] CHAR (10)        CONSTRAINT [DF__TRANSFER__TO_ACT__6251440D] DEFAULT ('') NOT NULL,
    [XFER_UNIQ]  CHAR (10)        CONSTRAINT [DF__TRANSFER__XFER_U__63456846] DEFAULT ('') NOT NULL,
    [BY]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [TRANSFER_PK] PRIMARY KEY CLUSTERED ([XFER_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FR_ACTVKEY]
    ON [dbo].[TRANSFER]([FR_ACTVKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [FR_DEPT_ID]
    ON [dbo].[TRANSFER]([FR_DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [FR_NUMBER]
    ON [dbo].[TRANSFER]([FR_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [TO_ACTVKEY]
    ON [dbo].[TRANSFER]([TO_ACTVKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [TO_DEPT_ID]
    ON [dbo].[TRANSFER]([TO_DEPT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [TO_NUMBER]
    ON [dbo].[TRANSFER]([TO_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[TRANSFER]([WONO] ASC);


GO
CREATE NONCLUSTERED INDEX [WONOFROM]
    ON [dbo].[TRANSFER]([WONO] ASC, [FR_DEPTKEY] ASC, [FR_ACTVKEY] ASC);


GO
CREATE NONCLUSTERED INDEX [WONOTO]
    ON [dbo].[TRANSFER]([WONO] ASC, [TO_DEPTKEY] ASC, [TO_ACTVKEY] ASC);

