CREATE TABLE [dbo].[TRIGOPEN] (
    [UNIQTRIG]   CHAR (10)      CONSTRAINT [DF__TRIGOPEN__UNIQTR__18AD54BE] DEFAULT ('') NOT NULL,
    [UNIQOPEN]   CHAR (10)      CONSTRAINT [DF__TRIGOPEN__UNIQOP__19A178F7] DEFAULT ('') NOT NULL,
    [CLEARDTTM]  SMALLDATETIME  NULL,
    [TRIGDTTM]   SMALLDATETIME  NULL,
    [REF]        NVARCHAR (MAX) CONSTRAINT [DF__TRIGOPEN__REF__1A959D30] DEFAULT ('') NOT NULL,
    [ATTACHFILE] CHAR (80)      CONSTRAINT [DF__TRIGOPEN__ATTACH__1B89C169] DEFAULT ('') NOT NULL,
    CONSTRAINT [TRIGOPEN_PK] PRIMARY KEY CLUSTERED ([UNIQOPEN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNIQTRIG]
    ON [dbo].[TRIGOPEN]([UNIQTRIG] ASC);

