CREATE TABLE [dbo].[TRIGSENT] (
    [UNIQEMAIL]  CHAR (10)     CONSTRAINT [DF__TRIGSENT__UNIQEM__1E662E14] DEFAULT ('') NOT NULL,
    [UNIQOPEN]   CHAR (10)     CONSTRAINT [DF__TRIGSENT__UNIQOP__1F5A524D] DEFAULT ('') NOT NULL,
    [DTTIMESENT] SMALLDATETIME NULL,
    [UNIQTRSENT] CHAR (10)     CONSTRAINT [DF__TRIGSENT__UNIQTR__204E7686] DEFAULT ('') NOT NULL,
    CONSTRAINT [TRIGSENT_PK] PRIMARY KEY CLUSTERED ([UNIQTRSENT] ASC)
);

