CREATE TABLE [dbo].[UdfINVENTOR_AUDIO] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_AUDIO_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_AUDIO_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [test]       VARCHAR (77)     CONSTRAINT [DF_UdfINVENTOR_AUDIO_test] DEFAULT ('') NULL,
    [INT]        INT              CONSTRAINT [DF_UdfINVENTOR_AUDIO_INT] DEFAULT ('553') NOT NULL,
    [DT]         SMALLDATETIME    CONSTRAINT [DF_UdfINVENTOR_AUDIO_DT] DEFAULT ('06/29/2019 0:0:0') NOT NULL,
    CONSTRAINT [PK_UdfINVENTOR_AUDIO] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

