CREATE TABLE [dbo].[UdfINVENTOR_RES_SMT] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_RES_SMT_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_RES_SMT_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [Cust_int]   INT              CONSTRAINT [DF_UdfINVENTOR_RES_SMT_Cust_int] DEFAULT ('55') NULL,
    [Value]      VARCHAR (800)    CONSTRAINT [DF_UdfINVENTOR_RES_SMT_Value] DEFAULT ('') NULL,
    [Voltage]    VARCHAR (200)    CONSTRAINT [DF_UdfINVENTOR_RES_SMT_Voltage] DEFAULT ('') NULL,
    CONSTRAINT [PK_UdfINVENTOR_RES_SMT] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

