CREATE TABLE [dbo].[UdfINVENTOR_CHB] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_CHB_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_CHB_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_UdfINVENTOR_CHB] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

