CREATE TABLE [dbo].[UdfINVENTOR_IC_SMT] (
    [udfId]        UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_IC_SMT_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY]   CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_IC_SMT_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [TEST]         VARCHAR (66)     CONSTRAINT [DF_UdfINVENTOR_IC_SMT_TEST] DEFAULT ('') NULL,
    [TESTCheck]    BIT              CONSTRAINT [DF_UdfINVENTOR_IC_SMT_TESTCheck] DEFAULT ('False') NULL,
    [Testdatetime] SMALLDATETIME    CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Testdatetime] DEFAULT ('11/08/2019 0:0:0') NULL,
    [Testdate]     DATE             CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Testdate] DEFAULT ('11/07/2019') NULL,
    [Testdecimal]  DECIMAL (38, 6)  CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Testdecimal] DEFAULT ('55.55') NULL,
    [Testdrop]     VARCHAR (MAX)    CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Testdrop] DEFAULT ('54') NULL,
    [Testint]      INT              CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Testint] DEFAULT ('78') NULL,
    [Rating]       VARCHAR (60)     CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Rating] DEFAULT ('') NULL,
    [Voltage]      VARCHAR (500)    CONSTRAINT [DF_UdfINVENTOR_IC_SMT_Voltage] DEFAULT ('12V') NULL,
    CONSTRAINT [PK_UdfINVENTOR_IC_SMT] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

