CREATE TABLE [dbo].[UdfINVENTOR_BATTERY] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_BATTERY_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_BATTERY_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [Test]       VARCHAR (700)    CONSTRAINT [DF_UdfINVENTOR_BATTERY_Test] DEFAULT ('') NULL,
    CONSTRAINT [PK_UdfINVENTOR_BATTERY] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

