CREATE TABLE [dbo].[UdfINVENTOR_CAP_SMT] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_CAP_SMT_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_CAP_SMT_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [Voltage]    VARCHAR (100)    CONSTRAINT [DF_UdfINVENTOR_CAP_SMT_Voltage] DEFAULT ('10V') NULL,
    [Project]    VARCHAR (100)    CONSTRAINT [DF_UdfINVENTOR_CAP_SMT_Project] DEFAULT ('') NULL,
    [Tolerance]  INT              CONSTRAINT [DF_UdfINVENTOR_CAP_SMT_Tolerance] DEFAULT ('') NULL,
    [Weight]     VARCHAR (50)     CONSTRAINT [DF_UdfINVENTOR_CAP_SMT_Weight] DEFAULT ('5lbs') NULL,
    CONSTRAINT [PK_UdfINVENTOR_CAP_SMT] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

