CREATE TABLE [dbo].[UdfINVENTOR_BHB] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_BHB_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_BHB_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_UdfINVENTOR_BHB] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

