CREATE TABLE [dbo].[UdfINVENTOR_LOT] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_LOT_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_LOT_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [Reference]  VARCHAR (30)     CONSTRAINT [DF_UdfINVENTOR_LOT_Reference] DEFAULT ('') NULL,
    CONSTRAINT [PK_UdfINVENTOR_LOT] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

