CREATE TABLE [dbo].[UdfINVENTOR_PLASTIC] (
    [udfId]       UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_PLASTIC_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY]  CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_PLASTIC_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    [Plastic_INT] INT              CONSTRAINT [DF_UdfINVENTOR_PLASTIC_Plastic_INT] DEFAULT ('553') NULL,
    CONSTRAINT [PK_UdfINVENTOR_PLASTIC] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

