CREATE TABLE [dbo].[UdfINVENTOR_RESN_SMT] (
    [udfId]      UNIQUEIDENTIFIER CONSTRAINT [DF_UdfINVENTOR_RESN_SMT_udfId] DEFAULT (newid()) NOT NULL,
    [fkUNIQ_KEY] CHAR (10)        CONSTRAINT [DF_UdfINVENTOR_RESN_SMT_fkUNIQ_KEY] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_UdfINVENTOR_RESN_SMT] PRIMARY KEY CLUSTERED ([udfId] ASC)
);

