CREATE TABLE [dbo].[UPDMATTPLOG] (
    [UQMTTPLOG]    CHAR (10)      CONSTRAINT [DF__UPDMATTPL__UQMTT__4397B2C3] DEFAULT ('') NOT NULL,
    [UNIQ_KEY]     CHAR (10)      CONSTRAINT [DF__UPDMATTPL__UNIQ___448BD6FC] DEFAULT ('') NOT NULL,
    [FROMMATLTYPE] CHAR (10)      CONSTRAINT [DF__UPDMATTPL__FROMM__457FFB35] DEFAULT ('') NOT NULL,
    [TOMATLTYPE]   CHAR (10)      CONSTRAINT [DF__UPDMATTPL__TOMAT__46741F6E] DEFAULT ('') NOT NULL,
    [MTCHGDT]      SMALLDATETIME  NULL,
    [MTCHGINIT]    NVARCHAR (256) NULL,
    CONSTRAINT [UPDMATTPLOG_PK] PRIMARY KEY CLUSTERED ([UQMTTPLOG] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JQMTTPLOG]
    ON [dbo].[UPDMATTPLOG]([UQMTTPLOG] ASC);

