CREATE TABLE [dbo].[UPDTSTD] (
    [UNIQ_KEY]        CHAR (10)       CONSTRAINT [DF__UPDTSTD__UNIQ_KE__5C63608D] DEFAULT ('') NOT NULL,
    [UNIQ_UPDT]       CHAR (10)       CONSTRAINT [DF__UPDTSTD__UNIQ_UP__5D5784C6] DEFAULT ('') NOT NULL,
    [WH_GL_NBR]       CHAR (13)       CONSTRAINT [DF__UPDTSTD__WH_GL_N__6033F171] DEFAULT ('') NOT NULL,
    [QTY_OH]          NUMERIC (12, 2) CONSTRAINT [DF__UPDTSTD__QTY_OH__612815AA] DEFAULT ((0)) NOT NULL,
    [OLDSTDCOST]      NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__OLDSTDC__621C39E3] DEFAULT ((0)) NOT NULL,
    [NEWSTDCOST]      NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__NEWSTDC__63105E1C] DEFAULT ((0)) NOT NULL,
    [CHANGEAMT]       NUMERIC (12, 2) CONSTRAINT [DF__UPDTSTD__CHANGEA__64048255] DEFAULT ((0)) NOT NULL,
    [RUNDATE]         SMALLDATETIME   NULL,
    [UPDTDATE]        SMALLDATETIME   NULL,
    [INIT]            CHAR (8)        CONSTRAINT [DF__UPDTSTD__INIT__65ECCAC7] DEFAULT ('') NULL,
    [ROLLTYPE]        CHAR (4)        CONSTRAINT [DF__UPDTSTD__ROLLTYP__66E0EF00] DEFAULT ('') NOT NULL,
    [IS_rel_gl]       BIT             CONSTRAINT [DF__UPDTSTD__GL_RELE__67D51339] DEFAULT ((0)) NOT NULL,
    [MATL_COST]       NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__MATL_CO__69BD5BAB] DEFAULT ((0)) NOT NULL,
    [NEWMATLCST]      NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__NEWMATL__6AB17FE4] DEFAULT ((0)) NOT NULL,
    [OLDMATLCST]      NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__OLDMATL__6BA5A41D] DEFAULT ((0)) NOT NULL,
    [UniqWh]          CHAR (10)       CONSTRAINT [DF_UPDTSTD_UniqWh] DEFAULT ('') NOT NULL,
    [NEWSTDCOSTPR]    NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__NEWSTDC__2669A494] DEFAULT ((0)) NOT NULL,
    [OLDSTDCOSTPR]    NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__OLDSTDC__275DC8CD] DEFAULT ((0)) NOT NULL,
    [CHANGEAMTPR]     NUMERIC (12, 2) CONSTRAINT [DF__UPDTSTD__CHANGEA__23232395] DEFAULT ((0)) NOT NULL,
    [MATL_COSTPR]     NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__MATL_CO__241747CE] DEFAULT ((0)) NOT NULL,
    [NEWMATLCSTPR]    NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__NEWMATL__250B6C07] DEFAULT ((0)) NOT NULL,
    [OLDMATLCSTPR]    NUMERIC (13, 5) CONSTRAINT [DF__UPDTSTD__OLDMATL__25FF9040] DEFAULT ((0)) NOT NULL,
    [PRFCUSED_UNIQ]   CHAR (10)       CONSTRAINT [DF__UPDTSTD__PRFCUSE__26F3B479] DEFAULT ('') NOT NULL,
    [FUNCFCUSED_UNIQ] CHAR (10)       CONSTRAINT [DF__UPDTSTD__FUNCFCU__27E7D8B2] DEFAULT ('') NOT NULL,
    [IS_ERADJ]        BIT             CONSTRAINT [DF__UPDTSTD__IS_ERAD__126D98DF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [UPDTSTD_PK] PRIMARY KEY CLUSTERED ([UNIQ_UPDT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_ISRELEASED]
    ON [dbo].[UPDTSTD]([IS_rel_gl] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_uniqkey]
    ON [dbo].[UPDTSTD]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_UPDTSTD]
    ON [dbo].[UPDTSTD]([UNIQ_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_wuniqwh]
    ON [dbo].[UPDTSTD]([UniqWh] ASC);


GO
CREATE NONCLUSTERED INDEX [updtdate]
    ON [dbo].[UPDTSTD]([UPDTDATE] ASC);

