CREATE TABLE [dbo].[VOLPKG] (
    [ACTVOL_ID] CHAR (10)      CONSTRAINT [DF__VOLPKG__ACTVOL_I__2201B4CE] DEFAULT ('') NOT NULL,
    [UNIQPKG]   CHAR (10)      CONSTRAINT [DF__VOLPKG__UNIQPKG__22F5D907] DEFAULT ('') NOT NULL,
    [VOL_HR]    NUMERIC (8, 2) CONSTRAINT [DF__VOLPKG__VOL_HR__23E9FD40] DEFAULT ((0)) NOT NULL,
    [RECORDID]  CHAR (10)      CONSTRAINT [DF__VOLPKG__RECORDID__24DE2179] DEFAULT ('') NOT NULL,
    CONSTRAINT [VOLPKG_PK] PRIMARY KEY CLUSTERED ([RECORDID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACTVOL_ID]
    ON [dbo].[VOLPKG]([ACTVOL_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [ACTVOLPKG]
    ON [dbo].[VOLPKG]([ACTVOL_ID] ASC, [UNIQPKG] ASC);


GO
CREATE NONCLUSTERED INDEX [UNIQPKG]
    ON [dbo].[VOLPKG]([UNIQPKG] ASC);

