CREATE TABLE [dbo].[wmReportsCust] (
    [rptId]                   CHAR (10)     NOT NULL,
    [fkrptGroupId]            VARCHAR (50)  CONSTRAINT [DF_WmReportsCust_rptGroup] DEFAULT ('') NOT NULL,
    [rptTitle]                VARCHAR (100) CONSTRAINT [DF_WmReportsCust_rptTitle] DEFAULT ('') NOT NULL,
    [rptTitleLong]            VARCHAR (100) CONSTRAINT [DF_WmReportsCust_rptTitleLong] DEFAULT ('') NOT NULL,
    [rptDescription]          VARCHAR (500) CONSTRAINT [DF_WmReportsCust_reportDescription] DEFAULT ('') NOT NULL,
    [sequence]                INT           NOT NULL,
    [label]                   BIT           CONSTRAINT [DF_rptReportsCust_label] DEFAULT ((0)) NOT NULL,
    [filePath]                VARCHAR (200) CONSTRAINT [DF_WmReportsCust_filePath] DEFAULT ('') NOT NULL,
    [display]                 BIT           CONSTRAINT [DF_WmReportsCust_display] DEFAULT ((0)) NOT NULL,
    [dataSource]              VARCHAR (200) CONSTRAINT [DF_WmReportsCust_dataSource] DEFAULT ('Report') NOT NULL,
    [reportType]              VARCHAR (50)  CONSTRAINT [DF_WmReportsCust_reportType] DEFAULT ('quickView') NOT NULL,
    [paramGroup]              VARCHAR (50)  CONSTRAINT [DF_WmReportsCust_paramGroup] DEFAULT ('') NOT NULL,
    [groupedCol]              VARCHAR (100) CONSTRAINT [DF_WmReportsCust_groupedCol] DEFAULT ('') NOT NULL,
    [showGroupSummary]        BIT           CONSTRAINT [DF_wmReportsCust_showGroupSummary] DEFAULT ((0)) NOT NULL,
    [showSummaryOnHide]       BIT           CONSTRAINT [DF_wmReportsCust_showSummaryOnHide] DEFAULT ((0)) NOT NULL,
    [rowLink]                 VARCHAR (200) CONSTRAINT [DF_wmReportsCust_rowLink] DEFAULT ('') NOT NULL,
    [rowLinkId]               VARCHAR (50)  CONSTRAINT [DF_wmReportsCust_rowLinkId] DEFAULT ('') NOT NULL,
    [reportCount]             INT           CONSTRAINT [DF_wmReportsCust_reportCount] DEFAULT ((0)) NOT NULL,
    [quickViewCount]          INT           CONSTRAINT [DF_wmReportsCust_quickViewCount] DEFAULT ((0)) NOT NULL,
    [exportCount]             INT           CONSTRAINT [DF_wmReportsCust_exportCount] DEFAULT ((0)) NOT NULL,
    [sendreportCount]         INT           CONSTRAINT [DF_wmReportsCust_sendreportCount] DEFAULT ((0)) NOT NULL,
    [dateLastRun]             SMALLDATETIME NULL,
    [quickviewTitleTemplate]  VARCHAR (200) CONSTRAINT [DF_wmReportsCust_quickviewTitleTemplate] DEFAULT ('') NOT NULL,
    [quickViewHeaderTemplate] VARCHAR (200) CONSTRAINT [DF_wmReportsCust_quickViewHeaderTemplate] DEFAULT ('') NOT NULL,
    [MaxSQLTimeout]           INT           CONSTRAINT [wmDF_WmReports_MaxSQLTimeout] DEFAULT ((30)) NOT NULL,
    CONSTRAINT [PK_WmReportsCust] PRIMARY KEY CLUSTERED ([rptId] ASC)
);

