CREATE TABLE [dbo].[wmTriggers] (
    [triggerId]              UNIQUEIDENTIFIER CONSTRAINT [DF_WMTriggers_triggerId] DEFAULT (newid()) NOT NULL,
    [triggerName]            VARCHAR (50)     CONSTRAINT [DF_WMTriggers_triggerName] DEFAULT ('') NOT NULL,
    [trigType]               VARCHAR (50)     CONSTRAINT [DF_WMTriggers_trigType] DEFAULT ('standard') NOT NULL,
    [dateLastRun]            DATETIME2 (0)    NULL,
    [startDate]              DATETIME2 (0)    CONSTRAINT [DF_WMTriggers_startDate] DEFAULT (getdate()) NOT NULL,
    [repeatInterval]         VARCHAR (50)     CONSTRAINT [DF_WMTriggers_repeatInterval_1] DEFAULT ('min') NOT NULL,
    [repeatValue]            INT              CONSTRAINT [DF_WMTriggers_repeatValue] DEFAULT ((1)) NOT NULL,
    [intervalDesc]           VARCHAR (50)     CONSTRAINT [DF_WMTriggers_intervalValue] DEFAULT ('') NOT NULL,
    [active]                 BIT              CONSTRAINT [DF_WMTriggers_active] DEFAULT ((0)) NOT NULL,
    [toString]               VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_toString] DEFAULT ('') NOT NULL,
    [ccString]               VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_ccString] DEFAULT ('') NOT NULL,
    [bccString]              VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_bccString] DEFAULT ('') NOT NULL,
    [emailSubject]           VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_emailSubject] DEFAULT ('AUTO EMAIL') NOT NULL,
    [emailBody]              VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_emailBody] DEFAULT ('') NOT NULL,
    [headerBackgroundColor]  VARCHAR (50)     CONSTRAINT [DF_WMTriggers_headerBackgroundColor] DEFAULT ('silver') NOT NULL,
    [headerColor]            VARCHAR (50)     CONSTRAINT [DF_WMTriggers_headerColor] DEFAULT ('white') NOT NULL,
    [evenRowBackgroundColor] VARCHAR (50)     CONSTRAINT [DF_WMTriggers_evenRowBackgroundColor] DEFAULT ('#fcfeff') NOT NULL,
    [oddRowBackgroundColor]  VARCHAR (50)     CONSTRAINT [DF_WMTriggers_oddRowBackgroundColor] DEFAULT ('#f2fbff') NOT NULL,
    [tableSelect]            VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_tableSelect] DEFAULT ('') NOT NULL,
    [footerSelect]           VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_footerSelect] DEFAULT ('') NOT NULL,
    [stopIfTableNull]        BIT              CONSTRAINT [DF_WMTriggers_stopIfTableNull] DEFAULT ((0)) NOT NULL,
    [triggerSp]              VARCHAR (50)     CONSTRAINT [DF_WMTriggers_triggerSp] DEFAULT ('') NOT NULL,
    [formSelect]             VARCHAR (MAX)    CONSTRAINT [DF_WMTriggers_formSelect] DEFAULT ('') NOT NULL,
    [successNotify]          BIT              CONSTRAINT [DF_WMTriggers_successNotify] DEFAULT ((0)) NOT NULL,
    [endDate]                DATETIME2 (7)    NULL,
    CONSTRAINT [PK_WMTriggers] PRIMARY KEY CLUSTERED ([triggerId] ASC)
);

