CREATE TABLE [dbo].[WODUEDTS] (
    [WONO]       CHAR (10)      CONSTRAINT [DF__WODUEDTS__WONO__463F1544] DEFAULT ('') NOT NULL,
    [DUE_DTS]    SMALLDATETIME  NULL,
    [QTY]        NUMERIC (9, 2) CONSTRAINT [DF__WODUEDTS__QTY__4733397D] DEFAULT ((0)) NOT NULL,
    [DUEDT_UNIQ] CHAR (10)      CONSTRAINT [DF__WODUEDTS__DUEDT___48275DB6] DEFAULT ('') NOT NULL,
    CONSTRAINT [WODUEDTS_PK] PRIMARY KEY CLUSTERED ([DUEDT_UNIQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WONO]
    ON [dbo].[WODUEDTS]([WONO] ASC);

