CREATE TABLE [dbo].[WRKCKLST] (
    [UNIQ_KEY]        CHAR (10)   CONSTRAINT [DF__WRKCKLST__UNIQ_K__7E836E67] DEFAULT ('') NOT NULL,
    [DEPT_ACTIV]      CHAR (4)    CONSTRAINT [DF__WRKCKLST__DEPT_A__7F7792A0] DEFAULT ('') NOT NULL,
    [UNIQNUMBER]      CHAR (10)   CONSTRAINT [DF__WRKCKLST__UNIQNU__006BB6D9] DEFAULT ('') NOT NULL,
    [NUMBER]          NUMERIC (4) CONSTRAINT [DF__WRKCKLST__NUMBER__015FDB12] DEFAULT ((0)) NOT NULL,
    [CHKLST_TIT]      CHAR (100)  CONSTRAINT [DF__WRKCKLST__CHKLST__0253FF4B] DEFAULT ('') NOT NULL,
    [UNIQNBRA]        CHAR (10)   CONSTRAINT [DF__WRKCKLST__UNIQNB__03482384] DEFAULT ('') NOT NULL,
    [WRKCKUNIQ]       CHAR (10)   CONSTRAINT [DF__WRKCKLST__WRKCKU__043C47BD] DEFAULT ('') NOT NULL,
    [TemplateId]      INT         NULL,
    [wccheckpriority] INT         CONSTRAINT [DF_WRKCKLST_wccheckpriority] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [WRKCKLST_PK] PRIMARY KEY CLUSTERED ([WRKCKUNIQ] ASC),
    CONSTRAINT [FK_WRKCKLST_TemplateId] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[RoutingTemplate] ([TemplateID])
);


GO
CREATE NONCLUSTERED INDEX [UNIQKEYNBR]
    ON [dbo].[WRKCKLST]([UNIQ_KEY] ASC, [UNIQNUMBER] ASC, [UNIQNBRA] ASC);

