CREATE TABLE [dbo].[WRKSHIFT] (
    [SHIFT_NO]   NUMERIC (3)     CONSTRAINT [DF__WRKSHIFT__SHIFT___0718B468] DEFAULT ((0)) NOT NULL,
    [SHIFT_DESC] CHAR (25)       CONSTRAINT [DF__WRKSHIFT__SHIFT___080CD8A1] DEFAULT ('') NOT NULL,
    [DAY_START]  CHAR (10)       CONSTRAINT [DF__WRKSHIFT__DAY_ST__0900FCDA] DEFAULT ('') NOT NULL,
    [NO_OF_DAYS] NUMERIC (3)     CONSTRAINT [DF__WRKSHIFT__NO_OF___09F52113] DEFAULT ((0)) NOT NULL,
    [SHIFT_NOTE] TEXT            CONSTRAINT [DF__WRKSHIFT__SHIFT___0AE9454C] DEFAULT ('') NOT NULL,
    [DHR_STRT]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__DHR_ST__0BDD6985] DEFAULT ((0)) NOT NULL,
    [DHR_END]    NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__DHR_EN__0CD18DBE] DEFAULT ((0)) NOT NULL,
    [DMIN_STRT]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__DMIN_S__0DC5B1F7] DEFAULT ((0)) NOT NULL,
    [DMIN_END]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__DMIN_E__0EB9D630] DEFAULT ((0)) NOT NULL,
    [BHR_STRT1]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_ST__0FADFA69] DEFAULT ((0)) NOT NULL,
    [BHR_END1]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_EN__10A21EA2] DEFAULT ((0)) NOT NULL,
    [BMIN_STRT1] NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_S__119642DB] DEFAULT ((0)) NOT NULL,
    [BMIN_END1]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_E__128A6714] DEFAULT ((0)) NOT NULL,
    [BHR_STRT2]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_ST__137E8B4D] DEFAULT ((0)) NOT NULL,
    [BHR_END2]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_EN__1472AF86] DEFAULT ((0)) NOT NULL,
    [BMIN_STRT2] NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_S__1566D3BF] DEFAULT ((0)) NOT NULL,
    [BMIN_END2]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_E__165AF7F8] DEFAULT ((0)) NOT NULL,
    [BHR_STRT3]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_ST__174F1C31] DEFAULT ((0)) NOT NULL,
    [BHR_END3]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_EN__1843406A] DEFAULT ((0)) NOT NULL,
    [BMIN_STRT3] NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_S__193764A3] DEFAULT ((0)) NOT NULL,
    [BMIN_END3]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_E__1A2B88DC] DEFAULT ((0)) NOT NULL,
    [BHR_STRT4]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_ST__1B1FAD15] DEFAULT ((0)) NOT NULL,
    [BHR_END4]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BHR_EN__1C13D14E] DEFAULT ((0)) NOT NULL,
    [BMIN_STRT4] NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_S__1D07F587] DEFAULT ((0)) NOT NULL,
    [BMIN_END4]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__BMIN_E__1DFC19C0] DEFAULT ((0)) NOT NULL,
    [LHR_STRT1]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LHR_ST__1EF03DF9] DEFAULT ((0)) NOT NULL,
    [LHR_END1]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LHR_EN__1FE46232] DEFAULT ((0)) NOT NULL,
    [LMIN_STRT1] NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LMIN_S__20D8866B] DEFAULT ((0)) NOT NULL,
    [LMIN_END1]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LMIN_E__21CCAAA4] DEFAULT ((0)) NOT NULL,
    [LHR_STRT2]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LHR_ST__22C0CEDD] DEFAULT ((0)) NOT NULL,
    [LHR_END2]   NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LHR_EN__23B4F316] DEFAULT ((0)) NOT NULL,
    [LMIN_STRT2] NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LMIN_S__24A9174F] DEFAULT ((0)) NOT NULL,
    [LMIN_END2]  NUMERIC (2)     CONSTRAINT [DF__WRKSHIFT__LMIN_E__259D3B88] DEFAULT ((0)) NOT NULL,
    [TOT_MIN]    NUMERIC (12, 2) CONSTRAINT [DF__WRKSHIFT__TOT_MI__26915FC1] DEFAULT ((0)) NOT NULL,
    [BREAK_MIN]  NUMERIC (12, 2) CONSTRAINT [DF__WRKSHIFT__BREAK___278583FA] DEFAULT ((0)) NOT NULL,
    [LUNCH_MIN]  NUMERIC (12, 2) CONSTRAINT [DF__WRKSHIFT__LUNCH___2879A833] DEFAULT ((0)) NOT NULL,
    [GLDIVNO]    CHAR (2)        CONSTRAINT [DF__WRKSHIFT__GLDIVN__296DCC6C] DEFAULT ('') NOT NULL,
    [UNIQUEREC]  CHAR (10)       CONSTRAINT [DF__WRKSHIFT__UNIQUE__2A61F0A5] DEFAULT ('') NOT NULL,
    CONSTRAINT [WRKSHIFT_PK] PRIMARY KEY CLUSTERED ([UNIQUEREC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SHIFT_NO]
    ON [dbo].[WRKSHIFT]([SHIFT_NO] ASC);

