-- =============================================  
-- Author: Rajendra K  
-- Create date: <12/20/2016>  
-- Description: Add/Update Contract records  
-- Modification  
 -- 03/28/17 YS : Changed length of the part_no column from 25 to 35  
    -- 08/18/2017 Rajendra K : Removed Insert/Update Foreign currncy related column into ContractHeader insert/Update trigger  
 -- 08/22/2017 Rajendra K : Inserting transction value into PriceFc  
 -- 09/19/2017 Rajendra K : Inserting @PriceFC value into PriceFc On 09/19/2017 - Rajendra K  
 -- 09/19/2017 Rajendra K : Inserting @Price value into Price On 09/19/2017 - Rajendra K  
 -- 09/19/2017 Rajendra K : Insert values in fcused_uniq & fchist_key columns  
 -- 12/31/2018 Nitesh B : Changed length of the ConrtactNumber parameter from 9 to 40  
 -- 01/04/2019 Nitesh B : Changed length of the ConrtactNumber parameter from 40 to 20  
 -- 09/26/19 YS modifed part_no to have 35 characters
-- =============================================  
CREATE PROCEDURE  [dbo].[AddUpdateContract]  
(  
@ContractHeaderKey NVARCHAR(10)=NULL,  
@ConrtactNumber NVARCHAR(20), -- 12/31/2018 Nitesh B : Changed length of the ConrtactNumber parameter from 9 to 40  
								-- 01/04/2019 Nitesh B : Changed length of the ConrtactNumber parameter from 40 to 20
@QuoteNumber NVARCHAR(4000),  
@StartDate DATE,  
@ExpireDate DATE = null,  
@IsPrimSupplier BIT=0,  
@ContractNote NVARCHAR(MAX),  
@UniqSupplierNumber CHAR(10),  
@UserId UNIQUEIDENTIFIER,  
@IsAutoGenerated BIT=0,  
@XMLContractItemList XML,  
@Out_ContractHeader NVARCHAR(MAX) OUTPUT  
)  
AS  
BEGIN  
 SET NOCOUNT ON;  
    --Declare variables  
 DECLARE @FCUsedUniq CHAR(10),  -- 09/19/2017 Rajendra K : added variable @FCUsedUniq to insert FCUsed_Uniq in ContractHeader table  
   @FCHistoryKey CHAR(10), -- 09/19/2017 Rajendra K : added variable @FCHist to insert FCHist_Key in ContractHeader table  
   @IsInsert BIT = 1,  
   @OutContractHeaderUniq CHAR(15),  
   @OutContractUniq CHAR(10),  
   @OutMFGRUniq CHAR(10)     
  
    --Declare table for ContractItem list  
 DECLARE @ContractItemTable TABLE  
   (   
     ROWID int identity(1,1) primary key  
    ,UniqKey  CHAR(10)
	 -- 09/26/19 YS modifed part_no to have 35 characters
     ,PartNumber CHAR(35)  
    ,PartRevision CHAR(8)  
    ,QualityLimit NUMERIC(7,0)  
    ,MinQuality NUMERIC(7,0)  
    ,ContractItemNote NVARCHAR(MAX)   
    ,ContractMFGRList NVARCHAR(MAX)  
   )   
  
   INSERT INTO @ContractItemTable  
   SELECT  
        data.col.value('@UniqKey', 'CHAR(10)')  
		 -- 09/26/19 YS modifed part_no to have 35 characters
      , data.col.value('@PartNumber', 'CHAR(35)')  
      , data.col.value('@PartRevision', 'CHAR(8)')  
      , data.col.value('@QualityLimit', 'NUMERIC(7,0)')  
      , data.col.value('@MinQuality', 'NUMERIC(7,0)')  
      , data.col.value('@ContractItemNote', 'NVARCHAR(MAX)')  
      , data.col.value('@ContractMFGRList', 'NVARCHAR(MAX)')  
   FROM @XMLContractItemList.nodes('//a') data(col)  
   
 --Create temp table for ContractMFGRList  
 CREATE TABLE #ContractMFGRListTable  
            (  
        ROWMFID int identity(1,1) primary key  
       ,PartManufacturer CHAR(8)  
       ,ManufacturerPartNumber CHAR(30)  
       ,PurLineItem INT  
       ,PurUnit CHAR(2)  
       ,Priority INT  
       ,ContractPriceList NVARCHAR(MAX)  
   )  
     
   --Declare ContractPriceList temp table   
 DECLARE @ContractPriceListTable TABLE  
   (  
        Quantity NUMERIC(10,0)  
          ,Price NUMERIC(13,5)  
          ,PriceFC NUMERIC(13,5)  
   )  
  
 --Declare table variable for ContractHeaderKey  
 DECLARE @ContractHeader TABLE(  
   id CHAR(15) NOT NULL  
   )  
      
 -- 08/18/2017 Rajendra K : Removed Insert/Update Foreign currncy related column into ContractHeader insert/Update trigger  
   
  
 --09/19/2017 Rajendra K : Get @FCUsedUniq & @FCUsedUniq from SUPINFO table  
  SET @FCUsedUniq = (SELECT Fcused_Uniq FROM SUPINFO WHERE UNIQSUPNO = @UniqSupplierNumber)   
  
  --09/19/2017 Rajendra K : Get @FCUsedUniq from FcHistory table  
  SET @FCHistoryKey = dbo.getLatestExchangeRate(@FCUsedUniq)  
  
  
 --Set @IsInsert flag = 0 if record already exists for given @ConrtactNumber,@QuoteNumber and @UniqSuppierKey  
    IF EXISTS(SELECT 1 FROM contractHeader   
        WHERE Contr_no = ISNULL(@ConrtactNumber,'') AND quote_no= ISNULL(@QuoteNumber,'') AND uniqsupno = @UniqSupplierNumber)  
 BEGIN  
  SET @IsInsert = 0  
 END  
  
 --Check entry is new or existing  
 DECLARE @UdpateContractHeader BIT = 0  
 IF (@ContractHeaderKey IS NOT NULL AND @ContractHeaderKey <> '')  
 BEGIN  
 IF EXISTS (SELECT 1 FROM dbo.contractHeader WHERE ContractH_unique = @ContractHeaderKey)  
 BEGIN  
 SET @UdpateContractHeader = 1  
 END  
    END  
  
IF (@UdpateContractHeader=1)  
 BEGIN  
  UPDATE ContractHeader  
  SET Contr_no = ISNULL(@ConrtactNumber,'')  
   ,quote_no = ISNULL(@QuoteNumber,'')  
   ,startDate = @StartDate  
   ,expireDate = @ExpireDate  
   ,primSupplier = @IsPrimSupplier  
   ,contractNote = @ContractNote  
   ,uniqsupno = uniqsupno  
   -- 08/18/2017 Rajendra K :  Removed Insert/Update Foreign currncy related column into ContractHeader insert/Update trigger  
   ,contrUpdateDate = GETDATE()  
   ,contrUpdatedby = @UserId  
   ,AutoGenerated = @IsAutoGenerated     
  WHERE ContractH_unique = @ContractHeaderKey  
     SET @OutContractHeaderUniq = @ContractHeaderKey  
 END  
 ELSE  
 BEGIN  
--Insert values into tables  
  IF (@IsInsert =1)  
   BEGIN  
 --Insert values into table contractHeader   
   INSERT INTO ContractHeader   
             (  
              Contr_no  
             ,quote_no  
             ,startDate  
             ,expireDate  
             ,primSupplier  
             ,contractNote  
             ,uniqsupno  
             --Removed Insert/Update Foreign currncy related column into ContractHeader insert/Update trigger  
    ,AutoGenerated  
    ,contrUserId  
    ,contrUpdatedby  
    ,fcused_uniq --09/19/2017 Rajendra K : Insert @FCUsedUniq in fcused_uniq  
    ,fchist_key  --09/19/2017 Rajendra K : Insert @FCHistoryKey in fchist_key  
           )  
 --Get ContractHeaderKey for newsly inserted record  
 OUTPUT inserted.ContractH_unique INTO @ContractHeader  
 VALUES  
    (  
     ISNULL(@ConrtactNumber,'')  
    ,ISNULL(@QuoteNumber,'')  
    ,@StartDate  
    ,@ExpireDate   
    ,@IsPrimSupplier  
    ,@ContractNote  
    ,@UniqSupplierNumber  
    -- 08/18/2017 Rajendra K : Removed Insert/Update Foreign currncy related column into ContractHeader insert/Update trigger  
    ,@IsAutoGenerated  
    ,@UserId  
    ,@UserId  
    ,ISNULL(@FCUsedUniq,'') --09/19/2017 Rajendra K : Insert @FCUsedUniq in fcused_uniq  
    ,ISNULL(@FCHistoryKey,'') --09/19/2017 Rajendra K : Insert @FCHistoryKey in fchist_key  
    )  
 --Set ContractHeaderKey for newsly inserted record  
   SET @OutContractHeaderUniq = (SELECT id FROM @ContractHeader)   
   END  
  ELSE  
   BEGIN  
   SET @OutContractHeaderUniq = (SELECT ContractH_unique FROM contractHeader   
        WHERE Contr_no = ISNULL(@ConrtactNumber,'') AND quote_no= ISNULL(@QuoteNumber,'') AND uniqsupno = @UniqSupplierNumber)  
  END  
 END  
DECLARE @MAXID INT, @Counter INT  
 SET @COUNTER = 1  
   
 SELECT @MAXID = COUNT(*) FROM @ContractItemTable  
   
 WHILE (@COUNTER <= @MAXID)  
 BEGIN  
  IF EXISTS(SELECT 1 FROM CONTRACT WHERE contractH_unique = @OutContractHeaderUniq AND UNIQ_KEY = (SELECT UniqKey FROM @ContractItemTable WHERE ROWID = @Counter))  
   BEGIN  
    SET @OutContractUniq =   
    (  
    SELECT CONTR_UNIQ FROM CONTRACT WHERE contractH_unique = @OutContractHeaderUniq AND UNIQ_KEY = (SELECT UniqKey FROM @ContractItemTable WHERE ROWID = @Counter)  
    )  
    UPDATE CONTRACT SET   
        CONTRACT.QTYLIMIT = QualityLimit  
        ,MINQTY = MinQuality  
        ,CONTRACT.contractItemNote = CIT.ContractItemNote    
    FROM @ContractItemTable CIT   
    WHERE ROWID = @Counter   
       AND Contract.contractH_unique = @OutContractHeaderUniq   
       AND dbo.CONTRACT.UNIQ_KEY = ( SELECT UniqKey   
             FROM @ContractItemTable   
             WHERE ROWID = @Counter)  
   END  
  ELSE  
   BEGIN  
    SET @OutContractUniq = dbo.fn_GenerateUniqueNumber()  
       --Insert values into table CONTRACT   
    INSERT INTO CONTRACT  
       (  
         CONTR_UNIQ  
        ,UNIQ_KEY  
        ,QTYLIMIT  
        ,MINQTY  
        ,contractItemNote  
        ,contractH_unique  
       )  
        SELECT @OutContractUniq  
        ,UniqKey  
        ,QualityLimit  
        ,MinQuality  
        ,ContractItemNote  
        ,@OutContractHeaderUniq   
       FROM @ContractItemTable   
       WHERE ROWID = @COUNTER   
  END  
   
    --Extract rows from ContractManufacturer XML record and set into variable       
    DECLARE @ContractMFGRString NVARCHAR(MAX), @XMLMFGRListTable XML;  
  
    SET @ContractMFGRString =(SELECT ContractMFGRList FROM @ContractItemTable WHERE ROWID = @COUNTER)  
     
    SET @ContractMFGRString = '<data>' +  @ContractMFGRString  
    SET @ContractMFGRString = replace(@ContractMFGRString, '?', '<a')  
    SET @ContractMFGRString = replace(@ContractMFGRString, '#', '"')  
    SET @ContractMFGRString = replace(@ContractMFGRString, '!!', '/>')  
    SET @ContractMFGRString = @ContractMFGRString + '</data>'  
  
    SET @XMLMFGRListTable = @ContractMFGRString  
  
    --Declare table for contract Price   
   TRUNCATE TABLE  #ContractMFGRListTable  
   
       --insert XML record into temp table  
   INSERT INTO #ContractMFGRListTable  
   SELECT  
        data.col.value('@PartManufacturer', 'CHAR(8)')  
      , data.col.value('@ManufacturerPartNumber', 'CHAR(30)')  
      , data.col.value('@PurLineItem', 'INT')  
       , data.col.value('@PurUnit', 'CHAR(2)')  
       , data.col.value('@Priority', 'INT')  
        , data.col.value('@ContractPriceList', 'NVARCHAR(MAX)')  
   FROM @XMLMFGRListTable.nodes('//a') data(col)  
  
 DECLARE @MAXMFID INT, @CounterMF INT  
 SET @CounterMF = 1  
   
 SELECT @MAXMFID = COUNT(*) FROM #ContractMFGRListTable  
   
 WHILE (@CounterMF <= @MAXMFID)  
 BEGIN   
 --Update/Insert record into CONTMFR table  
 IF EXISTS(SELECT 1 FROM CONTMFGR CF INNER JOIN  #ContractMFGRListTable CIT ON CF.PARTMFGR =  CIT.PartManufacturer  AND CF.MFGR_PT_NO = CIT.ManufacturerPartNumber  
  WHERE CIT.ROWMFID = @CounterMF AND CF.CONTR_UNIQ = @OutContractUniq)  
   BEGIN  
    UPDATE CONTMFGR SET   
       CONTMFGR.Pur_ltime = CIT.PurLineItem   
      ,CONTMFGR.pur_lunit = CIT.PurUnit   
      ,CONTMFGR.Priority = CIT.Priority   
  FROM #ContractMFGRListTable CIT   
  INNER JOIN CONTMFGR ON CONTMFGR.PARTMFGR = CIT.PartManufacturer AND CONTMFGR.MFGR_PT_NO = CIT.ManufacturerPartNumber   
  WHERE ROWMFID = @CounterMF  
    AND CONTMFGR.CONTR_UNIQ = @OutContractUniq  
    SET @OutMFGRUniq = (SELECT MFGR_UNIQ FROM CONTMFGR CF INNER JOIN  #ContractMFGRListTable CIT ON CF.PARTMFGR =  CIT.PartManufacturer   
     AND CF.MFGR_PT_NO = CIT.ManufacturerPartNumber  
    WHERE ROWMFID = @CounterMF AND CF.CONTR_UNIQ = @OutContractUniq)  
   END  
 ELSE  
   BEGIN  
    SET @OutMFGRUniq = dbo.fn_GenerateUniqueNumber()  
      
    --Insert values into table CONTMFGR  
    INSERT INTO CONTMFGR  
        (  
             CONTR_UNIQ  
         ,MFGR_UNIQ  
         ,PARTMFGR  
         ,MFGR_PT_NO  
         ,Pur_ltime  
         ,pur_lunit  
       ,Priority  
         )  
    SELECT    @OutContractUniq  
        ,@OutMFGRUniq  
        ,PartManufacturer  
        ,ManufacturerPartNumber  
        ,PurLineItem  
        ,PurUnit  
      ,Priority  
    FROM #ContractMFGRListTable   
    WHERE ROWMFID = @CounterMF  
   END  
  
   --Extract rows from ContractManufacturer XML record and set into variable       
    DECLARE @ContractPriceString NVARCHAR(MAX), @XMLPriceListTable XML;  
   SET @ContractPriceString =(SELECT ContractPriceList FROM #ContractMFGRListTable WHERE ROWMFID = @CounterMF)  
  
    SET @ContractPriceString = '<data>' +  @ContractPriceString  
    SET @ContractPriceString = replace(@ContractPriceString, '|', '<a')  
    SET @ContractPriceString = replace(@ContractPriceString, '`', '"')  
    SET @ContractPriceString = replace(@ContractPriceString, '~~', '/>')  
    SET @ContractPriceString = @ContractPriceString + '</data>'  
  
    SET @XMLPriceListTable = @ContractPriceString  
  
    --Declare table for contract Price   
   DELETE FROM @ContractPriceListTable  
   
   INSERT INTO @ContractPriceListTable  
   SELECT  
        data.col.value('@Quantity', 'NUMERIC(10,0)')  
      , data.col.value('@Price', 'NUMERIC(13,5)')  
      , data.col.value('@PriceFC', 'NUMERIC(13,5)')  
   FROM @XMLPriceListTable.nodes('//a') data(col)  
  
   IF EXISTS(SELECT 1 FROM CONTPRIC WHERE MFGR_UNIQ = @OutMFGRUniq AND CONTR_UNIQ = @OutContractUniq)  
   BEGIN  
    DELETE FROM CONTPRIC WHERE MFGR_UNIQ = @OutMFGRUniq AND CONTR_UNIQ = @OutContractUniq  
   END  
      --Insert values into table CONTPRIC   
   INSERT INTO CONTPRIC   
      (  
        MFGR_UNIQ  
       ,PRIC_UNIQ  
       ,QUANTITY  
       ,PRICE  
       ,CONTR_UNIQ  
       ,PriceFC  
       )  
          SELECT @OutMFGRUniq  
       ,dbo.fn_GenerateUniqueNumber()  
       ,ISNULL(Quantity,0)  
       --,0      -- 08/22/2017 Rajendra K Inserting transction value into PriceFc  
       ,ISNULL(Price,0) -- 09/19/2017 Rajendra K : Inserting @Price value into Price  
       ,@OutContractUniq  
       --,Price   -- 08/22/2017 Rajendra K : Inserting transction value into PriceFc  
       ,ISNULL(PriceFC,0) -- 09/19/2017 Rajendra K : Inserting @PriceFC value into PriceFc On 09/19/2017 - Rajendra K  
         FROM @ContractPriceListTable  
  
      SET @CounterMF = @CounterMF + 1  
      END  
  
  SET @COUNTER = @COUNTER + 1  
 END  
   
 SET @Out_ContractHeader = @OutContractHeaderUniq  
 SELECT @Out_ContractHeader  
END  
  