CREATE PROC [dbo].[GeneralSetupSecurityView]
AS  
SELECT [XLIVAL]
      ,[XDT]
      ,[XORIG]
      ,[CHAUDNOMEN1]
      ,[CHAUDNOMEN2]
      ,[CHAUDNOMEN3]
      ,[CHAUDNOMEN4]
      ,[CHAUDNOMEN5]
      ,[CHAUDNOMEN6]
      ,[CHAUDNOMEN7]
      ,[CHAUDNOMEN8]
      ,[CHAUDNOMEN9]
      ,[UNIQUEREC]
      ,[CUSTOMROOTURL]
  FROM [dbo].[GENERALSETUP]