-- =============================================
-- Author:		Rajendra K	
-- Create date: <04/24/2017>
-- Description:Get ContractItem list from UI
--- 07/11/18 YS part number changed to 35
-- =============================================
CREATE PROCEDURE [dbo].[GetContractItemList]
(
@ContractHeaderKey CHAR(10)=null,
--- 07/11/18 YS part number increased from 25 to 35
@PartNumber CHAR(35),
@Rev CHAR(8)
)
AS
BEGIN
   SET NOCOUNT ON;  

  SELECT DISTINCT
		   CH.ContractH_unique
		  ,C.UNIQ_KEY 
		  ,I.PART_NO + (CASE WHEN I.REVISION IS NULL OR I.REVISION = '' THEN I.REVISION ELSE '/'+ I.REVISION END) AS PART_NO
		  ,(CASE WHEN I.PART_CLASS IS NULL OR  I.PART_CLASS = '' THEN I.PART_CLASS ELSE I.PART_CLASS +'/ ' END ) + 
		   (CASE WHEN I.PART_TYPE IS NULL OR I.PART_TYPE ='' THEN ' / '+ I.DESCRIPT ELSE I.PART_TYPE + '/'+I.DESCRIPT END) AS Descript 
		  ,I.REVISION
		  ,I.PART_TYPE
		  ,CH.uniqsupno
		  ,S.SUPNAME AS supname
		  ,S.SUPID 
		  ,CH.Contr_no
		  ,CH.quote_no
		  ,CH.startDate
		  ,CH.expireDate
		  ,CH.primSupplier
		  ,CH.contractNote
		  ,CH.AutoGenerated
		  ,AP.Initials AS UserId
		  ,C.CONTR_UNIQ
		  ,C.QTYLIMIT
		  ,ISNULL(C.MINQTY,0) AS MINQTY
		  ,CAST (C.contractItemNote AS NVARCHAR(MAX)) AS contractItemNote
	FROM contractHeader CH 
		  INNER JOIN CONTRACT C ON CH.ContractH_unique = C.contractH_unique 
		  INNER JOIN INVENTOR I ON C.UNIQ_KEY  = I.UNIQ_KEY
		  INNER JOIN CONTMFGR CM ON C.CONTR_UNIQ = CM.CONTR_UNIQ
		  INNER JOIN CONTPRIC CP ON CM.CONTR_UNIQ = CP.CONTR_UNIQ AND CM.MFGR_UNIQ = CP.MFGR_UNIQ
		  INNER JOIN SUPINFO S ON CH.uniqsupno = S.UNIQSUPNO
		  INNER JOIN aspnet_Profile AP ON CH.contrUserId = AP.UserId
	WHERE (@ContractHeaderKey IS NULL OR @ContractHeaderKey ='' OR CH.ContractH_unique = @ContractHeaderKey )
	      AND ((@PartNumber IS NULL OR @PartNumber = '')OR (I.PART_NO =  @PartNumber AND (PART_SOURC ='BUY' OR (PART_SOURC = 'MAKE' AND MAKE_BUY = 1)))
		  AND (REVISION = ISNULL(@Rev,REVISION ) OR @Rev=''))
END