-- =============================================  
-- Author:  Rajendra K   
-- Create date: <12/08/2016>  
-- Description:Get Contract records  
--- 03/28/17 YS changed length of the part_no column from 25 to 35  
--- 07/11/18 YS supname increased from 30 to 50  
-- =============================================  
CREATE PROCEDURE [dbo].[GetContract]  
(  
--- 03/28/17 YS changed length of the part_no column from 25 to 35  
@PartNumber CHAR(35),  
@Rev CHAR(8),  
--- 07/11/18 YS supname increased from 30 to 50  
@SupplierName CHAR(50),  
@SupplierUniq CHAR(10),  
@ContractNumber NVARCHAR(20),  
@ExpiredContract BIT = 0,  
@IsAutoGenerated BIT = 0,  
@TodayDate DATETIME    
)  
AS  
BEGIN  
 DECLARE @SupplierUniqKey CHAR(10)  
       
  --Get SupplierUniqKey from SupplierName  
     IF @SupplierName IS NOT NULL  
  BEGIN  
  SET @SupplierUniqKey = (SELECT TOP(1)UNIQSUPNO FROM SUPINFO WHERE SUPNAME = @SupplierName)  
  END  
  ELSE  
  BEGIN  
  IF @SupplierUniq IS NOT NULL  
  BEGIN  
  SET @SupplierUniqKey = @SupplierUniq  
  END  
  END  
 SELECT DISTINCT C.UNIQ_KEY   
    ,I.PART_NO  
    ,(CASE WHEN I.PART_CLASS IS NULL OR  I.PART_CLASS = '' THEN I.PART_CLASS ELSE I.PART_CLASS +'/ ' END ) +   
    (CASE WHEN I.PART_TYPE IS NULL OR I.PART_TYPE ='' THEN I.PART_TYPE ELSE I.PART_TYPE + '/ '+I.DESCRIPT END) AS DESCRIPT  
    ,I.PART_CLASS   
    ,I.REVISION  
    ,I.PART_TYPE  
    --,I.DESCRIPT  
    ,CH.ContractH_unique  
    ,CH.Contr_no  
    ,CH.quote_no  
    ,CH.startDate  
    ,CH.expireDate  
    ,CH.primSupplier  
    ,CH.contractNote  
    ,CH.uniqsupno  
    ,CH.AutoGenerated  
    ,AP.Initials AS UserId  
    ,S.SUPNAME  
    ,CH.fcused_uniq  
    ,CH.fchist_key  
    ,C.QTYLIMIT  
    ,ISNULL(C.MINQTY,0) AS MINQTY  
    ,C.CONTR_UNIQ  
    ,CAST (C.contractItemNote AS NVARCHAR(MAX)) AS contractItemNote  
    ,CM.MFGR_UNIQ  
    ,CM.PARTMFGR  
    ,CM.MFGR_PT_NO  
    ,CM.Priority  
    ,CM.Pur_ltime  
    ,CM.pur_lunit  
    ,CP.PRIC_UNIQ  
    ,CP.QUANTITY  
    ,CP.PRICE  
    ,CP.PriceFC  
 FROM contractHeader CH   
  INNER JOIN CONTRACT C ON CH.ContractH_unique = C.contractH_unique   
  INNER JOIN INVENTOR I ON C.UNIQ_KEY  = I.UNIQ_KEY  
  INNER JOIN CONTMFGR CM ON C.CONTR_UNIQ = CM.CONTR_UNIQ  
  INNER JOIN CONTPRIC CP ON CM.CONTR_UNIQ = CP.CONTR_UNIQ AND CM.MFGR_UNIQ = CP.MFGR_UNIQ  
  INNER JOIN SUPINFO S ON CH.uniqsupno = S.UNIQSUPNO  
  INNER JOIN aspnet_Profile AP ON CH.contrUserId = AP.UserId  
 WHERE ((@PartNumber IS NULL OR @PartNumber = '')OR (I.PART_NO =  @PartNumber AND   
    (PART_SOURC ='BUY' OR (PART_SOURC = 'MAKE' AND MAKE_BUY = 1)) AND (REVISION = ISNULL(@Rev,REVISION ) OR @Rev='')))  
       AND (@SupplierName IS NULL OR @SupplierName = '' OR CH.uniqsupno = @SupplierUniqKey)  
    AND (@SupplierUniq IS NULL OR @SupplierName = '' OR CH.uniqsupno = @SupplierUniqKey)  
    AND (@ContractNumber ='' OR CH.Contr_no = ISNULL(@ContractNumber,CH.Contr_no ))  
    AND (@ExpiredContract = 0 OR CH.expireDate < ISNULL(@TodayDate,GETDATE()))  
    AND (CH.AutoGenerated = @IsAutoGenerated)  
END