
-- =============================================
-- Date			: 07/27/2019
-- Author		: Mahesh B
-- Description:	This SP is Used for for get Part Class Type Uploaded Data
-- GetPartClassTypeUploadDataByImportId '67d81d37-5824-4bb8-bf80-4d46f10b164c'
-- 11/04/2019  MaheshB - Rename the Column Name from USEIPKEY to MTC for Fixed the CAPA 2046.
-- =============================================

CREATE PROCEDURE GetPartClassTypeUploadDataByImportId 
@Importid UNIQUEIDENTIFIER

AS
SET NOCOUNT ON; 
    
	Declare @ModuleId INT

	SELECT @ModuleId = ModuleId FROM MnxModule WHERE ModuleName = 'Part Master &  AML Control (PM)' AND FilePath = 'PartMaster'

SELECT Pvt.importId,ImportTemplateId,Pvt.rowId,Pvt.part_class,Pvt.classDescription,Pvt.classUnique ,
	Pvt.CssClass,Pvt.Validation,ORD_POLICY
	,CASE WHEN TRIM(LTRIM(STDCOST)) = '' OR ISNUMERIC(STDCOST) = 0 THEN 0 ELSE CAST(STDCOST AS DECIMAL(13,5)) END AS STDCOST
	,CASE WHEN TRIM(LTRIM(PUSH_OUT)) = '' OR ISNUMERIC(PUSH_OUT) = 0 THEN 0 ELSE CAST(PUSH_OUT AS DECIMAL(3,0)) END PUSH_OUT 
	,CASE WHEN TRIM(LTRIM(PULL_IN)) = '' OR ISNUMERIC(PULL_IN) = 0 THEN 0 ELSE CAST(PULL_IN AS DECIMAL(3,0)) END AS PULL_IN
	,CASE WHEN TRIM(LTRIM(SCRAP)) = '' OR ISNUMERIC(SCRAP) = 0 THEN 0 ELSE CAST(SCRAP AS DECIMAL(6,2)) END AS SCRAP
	,CASE WHEN TRIM(LTRIM(PUR_LTIME)) = '' OR ISNUMERIC(PUR_LTIME) = 0 THEN 0 ELSE CAST(PUR_LTIME AS DECIMAL(3,0)) END AS PUR_LTIME
	,CASE WHEN TRIM(LTRIM(ORDMULT)) = '' OR ISNUMERIC(ORDMULT) = 0 THEN 0 ELSE CAST(ORDMULT AS DECIMAL(7,0)) END AS ORDMULT
	,CASE WHEN TRIM(LTRIM(OVERHEAD)) = '' OR ISNUMERIC(OVERHEAD) = 0 THEN 0 ELSE CAST(OVERHEAD AS DECIMAL(13,5)) END AS OVERHEAD
	,CASE WHEN TRIM(LTRIM(DAYOFMO2)) = '' OR ISNUMERIC(DAYOFMO2) = 0 THEN 0 ELSE CAST(DAYOFMO2 AS DECIMAL(2,0)) END AS DAYOFMO2
	,CASE WHEN TRIM(LTRIM(DAYOFMO)) = '' OR ISNUMERIC(DAYOFMO) = 0 THEN 0 ELSE CAST(DAYOFMO AS DECIMAL(2,0)) END AS DAYOFMO
	,CASE WHEN TRIM(LTRIM(DAY)) = '' OR ISNUMERIC(DAY) = 0 THEN 0 ELSE CAST(DAY AS DECIMAL(1,0)) END AS DAY
	,CASE WHEN TRIM(LTRIM(MINORD)) = '' OR ISNUMERIC(MINORD) = 0 THEN 0 ELSE CAST(MINORD AS DECIMAL(7,0)) END AS MINORD
	,CASE WHEN TRIM(LTRIM(PROD_LTIME)) = '' OR ISNUMERIC(PROD_LTIME) = 0 THEN 0 ELSE CAST(PROD_LTIME AS DECIMAL(3,0)) END AS PROD_LTIME
	,CASE WHEN TRIM(LTRIM(FGIEXPDAYS)) = '' OR ISNUMERIC(FGIEXPDAYS) = 0 THEN 0 ELSE CAST(FGIEXPDAYS AS DECIMAL(4,0)) END AS FGIEXPDAYS
	,CASE WHEN TRIM(LTRIM(REORDPOINT)) = '' OR ISNUMERIC(REORDPOINT) = 0 THEN 0 ELSE CAST(REORDPOINT AS DECIMAL(7,0)) END AS REORDPOINT
	,CASE WHEN TRIM(LTRIM(OTHERCOST2)) = '' OR ISNUMERIC(OTHERCOST2) = 0 THEN 0 ELSE CAST(OTHERCOST2 AS DECIMAL(13,5)) END AS OTHERCOST2
	,CASE WHEN TRIM(LTRIM(OTHER_COST)) = '' OR ISNUMERIC(OTHER_COST) = 0 THEN 0 ELSE CAST(OTHER_COST AS DECIMAL(13,5)) END AS OTHER_COST
	,CASE WHEN TRIM(LTRIM(TARGETPRICE)) = '' OR ISNUMERIC(TARGETPRICE) = 0 THEN 0 ELSE CAST(TARGETPRICE AS DECIMAL(13,5)) END AS TARGETPRICE
	,CASE WHEN TRIM(LTRIM(REORDERQTY)) = '' OR ISNUMERIC(REORDERQTY) = 0 THEN 0 ELSE CAST(REORDERQTY AS DECIMAL(7,0)) END AS REORDERQTY
	,CASE WHEN TRIM(LTRIM(SETUPSCRAP)) = '' OR ISNUMERIC(SETUPSCRAP) = 0 THEN 0 ELSE CAST(SETUPSCRAP AS DECIMAL(4,0)) END AS SETUPSCRAP
	,CASE WHEN TRIM(LTRIM(KIT_LTIME)) = '' OR ISNUMERIC(KIT_LTIME) = 0 THEN 0 ELSE CAST(KIT_LTIME AS DECIMAL(3,0)) END AS KIT_LTIME
	,CASE WHEN TRIM(LTRIM(LABORCOST)) = '' OR ISNUMERIC(LABORCOST) = 0 THEN 0 ELSE CAST(LABORCOST AS DECIMAL(13,5)) END AS LABORCOST
	,CASE WHEN TRIM(LTRIM(MATL_COST)) = '' OR ISNUMERIC(MATL_COST) = 0 THEN 0 ELSE CAST(MATL_COST AS DECIMAL(13,5)) END AS MATL_COST
	-- 11/04/2019  MaheshB - Rename the Column Name from USEIPKEY to MTC for Fixed the CAPA 2046
	,CAST((CASE WHEN TRIM(LTRIM(MTC)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS USEIPKEY
	,CAST((CASE WHEN TRIM(LTRIM(allowAutoKit)) IN ('Yes','Y','TRUE','1') THEN 1 ELSE 0 END) AS BIT) AS allowAutoKit
	,CAST((CASE WHEN TRIM(LTRIM(AUTONUM)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS AUTONUM
	,CAST((CASE WHEN TRIM(LTRIM(AUTODT)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS AUTODT
	,CAST((CASE WHEN TRIM(LTRIM(UseCustPFX)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS UseCustPFX
	,CAST((CASE WHEN TRIM(LTRIM(Taxable)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS Taxable
	,CAST((CASE WHEN TRIM(LTRIM(AUTOLOCATION)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS AUTOLOCATION
	,CAST((CASE WHEN TRIM(LTRIM(CERT_REQ)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS CERT_REQ
	,CAST((CASE WHEN TRIM(LTRIM(LOTDETAIL)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS LOTDETAIL
	,CAST((CASE WHEN TRIM(LTRIM(INSP_REQ)) IN ('Yes','Y','TRUE','1') THEN  1 ELSE 0 END) AS BIT) AS INSP_REQ	

	,ABC,CERT_TYPE,Buyer,U_OF_MEAS,MRC,LOC_TYPE,[DESCRIPTION],ORD_FREQ,PACKAGE,CLASSDESCRIPTION,PUR_UOFM
	,PART_PKG,WAREHOUSE,PREFIX,PART_TYPE
	FROM        
	(
	SELECT ibf.fkImportId AS importId, ti.ImportTemplateId,ibf.rowId,
	ti.classUnique AS classUnique ,
	sub.class AS CssClass,sub.Validation,fd.fieldName,adjusted		   
	FROM ImportFieldDefinitions fd          			
	INNER JOIN importPartClassTypeFields ibf ON fd.FieldDefId = ibf.FKFieldDefId           
	INNER JOIN importPartClassTypeInfo ti ON ti.ImportTemplateId = ibf.FKImportTemplateId    
	INNER JOIN importPartClassTypeHeader h ON h.ImportId = ti.FkImportId       
	INNER JOIN 
	(
			SELECT fkImportId,rowid,MAX(STATUS) AS Class ,MIN(MESSAGE) AS VALIDATION      
			FROM importPartClassTypeFields rf
			INNER JOIN ImportFieldDefinitions ifd ON ifd.FieldDefId = rf.FKFieldDefId
			WHERE ifd.FieldName IN (SELECT fieldname FROM ImportFieldDefinitions  WHERE ModuleId = @ModuleId AND UploadType ='PartClassTypeUpload') 
			AND fkImportId = @Importid    
			GROUP BY fkImportId,rowid
			HAVING MAX(STATUS) <> 'i05red'
	) Sub    
	ON ibf.fkImportid=Sub.FkImportId AND ibf.rowid=sub.rowid        
	WHERE ibf.fkImportId = @Importid        
) st        
PIVOT (MAX(adjusted) FOR fieldName IN (ORD_POLICY,STDCOST,PULL_IN,ABC,PUSH_OUT,AUTOLOCATION,SCRAP,PUR_LTIME
	,CERT_TYPE,ORDMULT,Buyer,U_OF_MEAS,MTC,allowAutoKit,OVERHEAD,MRC,LOC_TYPE,LOTDETAIL,INSP_REQ
	,DAY,PART_TYPE,[DESCRIPTION],MINORD,ORD_FREQ,PACKAGE,PROD_LTIME,CLASSDESCRIPTION,FGIEXPDAYS,REORDPOINT
	,PUR_UOFM,PART_CLASS,OTHERCOST2,TARGETPRICE,REORDERQTY,SETUPSCRAP,KIT_LTIME,Taxable,UseCustPFX
	,AUTODT,OTHER_COST,AUTONUM,LABORCOST,MATL_COST,DAYOFMO,PART_PKG,CERT_REQ,WAREHOUSE,DAYOFMO2,PREFIX)) AS PVT